### ISSUE TITLE
Video slider is messed up

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#1]
Specially in videos with segments. Overlap is happening.

**Comment by MysteryHawk17** [comment]
Hi @hkirat  Please assign this issue to me.

**Comment by virajp4** [comment]
I would like to take up this issue

**Comment by MysteryHawk17** [comment]
@hkirat  ,I have fixed the issue involving the design of the segments in the slider.
You could check it  [https://github.com/code100x/cms/pull/17](here)
