### ISSUE TITLE
Improve Readme 

### ISSUE THREAD

**Issue by jayk-gupta** [code100x/cms#100]
Please mention the steps clearly to run the project locally.
I want to run the project locally but can't understand the steps as they are not clearly mentioned.

**Comment by Praashh** [comment]
Hey Jay! in the below ss you can see, there are already mentioned step by step Setup procedure. may be  you are missing something. 

![image](https://github.com/code100x/cms/assets/99237795/9821a7d3-f91a-45ad-b7e0-20d9a2c82a5e)
