### ISSUE TITLE
bug: Typo Error in Sidebar 

### ISSUE THREAD

**Issue by imanasdash** [code100x/cms#1000]
<img width="277" alt="Screenshot 2024-08-24 at 8 37 56 AM" src="https://github.com/user-attachments/assets/87acee90-66bf-4853-8ead-37647b574c3f">

**Comment by x15sr71** [comment]
Working on it.

**Comment by x15sr71** [comment]
@imanasdash I think that Typo is already being fixed, but isn't merged in the production.

**Comment by x15sr71** [comment]
@imanasdash @siinghd I think that Typo is already being fixed, but isn't merged in the production.

**Comment by imanasdash** [comment]
Yes . I was also bit confused to see that it is already fixed in the code
