### ISSUE TITLE
bug: this is bug comes when i try to scroll at the end of week_35 the Title content is showing only half 

### ISSUE THREAD

**Issue by prayag-ahire** [code100x/cms#1007]
**Describe the bug**
i am seeing this bug in that i can't scroll more i think the height is longer then screen size

![Screenshot (116)](https://github.com/user-attachments/assets/103e328d-74a1-4bd7-87ed-40cc3fe6f866)

**Comment by mdatif796** [comment]
I will solve this issue by the following approach -->
1. I will make this container height as dynamic which will change according to viewport height.
2. I will give padding on the bottom to this container.
