### ISSUE TITLE
bug: Thumbnail of Adhoc and DSA classes are not loaded

### ISSUE THREAD

**Issue by GeeekySouro003** [code100x/cms#1012]
Description:It seems that there is an issue where the thumbnails for the ad-hoc and DSA (Data Structures and Algorithms) classes are not visible.

Below is the image attached for reference:-
![image](https://github.com/user-attachments/assets/ede77d84-da39-4a9d-bf2c-b9e9b1589938)

**Comment by TarunVishwakarma1** [comment]
![image_2024-08-25_203505264](https://github.com/user-attachments/assets/78061fae-3dea-45d7-acbb-5ee6ce3bc3d8)

I guess they were updating the image at that time. Thumbnails are visible now.

**Comment by GeeekySouro003** [comment]
yeah i noticed it so i could now close the issue.
