### ISSUE TITLE
bug: Add back a `refresh db` button

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#1016]
it was present in the old design 
<img width="618" alt="Screenshot 2024-08-25 at 1 09 43 PM" src="https://github.com/user-attachments/assets/5ca07329-3a86-4d19-96a6-8fb0f944fbdf">

**Comment by hkirat** [comment]
Put it right above the logout button

**Comment by rameshguditalu** [comment]
@hkirat What does refresh db button should do onclicking of the button?

**Comment by toufiqfarhan0** [comment]
@hkirat @siinghd can you please review it ?

**Comment by rameshguditalu** [comment]
@hkirat @siinghd Kindly review this PR - https://github.com/code100x/cms/pull/1019

**Comment by hkirat** [comment]
Closing since the diff is so big, please dont merge lock files
Merged https://github.com/code100x/cms/pull/1019 instead
