### ISSUE TITLE
feature: Admins should be able to delete comments

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#1031]
![Screenshot 2024-08-26 at 7 58 38 PM](https://github.com/user-attachments/assets/e7d59a3d-944f-4774-96b5-ecd900d01138)

**Comment by YunusShaikh29** [comment]
![image](https://github.com/user-attachments/assets/a68ca39b-7cdb-4075-810b-561d61aa90ce)

Not able to reproduce this!

**Comment by vanshavenger** [comment]
@hkirat the logic is already implemented for the same.
<img width="549" alt="Screenshot 2024-08-26 at 9 42 06 PM" src="https://github.com/user-attachments/assets/58c552d6-6e8a-4fb1-b1ae-36fb8222dab0">
<img width="401" alt="Screenshot 2024-08-26 at 9 40 53 PM" src="https://github.com/user-attachments/assets/65ab4fe0-feb2-445e-a4eb-1198072407a8">

**Comment by devsargam** [comment]
is this still a problem @hkirat?

**Comment by kumawatkaran523** [comment]
Can I try
