### ISSUE TITLE
The Question Page UI is broken. 

### ISSUE THREAD

**Issue by zenithexe** [code100x/cms#1046]
The UI of the Questions and Answers Page is broken. It's totally unreadable.

### Questions List
![Old Question 1](https://github.com/user-attachments/assets/078d07e3-dbee-419f-8c3b-8955c0a2451e)

### Question Page
![Old Question 2](https://github.com/user-attachments/assets/35dad392-3d5d-4ecd-8d86-65a2dc8d10c6)

### Answers
![Old Answers 3](https://github.com/user-attachments/assets/fbe337eb-92f4-4632-8726-1218981d6837)

I have already worked on this and will make a PR soon.

**Comment by zenithexe** [comment]
Can you look at my PR, I have tried to improve the UI ?
@hkirat @devsargam @siinghd

**Comment by nischal-shetty2** [comment]
can be closed

**Comment by zenithexe** [comment]
@nischal-shetty2 I have tried to redesign it, and make the Answers more readable.
