### ISSUE TITLE
bug: Comments posted empty

### ISSUE THREAD

**Issue by prateekkumaroriginal** [code100x/cms#1060]
**Describe the bug**
- Request goes to backend even if the comment box is empty. 
- Comment shouldn't be posted if the comment input field consists entirely of whitesapces.

**To Reproduce**
1.1. Post Comment without writing anything.
1.2. See error
2.1. Post Comment with 1 space or Enter key.
2.2. Comment will be posted

**Expected behavior**
No backend request should be made if the comment input field is empty or contains only whitespace. Comment should not be posted if it consists entirely of whitesapces.

**Screenshots or GIFs**

https://github.com/user-attachments/assets/e882289c-1918-47e0-bd3f-18f025365bb2

**Info (please complete the following information):**
 - Brave

**Additional context**
N/A

**Comment by prateekkumaroriginal** [comment]
@siinghd Please assign this issue to me. I have solved it.

**Comment by Sanjay-Balam** [comment]
@siinghd Please assign this issue to me.
