### ISSUE TITLE
bug: Sidebar UI not looking good 

### ISSUE THREAD

**Issue by Shobhit2205** [code100x/cms#1065]
**Describe the bug**
The sidebar UI is not looking good after inserting RefreshDB Component 

**Screenshots or GIFs**
<img width="1440" alt="Screenshot 2024-08-28 at 12 06 07 PM" src="https://github.com/user-attachments/assets/47cf1f7b-8b68-4649-913d-23de8a07ad62">

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by shekhtausif8090** [comment]
hey this issue is not closed
