### ISSUE TITLE
bug: Alignment Issue Sidebar Component

### ISSUE THREAD

**Issue by Prakash-Raut** [code100x/cms#1068]
**Describe the bug**
Alignment Issue in the Sidebar Component

**Expected behavior**
The Sidebar should be present on the right hand side.

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/edc51bc0-96ca-4fd8-8870-806dbf0ed993)

**Comment by shekhtausif8090** [comment]
Hi #1068 may i know this issue not fixed then i can work

**Comment by Prakash-Raut** [comment]
@shekhtausif8090 
It is fixed.

**Comment by shekhtausif8090** [comment]
ok thanks
