### ISSUE TITLE
admin ui could be a lot better

### ISSUE THREAD

**Issue by nirban07** [code100x/cms#108]
<img width="1427" alt="Screenshot 2024-02-23 at 2 02 56 AM" src="https://github.com/code100x/cms/assets/59662434/e29c1c94-8021-4c1d-be60-bb79c7565c7f">
<img width="1421" alt="Screenshot 2024-02-23 at 2 02 48 AM" src="https://github.com/code100x/cms/assets/59662434/1ceee151-da71-4997-a734-8cae03b69c93">

The ui of the admin can be improved.
i have already made some changes. Open to suggestions
Happy to submit pull request once assigned.

**Comment by Vaibhav-Kumar-K-R** [comment]
I can do this by changing some tailwind classes and addin some padding ...etc
