### ISSUE TITLE
enhance: Inconsistency in UI

### ISSUE THREAD

**Issue by yntpdotme** [code100x/cms#1080]
- Device: Mac
- OS: Sonoma 14.6.1
<br>

- Bottom Borders are not aligned 
![image](https://github.com/user-attachments/assets/80222b9e-94e6-4c91-ad4c-914ad9733da4)
<br>

- Refresh Button is not collapsing when sidebar minimise
![image](https://github.com/user-attachments/assets/817f3250-ca86-4732-8260-ffeb95295902)
<br>

- Week 9, 10 and 12 are not aligned to left 
![image](https://github.com/user-attachments/assets/217788fe-6816-48d4-9276-e6cacb663c91)
<br>

**Comment by csgaikwad** [comment]
I had the same issue
@hkirat is anyone working on this ? If no, can i work on this

**Comment by devsargam** [comment]
Pls don't use npm
We are trying to migrate to pnpm
