### ISSUE TITLE
style: Search results hidden by course content 

### ISSUE THREAD

**Issue by csgaikwad** [code100x/cms#1082]
# Issue Description
The search results are not fully visible as they are being blocked by course content due to incorrect z-index values.

# Required Action
Adjust the z-index values and layout to ensure that all elements, including search results, are fully visible.

## Before
<img width="400" height="300" alt="image" src="https://github.com/user-attachments/assets/b38487b7-8a81-4823-890a-5624f5c9c241"> 

## After
<img width="400" height="300" alt="image" src="https://github.com/user-attachments/assets/cd460aa3-6322-40d1-be7e-01f6cc85a573">

**Comment by JkrishnaD** [comment]
@csgaikwad is this issue was done or can i proceed

**Comment by csgaikwad** [comment]
This pr #1086 should fix the issue
