### ISSUE TITLE
style: Fix title "course content" to stick to the top.

### ISSUE THREAD

**Issue by csgaikwad** [code100x/cms#1084]
## Is your issue related to a problem? Please describe.
The title of the page, currently labeled "Course Content," does not remain fixed at the top when scrolling. This issue causes the title to disappear from view, making it difficult to navigate back to the section header while scrolling through lengthy content.

## Describe the solution you'd like
I would like the "Course Content" title to be styled so that it sticks to the top of the page, remaining visible as users scroll through the content. This will improve navigation and ensure the title is always accessible.

## Describe alternatives you've considered

- **Make the title sticky** : Use CSS `position: sticky` to keep the title fixed at the top while scrolling.
- **Move the title outside the scrolling div** : Place the title outside of the scrolling content container to ensure it remains visible.
- **Make the title fixed** : Use CSS `position: fixed` to keep the title always visible at the top of the viewport.

<img width="400"  alt="image" src="https://github.com/user-attachments/assets/209ac555-c8f8-43b2-b842-06d0b00b77f0">
<br>
&nbsp&nbsp&nbsp |
<br>
&nbsp&nbsp \/
<br>
<img width="400"  alt="image" src="https://github.com/user-attachments/assets/21119707-82d1-4a50-be45-c8497e2af900">

**Comment by csgaikwad** [comment]
should i work on this?

**Comment by zenithexe** [comment]
I have already made an PR (#1053) regarding this.

**Comment by csgaikwad** [comment]
> I have already made an PR (#1053) regarding this.

why is there a failed check ?
