### ISSUE TITLE
bug: Split screen ui is really bad

### ISSUE THREAD

**Issue by mani-rive** [code100x/cms#1094]
**Describe the bug**
As we are learning and trying to implement the code snippet as the class goes along it's really hard when we try to use split screen the video is very small and we are unable to follow it.

**To Reproduce**
1. open any video in the 100xdev
3. and try to use split screen

**Expected behavior**
i want the video to appear normal like other platform so that i can properly follow along with the code tutorial

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/dfdef713-dc38-4b6d-8028-4b0d1828b86a)
@hkirat

**Comment by karandhanwani16** [comment]
Hello I have raised an PR, Can you please check and let me know if there are any changes required.?

**Comment by devsargam** [comment]
Should be fixed in the latest
