### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Husain01** [code100x/cms#1098]
**Describe the bug**
In the dailyCode platform, i.e., projects.100xdevs.com, for the Paytm project slides, the slides are not properly traversing while going to the next or the previous slides, even the jump to dropdown is not proper
**To Reproduce**
1. Go to [PayTM Project](https://projects.100xdevs.com/tracks/oAjvkeRNZThPMxZf4aX5/JLaLbhDuYn3h5Cn7WJu1), and now try to go to the next pages, it does not go in the proper order
2. You'll see after the second page it starts to get somewhat random, and even the previous is random

**Expected behavior**
To incrementally go to the next pages, 1 then 2 then 3 and so on

**Comment by Munadil16** [comment]
raise the issue in the below link please (not related to cms)
https://github.com/code100x/daily-code/issues
