### ISSUE TITLE
FAQ and discussions

### ISSUE THREAD

**Issue by aakash2330** [code100x/cms#11]
It would be pretty nice to have a section right below the video , that contains FAQ and discussions about the topic the user's currently watching . I've seen a lot of people being overwhelmed about using discord after seeing so many channels and discussion groups . it'll give them a place to participate too .

**Comment by HectorShaw** [comment]
Questions, just for my clarification.

1.  You need a comments tab, right?
2.  Should a user be able to reply to a reply? 
3.  A tip, a small link button to redirect to discord channel to the specific lecture's doubt channel.

**Comment by aakash2330** [comment]
@HectorShaw I'm thinking more like syncing the website section and the discord doubts section

![Screenshot from 2024-02-01 20-34-02](https://github.com/code100x/cms/assets/78924853/f5ef5416-04c7-4d39-a314-f7e72afa2fe4)

Something like this .

1 . Yes but mostly for doubts related stuff , we can maybe expand it more to feedback and general comments.
2 . Yes the user should be able to engage .
3 . That's a great idea , discord is much better place for this stuff but also overwhelming for someone who hasn't used it before

It'll help them go give a digestible UI while making sure they're in sync with valuable knowledge that people share within doubts section .
