### ISSUE TITLE
bug: Db seed error in instalation

### ISSUE THREAD

**Issue by Sukomal07** [code100x/cms#1100]
**Describe the bug**
When I tried to install the folder in local without Docker, I got this error . when i run `npm run db:seed`
![Screenshot 2024-09-01 114701](https://github.com/user-attachments/assets/08b30385-877f-4a2c-bcac-4e65383a9923)

**To Reproduce**
1. Try to install the folder in local without Docker. after `npm run prisma:migrate` when you run `npm run db:seed`. This error comes.

**Comment by rameshguditalu** [comment]
@Sukomal07  is this issue resolved (db seed error)

**Comment by Sukomal07** [comment]
> @Sukomal07 is this issue resolved (db seed error). If it's resolved, please let me know how did you fix it

Run this before seed
`npx prisma generate
 `
