### ISSUE TITLE
feature: Top Loader Bar

### ISSUE THREAD

**Issue by Paribesh01** [code100x/cms#1104]
**Is your feature request related to a problem? Please describe.**
When we navigate to pages, there is nothing to indicate loading, so it feels like nothing is happening

**Describe the solution you'd like**
i will achieve this by applying nextjs-toploader package

**Additional context**
![Screenshot from 2024-09-01 14-39-38](https://github.com/user-attachments/assets/dd1eadaf-ce96-4745-8a2b-bb97822b0ebc)

**Comment by MeerUzairWasHere** [comment]
Nice improvement, but we have a loader on top right corner.
