### ISSUE TITLE
bug:  watch history feature not working 

### ISSUE THREAD

**Issue by Nimit1775** [code100x/cms#1106]
**Describe the bug**
in the watch history page whenever i click on any video it redirects me to the home page instead of that particular video 

**To Reproduce**
1. go to the watch history page 
2. click on a video 

**Expected behavior**
expected to be redirected the clicked video 

**Screenshots or GIFs**
https://drive.google.com/file/d/1J9L6kpcIBPk4E1gYRRJ6ilEN2So52lVF/view?usp=sharing

**Info (please complete the following information):**
 - chrome
 - Version 128.0.6613.86 (Official Build) (64-bit)

**Comment by GeeekySouro003** [comment]
@Nimit1775 try to refresh ur browser and click on the refresh database .

Works fine for me

![image](https://github.com/user-attachments/assets/aa686d85-cba6-453b-8efa-6e66ef85c6cf)

**Comment by Nimit1775** [comment]
@GeeekySouro003  still not working for me , it's still getting redirected to homepage

**Comment by GeeekySouro003** [comment]
Can you add the screenshot or maybe a small gif supporting to the cause

**Comment by Nimit1775** [comment]
@GeeekySouro003 i have already added a drive video link please check that out

**Comment by Munadil16** [comment]
@Nimit1775 works fine for me too

**Comment by Nimit1775** [comment]
@Munadil16  is it taking you to the video when clicked  ?  , it still doesn't work for me

**Comment by GeeekySouro003** [comment]
@Nimit1775 its working for me in brave and chrome browser ig its a client side error

**Comment by Nimit1775** [comment]
@GeeekySouro003   let me try in brave maybe there is a  problem in my browser or smth

**Comment by Nimit1775** [comment]
@GeeekySouro003  having the same error in brave too maybe  there is something on my side ig

**Comment by Munadil16** [comment]
@Nimit1775 yes it takes me to respective video. try logging in again / clearing cache

**Comment by Nimit1775** [comment]
@Munadil16  already tried all of that
