### ISSUE TITLE
bug: questions page is missing main layout

### ISSUE THREAD

**Issue by Paribesh01** [code100x/cms#1107]
**Describe the bug**
/questions page is missing the nav bar,

**To Reproduce**
just go to https://app.100xdevs.com/questions

**Expected behavior**
there should be a nav bar to navigate to other pages

**Screenshots or GIFs**
![Screenshot from 2024-09-01 15-39-03](https://github.com/user-attachments/assets/79cd0604-d2f1-4fbb-9fcf-e0a10e1f617e)

**Info (please complete the following information):**
 - Browser [chrome]

**Comment by KIWILmao** [comment]
there are two routes for questions one is /question and one is /quetions you are probably visiting the /questions page

**Comment by Paribesh01** [comment]
@KIWILmao  I think questions page also need the nab bar, because there is no option to go to other pages

**Comment by KIWILmao** [comment]
The main issue here is there are two question endpoint the other one has the navbar

**Comment by palveVaishnav** [comment]
@devsargam , Why are there two routes ? the questions on both of them are same !!

**Comment by abhirupPann** [comment]
So there is no need of the questions route. As the questions button is already linking to the question  route. So simply deleting the questions route will resolve the issue I guess ?
