### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by GeeekySouro003** [code100x/cms#1109]
**Describe the bug**
In the payout section while connecting to the github .The link does not work it seems to be broken.

Here are the screenshots of the problem mentioned below:-

![image](https://github.com/user-attachments/assets/773f202a-21ee-4e94-b395-c28c1c4e723c)
![image](https://github.com/user-attachments/assets/dcc0ddd4-5717-43a6-b3ca-2fe4cdc402da)

**Comment by ItsFlash10** [comment]
It's prolly coz .env wasn't updated for the GitHub creds before deployment, it'll be fixed in the next deployment ig.
cc: @siinghd

**Comment by GeeekySouro003** [comment]
ok
