### ISSUE TITLE
bug: Formatting of course cards have too much spacing

### ISSUE THREAD

**Issue by DraKen0009** [code100x/cms#1110]
**Describe the bug**
 Formatting of course cards have too much spacing. I'm using firefox and 27 inch display.

**To Reproduce**
1. Go to course page
![image](https://github.com/user-attachments/assets/b84003df-9693-4b7a-be5f-d59e97e09f97)

**Expected behavior**
Spacing should be fixed , we can increase the number of columns as per screen width

**Comment by DraKen0009** [comment]
**For anyone wanting to fix this** - I'm already working on this, so please pick another issue to avoid duplication of labor. Thanks

**Comment by ItsFlash10** [comment]
> **For anyone wanting to fix this** - I'm already working on this, so please pick another issue to avoid duplication of labor. Thanks

Hey since it's been a while, I just saw this and had this fixed already but since it was just a couple of line changes I haven't had it pushed. Raising a PR now, hope it fine with you :)

**Comment by DraKen0009** [comment]
@ItsFlash10  it's not even been 24 hours. How is `since it's been a while` is in picture already ? I don't really have any issue with you raising a PR, but you should be more considerate if someone have already picked something and have clearly mentioned that they are working on it, and probably also reconsider what is meant by `since it's been a while`

**Comment by ItsFlash10** [comment]
@DraKen0009 Hey, I'm sorry but I didn't mean it that way, it's just that I already had it solved but as I mentioned it was a small change, and I was expecting to push it with another change. I can close my PR if you already spent time and have solved the issue. You can lemme know. It's an infinite sum game my friend :)

**Comment by DraKen0009** [comment]
Nah, it's fine you don't need to close your PR. I'm not great at frontend so wanted to give it a try since it's a small issue. But anyways maybe next time. Cheers 🍻
