### ISSUE TITLE
bug: Toggle Buttons moving out of the window

### ISSUE THREAD

**Issue by gojekarthik** [code100x/cms#1122]
Toggle Buttons on the Video Screen Moving out of the Window

1. Go to any course video
2. Click on Show List
3. Click on View All Chapters

![cmsissue](https://github.com/user-attachments/assets/dfcd413a-a36e-412e-ab01-7ede396d7d02)

**Comment by ShobhitPatra** [comment]
Hey , Would like to pick this issue if anyone's not into it currently .

**Comment by Subas-mohanty** [comment]
Can't see anything like that 

![Screenshot from 2024-09-03 17-14-51](https://github.com/user-attachments/assets/a3726821-8cf5-4cba-91db-ca08a95c4400)

**Comment by shashwat558** [comment]
It's not happening with me too

**Comment by shashwat558** [comment]
it fine for me

**Comment by shashwat558** [comment]
it's fine for me

**Comment by KiranPolaki** [comment]
Cant see anything either, can you tell how to recreate this? @gojekarthik

**Comment by MeerUzairWasHere** [comment]
On small screens, 13' I think.

**Comment by Mihan786Chistie** [comment]
> On small screens, 13' I think.

![100xbuttonover](https://github.com/user-attachments/assets/a85f34af-c8c6-4877-85f6-9e4722d028a6)
I get the issue when every side drawers are open. Mine is 15' screen

**Comment by MeerUzairWasHere** [comment]
https://github.com/code100x/cms/pull/1126

I changed default values to false, please let them merge this or close then you can make new branch on that

**Comment by devsargam** [comment]
Fixed in the main branch
