### ISSUE TITLE
bug: When pressing `back` button from any video inside folder, it leads to class contents instead of corresponding folder's content

### ISSUE THREAD

**Issue by ParmarKrishna** [code100x/cms#1129]
**Describe the bug**
When we click to `back` button from the video, it leads to the class contents (cohort contents), and not to the video's parent folder's content.
For example, if I click on `back` button from "Week 3.1 | Middlewares, global catches and zod", it leads to cohort's home page. 

**To Reproduce**
1. Navigate to Cohort Homepage > Any Folder > Video
2. Click on `back` button

**Expected behavior**
It should lead to corresponding parent's folder and show its contents.

**Screenshots or GIFs**
- When Clicked on button highlighted
![Screenshot 2024-09-04 at 12 54 52 PM](https://github.com/user-attachments/assets/352cb5f3-aa49-44b0-97bf-35bf4b6f742c)
-It leads to here
<img width="1264" alt="Screenshot 2024-09-04 at 12 57 26 PM" src="https://github.com/user-attachments/assets/eacef206-8c39-4185-b6df-961e36c27176">

**Info (please complete the following information):**
- Chrome 128.0.6613.119
- Safari 

**Additional context**
N/A Required

**Comment by maheshsp1809** [comment]
@ParmarKrishna this is http://harkirat.classx.co.in/ which is not maintained by @hkirat and this CMS repo is for this https://app.100xdevs.com/

**Comment by ParmarKrishna** [comment]
> @ParmarKrishna this is http://harkirat.classx.co.in/ which is not maintained by @hkirat and this CMS repo is for this https://app.100xdevs.com/ 

I see.
Thank you for letting me know.
I think, I got confused between the two.

I'll be closing the issue.
