### ISSUE TITLE
bug: Github linking fails

### ISSUE THREAD

**Issue by asutoshranjan** [code100x/cms#1134]
**Describe the bug**
Clicking on the GitHub link button gives 404, integration issue, the clientId and redirectUri is undefined

**To Reproduce**
1. Click on link Github

**Expected behavior**
Opens a code100x Github app and requests user to grant access 

**Screenshots or GIFs**

https://github.com/user-attachments/assets/ef21fb92-b3a1-47d2-9cdf-fc9ebb0099cf

**Info (please complete the following information):**
 - Browser [e.g. chrome, brave]

**Comment by ishanaudichya** [comment]
For anyone wanting to fix this - I'm already working on this, so please pick another issue to avoid duplication of labor. Thanks
Will update if required cool?

**Comment by devsargam** [comment]
This is not an issue. We haven't configured github secret for the app

**Comment by harsimran-d** [comment]
@devsargam  This issue still persists 

https://github.com/user-attachments/assets/f86b3ad3-c333-4baf-9450-c8e80329bbbf

**Comment by devsargam** [comment]
It persists since we don't have api keys not because something is wrong with code

**Comment by harsimran-d** [comment]
oh i thought it was working when we saw it in pull request demo in class 
https://github.com/code100x/cms/pull/1066

**Comment by harsimran-d** [comment]
my bad just realized they used the person who won the bounty used their own api keys etc. 
but the orignal .env file is missing with OAuth creds for the app.100xdevs.com 
makes sense now
