### ISSUE TITLE
feature: Add Transaction Support for Bookmark Operations

### ISSUE THREAD

**Issue by noobpiyush** [code100x/cms#1137]
Description:
Currently, bookmark creation and deletion operations in the codebase do not use transactions. This can lead to potential issues with data integrity if any part of the operation fails. To ensure atomicity and maintain consistency, it is necessary to wrap these operations in transactions.

Problem:
Data Integrity Risks: Without transactions, partial updates or failures during bookmark creation or deletion can result in inconsistent data states.
Error Handling: In the absence of transactions, handling errors during these operations can be challenging, leading to potential data inconsistencies.
Proposed Solution:
Implement Transactions: Use db.$transaction to wrap the bookmark creation and deletion operations in transactions. This ensures that all operations within the transaction are completed successfully or rolled back if any part fails.
Update Error Handling: Enhance error handling to ensure that any errors during transactions are properly managed and reported.
Reload Bookmark Page: Ensure that the bookmark page is revalidated after a successful transaction to reflect changes immediately.
Benefits:
Enhanced Data Integrity: Ensures that bookmark creation and deletion operations are atomic, reducing the risk of inconsistent data.
Improved Reliability: Provides a more robust implementation by rolling back changes in case of errors, thus maintaining consistency.
Better Error Handling: Simplifies error management by ensuring that transactions are properly handled.
Steps to Reproduce:
Attempt to create or delete a bookmark with a failure scenario (e.g., database error).
Observe the potential inconsistency in bookmark data if operations are not wrapped in transactions.
Additional Notes:
Implementing transaction support will improve the overall reliability and consistency of bookmark operations. Please let me know if there are any questions or if further information is required.

**Comment by devsargam** [comment]
Not relavent
