### ISSUE TITLE
bug: Conflict dependency tree

### ISSUE THREAD

**Issue by MethodManav** [code100x/cms#1139]
**Describe the bug**
Encountered a dependency conflict while setting up the project.

**Comment by MethodManav** [comment]
<img width="831" alt="Screenshot 2024-09-04 at 8 57 02 PM" src="https://github.com/user-attachments/assets/cf2db0b5-62ff-4dd5-b9b8-defbb7962a41">

**Comment by KIWILmao** [comment]
run npm install --force

**Comment by devsargam** [comment]
Don't use npm
