### ISSUE TITLE
bug: local setup suggests to use npm install whereas it is pnpm package manager used 

### ISSUE THREAD

**Issue by dhaliwal-h** [code100x/cms#1141]
**Describe the bug**
The file suggests using `npm install` for the packages but `pnpm install` works as it is being used as the package manager
the remaining local setup commands can work with `npm`

**To Reproduce**
Try to setup locally WITHOUT `docker-compose up`

**Comment by devsargam** [comment]
Closing nothing useful here

**Comment by dhaliwal-h** [comment]
unable to setup locally if using npm install

npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: cms@0.1.0
npm ERR! Found: vitest@1.6.0
npm ERR! node_modules/vitest
npm ERR!   dev vitest@"^1.6.0" from the root project
npm ERR!   peer vitest@"1.6.0" from @vitest/browser@1.6.0
npm ERR!   node_modules/@vitest/browser
npm ERR!     peerOptional @vitest/browser@"1.6.0" from vitest@1.6.0
npm ERR!   1 more (@vitest/ui)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vitest@">=2.0.0" from vitest-mock-extended@1.3.2
npm ERR! node_modules/vitest-mock-extended
npm ERR!   dev vitest-mock-extended@"^1.3.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/hd/.npm/_logs/2024-09-05T12_04_27_070Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/hd/.npm/_logs/2024-09-05T12_04_27_070Z-debug-0.log

**Comment by dhaliwal-h** [comment]
I am still having this issue @devsargam

**Comment by devsargam** [comment]
Don't use npm. We are using pnpm try with that

**Comment by dhaliwal-h** [comment]
that is what I had the pull request for
to update README.md that states to use npm that is 
why lot of people having same issue

**Comment by dhaliwal-h** [comment]
please merge [PR](https://github.com/code100x/cms/pull/1128)

**Comment by devsargam** [comment]
Pls do code contributions @dhaliwal-h. There's a pr going on that already solves some code issues + fixes the readme
