### ISSUE TITLE
bug: Unauthorized user can click on 3 dots in question

### ISSUE THREAD

**Issue by MeerUzairWasHere** [code100x/cms#1145]
An unauthorized user can see and click on the 3-dot action menu in a question that they did not post. The delete option appears in the menu, but only the buttons for these actions are being handled in the backend, not the display of the options themselves.

**To Reproduce**  
1. Log in as a user who did not post the question.
2. Navigate to a question posted by someone else.
3. Click on the 3 dots next to the question.
4. Observe that the "option" is visible even though the user is not authorized to delete the question.

**Expected behavior**  
The delete option (or any other unauthorized actions) should not be visible to users who are not the owner of the question.

**Additional context**  
The issue is related to frontend handling of the visibility of options in the 3-dot menu. Although we handle the backend actions for these options correctly, unauthorized users can still see the option, which creates confusion.

![image](https://github.com/user-attachments/assets/1b2e53d0-4294-4129-a4e7-8d84b14dac93)

**Comment by kk7188048** [comment]
I am not able to reproduce the error, for me only authenticated user can only delete.

**Comment by MeerUzairWasHere** [comment]
Read description 🤦🏻‍♂️
