### ISSUE TITLE
bug: No space between question search input icon and search button

### ISSUE THREAD

**Issue by kk7188048** [code100x/cms#1147]
**Describe the bug**
There is no space between search and input icon

**To Reproduce**
1. Login and go to Question Section
2. See the input and search button

**Expected behavior**
There should be some space between both of them

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/22d81e62-1af8-4b99-a407-a66a9994ea77)
**Info (please complete the following information):**

**Additional context**
This issue is not in the production URL only on the local host after setup

**Comment by sundaramsharma** [comment]
I see a new interface here

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/6d20da64-d99d-4500-834f-32ad35d2a537">

**Comment by kk7188048** [comment]
The code which i have it shows me the frontend i shared.
