### ISSUE TITLE
feature: Request for a dev branch to streamline contributions

### ISSUE THREAD

**Issue by MeerUzairWasHere** [code100x/cms#1149]
I wanted to propose the introduction of a dedicated `dev` (development) branch for the repository. Currently, all contributions and pull requests are merged directly into the `main` branch, which can sometimes lead to inconsistencies between the codebase and the production environment. Here are some points to consider:

1. **Separation of Concerns**: Having a `dev` branch would allow developers to work on contributions and merge them into a dedicated space for testing and CI/CD validation before they reach the `main` branch. This helps avoid potential disruptions in production due to issues in newly merged code.
   
2. **Streamlining Contributions**: By introducing a `dev` branch, contributors can fork and base their work off this branch, ensuring they have access to the most up-to-date code for development. This minimizes the risk of conflicts or bugs that could arise from directly working with the `main` branch.

3. **Continuous Integration**: A `dev` branch could serve as a staging area where automated tests and builds can be run before merging into `main`. This will help ensure the stability of the code that eventually reaches production.

4. **Facilitating Hotfixes**: Having a `dev` branch allows the `main` branch to remain stable and ready for deployment, while still accommodating contributors working on new features, bug fixes, and improvements.

I believe this would help improve the contribution process and enhance the stability of the project. Please consider adding a `dev` branch as part of the repository’s workflow.

Thank you for your time and consideration!

**Comment by devsargam** [comment]
I agree with this we are thinking of implementing something similar closing this for now
