### ISSUE TITLE
bug: Video controllers - popping out 

### ISSUE THREAD

**Issue by Chandan-6** [code100x/cms#1153]
**Describe the bug**
When the Sidebar + Chapters Bar + Videos list bar is opened, the video controllers are displayed outside the video boundary.

**Expected behavior**
The controller's size ( icons ) should become small according to the layout.

**Screenshots or GIFs**

https://github.com/user-attachments/assets/f580850b-02a8-4abb-9887-fc68939d498d

**Info (please complete the following information):**

**Comment by VanshikaSabharwal** [comment]
@Chandan-6 I faced this issue and wanted to correct it for so long. So, can you please assign this issue to me.

**Comment by MeerUzairWasHere** [comment]
New UI is coming up it'll be fixed

**Comment by SadatHussain7** [comment]
@MeerUzairWasHere When is the new UI coming? Is someone currently working on it? Don't we need to fix this then?

**Comment by MeerUzairWasHere** [comment]
@SadatHussain7  I don't know when it is coming. Yes, we don't need to fix it. because if clone the repo to local it's whole different on local. lol 
we should have a dev and main branch @devsargam

**Comment by devsargam** [comment]
New UI coming today :tada
