### ISSUE TITLE
feature: Add "Next" and "Previous" Buttons for Module Navigation

### ISSUE THREAD

**Issue by MeerUzairWasHere** [code100x/cms#1166]
![image](https://github.com/user-attachments/assets/5135ce13-4e06-4b0d-850c-8db7dc85a7b4)

**Description**:
We need to implement "Next" and "Previous" buttons below the video to allow users to easily navigate between modules and courses.

**Scope**:
1. Add two buttons, "Next" and "Previous," below the video in the course module page.
2. The buttons should allow users to:
   - Move to the next module if available.
   - If there are no more modules in the current course, navigate to the next course.
   - Move to the previous module if available.
   - If at the first module, navigate to the previous course’s last module.
   - If no further modules or courses are available, disable the respective button.

**Acceptance Criteria**:
1. "Next" button should navigate to the next module in the current course.
2. If the last module of the course is reached, the "Next" button should navigate to the first module of the next course.
3. "Previous" button should navigate to the previous module in the current course.
4. If at the first module of the course, the "Previous" button should navigate to the last module of the previous course.
5. Both buttons should be disabled when there are no further modules or courses.
6. Buttons should be visible below the video player on the module page.

**UI/UX Considerations**:
- Place buttons directly below the video player.
- Ensure the button design is consistent with the overall UI theme.
- Add hover and disabled states to indicate functionality.

**Comment by KiranPolaki** [comment]
Hey i was also looking into it. Completely agree with you @MeerUzairWasHere because the problem is routes are not linear in nature. would like to know more about your approach.

And i also seem to remember previously this feature was available so i will dig into the commits once.

**Comment by MeerUzairWasHere** [comment]
I already told my approach above. If any repo maintainer agrees to add prev and next urls. Then I'll look into it.

**Comment by devsargam** [comment]
Don't think we can easily get the next and prev urls. We need to calculate with the tree that we have of course content
