### ISSUE TITLE
bug: Search missing in the new UI

### ISSUE THREAD

**Issue by ItsFlash10** [code100x/cms#1175]
**Describe the bug**
- Search in the course content screen is missing which was present previously.
- Also the sidebar header is missing the background colour.

**Expected behaviour**
There must be a search bar in the UI and the sidebar header should have a background colour.

**Screenshots or GIFs**
<img width="435" alt="Screenshot 2024-09-10 at 12 25 52 PM" src="https://github.com/user-attachments/assets/7dd4b996-66ad-46c2-a023-dcdccd2bb735">

**Comment by ItsFlash10** [comment]
I was watching a class and I usually search for the topics but then saw the searchbar missing in the new UI. This might needs triage @hkirat @siinghd

**Comment by toufiqfarhan0** [comment]
@ItsFlash10  there is already one present at https://app.100xdevs.com/home
![image](https://github.com/user-attachments/assets/4b6ba602-15f7-4833-b2c6-a79ef9c54625)

**Comment by ItsFlash10** [comment]
@toufiqfarhan0, not on this page, the course content page.
