### ISSUE TITLE
feature: Course Enrollment and Purchase Tracking

### ISSUE THREAD

**Issue by Umesh-Tiruvalluru** [code100x/cms#1178]
It’s frustrating not being able to track how many users have enrolled in or purchased courses. Without this data, it’s hard to measure course success or improve content and marketing strategies.

**Description:**
I would like a simple dashboard that shows how many users have enrolled in or bought each course. It should also track revenue for paid courses and display engagement metrics, such as user progress and course completion rates.

**Comment by KiranPolaki** [comment]
I guess these metrics will be provided to Harkirat by Appx platform but wont be visible to us.
