### ISSUE TITLE
bug: new ui bug

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#1180]
![Screenshot 2024-09-10 at 10 20 03 PM](https://github.com/user-attachments/assets/f6356cab-36bc-4e2f-8d32-74b24fb7d2b0)

**Comment by Tarunmeena0901** [comment]
happy to work on it

**Comment by jayzalani** [comment]
I just checked the situation he describe and is it working good on my pc or just I don't understand the whole problem @hkirat can you please provide more context ??

**Comment by shaurya35** [comment]
@hkirat 
Tried to fix this screen space bug.
please check #1262 
open for suggestions or improvement

**Comment by devsargam** [comment]
This is still up for grasp guys @keshav-exe

**Comment by keshav-exe** [comment]
Should i do it 👀 @devsargam

**Comment by devsargam** [comment]
@keshav-exe happy if u can

**Comment by shaurya35** [comment]
@devsargam #1325 Fixed the UI bug
