### ISSUE TITLE
bug: Courses dashboard gets partially covered

### ISSUE THREAD

**Issue by spc-28** [code100x/cms#1186]
**Describe the bug**
On opening the side navBar  the courses Dashboard get covered.

**To Reproduce**
1. Click on the show Nav button in the left div at the top.
2. It covers the courses dashboard.

**Expected behavior**
The complete courses dashboard should be visible even if the nav is open.

Screenshots or GIFs
<img width="1347" alt="Screenshot 2024-09-11 at 12 50 27 PM" src="https://github.com/user-attachments/assets/bd28b893-2b92-4d3b-bee5-9fd492c6f8cd">

**Comment by spc-28** [comment]
@keshav-exe 
On the Home page of the website, when we Click on the Menu Button which is present on the top left corner of the page, it opens up the Menu bar. This Menu bar is overlapping  the contents like the "Greeting" and the Courses present, which is impacting the user experience on the site. Here is an image for reference,
<img width="1347" alt="g1" src="https://github.com/user-attachments/assets/3508f056-c20e-4e34-bc02-fd21c1f2c6e3">

**Comment by keshav-exe** [comment]
Perfect, will fix this in the next pr. Thanks
