### ISSUE TITLE
bug: full screen issue

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#1190]
![Screenshot 2024-09-11 at 5 29 10 PM](https://github.com/user-attachments/assets/e8c7d297-c8be-4436-bb35-944d3c0a4eb5)

**Comment by Aarif5435** [comment]
Hi @hkirat is this issue fix or what because I'm not able to face this issue on prod.
![image](https://github.com/user-attachments/assets/03e30ead-c9f8-48df-9e53-a45e3c14586f)

**Comment by ashutosh017** [comment]
What's the issue man?

**Comment by MeerUzairWasHere** [comment]
Full Video Screen should be visible like YouTube

**Comment by GARY121github** [comment]
@MeerUzairWasHere can i work on this issue ?

**Comment by GARY121github** [comment]
But the full screen is working completely fine.

**Comment by GARY121github** [comment]
@MeerUzairWasHere  But the full screen is working perfectly fine.
![Screenshot from 2024-09-11 20-53-43](https://github.com/user-attachments/assets/d368c48d-a6ad-483e-8d38-293133aa97b6)
Same as youtube
![Screenshot from 2024-09-11 20-54-42](https://github.com/user-attachments/assets/303eda89-17b0-41b6-95f8-fa7484eeb1fa)

**Comment by MeerUzairWasHere** [comment]
No, You should be able to see full screen while navigating..
like these 
![image](https://github.com/user-attachments/assets/f5480517-aa1d-4d8d-8184-0e3af1e788e6)
![image](https://github.com/user-attachments/assets/dd7c6b34-7c54-4806-9296-0719d8c95c67)
I'm not in full mode but i am able to see full screen

**Comment by MeerUzairWasHere** [comment]
- Before
![Macbook-Air-app 100xdevs com](https://github.com/user-attachments/assets/54eca6f9-9957-40c4-9e99-eea19442135d)

- After
![Macbook-Air-localhost](https://github.com/user-attachments/assets/507317f0-1951-4ddb-ac77-8da7adaedf89)
- I made Navbar static.
- Removed extra padding as we have static Navbar.
- Reduced padding of Bottom Navbar.

What about this @hkirat @devsargam?
But I'm unable make a PR, as when I make a commit, it gives me error as shown below. please fix it so we can work on it.

![image](https://github.com/user-attachments/assets/6b8e33bf-11c1-40d5-9ee5-7bb069f51c18)

**Comment by Dhaneshwarguiyan** [comment]
Can i work on this ?

**Comment by mdsimar1901** [comment]
i can work on this!

**Comment by Dhaneshwarguiyan** [comment]
I have fixed this issue by using fill property in the options and gave the container the height which shall be visible within the viewport
![Before](https://github.com/user-attachments/assets/258ccb30-8d44-4004-bc9d-218e3a14bd48)
Before
![After](https://github.com/user-attachments/assets/8044f8e1-da6d-465b-9993-c232d950238d)
After
