### ISSUE TITLE
bug: In the Main README.md file have there is some starting commad two times.

### ISSUE THREAD

**Issue by gauravsingh94** [code100x/cms#1193]
**Describe the bug**
In the README.md file theer](bug: In the Main README.md file have the docker command two times.)

**To Reproduce**
1. Do something
2. See error

**Expected behavior**
The should be only one command in the Readme.md file

**Screenshots or GIFs**
<img width="852" alt="image" src="https://github.com/user-attachments/assets/7c5942eb-b0c0-44ee-a556-58c8853b75a0">

**Info (please complete the following information):**

**Additional context**

**Comment by singh-sudhir16** [comment]
It has been fiex
