### ISSUE TITLE
bug: the course content overlaps with the "Course Content" heading in show Courses

### ISSUE THREAD

**Issue by Rajankannaujiya** [code100x/cms#1195]
**Describe the bug**
When scrolling through the course content, the content appears behind the "Course Content" heading, making it look visually unappealing.

**To Reproduce**
1. Scroll through the courses page.
2. Observe that the course content scrolls behind the "Course Content" heading.

**Expected behavior**
The heading should remain visible, and the course content should not overlap or show behind the heading area. The content should scroll underneath without affecting the heading.

**Screenshots or GIFs**
[Screencast from 2024-09-12 00-14-53.webm](https://github.com/user-attachments/assets/bfa3044c-a741-4b9c-b98d-c339bfb1f3f7)
![Screenshot from 2024-09-12 00-14-40](https://github.com/user-attachments/assets/6af66092-6d4c-4bc5-93b4-8306a2858b88)

-Browser: Chrome, Brave
-Version: latest

**Comment by ItsFlash10** [comment]
#1176 has a fix for this
