### ISSUE TITLE
bug: Thumbnail component leaks video metadata

### ISSUE THREAD

**Issue by paahaad** [code100x/cms#1198]
**Describe the bug**
Thumbnail component exposes video content to users who haven't purchased the course.

**Comment by ItsFlash10** [comment]
@paahaad can we add this check in the server action to check if the user has purchased the course or not first and then query the db for the content?

```
const hasPurchasedCourse = async (userId, courseId) => {
  const purchase = await db.purchase.findFirst({
    where: {
      userId,
      courseId,
    },
  });
  return !!purchase; 
};  

const userHasPurchased = await hasPurchasedCourse(userId, courseId);

  if (!userHasPurchased) {
    return [];
  }
  ```
  
  PS: Pardon me but I've just started exploring BE and recently started NextJS as well : )

**Comment by ItsFlash10** [comment]
> > @paahaad can we add this check in the server action to check if the user has purchased the course or not first and then query the db for the content?
> > ```
> > const hasPurchasedCourse = async (userId, courseId) => {
> >   const purchase = await db.purchase.findFirst({
> >     where: {
> >       userId,
> >       courseId,
> >     },
> >   });
> >   return !!purchase; 
> > };  
> > 
> > const userHasPurchased = await hasPurchasedCourse(userId, courseId);
> > 
> >   if (!userHasPurchased) {
> >     return [];
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > PS: Pardon me but I've just started exploring BE and recently started NextJS as well : )
> 
> This is a great idea. but the ideal approach is "least privileged" meaning we only expose what is needed can be endpoint, port or any services. since we are not using the feature no need to expose it.

Yes, so we can implement this if we want to use that feature ig xD
