### ISSUE TITLE
bug: Payout Methods is UNPROTECTED from Authentication Check and along with Calendar their Navbars are Overflowing onto the Page Contents as well.

### ISSUE THREAD

**Issue by rahulbarmann** [code100x/cms#1201]
**Describe The Bugs**
1. The /payout-methods route is unprotected from authentication check i.e, users can access this page irrespective of them being logged in or not.
2. The /payout-methods and /calendar pages have their Navbar overflowing onto the page contents which leads to it not being visible completely.

**To Reproduce**
**Steps to reproduce the behavior of Issue 1:**
1. Visit https://app.100xdevs.com/payout-methods using any browser window that does not have your logged-in cookie (ex. incognito)
2. You will still be able to access this page even if you aren't logged in.

**Steps to reproduce the behavior of Issue 2:**
1. Visit /payout-methods and /calendar routes at app.100xdevs.com.
2. You will notice the Navbar overflows onto the contents of the page. 

**Expected behavior for Issue 1**
Users who are logged in should only be the ones allowed to access the page. (i.e only who has the auth cookie)

**Expected behavior for Issue 2**
The Page Contents should follow under the Navbar with appropriate padding and margin.

**Video for Issue 1**

https://github.com/user-attachments/assets/e031e387-2f01-4839-ba44-47508e309e6b

**Video for Issue 1**

https://github.com/user-attachments/assets/2ab0671f-8389-4cac-9b62-3f28ed16322f

**Info (please complete the following information):**

**Additional context**
#1159 and #1168 already dicusses about the Navbar overlow issue but donot completey fix the authentication bug as well.

**Comment by toufiqfarhan0** [comment]
resolves #1169

**Comment by rahulbarmann** [comment]
Hey,

I checked out #1169 but it only solves the Navbar Overflow Issue.
Please go through this issue carefully once again, Here I have talked about both the auth check implementation in /payout-methods and the navbar overflow. Both of these issues can be solved with just a simple re-structure of the files which I did my my PR #1203. So technically #1169 does not fix this issue completely.

**Comment by devsargam** [comment]
But your pr was empty pr
