### ISSUE TITLE
bug: Comment overflowing and not wrapping 

### ISSUE THREAD

**Issue by r-mayyank** [code100x/cms#1206]
**Describe the bug**
Comment overflowing the screen and giving horizontal scroll, bcz of this when you try to forward video it scrolls horizontaly 

You can check the bug in this lecture here: https://app.100xdevs.com/courses/3/195/196

**Expected behavior**
I guess comments should wrap around if exceds the max width

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/9242c390-0809-41f7-a399-04ec4a10b2ad)
![image](https://github.com/user-attachments/assets/d40a31b1-e918-4da8-a1cd-e9df894f8ce1)

**Comment by karthiknadar1204** [comment]
if this issue is up for grabs, I would like to work on it

**Comment by KiranPolaki** [comment]
@mayankraja-me totally agree so i added a break-all which would wrap if the max-width of the page hits. My PR fixes it

**Comment by mayankraja-me** [comment]
I hope it gets merged
