### ISSUE TITLE
bug: on Login Page, Phone number login displays email suggestions and blocks login without an email

### ISSUE THREAD

**Issue by kingpranav21** [code100x/cms#1211]
**Describe the bug**
Login form should allow users to sign in using either their phone number or email. However, when a phone number is entered, the form still displays email suggestions like "9090900904@gmail.com," and prevents login without entering an email. I have to disable these email suggestions when a valid phone number is detected.

**To Reproduce**
Users should be able to log in using either an email or a phone number.
When a phone number (e.g., "9090900904") is entered, no email suggestions should appear, and the form should process the login correctly.

**Expected behavior**
Login using phone number also

**Actual Behavior**
When entering a phone number, the form incorrectly displays email suggestions, such as "9090900904@gmail.com."
The login attempt is blocked, as it expects an email instead of a phone number.

**Steps to Reproduce**
Implement the login form with fields for email and password.
Enter a valid 10-digit phone number into the email field.
Observe that email suggestions are generated (e.g., "9090900904@gmail.com").
Try to log in with the phone number — it fails without entering a valid email address.

**Screenshots or GIFs**
<img width="1680" alt="Screenshot 2024-09-14 at 1 37 58 AM" src="https://github.com/user-attachments/assets/fa682ae4-3b08-42e6-8724-428fbe2bd74c">

**Comment by kingpranav21** [comment]
Just added the Solution for this , if that's correct please accept my pull request

**Comment by anshux1** [comment]
As of now login with phone is not  implemented bcs i dont think its needed and changing the suggestion is not a solution u cannot enter phone no. in a email field

**Comment by kingpranav21** [comment]
I can’t login with my phone number , i have created my account using phone
number🙂

**Comment by kingpranav21** [comment]
Changing suggestions will help because whenever you are writing phone
number you don’t need suggestions

**Comment by kingpranav21** [comment]
So can we add a feature to login using phone number?

**Comment by SargunSinghSethi** [comment]
Just remove the suggestions area it is simple, then it does not matter whether we are using a phone number or an email and it is very much hectic to see the suggestions, if a user comes to a particular website and sees this he/ she will not be happy with this
