### ISSUE TITLE
bug: Fix Menu bar UI

### ISSUE THREAD

**Issue by Parikshit2001** [code100x/cms#1219]
**Describe the bug**
Menu bar UI is bad, the button is moving on opening and closing it. This is annoying

**To Reproduce**
1. Set up the project
2. Open and close the left sidebar and see the button to open and close moves, its very annoying

**Expected behavior**
Button should stay at one place only, so its easier control

**Screenshots or GIFs**
<img width="1710" alt="Screenshot 2024-09-14 at 10 26 18 PM" src="https://github.com/user-attachments/assets/bbd412b1-120a-4ed8-a9ff-8bb888ec622c">
<img width="1710" alt="Screenshot 2024-09-14 at 10 26 14 PM" src="https://github.com/user-attachments/assets/f206c95a-e407-4554-a211-c07c5b949406">

**Info (please complete the following information):**
 - Browser [Brave]
 - Version [v1.69.168]

**Comment by keshav-exe** [comment]
Hey parikshit, you have the browser window zoomed in are you still facing this issue at 100% zoom?

**Comment by Parikshit2001** [comment]
My browser window is at 100% zoom only and the issue is there

Its even there on the deployed website - https://app.100xdevs.com/home

Try opening and closing the left sidebar,
you'll see the button moves and then then when you close it moves to its original place

# Before
https://github.com/user-attachments/assets/20902e97-8fd4-4f65-b98d-9f84a3e4943a

# After
https://github.com/user-attachments/assets/5248fa96-6446-4cc6-af33-997b86ea5291
