### ISSUE TITLE
bug: Bookmark is broken.

### ISSUE THREAD

**Issue by paahaad** [code100x/cms#1231]
**Describe the bug**
1. duplicates records are being generated in bookmark table, due to incorrect flow of bookmark data to course page.
2. No support for notion docs or folder to bookmark.

[Screencast from 15-09-24 09:50:55 PM IST.webm](https://github.com/user-attachments/assets/f8be8bb2-f9d0-47c4-b4ba-78a5b5b1b55d)

**Comment by KeshavDev15** [comment]
Hello I want to contribute to this issue .

**Comment by sahilc-xd** [comment]
Hey will be contributing to this error , lets connect @KeshavDev15 , we can fix this together as well if you are still interested

**Comment by KeshavDev15** [comment]
Sure it will be helpful

**Comment by sahilc-xd** [comment]
I think @paahaad has already contributed to this ?is it complete @paahaad

**Comment by paahaad** [comment]
> I think @paahaad has already contributed to this ?is it complete @paahaad 

Yes it's completed.

**Comment by KeshavDev15** [comment]
is it not merged @paahaad
