### ISSUE TITLE
bug: in hero page , got error

### ISSUE THREAD

**Issue by mrsamirr** [code100x/cms#1237]
**Describe the bug** 
whenever i log in and comes to home page , i got this error
the credentials are
 user:`testuser2@example.com`
 password: `123456`

**Expected behavior**
can someone explain , why i got this error?

**Screenshots or GIFs**
![Screenshot from 2024-09-16 21-22-26](https://github.com/user-attachments/assets/07767a8a-1e9f-493f-b750-b768dc693237)

**Info (please complete the following information):**

**Additional context**

**Comment by KeshavDev15** [comment]
hello @mrsamirr  I am getting the same error can you help me

**Comment by mrsamirr** [comment]
just setup using manual way instead of docker-compose
