### ISSUE TITLE
bug: Cover Image for courses not showing up on the home page which comes after login

### ISSUE THREAD

**Issue by Parikshit2001** [code100x/cms#1238]
**Describe the bug**
Cover Image is not showing up on the home page which comes after login.
If I go to the src of that image it says access denied. 

**To Reproduce**
1. Set up the project
2. Go to the landing page

**Expected behavior**
Image should show up on landing page

**Screenshots or GIFs**
<img width="1710" alt="Screenshot 2024-09-17 at 12 06 53 AM" src="https://github.com/user-attachments/assets/eb355d79-a7e2-4081-8659-02ce398b38e8">

**Info (please complete the following information):**
 - Browser [Brave]
 - Version [v1.69.168]

**Additional context**
The data is seeded in the prisma/seed.ts file - https://github.com/code100x/cms/blob/main/prisma/seed.ts

**Comment by Parikshit2001** [comment]
In my opinion either @hkirat has to fix it from the backend OR
if you want some other image URLs, then please give it to me, I'll add them in the prisma/seed.ts file

**Comment by anandrajsingh** [comment]
It shows access denied when you try to open the image url directly on browser

**Comment by ItsFlash10** [comment]
It's not a bug, the link added in the seed command is not public, you can replace it in your machine if you want.

**Comment by sahitya-chandra** [comment]
@Parikshit2001 Hey can you tell me what is the use of prisma/seed.ts file and scripts folder in src folder path src/scripts

**Comment by upgraderboy** [comment]
> @Parikshit2001 Hey can you tell me what is the use of prisma/seed.ts file and scripts folder in src folder path src/scripts

The scripts present in scripts folder is used to automatic deploy your application on server that u will see study in dev ops, if you are member of cohort 3.
The seed file in prisma is to add mockup data in your database using the file, in most of case that performed for testing purpose in dev environment.
