### ISSUE TITLE
Fix votes on own posts

### ISSUE THREAD

**Issue by Zafeeruddin** [code100x/cms#1250]
Currently users can vote their own posts (questions, answers, replies), Shouldn't we forbid user voting their own posts?

@siinghd  @devsargam 

Can work on it if required?

**Comment by wraith2009** [comment]
I think its common for users to vote their own questions and everything . it happens everywhere

**Comment by devsargam** [comment]
Like @wraith2009 said it's a common usecase and done in most of places
