### ISSUE TITLE
bug: Shows question has been downvoted even when we remove the downvote

### ISSUE THREAD

**Issue by wraith2009** [code100x/cms#1254]
Recently i noticed that a toast shows up when we remove the downvote and it shows question has been downvoted .
![image](https://github.com/user-attachments/assets/fee2ca19-3035-4857-b078-d5203c5d2fff)
It is a minor issue if You want to address it . i will update it today.

**Comment by devendra0009** [comment]
Can you specify the steps to reproduce, in which page it is creating the problem?

**Comment by wraith2009** [comment]
If you go to any of the question post on 100xdevs you can see that whenever we remove any upvote or downvote it shows the question has been upvoted or vice versa based on the action.

**Comment by wraith2009** [comment]
I have already solved this and raise a pr along with other enhancements in #1255
