### ISSUE TITLE
feature: Opening an Issue for Enhancements to Questions Page (Loader, Confirmation Dialog, UI Changes, Mark as Resolved)

### ISSUE THREAD

**Issue by wraith2009** [code100x/cms#1255]
Hi Maintainers,

I’m opening an issue to track the improvements I’m working on for the Questions Page. Here’s a quick summary of what I’m working on:

Planned Enhancements:
1. Loader on Submit Button
A loading spinner will be added to the submit button when a question is being submitted to enhance user feedback.

2. Confirmation Dialog for Deleting a Question
I  will add a confirmation dialog to prevent accidental deletions.

3. Minor UI Changes
I’ll be removing the toast notification that appears when a vote is removed from a question.
Mark as Resolved Feature

4. I plan to add a "Mark as resolved" option when a question has been answered the owner can mark it as resolved.
I’m currently working on these changes and will update the issue once everything is complete. Please let me know if you have any concerns or suggestions.

Thanks,
Rahul

**Comment by Zafeeruddin** [comment]
Have u already started working on it?

**Comment by wraith2009** [comment]
yes , will be done by tommorow

**Comment by wraith2009** [comment]
I have checked linting issues if they are failing again , please let me know
