### ISSUE TITLE
feature: Course Contents Sidebar Close Improvement

### ISSUE THREAD

**Issue by ncjpr04** [code100x/cms#1257]
The course content sidebar (the red area) should close on clicking anywhere on the main area (green area)
![Screenshot 2024-09-18 222036](https://github.com/user-attachments/assets/4c2340a3-e2d1-49b6-971a-e78d1e1195df)

**Is your feature request related to a problem? Please describe.**
It's in habit that on clicking in the green area the sidebar(red)  will close automatically but it is not closing.

**Describe the solution you'd like**
The course content sidebar (the red area) should close on clicking anywhere on the main area (green area)

**Comment by wraith2009** [comment]
I think a button is already provided for closing this and sometimes a user needs to scroll through the content and switch to other videos if the side bar closes again and again it wont be helping anyone . just suggesting . although you can wait for maintainers to check this but in my opinion this enhancement is very subjective based on user personal preference.

**Comment by surajTade** [comment]
Agree with you point @ncjpr04, like this is a common feature in most of the websites that whenever a user clicks on the main area the sidebar or in this case the course content sidebar should disappear.

**Comment by viveksuyal37** [comment]
anyone working on it? If not then i'll be happy taking it.

**Comment by devsargam** [comment]
This is done
