### ISSUE TITLE
bug: After clicking on the any comment's options button, can't able to scroll the page, and also there are no options there

### ISSUE THREAD

**Issue by ncjpr04** [code100x/cms#1258]
**Describe the bug**
After clicking on the any comment's options button, can't able to scroll the page, scrollbar hides, and also there are no options there

**To Reproduce**
open the course player and click on any comment's options

**Expected behavior**
Thre should be options about the comment and it should not affect the scrolling of the page

**Screenshots or GIFs**
![Screenshot 2024-09-18 224115](https://github.com/user-attachments/assets/2e9315b9-d115-4945-8912-b6022bd558a4)

**Info**
 - Browser [chrome]

**Comment by MohammedYaseenRon** [comment]
can i work on this?

**Comment by wraith2009** [comment]
hey, i think the issue has been resolved in #1259 you can wait for the maintainers to check this
