### ISSUE TITLE
bug: Able to click on 3 dots (options) for comments not authored by the user

### ISSUE THREAD

**Issue by MeerUzairWasHere** [code100x/cms#1259]
**Description:**  
There is a bug where users can click on the 3 dots (options menu) for comments that they did not author. This action should be restricted to the comment's author only. 

**Steps to Reproduce:**
1. Log in as a user.
2. Navigate to a course video with comments.
3. Find a comment authored by another user.
4. Attempt to click on the 3 dots/options menu for that comment.

**Expected Behavior:**  
Only the author of the comment should be able to click on the 3 dots.

**Actual Behavior:**  
Any user can click on the 3 dots/options menu for comments not authored by them.

**Attachments:** 
![image](https://github.com/user-attachments/assets/802ee285-789b-4a36-b5f5-1aa5d9d4028d)
![image](https://github.com/user-attachments/assets/41550714-3dad-46ad-9a93-ae3689af0aae)

**Comment by wraith2009** [comment]
hey have you resolved the issue and now the ... dots arenot showing anymore right? just confirming.

**Comment by MeerUzairWasHere** [comment]
@wraith2009  Ah Yeah. I have also shared the image on PR.
