### ISSUE TITLE
Optimizing User Experience: Implementing Hyperlinks with New Tab Functionality.

### ISSUE THREAD

**Issue by Sameer93A** [code100x/cms#126]
Incorporating hyperlink functionality in the comment section. When users click on the provided link, it should seamlessly direct them to the associated webpage, opening in a new tab for a smoother browsing experience.

**How to reproduce.**
![1](https://github.com/code100x/cms/assets/121109714/8184d774-7abc-4ef6-b9b6-31550e16af39)
![2](https://github.com/code100x/cms/assets/121109714/7d9413fb-596d-4ce6-a126-24a089a0e155)

**Comment by ssk090** [comment]
Hey @hkirat
I have implemented comments with hyperlinks here: https://github.com/code100x/cms/pull/128

please check the PR, Thank you

**Comment by MangaByteCoder** [comment]
I'm able to login with the provided userid and password from readme but its not fetching the courses.
![Screenshot (3211)](https://github.com/code100x/cms/assets/160803937/58afde12-a193-46c0-87cc-0fbaa7c167a7)
