### ISSUE TITLE
bug: Login button doesn't work 

### ISSUE THREAD

**Issue by sangamesh27** [code100x/cms#1261]
Description:
When the account gets logged out and it ask to re-login the login button doesn't work 

To Reproduce:
1. Login to 2 devices or 3 and when the account gets logged out from one device and when you press home it ask to re-login the button doesn't work you have to click again on the login button on the top right to reload the page and then it works
2. When you do these steps try clicking the login button

**Expected behavior**
Login button should work without reloading the page

**Info (please complete the following information):**
 - Browser: Firefox
 - Version:130

**Comment by aryanbansal73** [comment]
Hi, I am not able to reproduce the issue. 
I am opening the website https://app.100xdevs.com/ in chrome , firefox and my mobile , both normal browser mode and incognito .  When I log out from one , i am still able to click on login to login again

**Comment by Zafeeruddin** [comment]
Hey can u share the video?

**Comment by sangamesh27** [comment]
Hey there, seems like I couldn't reproduce the issue as I mentioned in the
same way as I was trying. I'll send the video once I find it again. I was
able to reproduce it a few minutes ago but the file got corrupted. I'll
send it once again when I face it.

**Comment by sangamesh27** [comment]
Hey there seems like this got reproduced can a maintainer have a look in this? @siinghd
the login button which is at the center isn't clickable. 
![image](https://github.com/user-attachments/assets/371c65e6-b82f-4493-a76b-ca219a7606b5)

**Comment by sangamesh27** [comment]
seems like this is not taking the autofill as completed field and we can't click the login button. It works fine once you refill the details.
