### ISSUE TITLE
feature:  Add Loading Animation When Clicking on questions in the Questions Section

### ISSUE THREAD

**Issue by ganeshkondaka** [code100x/cms#1264]
**When users click on a question in the Qqestions, there is a noticeable delay before the comments page loads, but there is no visual indication during this time.**

This can be confusing as users are unsure whether the action has been registered or if the page is loading.
users may accidentally click multiple times,

https://github.com/user-attachments/assets/e51ae5e1-a3cf-4d82-ae31-05cf4010ae81

**Comment by Dev79844** [comment]
Hey @ganeshkondaka!
I would like to take this up.

**Comment by Adiflickzzz** [comment]
Got it @ganeshkondaka ! .. This can be solved using useTransition() by react !

**Comment by Adiflickzzz** [comment]
![Screenshot 2024-09-19 175122](https://github.com/user-attachments/assets/fb657434-960b-45e1-ae09-3963a98d821d)
![Screenshot 2024-09-19 175108](https://github.com/user-attachments/assets/2bdcbe84-84c2-434c-8165-72684f0b44aa)
@ganeshkondaka 👋
If this is added to the **main div in PostCard.tsx** , will make the card pulse and not confuse the user after clicking it !
