### ISSUE TITLE
bug: Fix husky and prettier

### ISSUE THREAD

**Issue by Parikshit2001** [code100x/cms#1267]
**Describe the bug**
Whenever I'm making any commit to cms, husky is running pre commit prettier script and changing ~17 files

**To Reproduce**
1. set up the repo
2. make a small change
3. make a commit
4. revisit the diff in commit, it will show 17 files changed

**Comment by Parikshit2001** [comment]
<img width="732" alt="Screenshot 2024-09-19 at 1 07 02 PM" src="https://github.com/user-attachments/assets/53df0103-bb09-4807-aa15-8bd5d1188b42">
<img width="743" alt="Screenshot 2024-09-19 at 1 07 29 PM" src="https://github.com/user-attachments/assets/0f61e0de-3fc0-46f8-8967-6a611fb43ff1">

**Comment by wraith2009** [comment]
hey @Parikshit2001  for me i just ran a cmd npx husky-init and it was fixed and changing the files is prob due to linting issue . you can ask mods for the reason as i might be wrong

**Comment by Parikshit2001** [comment]
@hkirat what should we do
I also did not change anything in the husky
I just made a small change removing a unused import and made a commit
When the commit was being made, a prettier script ran which changed ~17 files
