### ISSUE TITLE
bug: Weeks data overflowing and not hiding under the course content thing

### ISSUE THREAD

**Issue by sahilc-xd** [code100x/cms#1269]
**Describe the bug**

The data for each week (Week 1, Week 2, Week 3, Week 4) is overflowing and is not being properly hidden when the user navigates the collapsed view under "Course Content." Instead of hiding the content, it remains visible, leading to layout overflow.

**To Reproduce**
Steps to reproduce the behavior:/

1.Load the course content page.
2.Collapse or expand the sections for Week 1, Week 2, etc.
3.Observe that the content for Week 4 overflows instead of being hidden properly under the collapsed sections.

**Expected behavior**
When the course content sections (Week 1, Week 2, etc.) are collapsed, the contents inside should hide properly. The overflowed content should only be visible when the section is expanded.

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/ac671834-a42b-4240-afbe-1c00cc655ceb)

Browser:chrome
latest version 

(Will be fixing this bug)

**Comment by wraith2009** [comment]
hi @sahilc-xd . I wanted to let you know that I’ve raised a PR for the issue you mentioned and made the necessary fixes as of yesterday.

**Comment by sahilc-xd** [comment]
Ohh it's okay , can you please let me know any bugs that have not been touched by anyone , any new bugs, anything

**Comment by sahilc-xd** [comment]
@wraith2009 any bugs that have not been touched , can you please mention them here or assign it to me please

**Comment by wraith2009** [comment]
i am not the moderator bro even i look for bugs . u can ask others or just
find one and update the mode on it . ask them to assign the bug to you. ofc
u can solve the bug and let them know at the same time
