### ISSUE TITLE
feature: Add pre-downloading of video to prevent buffering like on youtube

### ISSUE THREAD

**Issue by ashutosh017** [code100x/cms#1275]
I think currently app.100xdevs doesn't pre-download video like on youtube, hence it buffers a lot.

![no-predownloading](https://github.com/user-attachments/assets/09f4123a-07ac-4567-a044-f7f57fc881c7)

![predownloading-example](https://github.com/user-attachments/assets/44383e46-9581-49e5-adca-5932c0509952)

**Comment by CuriousCoder00** [comment]
I did some research on it and it can be done with defining preloading that suggests to the browser whether or not the video data should begin downloading as soon as the `video` element is loaded.
Need to do a few tests. @devsargam can you assign it to me?

**Comment by devsargam** [comment]
Cool guys

**Comment by devsargam** [comment]
Guys @ashutosh017 @CuriousCoder00 can u guys take it from here?

**Comment by devsargam** [comment]
Cool want to see the changes can u pr it?

**Comment by CuriousCoder00** [comment]
@devsargam I'm having a bit issue in raising the PR

**Comment by CuriousCoder00** [comment]
Hey @devsargam Upon further investigation, I found that video preloading does occur. However, it is not easily noticeable for longer videos. This behavior is also observed with YouTube videos. Please see the attached screenshot for reference.
![image](https://github.com/user-attachments/assets/53e0563a-41de-46ab-b68e-98754120da77)
