### ISSUE TITLE
bug: Video quality doesn't display when the screen is in white mode

### ISSUE THREAD

**Issue by sangamesh27** [code100x/cms#1276]
**Describe the bug**
When the background is switched to white mode from dark mode the numbers which tell the quality of video doesn't display/doesn't change the color of the text to black or opposite color.

**To Reproduce**
1. Go to any video and turn on white mode.
2. click on the video quality button.

**Expected behavior**
The color of the text should change to black or the opposite color text which it is supposed to change to.

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/ce146a69-6d81-485c-8a92-513208c8c6c5)

**Info (please complete the following information):**
 - Browser : Every browser

**Comment by sangamesh27** [comment]
If possible can I take up this issue?

**Comment by Karthik150502** [comment]
The tailwind part doesnt have any issues; as you can see;
![Screenshot 2024-09-20 120646](https://github.com/user-attachments/assets/1cb2d538-bde2-4a4b-ab9c-3aa8c5a741db)

But there is this property in sr/app/globals.css, that is overriding the tailwind;
![Screenshot 2024-09-20 120712](https://github.com/user-attachments/assets/b5fbb7b0-1d3f-4218-ba93-894687c723e0)

![Screenshot 2024-09-20 120753](https://github.com/user-attachments/assets/1448cbce-6e9d-4e13-91f6-37ff7b755c5a)

If we remove these from globals.css, i guess we would be good to go.

**Comment by sangamesh27** [comment]
oh okay good thing that it got identified. someone has to fix this right? who will be doing this? I haven't contributed even once so I was hoping if I could get the chance to learn something new by fixing this.
