### ISSUE TITLE
bug: watch history cards failing to redirect to the video for some reason 

### ISSUE THREAD

**Issue by shivaraj110** [code100x/cms#1279]
**Describe the bug**
watch history cards failing to redirect to the video for some reason 

**To Reproduce**
1. go to watch history
2. click on a card

**Expected behavior**
the video is expected to be displayed

**Screenshots or GIFs**
https://github.com/user-attachments/assets/9585cbed-397f-4de2-9cf4-e444ea204bc8

**Info (please complete the following information):**
 - Browser [firefox , Brave Browser]

**Comment by Adiflickzzz** [comment]
https://github.com/user-attachments/assets/fde3f3d0-7cbc-4bfd-b472-9979f55decb3

No issue to be found on Brave browser !

**Comment by Adiflickzzz** [comment]
Yeah working clear with firefox too .. will submit the proof in a while ..

**Comment by shivaraj110** [comment]
i did checking on all devices available on me with all the browsers...... may be it's the network problem or something...

**Comment by Adiflickzzz** [comment]
Yeah make sure and close the issue

**Comment by shivaraj110** [comment]
closed the issue as it was happening for me only.
