### ISSUE TITLE
bug: The course content overflowing into the heading, also decreases the visibility of closing icon.

### ISSUE THREAD

**Issue by raghavdutt28** [code100x/cms#1284]
**Describe the bug**
The course content overflowing into the heading, also decreases the visibility of closing icon.
**To Reproduce**
1. Open a course.
2. Click on "Show Contents".
3. Scroll down in the Course Content(if scroll is not available, you just have to open enough sub-folders).
4. See the content overflowing.

**Expected behavior**
It shouldn't overflow into heading, which will make even the closing icon more visible.
![image](https://github.com/user-attachments/assets/51f07bb0-add9-47ca-a2aa-5f3ab87109c3)

**Comment by Adiflickzzz** [comment]
This is the code for the background color in the codebase for the sidebar header ! 
![Screenshot 2024-09-20 194627](https://github.com/user-attachments/assets/1a4e02e6-5c14-4753-9ea0-d7b4e00841e1)

This is the code thats being exicuted in the browser !
![Screenshot 2024-09-20 194702](https://github.com/user-attachments/assets/2314f69f-ac10-407e-99f7-8a6267681b7e)

The background classnames are not being applied in the browser even if it is defined the code base ..

**Comment by CuriousCoder00** [comment]
It's working perfectly fine on local and this is the screenshot i got from browser in development mode.
![image](https://github.com/user-attachments/assets/7a874c10-f213-4326-9de5-57dc21b1331c)

Meanwhile this issue is persent in Production..

**Comment by Adiflickzzz** [comment]
Yeah ..

**Comment by raghavdutt28** [comment]
why would you close it?

**Comment by devsargam** [comment]
@raghavdutt28 closing a lot of issues that are a duplicate to one another
