### ISSUE TITLE
bug: docker-compose up fails

### ISSUE THREAD

**Issue by Manohar-Penta** [code100x/cms#1293]
**Describe the bug**
docker-compose fails with .next/BUILD_ID not found error.

**To Reproduce**
1. Clone the repo && cd into cms
2. run
3. bash "docker-compose up"

**Expected behavior**
app and database up and running

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/547b9316-24a4-48e0-ad40-5fe1a350fefe)

**Comment by adityapandey23** [comment]
Getting on it!

**Comment by adityapandey23** [comment]
Hey!
I did fix it please check #1297 !
I am new to this so do let me know if there is some error.

**Comment by arnab1656** [comment]
hey adityapandey23 is your #1297 merged? it causing a error

**Comment by adityapandey23** [comment]
@arnab1656 No! 
not yet
