### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by shahrukhshaikh19** [code100x/cms#13]
UI changes needed looking very basic fonts, sidebar, cards, sidebar, Navbar. We have to give proper feeling of educational website. Please accept I will start contribution.

**Comment by hkirat** [comment]
do u have suggestions? any designs/figma mockups?

**Comment by Praashh** [comment]
Can we use this design ?

[Screencast from 01-02-24 06:14:18 PM IST.webm](https://github.com/code100x/cms/assets/99237795/73dd6af5-dd42-4992-a9c0-bf3ac7cd7bf9)

**Comment by shahrukhshaikh19** [comment]
> do u have suggestions? any designs/figma mockups?

https://www.figma.com/file/ngdaUf3VJaRXfUa47iZqhc/Educational-site-design-1?type=design&node-id=0-1&mode=design&t=H5bo3KCuF2Jf55i2-0

https://www.figma.com/file/Equti3KAHNkrOToxFKPZpN/Untitled?type=design&node-id=1-3&mode=design&t=uD4XkZHhOBfaIgAV-0

https://www.figma.com/file/ec58XWOFCg8r3ggwPPCTBK/E-Learning-Website-Design-(Community)?type=design&node-id=0-1&mode=design&t=gQT12nU5bKk6DNfx-0

This is type of patterns we can follow.

**Comment by navdeepbhanderi** [comment]
> Can we use this design ?
> 
>  Screencast.from.01-02-24.06.14.18.PM.IST.webm

This looks great !

**Comment by hkirat** [comment]
Yeah need to integrate this
Tagging @tanayvaswani if you are free
