### ISSUE TITLE
feature: To add the email/ password required, and valid email notification in the sign in form. dynamically.

### ISSUE THREAD

**Issue by Karthik150502** [code100x/cms#1301]
**Is your feature request related to a problem? Please describe.**
There is not warning to the user when they enter a invalid email, and when either of the fields in sign in form are empty.

**Solution**
To add the email/ password required, and invalid email notification in the sign in form. Using Zod.

https://github.com/user-attachments/assets/6cde0b6a-c306-4dac-80d4-f65386469e4a

Can i get this done, if it looks like a good thing to add?

**Comment by sumukhj1219** [comment]
assign me

**Comment by sumukhj1219** [comment]
@Karthik150502 i think we can make use of regix here which can easily detect the invalid email and password as it should be min 8 characters

**Comment by kumawatkaran523** [comment]
can I Try

**Comment by kumawatkaran523** [comment]
can I Try

**Comment by devsargam** [comment]
This is not useful. There's no requirement that the input should only be email. You can even try with using phone number it should work good
