### ISSUE TITLE
bug: Course Content aside Transparent Background

### ISSUE THREAD

**Issue by Bhavesh-0909** [code100x/cms#1307]
**Describe the bug**
Heading of aside sheet has transparent background which is not looking good.

![Screenshot 2024-09-23 185535](https://github.com/user-attachments/assets/7234c911-fa5a-4b6b-93e1-afcaac16851b)

**To Reproduce**
1. Asign background colour to the heading div.

**Expected behavior**
In Background of heading there should be no overlapping.

**Info (please complete the following information):**
 - Browser (Microsoft Edge)
 - Version [latest]

**Comment by anshumisra** [comment]
i am working on this

**Comment by anshumisra** [comment]
![image](https://github.com/user-attachments/assets/f3b484f2-3701-4288-bef7-be3ad5d1178f)

is the issue still visible?, for me the heading is not overlapping

**Comment by Bhavesh-0909** [comment]
I think this bug has been fixed by ui change pr
