### ISSUE TITLE
feature: Autoplay the next video after completion of one

### ISSUE THREAD

**Issue by SanjanaSogimatt** [code100x/cms#1308]
**Is your feature request related to a problem? Please describe.**
It is a hassle when the video ends and you have to go to contents tab and play the next video. Not sure if it's just me facing this issue but it is annoying

**Describe the solution you'd like**
I would want my next course video to be autoplayed whenever the present video ends. Just like the Youtube autoplay

**Describe alternatives you've considered**
Or maybe have a button in the corner which on clicking it redirects to the next video

I feel like it's doable for me, would like to work on this feature enhancement

**Comment by anshumisra** [comment]
I am working on this

**Comment by SanjanaSogimatt** [comment]
@hkirat @devsargam I believe this can be useful. Would it be okay if I work on this and submit a pull request?

**Comment by SahilLamba0008** [comment]
I would love to work on this. Can someone assign this to me ?

**Comment by shamun-khatri** [comment]
Who is working on this? Please assign that person. Otherwise, I can work on this.

**Comment by devsargam** [comment]
Anyone who makes the first pr. I will merge that

**Comment by Jatin123lodhi** [comment]
I am starting on it.

**Comment by SahilLamba0008** [comment]
@devsargam can you review my pr ?

**Comment by devsargam** [comment]
Out of scope for now
