### ISSUE TITLE
feature: Show the titles of the videos on the banner of weekly posted videos. 

### ISSUE THREAD

**Issue by mortale2004** [code100x/cms#1312]
Whenever I am visiting my course then I need to go thorough the each weekly videos group section to find where is that topic is taught.

**Comment by devsargam** [comment]
Can someone create like a tooltip or something that will do it?

**Comment by Jatin123lodhi** [comment]
okay I will do it @devsargam

**Comment by Jatin123lodhi** [comment]
@devsargam https://github.com/code100x/cms/pull/1429    please reivew

**Comment by devsargam** [comment]
@Jatin123lodhi for the rescue this is done
