### ISSUE TITLE
feature: Show the titles of the videos on the banner of weekly posted videos. 

### ISSUE THREAD

**Issue by mortale2004** [code100x/cms#1313]
Whenever I am visiting my course then I need to go thorough the each weekly videos group section to find where is that topic is taught. 
Ex. 
I need to click on this banner then I can see the contents of that week. This is bad way to find any video.

Improvements: 
1. Can I see the contents of that week directly on the banner of each week.
2. Highlight the contents which is not completed.
![Screenshot from 2024-09-25 09-16-54](https://github.com/user-attachments/assets/92259b1d-bbc5-4e00-bf20-46f9bbd16443)
![Screenshot from 2024-09-25 09-17-05](https://github.com/user-attachments/assets/a39d8dec-ac9f-4a49-bacd-65d9c8f4630d)

**Comment by mortale2004** [comment]
Hey @hkirat shall I procced for it to add this feature.

**Comment by devsargam** [comment]
You can just use the search box

**Comment by mortale2004** [comment]
You are saying just use search box, What if user doen't know the topic name then he needs to go through each week video. I want to add this feature because already data is coming from the backend and we are just showing the titles of the video so it is worthful.

**Comment by mortale2004** [comment]
Hello reviewer I'm waiting for reply!
