### ISSUE TITLE
bug :  Video Format Change Fails (Server or Network Error)

### ISSUE THREAD

**Issue by Rihanmulani12** [code100x/cms#1321]
Description: When attempting to change the video format (e.g., from 720p to 360p), the application displays an error message stating either "Server failed" or "Network failed." This issue occurs intermittently and prevents users from successfully switching video formats.

Steps to Reproduce:

Start the video playback in 720p.
Attempt to change the video format to 360p.
Observe that the application shows an error: "Server failed" or "Network failed."
Expected Behavior: The video format should change seamlessly between 720p and 360p without any errors.

Request to Work on the Issue: I would like to contribute by working on fixing this issue. If no one else is currently assigned to this, could I take it up? Please let me know if I can proceed or if there are any specific guidelines I should follow.

![100xdev bug](https://github.com/user-attachments/assets/befce7e9-a41f-4324-b8c9-0781fc8ca17d)

**Comment by raghavsingh05** [comment]
This issue may be due to some server error in the backend. Because if I try to play a video it shows the above error without me switching the video format...

example--- 

https://github.com/user-attachments/assets/a88c7cd7-e6e5-4283-bb60-2209cd5f6774

**Comment by SanjanaSogimatt** [comment]
It's happening to me as well. Any solution?

**Comment by mdsaqlainahmed786** [comment]
"The media could not be loaded, either because the server or network failed or because the format is not supported."
when i open the video lecture of week 10-19. Its been 2 days by this bug. Do anyone know how to fix it?

**Comment by devsargam** [comment]
This is nothing wrong with the codebase closing
