### ISSUE TITLE
bug: "Toast message shows incorrect feedback when removing an upvote  or downvote on a comment"

### ISSUE THREAD

**Issue by NawinKumarSharma** [code100x/cms#1322]
Describe the bug
When a comment is upvoted, the toast message correctly shows "Comment has been upvoted." However, when the user removes the upvote by clicking again, the same toast message ("Comment has been upvoted") is shown instead of indicating that the vote has been removed and similar for downvoting as well

To Reproduce

1. Upvote a comment.
2. Observe the toast message "Comment has been upvoted."
3. Remove the upvote by clicking the upvote button again.
4. The toast message again says "Comment has been upvoted" instead of indicating that the vote was removed.
similarly,
1. Downvote a comment.
2. Observe the toast message "Comment has been downvoted."
3. Remove the downvote by clicking the downvote button again.
4. The toast message again says "Comment has been downvoted" instead of indicating that the vote was removed.
Expected behavior
When the user removes the upvote, the toast message should display "Vote has been removed" or something similar, instead of "Comment has been upvoted."

Screenshots or GIFs
If applicable, add screenshots or GIFs to help explain the problem.
[Screencast from 2024-09-25 20-14-11.webm](https://github.com/user-attachments/assets/fd0b0fa0-00be-4ef4-9117-f0acfc742bd8)

Info (please complete the following information):

Browser: [e.g., Chrome, Safari]
Version: [e.g., 22]
Additional context
The issue seems to be related to the handleVote logic in the voting component, which does not differentiate between adding a vote and removing a vote.

**Comment by yuvrajinbhakti** [comment]
Hi @NawinKumarSharma , can you assign this issue to me.
