### ISSUE TITLE
feature: create a beautiful readme for the project

### ISSUE THREAD

**Issue by devsargam** [code100x/cms#1328]
Things to include:
- Main heading
- Running locally (tell them using mannual method is better as compared to docker)

**Comment by CuriousCoder00** [comment]
@devsargam I'm taking it.. assign it to me please..!!

**Comment by devsargam** [comment]
@CuriousCoder00 don't overcomplicate but make it simple and well documented

**Comment by CuriousCoder00** [comment]
@devsargam can you check if this much is fine? https://github.com/CuriousCoder00/percept-ui/blob/main/README.md

**Comment by devsargam** [comment]
Looks a bit off

**Comment by devsargam** [comment]
https://github.com/kubernetes/kubernetes

**Comment by CuriousCoder00** [comment]
Got it.. I'll be provide screenshots before raising a pr

**Comment by CuriousCoder00** [comment]
@devsargam Please review the changes made to the README and let me know if any additional modifications are needed.
