### ISSUE TITLE
bug: The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by mdsaqlainahmed786** [code100x/cms#1330]
This error is been shown since last 2 days. well its not this is the first video of the course, i have been watching this course from start and never happend this bug in my browser. I've tried everything from updating the chrome to clearing the cache. And yes, Reloading is also not working here. 
![Screenshot 2024-09-26 073048](https://github.com/user-attachments/assets/ae794e3f-f54a-47f9-821d-9908f734e9b1)
and there is the error of network of bad gateway(502) 
![Screenshot 2024-09-26 073234](https://github.com/user-attachments/assets/2b158f3a-f28a-46ce-97bb-e683e37ec757)

**Comment by ThatRandomGuy09** [comment]
![Screenshot (154)](https://github.com/user-attachments/assets/5cb5c1a1-56f6-46d7-b3be-a7d991ee93cd)

**Comment by ThatRandomGuy09** [comment]
![Screenshot (154)](https://github.com/user-attachments/assets/2a7cf0ce-7c21-47e8-8121-0dd21f1c8fec)

**Comment by raghavsingh05** [comment]
It has been updated, Please remove the issue @mdsaqlainahmed786
