### ISSUE TITLE
bug: Greeting problem 

### ISSUE THREAD

**Issue by saurabhraghuvanshii** [code100x/cms#1334]
As now time is 14:22 PM and greeting message should be Good Afternoon but it Show Good morning to user.

![Screenshot 2024-09-27 144628](https://github.com/user-attachments/assets/d6d877a5-d9fe-4a12-a676-01e07deb8076)

As you seen in screenshot ,
I think it is just logical error.

**Comment by raghavsingh05** [comment]
Hey, @saurabhraghuvanshii this bug has already been resolved in previous PRs, and it will soon be updated on the main website. We have CI pipelines but don't have CD (@devsargam please correct me if I am wrong), so there is a delay. 
![image](https://github.com/user-attachments/assets/7f7b1725-b077-4ad3-8f13-0acc3a03f9ce)

**Comment by devsargam** [comment]
Yep ur right

**Comment by saurabhraghuvanshii** [comment]
I think , it is problem from page.tsx file which in src/app/admin
