### ISSUE TITLE
feature: Add Success stories on the landing page with Twitter Posts

### ISSUE THREAD

**Issue by parthiv011** [code100x/cms#1347]
**Is your feature request related to a problem? Please describe.**
Yes, the current landing page lacks a section that showcases the success stories of students who have brought the cohort and gained some jobs/internships. Adding success stories could help to build trust, provide social proof and better communicate the benefits of the cohort.

**Describe the solution you'd like**
I would like to get the data of reported tweets from Kirat Sir's handle and showcase the tweets on the landing page of app.100xdevs.com. With a simple animation of vertical marquee for displaying the tweets. And also should be responsive for all the windows (tabs, screens, mobiles, ipads etc).

**Additional context**
The UI will look somewhat like this after building it

![Screenshot (27)](https://github.com/user-attachments/assets/7cd83241-8ebb-4227-be76-10ffd236e9f8)

**For Tablet View**

![Screenshot (29)](https://github.com/user-attachments/assets/b7e37873-e45e-4ad8-aa1b-33ff440b86c5)

**For Mobile View**

![Screenshot (30)](https://github.com/user-attachments/assets/24c42a1b-4ec1-416f-b461-a094a69432b4)

I would be happy to work on the feature if assigned.
Thank you.

**Comment by Vineetchelani1304** [comment]
can start working on it ?

**Comment by anshux1** [comment]
i already open a pr related to this but #1242 got rejected..

**Comment by parthiv011** [comment]
> can start working on it ?
> 

Already started 🫡

**Comment by parthiv011** [comment]
> i already open a pr related to this but #1242 got rejected..

This is different from your issue bro. This is not same as yours

**Comment by devsargam** [comment]
@hkirat @siinghd can u tell me if this is needed or not?

**Comment by devsargam** [comment]
<img width="497" alt="image" src="https://github.com/user-attachments/assets/1e939e71-f396-442b-aaa5-7ce572d9d3c5">
