### ISSUE TITLE
bug: Content of Sidebar UI in not appropriate in fixed sequence 

### ISSUE THREAD

**Issue by yadavshubham01** [code100x/cms#1348]
**Describe the bug**
sidebar in which my content is not fixed in on line when size decrease to  medium how to fixed it

**To Reproduce**
1. open 100xdev website
2. go to any course 
3. click on show content button 
4. decrease size medium of website
5. scroll down to week-10,11

**Expected behavior**
content in show content button is in fixed sequence and order

**Screenshots or GIFs**
![Screenshot 2024-09-29 110353](https://github.com/user-attachments/assets/ca8c93ad-87a2-4106-a00e-831adf2138ae)

**Info (please complete the following information):**

**Additional context**

**Comment by sudoarchie** [comment]
i am working on this issue
