### ISSUE TITLE
Optimizing User Experience: Ensuring Seamless Video Navigation with Static Menus.

### ISSUE THREAD

**Issue by sameer93a** [code100x/cms#135]
Would you kindly ensure that when clicking on the next video, only the video side changes, while the menu on the left side remains static? It would be greatly appreciated if the submenu, such as the Week-3 subfolder, stays open when selecting a new video within it. Thank you very much for your attention to this matter.

**Comment by Sameer93A** [comment]
[Screencast from 2024-02-29 18-10-39.webm](https://github.com/code100x/cms/assets/121109714/157832b1-cb83-4e77-893e-6efa9e8ac26d)

**Comment by Sameer93A** [comment]
[Screencast from 2024-02-29 18-10-39.webm](https://github.com/code100x/cms/assets/121109714/0fe2fad0-7695-4090-b63a-5d23d3cf8765)
