### ISSUE TITLE
bug: The timestamp and preview thumbnail are overlapping. 

### ISSUE THREAD

**Issue by aadubey01** [code100x/cms#1350]
**Describe the bug**
The timestamp and preview thumbnail are overlapping. 

**To Reproduce**
1. Open any video and hover over the progress bar
2. The timestamp and  preview thumbnail will overlap

**Expected behavior**
The preview thumbnail must be at bottom of progress bar .

**Screenshots or GIFs**
![Screenshot 2024-09-30 103512](https://github.com/user-attachments/assets/061d69b2-5fb8-4e1f-aa14-430780d5ee79)
.

**Info (please complete the following information):**
 - Browser Chrome
 - Version 129.0.6668.60 

**Additional context**

**Comment by sudoarchie** [comment]
working on this
