### ISSUE TITLE
feature: create a new accessibility label

### ISSUE THREAD

**Issue by Chityalaakhil** [code100x/cms#1355]
**Is your feature request related to a problem? Please describe.**
I'm seeing some accessibility issue on the site and I've been creating issues for them as bugs which are not really a bug but things that would be great to have.

**Describe the solution you'd like**
Create a new accessibility label to categorize issues properly.

**Describe alternatives you've considered**

**Additional context**
I would suggest adding axeDevTools chrome extension to find accessibility issue on any page. 
![image](https://github.com/user-attachments/assets/fdb6a169-fd2f-42cb-bf3d-ce93548e170d)

**Comment by devsargam** [comment]
We can probably ignore all these
