### ISSUE TITLE
When closing the sidebar using the cross button the video box is not responsive

### ISSUE THREAD

**Issue by shkhrtrxsh** [code100x/cms#136]
https://github.com/code100x/cms/assets/68225661/ec6cf524-c7a1-432c-9ddc-d8602bf8384c

**Comment by MangaByteCoder** [comment]
Can you elaborate on issue a bit more?

**Comment by shkhrtrxsh** [comment]
when we close the side bar on web screen then the video height does not fit the view height of the screen it overflows. Please watch the demo video I have provided.
