### ISSUE TITLE
bug: not able to select cards as a keyboard user

### ISSUE THREAD

**Issue by Chityalaakhil** [code100x/cms#1360]
**Describe the bug**
As a keyboard user, I'm not able to select and navigate to the weeks page by selecting the cards as the card is not receiving focus.

**To Reproduce**
1. Head to https://app.100xdevs.com/
2. Use keyboard to navigate the site (using tab).
3. Navigate to /courses/[id] page
4. And tab through the elements and notice that week cards won't receive focus and not able to select any week.

**Expected behavior**
Using tab to move focus to week cards, they should receive focus and moving focus onto them and pressing enter should take user to that specific page. 

**Screenshots or GIFs**

https://github.com/user-attachments/assets/9371320f-3ebb-46ff-92be-d1eda13d0f31

**Info (please complete the following information):**
Browser [e.g. Edge ]
Version [e.g. 129.0.2792.65]

**Comment by Jatin123lodhi** [comment]
I have raised a pr for this.

**Comment by Jatin123lodhi** [comment]
https://github.com/code100x/cms/pull/1363
