### ISSUE TITLE
bug: Can't able to Bookmark the video, having longer title.

### ISSUE THREAD

**Issue by Hemanth-Thaluru** [code100x/cms#1361]
**Describe the bug**

If the Title length of video is longer than sidebar div, then title is truncated.
Because of this truncation can't able to read full title and also can't bookmark the video, from the side bar.

**To Reproduce**
1. Do something
 Open any video having long title in sidebar.

2. See error
 Can't see full title and its bookmark icon

**Expected behavior**

Should show full title either by expanding the height of title div or by using tool tip and mainly bookmark icon should be visible regardless of title size.

**Screenshots or GIFs**
<img src="https://github.com/user-attachments/assets/d305d5df-2164-4934-9dac-c53b892753fc" alt="image" width="400"/>
<img src="https://github.com/user-attachments/assets/992de945-ed52-4763-be8e-bdde0b9fb2a6" alt="image" width="400"/>

**Info (please complete the following information):**
 - Browser : All browser 
 - Version : All Versions

**Comment by shamun-khatri** [comment]
Can I work on this? please assign me.

**Comment by Hemanth-Thaluru** [comment]
Hey @shamun-khatri , I'm on cohort -2 and my resolution set to default (100%) on a MacBook Air.
May be in cohort -3, the long titles weren't present for any video !!

**Comment by anpc21** [comment]
Hey @Hemanth-Thaluru 
Even i couldnot find ths as bug.
![Screenshot 2024-10-02 200653](https://github.com/user-attachments/assets/8341abea-7837-41aa-9760-5cffa30e6eaf)

**Comment by Hemanth-Thaluru** [comment]
Hello @anpc21 , that's strange! This is what I'm seeing on my end for cohort-2. 
I assume it's only happening with long titles!

https://github.com/user-attachments/assets/95fca7bc-f065-4af2-a1dd-726918940043
