### ISSUE TITLE
bug: Conents button width changing while toggling

### ISSUE THREAD

**Issue by durgaprasad118** [code100x/cms#1364]
**Describe the bug**
Contents button width changing while toggling between hide and show

**To Reproduce**
- fix the width of the button

**Expected behavior**
The width of the button should be same for both the options (hide/show)

**Screenshots or GIFs**

https://github.com/user-attachments/assets/bed9a48f-0060-4c87-b444-3741b4957eb6

**Comment by durgaprasad118** [comment]
@devsargam can you assign this to me.

**Comment by devsargam** [comment]
Don't think this is a issue. Buttons are ment to be dependent on the content width
