### ISSUE TITLE
bug: GitHub Link Redirect Problem

### ISSUE THREAD

**Issue by mutaliksamarth** [code100x/cms#1367]
**Describe the bug**
GitHub Assignments Link in the app.100xdev.com redirects to Cohort 2 assignments, but I have purchased Cohort 3.

**To Reproduce**
1. Go to app.100xdev.com/home
2. Click on Your Profile
3. Goto Github Assignments 
4. Redirects to Diffrent Cohort Assignments

**Expected behavior**
If the user has purchased Cohort 2, they should be redirected to Cohort 2 assignments. If the user has purchased Cohort 3, they should be redirected to Cohort 3 assignments.

**Comment by mutaliksamarth** [comment]
@hkirat Small bug, but I think it matters.

**Comment by yuvrajinbhakti** [comment]
Hi @mutaliksamarth , can you assign this issue to me.

**Comment by gupta-soham** [comment]
#1270 resolves this

**Comment by devsargam** [comment]
This is done
