### ISSUE TITLE
feat: Multistage Dockerfile

### ISSUE THREAD

**Issue by geekyharsh05** [code100x/cms#1368]
Issue:
- Currently the next-app build image have an enormous size. Adding a multistage docker file to reduce the size of the image.

**Comment by geekyharsh05** [comment]
@devsargam Can you please assign me?

**Comment by TanmayDhobale** [comment]
On it

**Comment by geekyharsh05** [comment]
@TanmayDhobale Can I do this?

**Comment by geekyharsh05** [comment]
@TanmayDhobale I have almost done it can I take this one?

**Comment by TanmayDhobale** [comment]
> @TanmayDhobale I have almost done it can I take this one?

Yea yea
