### ISSUE TITLE
feature: Create github worklow to assing issue to users on comment `take` or `any command to trigger action`

### ISSUE THREAD

**Issue by CuriousCoder00** [code100x/cms#1377]
Users can comment `take` or `any command to trigger action` on an issue to be auto-assigned the issue.

This creates a good experience for OSS users. They can grab an issue and it will make sure nobody else is assigned/working on it.

![image](https://github.com/user-attachments/assets/845e929e-c3ae-4933-88cd-50b6d9462264)

**Comment by CuriousCoder00** [comment]
If it needs to be implemented, please assign it to me @devsargam @siinghd

**Comment by geekyharsh05** [comment]
@CuriousCoder00 make it as /assign.

**Comment by CuriousCoder00** [comment]
yes, i mentioned it as any command can be given as input in workflow

**Comment by gauravkumar065** [comment]
have raised PR for this: https://github.com/code100x/cms/pull/1378

**Comment by CuriousCoder00** [comment]
@gauravkumar065 could've given a heads up before making the PR
