### ISSUE TITLE
bug: Show Content button overlapping the title of the video.

### ISSUE THREAD

**Issue by iamransh** [code100x/cms#1380]
**Describe the bug**

The Show Content button used to open the side drawer is overlapping the video title.

**Expected behavior**

The button should appear either above or before the video title. 

**Screenshots or GIFs**

![Screenshot 2024-10-03 071542](https://github.com/user-attachments/assets/bca24332-d564-4de2-959f-38bd279fbd70)

**Comment by iamransh** [comment]
@devsargam @siinghd should i fix this?

**Comment by Husain01** [comment]
I'd like to work on this. Seems like it's from a recent build that the issue stemmed out from.

**Comment by iamransh** [comment]
I think #1382 opend the issue and has already raised a PR for it.

**Comment by iamransh** [comment]
> I'd like to work on this. Seems like it's from a recent build that the issue stemmed out from.

I think #1382 opened the same issue and has already raised a PR for it.

**Comment by Bgmi10** [comment]
i fixed the issue 
<img width="960" alt="hk1" src="https://github.com/user-attachments/assets/30287566-368b-4a51-8830-7b88f3db6540">
