### ISSUE TITLE
bug: Hide Contents button is inconsistent.

### ISSUE THREAD

**Issue by iamransh** [code100x/cms#1381]
**Describe the bug**

If you try to close the side drawer using the hide contents button, it only works if you click on the 'X' icon, otherwise if you click anywhere else on the button instead of the the 'X' icon, the side drawer closes only for a brief second and then reopens automatically.

**To Reproduce**

1. Open the side drawer by clicking on the show contents button.

2. Try to close the side drawer by clicking on the hide contents button except for the 'X' icon.

**Expected behavior**

The side drawer should close by clicking anywhere on the hide contents button.

**Screenshots or GIFs**

https://github.com/user-attachments/assets/14fb3231-6cea-4ef3-a965-509cc27b2b30

**Comment by atul24112001** [comment]
Hey, I want to work on this

**Comment by Husain01** [comment]
I want to work on this! Seems like it's from a very recent build issue only.

**Comment by sidpan2011** [comment]
Hey, just came here to report the issue, but already created. I want to work on the above mentioned issue. I have checked, for sm: screen size, not getting the issue, so this might get fix with some tweaks in position for the breadCrumps.
