### ISSUE TITLE
bug: Unauthorized Access to Unpurchased Course Content in Search API

### ISSUE THREAD

**Issue by kushwahramkumar2003** [code100x/cms#1384]
**Description**
The `/api/search/route.ts` endpoint allows users to search and view content from courses they haven't purchased, including specific cohorts (e.g., Cohort 2). This bypasses our content access policies and payment system.

**To Reproduce**
1. Log in with a user account that hasn't purchased Cohort 2
2. Use Postman: GET `/api/search?q=cohort_2_specific_term`
3. Observe results include Cohort 2 content
4. Alternatively, use the platform's search bar to find Cohort 2 content

**Expected Behavior**
- Users should only see results from purchased courses and open courses
- Searches for unpurchased content should return no results
- Admins should have full access to all content

**Proposed Fix**
1. Implement authentication checks
2. Filter search results based on user purchases and permissions
3. Allow admin access based on email addresses in env variable
4. Update `/api/search/route.ts` with these changes

**Testing Instructions**
Test with:
1. Unauthenticated user (expect 401)
2. Regular user (verify access to purchased/open content only)
3. Admin user (verify full access)
4. Check caching and performance

**Severity**
High - Allows unauthorized access to paid content

**Video**

https://github.com/user-attachments/assets/0a797742-804a-4902-b578-3965ce66b128

**Comment by devsargam** [comment]
Closing will merge the pr shortly
