### ISSUE TITLE
bug: show content button hide the Breadcrumb

### ISSUE THREAD

**Issue by iam-prabha** [code100x/cms#1389]
**Describe the bug**
show content button position hide breadcrumb !!

**Screenshots or GIFs**
![Screenshot from 2024-10-03 12-18-58](https://github.com/user-attachments/assets/1bcebaeb-ecf6-43db-bc65-964ff56e946d)

**Info (please complete the following information):**
 - Browser : chrome
 - Version : Version 129.0.6668.58 (Official Build) (64-bit)

**Comment by yuvrajinbhakti** [comment]
Hi @iam-prabha , can I work on this issue.

**Comment by yadavshubham01** [comment]
but when i setup this project it does not show this error @iam-prabha 
![Screenshot 2024-10-03 141633](https://github.com/user-attachments/assets/466d50a1-d1dd-4cac-aa62-2a96049a023c)

**Comment by iam-prabha** [comment]
See in live website
