### ISSUE TITLE
Landing Page Navbar (Mobile)

### ISSUE THREAD

**Issue by itssishann** [code100x/cms#139]
This **issue** is on **mobile Side..**
When **theme is light** and click on **hamburger** button the **join now** button is not in blue color !
image attached 
![Mobile-error](https://github.com/code100x/cms/assets/73055623/8f4c02e2-3dd3-446d-91ed-b7e6d9187ae0)

**Comment by naman933** [comment]
Able to resolve the issue, do assign this issue to me. It is a simple one
