### ISSUE TITLE
bug: Sidebar overlapping on main content when not collapsed

### ISSUE THREAD

**Issue by abhisektomar1** [code100x/cms#1397]
**Describe the bug**
When User Open the sidebar, it  overlaps on main content and navbar as well which cause some data to hide. 

**To Reproduce**
1. Login 
2. Open Sidebar

https://github.com/user-attachments/assets/95e2384e-01a8-427d-9d0f-b5c9123166d7

**Expected behavior**
When open the side bar the other content should shift toward right with navbar so that all the main content must visible and accessible.

https://github.com/user-attachments/assets/e559edc2-6dec-43c4-b45f-1083288b73d9

**Comment by devsargam** [comment]
This is the expected behaviour. It's similar to how right side bar is working

**Comment by abhisektomar1** [comment]
No the expected behaviour should be that the main content should shift to right. because now when i open the navbar it is overlapping on other buttons like this one and also on many places do you think this is good.
![Screenshot 2024-10-05 105505](https://github.com/user-attachments/assets/10aa9d66-7848-4947-ae2d-2753c024919c)

Now do you think this is a good behaviour. bro you can check any other website you will never find overlapping content in good websites.
