### ISSUE TITLE
Sidebar should be fixed

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#14]
shouldnt scroll down
<img width="1138" alt="Screenshot 2024-02-01 at 1 17 21 PM" src="https://github.com/code100x/cms/assets/8079861/ac103793-9105-4e81-8391-aae514471bb6">

**Comment by tejaskh3** [comment]
Hello @hkirat  as I am already working upon the sidebar in the issue #6 I guess I can deliver this more efficiently. So, if that works for either assign this task to me.
