### ISSUE TITLE
bug: Incorrect message when removing upvote or downvote

### ISSUE THREAD

**Issue by raghavsingh05** [code100x/cms#1401]
**Describe the bug**
When a user removes an upvote or downvote on a comment, the success message always displays "Comment has been upvoted" or "Comment has been downvoted," even when the vote is being removed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Upvote or downvote a comment.
2. Remove the upvote or downvote.
3. Notice that the message still says the comment has been upvoted or downvoted, even when removing the vote.

**Expected behaviour**
A clear message indicating whether the upvote or downvote has been removed should be displayed. For example:
- "Upvote has been removed."
- "Downvote has been removed."

**Video of the Bug**

https://github.com/user-attachments/assets/e406966c-7dd2-43a0-b53a-a518abe51573

**Additional context**
This bug can cause confusion for users, as they are not clearly informed whether their vote has been removed or added. Clarifying the messages will improve user experience.

**Comment by raghavsingh05** [comment]
Hey, I just saw this issue has already been fixed recently, it's just not deployed yet. I am closing this PR. Sorry for the inconvenience.

**Comment by devsargam** [comment]
This has been fixed sir
