### ISSUE TITLE
bug: Text Overlap - Show Content Bar & Cohort 3.0 | Web Dev 

### ISSUE THREAD

**Issue by furyfist** [code100x/cms#1404]
Show Content Bar & Cohort 3.0 | Web Dev  **Text Overlaps**

**Screenshot**
![Bug 1 ss](https://github.com/user-attachments/assets/83ab7bc3-4a58-48a2-a827-79b38fecaab9)

**Video**
https://github.com/user-attachments/assets/81d772cb-6474-419c-8725-7da68df22114

**Comment by DevHrithik** [comment]
hey can i pick this issue

**Comment by furyfist** [comment]
Yes yes
