### ISSUE TITLE
feature: Improve the visibility/ readability 

### ISSUE THREAD

**Issue by dhruv-goyal-10** [code100x/cms#1405]
**Is your feature request related to a problem? Please describe.**

I found some places where readability can be improved.
<img width="404" alt="image" src="https://github.com/user-attachments/assets/959a7490-58b5-409d-89df-e268d61bae90">
<img width="90" alt="image" src="https://github.com/user-attachments/assets/398fd5d8-0474-45df-8bbe-741a37246f58">

**Describe the solution you'd like**
We should try avoiding these kinds of color combinations, where the contrast between foreground and background is very less, or change the foreground to black or white accordingly.

**Describe alternatives you've considered**
None

**Additional context**
You can find the above images in tags for questions at https://app.100xdevs.com/question

**Comment by sitanshu05** [comment]
Would like to work on this issue, I plan to create tag colours both for dark and light modes and add the swap, as this issue occurs only on light mode and requires clarity on a few things,
1. Do we use a fixed number of colours and reuse them if tags exceed
2. Ideally tag colors should indicate something so would it be better if we use the same color for all tags as the colors are randomly assigned

**Comment by sharabhh** [comment]
Hello, @sitanshu05 I was wondering If you're still working on this? 
If not please let me know and can this be assigned to me in that case @devsargam

**Comment by sitanshu05** [comment]
> Hello, @sitanshu05 I was wondering If you're still working on this? If not please let me know and can this be assigned to me in that case @devsargam

Yes I am working on it

**Comment by sitanshu05** [comment]
Is this okay? the tags look much cleaner and go well with the theme of the site 
<img width="1217" alt="Screenshot 2024-10-06 at 6 40 48 PM" src="https://github.com/user-attachments/assets/029f9820-c96c-44f1-873c-dd8842a7fdb3">
