### ISSUE TITLE
bug: Refresh Database action resulting in 500 error most of the times

### ISSUE THREAD

**Issue by dhruv-goyal-10** [code100x/cms#1407]
**Describe the bug**

1. Refresh Database button at the end of the home page, which is used to fetch the refreshed courses, is resulting in an 500 response, most of the times.
2. Sometimes, it is getting success (200) response as well.

<img width="1374" alt="image" src="https://github.com/user-attachments/assets/3efd9e97-d1f8-46a0-a4fc-aaf233e22954">

**To Reproduce**

1. Just click on Refresh Database Button at the end of home page. 
2. Try doing multiple clicks during an interval, if the first response is success.
3. You will be able to see 500 error in the API response, at least in one of the calls.

**Expected behavior**
Success Response in every API call, or show error if there is any.

<img width="1328" alt="image" src="https://github.com/user-attachments/assets/7872f331-b842-40fc-b87e-7718182e51bd">

**Info (please complete the following information):**
 - Chrome/ Brave

**Comment by devsargam** [comment]
You can ignore that no need to worry about it

**Comment by devsargam** [comment]
It's only needed for prod

**Comment by sudoarchie** [comment]
I don't think there is an error in Prod 
![image](https://github.com/user-attachments/assets/f7442248-7e2a-4fc1-af68-71875f268cab)

**Comment by devsargam** [comment]
You don't need to worry about it locally. It is just in production
