### ISSUE TITLE
feature: Implement automatic checkbox selection and progress calculation when a video is viewed to enhance user experience and track completion.

### ISSUE THREAD

**Issue by Vinit1014** [code100x/cms#1408]
**Is your feature request related to a problem? Please describe.**
Manual checkbox checking after watching a video can be inconsistent and often forgotten, leading to inaccurate progress tracking.

**Describe the solution you'd like**
Automatically check the box when the video is viewed 90% and calculate the progress in real time to ensure accurate tracking.

**Describe alternatives you've considered**
Allowing users to manually check the box or add a completion button at the end of the video.

**Additional context**
This feature would streamline progress tracking and improve user experience.

**Comment by devsargam** [comment]
This makes sense good feature to add. I think we do check it when the video is completely played though

**Comment by Vinit1014** [comment]
Yeah, I thought to implement that as the user completes 90% of video lecture, check the box.
