### ISSUE TITLE
bug: Show Contents Button Glitch

### ISSUE THREAD

**Issue by mishrayush15** [code100x/cms#1412]
**Describe the bug**
The "SHOW CONTENTS" button on the webpage of https://app.100xdevs.com/ is showing some unusual behavior. It's usual functionality is to show the side menu that has the list of all the videos folder wise (Week Folders). But whenever someone clicks on the middle part of the button or on the area of the button apart from the "Hamburger" icon of the same button, the side menu flickers. The side menu opens and closes and again opens. But if someone clicks on the "Hambuger" icon of the "Show Contents" buttonthen it is functioning as expected without any errors or glitches. 

**To Reproduce**
1. Click on any part of the "Show Contents" button apart from the "Hamburger" icon of the button

**Expected behavior**
The button is expected to OPEN and CLOSE the side menu bar whenever someone clicks on the button regardless of any part clicked of that same button.

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/66fc02e7-0f69-49fe-970a-540e73ea7b57)

**Info**
 - Browser -> Microsoft Edge
 - Version -> 129.0.2792.65

**Comment by Husain01** [comment]
Can I pick this up?

**Comment by jagadeeshm2002** [comment]
just remove xl:absolute in show contents button
