### ISSUE TITLE
bug:  Bookmark in Courses section isn't working

### ISSUE THREAD

**Issue by Hemanth-Thaluru** [code100x/cms#1413]
**Describe the bug**
When I attempt to bookmark an entire week in the Courses section, none of the videos from that week are bookmarked.

**To Reproduce**
* Open the Courses section and try to bookmark the whole week.
* Open the bookmarks section to find the week, but nothing appears there.

**Expected behavior**
Either the entire week's content should be visible in the Bookmark section, or the bookmark option for the whole week should be removed from the Courses section.

**Screenshots or GIFs**

https://github.com/user-attachments/assets/9a728d5b-425b-44e1-a215-e3a236959992

**Info (please complete the following information):**
 - Browser: All Browsers
 - Version : All

**Additional context**

**Comment by Kartik1110** [comment]
@Hemanth-Thaluru We can either remove the bookmark for week or we can do a few workarounds for this.
1. Change the Bookmark model to include folder(week).
2. Add all the videos etc. in the bookmarks section when the user clicks on bookmark for the week. (This would make the bookmark section cluttered.)

**Comment by Hemanth-Thaluru** [comment]
Yeah @Kartik1110, I think adding a folder (week) to the Bookmark model sounds like a solid option. It keeps things organized and prevents clutter in the bookmark section.

**Comment by devsargam** [comment]
This is solved
