### ISSUE TITLE
Video reloads when we click on quality button even if the quality is same

### ISSUE THREAD

**Issue by Dushyantbha012** [code100x/cms#142]
[Screencast from 03-03-24 11:31:28 AM IST.webm](https://github.com/code100x/cms/assets/89176588/a1719248-7e5b-49d7-b098-89baa8da1da1)
When you are watching videos say on 1080p on the website and in the quality list if we select 1080p it reloads, but it should not.
Please assign this issue to me, i am part of your 0-100 cohort2; i have found the files from where this issue can be solved.

**Comment by hkirat** [comment]
Whoever is solving this please attach the video selectors to the video player and remove the buttons we have created on the side

**Comment by vekariaayush04** [comment]
@hkirat bhaiya i tried solving the issue 

https://github.com/code100x/cms/assets/136103799/a85924a2-69c0-4fb9-bb09-d1e07af25a85

also removed side buttons and attached quality selector to the video player . but i am not sure about right approach as i am new to open-source should i raise pr??

**Comment by adarsh-mamgain** [comment]
Hey Harkirat, as per my understanding do you mean -

1. Delete the `QualitySelector` and `QualitySelectorControllBar`
2. Appending the video selectors to video player using some package like `@silvermine/videojs-quality-selector`
3. Then provide video quality source using:

Using <source>
```html
<video id="video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268">
   <source src="https://example.com/video_720.mp4" type="video/mp4" label="720P">
   <source src="https://example.com/video_480.mp4" type="video/mp4" label="480P" selected="true">
   <source src="https://example.com/video_360.mp4" type="video/mp4" label="360P">
</video>
```

Using player.src()
```js
player.src([
   {
      src: 'https://example.com/video_720.mp4',
      type: 'video/mp4',
      label: '720P',
   },
   {
      src: 'https://example.com/video_480.mp4',
      type: 'video/mp4',
      label: '480P',
      selected: true,
   },
   {
      src: 'https://example.com/video_360.mp4',
      type: 'video/mp4',
      label: '360P',
   },
]);

```

If the idea is correct, could you please assign the task. If not, please clarify.

**Comment by Deepak1649** [comment]
Hey, can you assign this issue to me.

**Comment by nimit9** [comment]
> Hey, can you assign this issue to me.

It's already resolved by https://github.com/code100x/cms/pull/220

**Comment by Nitin6404** [comment]
Why this issue isn't close ? and also labelled with bounty. If there any job left here, plz provide context So ppl can resolve it or else maintainers can close it.
