### ISSUE TITLE
bug: Pagination Component Is Not Fully Visible

### ISSUE THREAD

**Issue by abhirupPann** [code100x/cms#1420]
**Describe the bug**
The pagination component of the contents should be visible completely. But it is getting hidden under "Show Contents" component.

**To Reproduce**
1. View a course
2. Open any week content

**Expected behavior**
The pagination component should be visible completely.

**Screenshots or GIFs**
![Screenshot (1210)](https://github.com/user-attachments/assets/d3a439f5-0e0a-46da-a804-2a5ec29fbf43)

**Comment by sidpan2011** [comment]
Fixed with #1400
