### ISSUE TITLE
bug: Github Linking not working properly

### ISSUE THREAD

**Issue by dhruv-goyal-10** [code100x/cms#1423]
**Describe the bug**

Clicking on Github Link button is redirecting to some invalid URL.
`https://github.com/login/oauth/authorize?client_id=undefined&redirect_uri=undefined/api/github/callback&scope=read:user%20user:email`

Most probably, the client_id & redirect_uri is missing from secrets.

**To Reproduce**
1.  Go to https://app.100xdevs.com/payout-methods
2.  Click on Link Button under Github in Apps Section

**Expected behavior**
It should rather redirect to a valid page, where user can give consent to give required permissions.

**Screenshots or GIFs**

https://github.com/user-attachments/assets/a8f5d93e-d175-45b4-bf64-9240c30d4031

**Info (please complete the following information):**
 - Browser [Brave, Chrome]

**Additional context**
None

**Comment by sampath24-ss** [comment]
So can you tell where the github link have to be redirected to?

**Comment by dhruv-goyal-10** [comment]
@sampath24-ss I guess, if `client_id `and `redirect_uri` fields will be appropriately populated, it will start working, which are `undefined` as of now.

**Comment by sampath24-ss** [comment]
Yes i have seen the same they are empty as of now.

**Comment by devsargam** [comment]
The clientid is not configured properly
