### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by meinhoongagan** [code100x/cms#1424]
Bug Description
When a user clicks anywhere on the main content area outside the sidebar, the sidebar does not automatically close.

Expected Behavior
The sidebar should automatically close when a user clicks outside of it, on the main content area.

Current Behavior
Currently, the sidebar remains open even when the user clicks outside, requiring manual closing. This can lead to a frustrating user experience.

Steps to Reproduce
Open the sidebar by clicking on the menu icon.
Click anywhere outside the sidebar (on the main content area).
Observe that the sidebar does not close automatically.
Impact on User Experience
This issue can be irritating for users, as they must manually close the sidebar. It could be improved by making the sidebar auto-close when clicking outside of it, enhancing the overall user experience.

Additional Context
This behavior enhancement could make navigation smoother and prevent unnecessary steps for users when interacting with the sidebar.

![Kirat Bug](https://github.com/user-attachments/assets/ea4286d7-d2ca-4955-9834-d7fad37a66af)

**Comment by vanshavenger** [comment]
@devsargam needed?

**Comment by devsargam** [comment]
It's done actually just not in production

**Comment by vanshavenger** [comment]
Thankss sargam for clarifying
