### ISSUE TITLE
bug: Email suggestions on login page does not apply on clicking.

### ISSUE THREAD

**Issue by Karthik150502** [code100x/cms#1425]
**Describe the bug**
The email suggestions does not apply even after clicking on it, but it does apply when we toggle it using the up down keys.

**To Reproduce**
- Go to SIgnin page.
- Enter some text in email field, and after the email suggestions has been rendered, try clicking on them.

**Expected behavior**
- The email should be selected on clicking on them, along with the usual selection using the up-down keys.

**Screenshots or GIFs**
https://github.com/user-attachments/assets/2d42e3ac-5e3c-40ff-bcef-5a607d2eaeae

**Info (please complete the following information):**
 - Browser - Brave: 1.70.123, Google: 129.0.6668.90

**Additional context**
Also there is no hover effect on the email suggestions.

I can take this up, if seems right.

**Comment by devsargam** [comment]
It's fine let's not be too picky about these :)

**Comment by Karthik150502** [comment]
I am actively looking for some minor issues that i could contribute to, as i am a beginner to Open Source, I kindly request you to assign me some beginner level issues sir, @devsargam. It would be really helpful if I can contribute to some issues, and begin.

**Comment by devsargam** [comment]
@Karthik150502 there's nothing called `beginner level issues` if you are capable to write good scalable code you should be good enough to contribute to any repos. Feel free to find any improvements that you can make feel free to just raise a pr. If it's good I will surely merge it

**Comment by Karthik150502** [comment]
Sure @devsargam.
