### ISSUE TITLE
feature: Course Time Blocks and Schedule Sync Enhancement

### ISSUE THREAD

**Issue by furyfist** [code100x/cms#1433]
Is your feature request related to a problem? Please describe.
_**This feature will help us log our time, similar to how we do in Google Calendar.**_

Describe the solution you'd like : 

1. Each user should be able to edit the time entries the way they prefer (similar to Google Calendar).

2. Automatic time-blocking for the times of classes from the courses we are enrolled in. (For example, as I am enrolled in cohort 3.0 Web Dev, I would like it to log my time from 8-10 every Saturday and Sunday, including the class topic and a direct access link.)

3. **As I subscribed to it on Gmail, the time log automatically appears in my Google Calendar with details about the classes, so why not have the same functionality on the 100xDevs website?**

4. **Not limited to only 100xdevs Classes.**

**Current look :**

![image](https://github.com/user-attachments/assets/6c0d91ad-cad9-435f-84a6-8928e94ca8bb)

![image](https://github.com/user-attachments/assets/d9b25df4-43e2-4892-8622-e3a889063236)

**Desired look :**

![image](https://github.com/user-attachments/assets/7228365a-7ddb-4f27-bd2c-67ebb210aacb)

![image](https://github.com/user-attachments/assets/d7e4d813-263a-4b94-9783-297d4db316b2)

**Comment by NawinKumarSharma** [comment]
@furyfist , the issue seems intresting! can you describe more about the google calender thingy. currently , user can able to write their work for the particular time slot  in the particular days as they prefer.

**Comment by Prathamesh-Chavan-232** [comment]
Interesting enhancement! I would love to work on this issue, I think the time blocking issue could be easily resolved with adding bars with greater z-index in calendar and assigning colors to time slots which. This seems like shadcn calendar so probably just changing the color would work

**Comment by Prathamesh-Chavan-232** [comment]
@furyfist Please elaborate in more detail about your suggestion for user time logs, what time logs can the user add except for live classes? more explaination can help in creating tags if that time log functionality were to be implemented

**Comment by devsargam** [comment]
It's pretty hard to improve on this design. Anyone who is willing to solve it feel free to pr it. Closing for now but will happily look into a pr
