### ISSUE TITLE
Video height should be restricted when user has full screened the video

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#144]
Video overflowsfrom the bottom, should be max of the current height of the window
<img width="875" alt="Screenshot 2024-03-03 at 11 52 03 AM" src="https://github.com/code100x/cms/assets/8079861/b45400d3-b306-46b0-a085-feaaad6e367d">

**Comment by akshayK2021** [comment]
I am not able to find the solution to control the overflow of height with full width.

However, one of the possible solution is by reducing the witdth by little
following is the image after implementation
![Screenshot from 2024-03-03 19-28-42](https://github.com/code100x/cms/assets/95973239/eba484a6-76af-4c0c-ad69-ffdc0bb651a2)

It controls the overflow of height but reduces the width.

**Comment by hkirat** [comment]
can u show the code @akshayK2021 ?

**Comment by akshayK2021** [comment]
I have added this className in VideoPlayer2.tsx
![image](https://github.com/code100x/cms/assets/95973239/e123f6e4-3296-4959-8402-6dfdb7604540)

**Comment by devsargam** [comment]
working on it. Can I be assigned @hkirat

**Comment by devsargam** [comment]
Also, would be helpful if I know which video is being affected
