### ISSUE TITLE
bug: show content button position conflict

### ISSUE THREAD

**Issue by abcd799** [code100x/cms#1446]
Show contents button is conflicting with the folder path . Sometime looks ugly.
![image](https://github.com/user-attachments/assets/d5345076-ac6c-4a33-a59b-fc054d64bfec)

**Comment by tanmaysinghx** [comment]
Taking this up

**Comment by sharabhh** [comment]
Hello, can this task be assigned to me,

How I am going to tackle this situation:-

- I'll make that button positioning absolute alongside keeping it easily accessible for the user.
- I have also encountered this same issue with, the user always has to scroll to the top of the page when they want to click on it.

**Comment by parthjadhao** [comment]
@sharabhh I think it was already set to absolute positioning when I opened the code, and when I ran the code locally, it worked well in my environment without overlapping.
![Screenshot from 2024-10-07 14-22-27](https://github.com/user-attachments/assets/2d05cff6-78aa-4414-9ce5-819b21e5d25c)
![Screenshot from 2024-10-07 14-22-16](https://github.com/user-attachments/assets/90de941c-14d1-458e-b6d6-4cf80160e03f)

**Comment by sharabhh** [comment]
@parthjadhao but on scroll it moves upward atleast in the current production code

**Comment by parthjadhao** [comment]
@sharabhh, the Show button is rendered when the Sidebar component is rendered. In the screenshot below, you can see that it is already set to relative positioning.
![Screenshot from 2024-10-07 14-59-51](https://github.com/user-attachments/assets/390ed2e2-bbd0-4e84-8beb-99c31e2b0361)

In the code of the Sidebar component shown below, you can see that the Show content is already declared.
![Uploading Screenshot from 2024-10-07 15-02-56.png…]()

I believe it's moving upward because its parent element is also moving upward, but I am not completely sure why.

**Comment by sharabhh** [comment]
> @sharabhh, the Show button is rendered when the Sidebar component is rendered. In the screenshot below, you can see that it is already set to relative positioning. ![Screenshot from 2024-10-07 14-59-51](https://private-user-images.githubusercontent.com/84613656/374114871-390ed2e2-bbd0-4e84-8beb-99c31e2b0361.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTU0OTQsIm5iZiI6MTcyODI5NTE5NCwicGF0aCI6Ii84NDYxMzY1Ni8zNzQxMTQ4NzEtMzkwZWQyZTItYmJkMC00ZTg0LThiZWItOTljMzFlMmIwMzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA5NTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MWVhMDFhMDlhMmI2YTFhN2FjNThiYTIxYjE2MGE2NTdmY2MxNTc4NmFiY2JmODE5M2ZhMjY3NDc3ZjNkZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HBnB8qXq4UzOUnSuNxWs0NIXozszTEqHzLccup5enk8)
> 
> In the code of the Sidebar component shown below, you can see that the Show content is already declared. ![Screenshot from 2024-10-07 15-02-56](https://private-user-images.githubusercontent.com/84613656/374115243-4c5e2025-825a-41e4-becc-e71ab1f1894e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTU0OTQsIm5iZiI6MTcyODI5NTE5NCwicGF0aCI6Ii84NDYxMzY1Ni8zNzQxMTUyNDMtNGM1ZTIwMjUtODI1YS00MWU0LWJlY2MtZTcxYWIxZjE4OTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA5NTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZjc2MGExZGE1ZTE2YzU2NzRkMDQzMWQxM2IxMTM0NWI4MDk3NjUwN2ZiNTBjNTQ5MWE0NGRiZGQ1ZjJiZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mC08O20ApHESJxFNIWTbDWN9ZbUzlolQItx3ogHQGgg)
> 
> I believe it's moving upward because its parent element is also moving upward, but I am not completely sure why.
> 
> by the way in you locally hosted project is showcontent button is overlapping or rendering perfectly like mine

Yes exactly, just saw it in the code. It is moving according to the parent due to relative position. So if we want to make it stick individually we need to either take it out of that file entirely to another higher level file or maybe find a way to make it sticky in a way that it can work from there without going behind top navbar

**Comment by parthjadhao** [comment]
For now, the maintainer has asked to simply fix the issue of overlapping. If they want the button to be sticky, you can inquire further, but for now, I am submitting a pull request to resolve the bug.
