### ISSUE TITLE
bug: bookmarks functionality isn't working properly

### ISSUE THREAD

**Issue by dhruv-goyal-10** [code100x/cms#1449]
**Describe the bug**
So, there are 2 bugs
1. After adding the video in the bookmark & after refreshing the page, correct bookmarked state is not visible.
2. A single video can be added multiple times in the bookmarks, creating multiple entries.

**To Reproduce**
1. Add a bookmark to any video & Bookmark button will be active now.
2. Refresh the page and Bookmark button for the same video will be inactive now, even though the video was added to bookmarks.
3. Even you can add that same video, again to the bookmarks, resulting in multiple entries.

**Expected behavior**
1. Correct bookmark state should be visible.
2. There should be only 1 bookmark entry for 1 entity (video in this case).

**Screenshots or GIFs**

https://github.com/user-attachments/assets/94f10400-384b-4e83-aa7b-f74ae9c9d561

**Comment by devyess** [comment]
To resolve this issue, I plan to prevent duplicate bookmarks by checking if a bookmark already exists for the same video before adding it, and I will ensure that the bookmarked state is persisted correctly across page refreshes.

**Comment by dhruv-goyal-10** [comment]
Sounds good @devyess. You can proceed with this approach.

**Comment by Jatin123lodhi** [comment]
I have noticed it is working fine in local but not in production.

**Comment by paahaad** [comment]
Duplicate issue #1231, I guess PR is already merged  #1232

**Comment by dhruv-goyal-10** [comment]
Yep, the functionality seems to be working now.
