### ISSUE TITLE
feature: Remove Redundant Loader During Page Transitions (Skeletons Already in Use)

### ISSUE THREAD

**Issue by devansh-m12** [code100x/cms#1452]
**Is your feature request related to a problem? Please describe.**  
Yes, the loader appears in the top-left corner of the screen during page transitions, and its size and placement don't align with the rest of the header contents. Additionally, since we are already using skeleton screens for loading, the loader seems redundant.

https://github.com/user-attachments/assets/93f9c7f7-1a0a-405d-acb6-b585171427e4

**Describe the solution you'd like**  
I suggest removing the loader entirely, as the skeletons are sufficient for page loading feedback and provide a more consistent user experience.

**Describe alternatives you've considered**  
One alternative would be adjusting the loader's size and placement to match the header elements, but I believe removing it completely is a cleaner solution since skeletons are already in place.

**Additional context**  
I have a pull request ready with these changes. Let me know if you'd like me to proceed.

**Comment by AbhiPatel10** [comment]
I would love to work on this enhancement.

**Comment by devsargam** [comment]
This is a simple change fixing
