### ISSUE TITLE
bug: GitHub Link Redirects to 404 Due to Missing Environment Variables

### ISSUE THREAD

**Issue by devansh-m12** [code100x/cms#1453]
**Describe the bug**
The GitHub linking is not working in production because the GitHub Client App ID and the NextAuth URL are not set. As a result, the GitHub link redirects to a 404 page.

**To Reproduce**
1. Navigate to the payment method page.
2. Attempt to link a GitHub account.
3. You will be redirected to a 404 page.

**Expected behavior**
Upon linking a GitHub account, the user should be redirected to the proper GitHub authentication flow and successfully link their account without encountering a 404 page.

**Screenshots or GIFs**

https://github.com/user-attachments/assets/6083626c-5c2c-4562-9642-6d7a0e491fe0

**Additional context**
This issue occurs because the GitHub Client App ID and NextAuth URL are missing in the environment variables. Please add the necessary variables in the environment configuration to resolve this.

@hkirat @devsargam

**Comment by Code-bySalman** [comment]
Hey, I think we can easily fix this issue, would love to be a helping hand.

**Comment by devansh-m12** [comment]
@Code-bySalman The code is already as expected; only the environment variables need to be updated during deployment. I tested it by adding them in the local development environment, and they worked as expected.

**Comment by devsargam** [comment]
Env should be updated should be fixed soon
