### ISSUE TITLE
Light mode ui

### ISSUE THREAD

**Issue by Pratham271** [code100x/cms#146]
Currently in the light mode chapters bar is 
<img width="476" alt="Screenshot 2024-03-03 at 12 53 26 PM" src="https://github.com/code100x/cms/assets/83640434/3a9b92ae-ea53-4f6a-9618-1c8ae94db971">
ideally it should be 
<img width="463" alt="Screenshot 2024-03-03 at 1 02 38 PM" src="https://github.com/code100x/cms/assets/83640434/66ca830d-2ea5-4b04-a6bc-93bc509e2b56">
I am raising a pr for the same

**Comment by aryanprince** [comment]
@hkirat This issue can be closed since PR has been merged.
