### ISSUE TITLE
bug: Videos are getting downloaded, it could lead to piracy!

### ISSUE THREAD

**Issue by AdityaGupta-cyber** [code100x/cms#1462]
**Describe the bug**
The course contents are easily downloadable which can be a major piracy issue.

**To Reproduce**
1. Go to any video from the cohort.
2. Play the video
3.  Right-click on the video 
4. Click on show controls.

**Expected behavior**
There should be now option for the video to be downloaded when clicked on show controls. It should rather be DRM protected or Tokenized URL's should be implemented to avoid piracy!

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/a67fa1fb-2321-469d-b147-2b0da20b2433)

**Info (please complete the following information):**
 - Browser [e.g. Chrome]
 - Version [e.g. 129.0.XXXX.XX]

**Comment by x15sr71** [comment]
@AdityaGupta-cyber, I attempted to reproduce the behavior you mentioned, but I didn't find any options available for downloading the video. Could you please elaborate on your experience?

**Comment by sharabhh** [comment]
@AdityaGupta-cyber Hey Aditya, do you have any additional tool installed cause on mine there is no option to download

I am also on chrome Version 129.0 -----

![image](https://github.com/user-attachments/assets/1d7a16f5-efe6-407d-826f-9baac1057be6)

**Comment by watashiwaaniket** [comment]
For me also it's available and I'm on Opera GX browser
![Screenshot (22)](https://github.com/user-attachments/assets/81d512b0-e658-473a-959f-76f5b61582ec)

**Comment by devsargam** [comment]
This is something known. Please ignore it it's not possible to do it from cms it's a internal issue
