### ISSUE TITLE
feature: Download option for notes

### ISSUE THREAD

**Issue by chiraggowda92187** [code100x/cms#1468]
It would be really helpful if the notes section in app.100xdevs.com had a download option for Notion notes. This way, users could easily save and access their notes in Notion for better organization and offline use.
![notes](https://github.com/user-attachments/assets/d536f82c-4dba-49e9-8ebd-29901b12ffcd)

**Comment by riyan04** [comment]
Where should I navigate to get notes?

**Comment by chiraggowda92187** [comment]
> Where should I navigate to get notes?

Currently the download option is not there. This issue has been raised to add a download button to download the notes.

**Comment by Smnthjm08** [comment]
@chiraggowda92187 you can download docs from [daily-code](https://projects.100xdevs.com/)

**Comment by chiraggowda92187** [comment]
@Smnthjm08 The daily code notes is downloadable I agree but I am talking about the notes section in each week. Some of the notes have really good explanation which is missing the daily code notes.

**Comment by devsargam** [comment]
We already have the exact same feature in our other project https://github.com/code100x/daily-code
