### ISSUE TITLE
bug: Why Do I Still See the 'Login' and 'Join Now' Buttons After Logging In?

### ISSUE THREAD

**Issue by sohelhussain** [code100x/cms#1469]
**Describe the bug**
After logging in, you should typically see a Logout button in the navigation bar to indicate that you're signed in. However, if you're still seeing the Login and Join Now buttons, it might be due to a few potential issues, such as session errors, caching problems, or a bug in the UI. Ideally, the buttons should switch to a Logout button after a successful login to reflect your active session properly.

**Expected behavior**
typically see a Logout button

**Screenshots or GIFs**
<img width="1253" alt="Screenshot 2024-10-12 at 12 21 56 PM" src="https://github.com/user-attachments/assets/c3f581e6-31ca-4b60-85d0-7e05d050aded">

**Comment by abhishek-git25** [comment]
i am taking this up
but these buttons aren't visible all the time they pop and go

**Comment by abhishek-git25** [comment]
@sohelhussain i don't see this as an issue?

**Comment by retrogtx** [comment]
![image](https://github.com/user-attachments/assets/4640dc8b-63dd-4e1d-a8c8-7196abf46fe7)
seems to work fine for me, even for the same video as you have displayed.

**Comment by sohelhussain** [comment]
> @sohelhussain i don't see this as an issue?

i think this issue are fix

**Comment by sohelhussain** [comment]
[abhishek-git25](https://github.com/abhishek-git25) i think this issue are fix

**Comment by sohelhussain** [comment]
[abhishek-git25](https://github.com/abhishek-git25) i think this issue are fix

**Comment by Venki1402** [comment]
I don't thing this issue is fixed,
Im still able to see the login and join now button though I am logged in
On refresh its working fine though.
