### ISSUE TITLE
bug: Failed to load resource

### ISSUE THREAD

**Issue by Dhruv-Sood** [code100x/cms#1471]
**Describe the bug**
When I am trying to access the NextJS video in AdHOC I am getting "Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be "appx-recordings.classx.co.in", which could put your confidential information at risk."
While hitting the url:  https://appx-recordings.classx.co.in/drm/f3c9ebeb-c2b0-4bbf-afbb-388a0ed26a69/1080p/drm-hls/master-9879999.402992893.m3u8.m3u8 on network's tab

**Screenshots or GIFs**
<img width="1440" alt="Screenshot 2024-10-13 at 3 54 36 PM" src="https://github.com/user-attachments/assets/936c9d68-3af8-4729-a428-c23104894b1d">

**Info (please complete the following information):**
 - Browser Safari
 - Version 17.5

**Comment by avparadox** [comment]
Hey @Dhruv-Sood, please use browser like Chrome or Brave to access videos of app.100xdevs.com. These videos are DRM Encrypted in which modules like Widevine are to be enabled on the browser. 

Browsers like Safari don't provide with such features hence the videos gives a fail error. Requesting you to use Chrome or Brave either. 

Thanks. 

@devsargam can be closed. Not a bug.

**Comment by avparadox** [comment]
@devsargam sir this too can be closed. Not a bug.
