### ISSUE TITLE
feature: "Attribute-Based Breadcrumbs", "ShowContent Button"

### ISSUE THREAD

**Issue by sbhydv** [code100x/cms#1472]
**Is your feature request related to a problem? Please describe.**
-> frustrating to scroll back to top, to access the both "content button" and "relative path breadcrumb"

**Describe the solution you'd like**
- Both "content button -marked in red arrow" and "relative path breadcrumb -marked in red arrow" should stay at top while scrolling the page.

**Describe alternatives you've considered**
-> I thick they should stay at the top or if screen height taken into consideration to show more content, i think it shoud be either  on left or right somewhere.
alternative:
-> up and down button, as shown in the "blue color arrow" screenshot.

**Additional context**

*Provide the solved gist if some solve it. 

![Untitled design](https://github.com/user-attachments/assets/7c28dcce-8b5a-445a-9eff-b564a981abcf)

**Comment by IkramBagban** [comment]
Hey dear maintainer Please assign this task to me. i would love to add these feature.

**Comment by Jatin123lodhi** [comment]
@devsargam  Please can you review my pr - https://github.com/code100x/cms/pull/1473

https://github.com/user-attachments/assets/833d8590-e248-4442-8046-d18f620ad026

**Comment by Jatin123lodhi** [comment]
@sbhydv I tried to move the show contents button to the right but it was hiding when we click on it and the side drawer opens, let me know what do you think about the current implementation.

**Comment by UmarIbrahim20** [comment]
bro try to put in sidebar or navbar

**Comment by abhishek-git25** [comment]
i would love take this, can anyone please assign me?
