### ISSUE TITLE
feature: Add back Picture-in-Picture function to video player

### ISSUE THREAD

**Issue by ABDULLAHAHMEDSALIK** [code100x/cms#1474]
Implements Picture-in-Picture (PiP) mode for the video player as it was earlier. It was really helpful to code along with the tutor.

**Comment by Chityalaakhil** [comment]
@ABDULLAHAHMEDSALIK I'm seeing it already. Where are u not seeing it?

![image](https://github.com/user-attachments/assets/5b39f192-4817-4ca4-8ad1-8e3f9c4c6362)

can u add some more details to this issue?

**Comment by ABDULLAHAHMEDSALIK** [comment]
it is resolved now thanks.
