### ISSUE TITLE
bug: Greetings not working correctly

### ISSUE THREAD

**Issue by ArthKulkarni93** [code100x/cms#1475]
**Describe the bug**
The greetings on home page are dependent on the current time, but it seems like its not working as expected.

**To Reproduce**
1. Just go to Home page and you will see the greetings mismatched with current timings
2. Currently I am seeing 'Good Afternoon' and its 10pm.

**Expected behavior**
It should be 'Surprise to see you here!'

**Screenshots or GIFs**
<img width="1440" alt="Screenshot 2024-10-14 at 10 01 39 PM" src="https://github.com/user-attachments/assets/f84e3648-dfe2-4627-885e-2c7633f1369a">

**Info (please complete the following information):**
 -safari

**Additional context**

**Comment by vanshavenger** [comment]
Ig it is taking the timezone of the machine or cluster it is deployed in, Check in few hours check if changes, If not will try to deep dive in as it works correct on local but yes not on the production.
