### ISSUE TITLE
bug: Improper Sizing of Login Screen Card on Medium Breakpoints

### ISSUE THREAD

**Issue by Gurvinder-Singh02** [code100x/cms#1477]
**Describe the bug**
The login screen card is improperly sized for some breakpoints, resulting in a suboptimal user experience on medium-sized screens.

**To Reproduce**
1. go to login page
2. see the responsiveness for medium (md) screen sizes.

**Expected behavior**
The login screen card should be appropriately sized and aligned for medium screen sizes, ensuring that all input fields and buttons are easily accessible and visually balanced.

**Screenshots or GIFs**
<img width="892" alt="Screenshot 2024-10-15 at 4 15 19 AM" src="https://github.com/user-attachments/assets/af9e3940-9e54-40b6-8e06-a1ea7a35ef08">

**Info (please complete the following information):**

**Additional context**
Please assign this issue to me; I will fix it.

**Comment by Jatin123lodhi** [comment]
@devsargam Please review my pr - https://github.com/code100x/cms/pull/1478

https://github.com/user-attachments/assets/66bcf7aa-d462-4926-87e3-2df5bb229729
