### ISSUE TITLE
feature: Centralized Notes Section for Easy Navigation within Course Content

### ISSUE THREAD

**Issue by hamzahshahbazkhan** [code100x/cms#1479]
**Is your feature request related to a problem? Please describe.**
It's difficult to locate and navigate through course notes, as they are spread across different sections, making it time-consuming for users to review or reference them.

**Describe the solution you'd like**
A dedicated section that organizes all notes in one place, allowing users to easily browse and access them in a structured format without needing to navigate through individual modules.

**Describe alternatives you've considered**
I considered adding a search function or tags for filtering notes, but these options don’t provide the same ease of access as a centralized notes section.

**Additional context**
A centralized section would improve the user experience, especially for reviewing key materials efficiently.

**Comment by devsargam** [comment]
We have a separate project for this dedicatedly. https://github.com/code100x/daily-code
