### ISSUE TITLE
bug: Pagination Controls Not Functioning

### ISSUE THREAD

**Issue by kekubhai** [code100x/cms#1481]
Describe the bug
The pagination controls on the [relevant page/component] are not working as expected. When clicking on the "Previous" or "Next" buttons, or selecting a specific page number, the page content does not update accordingly. This prevents users from efficiently navigating through the content.

To Reproduce

Navigate to the [relevant page/component]
Click on the "Previous" or "Next" button, or select a different page number
Observe that the page content does not change
Expected behavior
When clicking on the "Previous" or "Next" button, or selecting a different page number, the page content should update to display the corresponding content.

Screenshots or GIFs
[Attach screenshots or GIFs demonstrating the issue, if applicable]
![Screenshot 2024-10-16 093600](https://github.com/user-attachments/assets/bd856004-27b8-4b6f-b748-d603ddaa0127)

Info (please complete the following information):

Browser [e.g. Chrome]
Version [e.g. 118, 109, 17]
Additional context
This issue is preventing users from effectively browsing through the content on the [relevant page/component]. Please investigate and resolve this issue as soon as possible.

**Comment by NawinKumarSharma** [comment]
@kekubhai  , can you speify, which route has pagination like this?

**Comment by kekubhai** [comment]
Its in the homepage,

**Comment by abhishek-git25** [comment]
@kekubhai cannot find this home page

**Comment by kekubhai** [comment]
I guess I have raised it in the wrong repo ,but here's for check : 
![image](https://github.com/user-attachments/assets/da064237-f260-469b-95e3-a44e71a0b68d)

**Comment by geekyharsh05** [comment]
@kekubhai Yeah it is in [daily-code](https://github.com/code100x/daily-code/)

**Comment by kekubhai** [comment]
Thanks man. I'll close it here.
