### ISSUE TITLE
feature: Option for 3x and 4x speed

### ISSUE THREAD

**Issue by prateeksingh19** [code100x/cms#1484]
**Is your feature request related to a problem? Please describe.**  
I find myself wanting to consume video content at a faster rate than what is currently allowed. It is frustrating when the maximum playback speed is limited to 2x or 1.5x, especially for content that I could easily absorb at a much faster pace.

**Describe the solution you'd like**  
I would like an option to increase the playback speed to 3x or 4x for videos.

**Describe alternatives you've considered**  
Nothing other than watching it in 2x speed.

**Additional context**  
This feature would be especially useful for Q/As part where users might prefer to skim through sections at higher speeds without losing time.

**Comment by prateeksingh19** [comment]
I've already made the adjustment to the code to implement this feature. If the issue gets approved, I'd create a PR with the modified code.

**Comment by devsargam** [comment]
that's too much damn

**Comment by prateeksingh19** [comment]
Is 3x fine???

**Comment by DhruvGahoi** [comment]
Is anyone working on this issue ?
