### ISSUE TITLE
feature: Show duration of the videos in Show Content Sidebar

### ISSUE THREAD

**Issue by navdeep-rajpurohit** [code100x/cms#1487]
**Is your feature request related to a problem? Please describe.**
It would be great if we add video duration to the sidebar which helps to directly check the duration without opening the specific video. 

**Describe the solution you'd like**
We can use existing params content.VideoMetadata.duration or content.videoProgress.VideoFullDuration to display the video duration

**Additional context**
Getting null for both the params. Please suggest something if we can get the video duration.
![Screenshot 2024-10-17 at 3 03 49 PM](https://github.com/user-attachments/assets/6e241a45-8e7a-425a-aa4f-7b0c05f373fd)
![Screenshot 2024-10-17 at 3 04 54 PM](https://github.com/user-attachments/assets/878548f9-70fa-49b3-8f90-9ab311145570)

**Comment by rameshchoyal** [comment]
Can you assign this issue to me?

**Comment by navdeep-rajpurohit** [comment]
> Can you assign this issue to me?

Working on it

**Comment by Sahil873** [comment]
Is anyone working on this issue

**Comment by navdeep-rajpurohit** [comment]
> Is anyone working on this issue

Yes I'm on it

**Comment by Sahil873** [comment]
The issue can be resolved by converting the VideoMetaData.duration to the required format (x hr y min) and adding it to the sidebar.

**Comment by navdeep-rajpurohit** [comment]
> The issue can be resolved by converting the VideoMetaData.duration to the required format (x hr y min) and adding it to the sidebar.

@devsargam Any suggestion on getting null values ??

**Comment by Sahil873** [comment]
by running the prisma migrations the VideoMetaData table has duration set to null. In the production db it would have the videos duration. 
@devsargam guide me about this.

**Comment by navdeep-rajpurohit** [comment]
Got it, thank you. Will raise PR

**Comment by devsargam** [comment]
Sorry I was not caught up but we don't have video duration on the prod db. Yeah we can do some hacks and get it but I don't think it's worth it to use something like ffmpeg and again populate duration in the db so closing as it seems out of scope
