### ISSUE TITLE
bug: Show Content button coming on top of content and does not close the content when clicked again.

### ISSUE THREAD

**Issue by MihirKotecha** [code100x/cms#1489]
**Describe the bug**
The show content button which is shown on the video page and the notes page hides some content behind it. And, once clicked although the text in the button changes to Hide Content when clicked it does not work properly and just closes and opens the side bar again.

**To Reproduce**
1. Navigate to any video page or the notes.
2. Click the show content button.

**Expected behavior**
The button should not hide the content and when clicked should close the side bar which opens up.

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/4aa0cdf0-b8ff-4e6f-8f96-70f00f24c0d2)

**Info (please complete the following information):**
 - Browser: Brave

**Comment by iSouvikKhan** [comment]
Hi @MihirKotecha 

I believe the bug is already fixed because the CMS local code does not contain this bug,
So the bug might have been fixed but the latest code is not deployed in production yet, which causes this issue.

Thanks

**Comment by devsargam** [comment]
It has been fixed in the recent prod. Thankyou for your effort
