### ISSUE TITLE
bug: from week 30 to week 35, most of the videos in this section are downloadable, which poses a risk of content theft and may impact the security of the materials.

### ISSUE THREAD

**Issue by siddharthharshraj** [code100x/cms#1490]
I’ve noticed that from week 30 to week 35, most of the videos in this section are downloadable, which poses a risk of content theft and may impact the security of the materials.

I am attaching relevant screenshots and links as proof of the issue. I kindly request that this be addressed to prevent any unauthorized distribution of the course content.
![Screenshot 2024-10-19 223620](https://github.com/user-attachments/assets/f87b4e7e-39d9-4497-8b85-298b41c5a8be)

**Comment by avparadox** [comment]
hey @devsargam please remove this issue. This is from last Cohort. Kirat Bro knows about it. At that time we didn't had dynamic watermarking. It's not a bug. 

PS: All the last cohort videos are already pirated so no point of fixing them now.

**Comment by siddharthharshraj** [comment]
Already solved

**Comment by devsargam** [comment]
Thanks @avparadox @siddharthharshraj
