### ISSUE TITLE
feature: Save Caption Settings Between Video Plays

### ISSUE THREAD

**Issue by nitesh2920** [code100x/cms#1493]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually adjust my caption settings every time I play a video. 
It would be much easier if my preferences were saved, as I often prefer captions to be enabled.

**Describe the solution you'd like**
I would like the application to save my caption settings using local storage or cookies so that when I play a video, my preference caption setting is automatically applied without doinng manually.

**Describe alternatives you've considered**
It can be implement using cookies also , but local storage is easy and more starighforward .

**Additional context**

**Comment by IkramBagban** [comment]
would love to work on it.
/assign

**Comment by IkramBagban** [comment]
Thanks

**Comment by IkramBagban** [comment]
PR is Done #1503

**Comment by nitesh2920** [comment]
@IkramBagban does it include all the styles of subtitles what user set one time will be persistent across all other videos like fontsize , background?

**Comment by IkramBagban** [comment]
> @IkramBagban does it include all the styles of subtitles what user set one time will be persistent across all other videos like fontsize , caption background?

I haven't tested that
