### ISSUE TITLE
bug: Next.js Video in Ad Hoc classes -> GSOC Section Fails to Load Due to Media Error

### ISSUE THREAD

**Issue by x15sr71** [code100x/cms#1506]
Describe the bug
The Next.js video in the Ad Hoc classes -> GSOC section/folder is unavailable. When attempting to play the video, the following error is logged: "The media could not be loaded, either because the server or network failed or because the format is not supported."

To Reproduce

Navigate to the Ad Hoc -> GSOC section/folder in Cohort 2 (0-100).
Attempt to play the Next.js video.
See the error: "The media could not be loaded, either because the server or network failed or because the format is not supported."
Expected behavior
The video should load and play without any issues.

Screenshots or GIFs
![Screenshot 2024-10-23 012318](https://github.com/user-attachments/assets/9ddd24f5-262f-4584-89bb-7fcf5dc35273)

Info (please complete the following information):

Browser: Chrome
Version: 
Additional context
The issue could be related to server availability or unsupported media format. Please check the media file's compatibility and server settings.

**Comment by avparadox** [comment]
Sorry for this. I'll report it to the mods. Will update, when it's back online. 

Thanks for reporting.

**Comment by avparadox** [comment]
Hey @x15sr71 please mention this issue in Discord & tag Rookie or Ankur bro. I'm sure they can help with this. 

Once the problem is solved, please feel free to close the issue.

**Comment by x15sr71** [comment]
Ok @avparadox , I will be raising this issue on Discord as suggested. Closing it here for now.
