### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by narasimha-1511** [code100x/cms#1508]
**Describe the bug**

![image](https://github.com/user-attachments/assets/c519f737-35cc-4170-b9fb-4cf1a0b20220)

the Show Contents is being rendered on the bread crumbs

**To Reproduce**
1. open any cousre and you can this

**Expected behavior**
show contents should not be on the bread crumbs

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/4722a9a4-457a-4264-a013-130dccd37471)

css of that particular element is having this media quey which should not be applied 

**Info (please complete the following information):**

**Additional context**

i want to take up this issue, but on the development store i am unable to reproduce it don't know why

**Comment by narasimha-1511** [comment]
@avparadox  😞 Okay Close this Issue Then

**Comment by avparadox** [comment]
@devsargam solved. Please close this too 😶‍🌫️
