### ISSUE TITLE
feature: Add next and prev play buttons

### ISSUE THREAD

**Issue by CodeAnk2829** [code100x/cms#1509]
**Actual Behaviour**
Every time I complete a lecture, I either have to open the sidebar to choose the next one or go back to the content list page to select it.

![Screenshot from 2024-10-25 00-52-11](https://github.com/user-attachments/assets/ffa9cd0a-6452-4de4-88bc-2d3a45095387)

**Expected Behaviour**
There should be "Next" and "Previous" buttons on the current page to easily navigate between lectures.

**Steps to reproduce** 
See any lecture page: 	[https://app.100xdevs.com/courses/3/385/387](https://app.100xdevs.com/courses/3/385/387)

**Comment by IkramBagban** [comment]
would love to work on this please assign

**Comment by AnubhavPurohit691** [comment]
can u assign me for this issue

**Comment by CodeAnk2829** [comment]
@IkramBagban and @AnubhavPurohit691 kindly contact maintainers.

**Comment by devsargam** [comment]
This is complicated as we don't have the db schema supporting it let's leave it
