### ISSUE TITLE
bug: Allowing iframe embedding leads to potential content piracy and shared access.

### ISSUE THREAD

**Issue by Aditya8840** [code100x/cms#1515]
**Describe the bug**
The platform’s content can currently be embedded in an iframe on any website. This allows anyone to stream the content by sharing links, potentially letting multiple people use one account. Major platforms like Netflix and Disney+ block this to avoid unauthorized access and piracy.

**To Reproduce**
1. Embed the platform URL in an iframe on a different website.
2. Open the website on another browser.
3. The content plays without any restrictions, allowing multiple users to view it if configured.

**Expected behavior**
Embedding should be restricted to prevent unauthorized streaming or sharing. Platforms often use settings to block iframes and protect content from being misused on third-party sites.

**Screenshots or GIFs**
https://github.com/user-attachments/assets/0e29b8e2-d106-4ab6-959a-9e6bbcf99843

**Info (please complete the following information):**
 - Browser: Chrome

**Comment by avparadox** [comment]
are you able to play videos using this method?

i tried it & it didn't worked for me. let me know if you can access courses & play videos in this manner.

**Comment by Aditya8840** [comment]
Actually, I don’t have access to any courses, so I couldn’t test playing videos directly. But I am able to access the website itself, which could be a problem. If you can provide any demo video link from this platform, I’d be able to check if it’s actually playable using this method by playing around with it.

**Comment by avparadox** [comment]
I tried it on the real website & it didn't worked for me. 

I recommend you cloning the repo & trying to reproduce the same for videos.  
You have tried it on docs which is easily available to everyone, so there's no thing of piracy there.

**Comment by Maurice1008** [comment]
It appears that that anyone can login and access the content on the platform

**Comment by Maurice1008** [comment]
But i wasn't able to stream videos , only the notes that are on the website.

**Comment by avparadox** [comment]
I don't think there's any bug here. If you think from first principals then even if we get a iframe link from someone, we don't have their cookie or JWT tokens. So either way we can't login someone's session. 

I believe the issue can be closed @Aditya8840

**Comment by Aditya8840** [comment]
Let me take one more day to conduct do research and experiment with it.
