### ISSUE TITLE
feature: Add notifications for users to make interaction lively

### ISSUE THREAD

**Issue by Zafeeruddin** [code100x/cms#1516]
Currently the reason why people not interact a lot on app is because of not having notifications on when someone interact with their problems

**Notifications could be added on:**

1. Notifying users on comments (including all users in the thread)
2. Notifying when users interact with questions.

The second one will be game changer, you would not need to purge questions page as mentioned in #1438.

Suggested architecture:
![image](https://github.com/user-attachments/assets/af00a54a-cebd-4c9c-ac17-9d1da458c9f9)

PS: I have already started working on it, will proceed to work if agreed upon.

**Comment by Zafeeruddin** [comment]
@hkirat @devsargam @siinghd

**Comment by deauthe** [comment]
looks like a great enhancement. Knowing that somebody's asking you a follow up question on a comment should be primitive behaviour. Upvotes

**Comment by devsargam** [comment]
Let's not go that route will make app more complicated
