### ISSUE TITLE
feature: Show hidden contents of togglable sidebar 

### ISSUE THREAD

**Issue by shivkumarojha** [code100x/cms#1518]
**Is your feature request related to a problem? Please describe.**
When we Press "Show Content" toggle button, is shows the side bar, if we click on multiple contents the contents in the last are not shown properly and get hidden.

**Describe the solution you'd like**
Either hide the bottom sticky navigation bar or hide the previous clicked contents so that when we click on the others there will be enough space to show the content. First approach will be better.

**Describe alternatives you've considered**
When we scroll the side bar make the sticky navigation bar hidden. But this may not be visually appealing.

**Additional context**
Here are the screenshots and video for the same issue.
In the video you can see that when we toggle content, we can't see the last content it simply hidden in the bottom navbar when we change the zoom of page we can see that it is there.

https://github.com/user-attachments/assets/6c14831f-ce59-4cbb-a99e-a3d531e9363c

**Comment by Munadil16** [comment]
#1513 resolves this

**Comment by avparadox** [comment]
Hey @shivkumarojha as #1513 solves this issue, please close this one.
