### ISSUE TITLE
Not Able to open ML and Android Courses from the Courses Dashboard

### ISSUE THREAD

**Issue by akshayK2021** [code100x/cms#152]
When opening the ML Ops and Android Development Courses It redirects to 100xdevs.com and we have to login again
also not  able to access this courses from app.100xdevs.com dashboard.
 we can access the other courses.

below video shows the issue:-
[simplescreenrecorder-2024-03-04_18.59.03.webm](https://github.com/code100x/cms/assets/95973239/7e77a8f7-a6b8-4b06-bac8-90c30586825d)

**Comment by krishhh16** [comment]
Dude, They've provided the content in harkirat.classx.co.in , if you are part of the cohort, you can access the content from the view content button of that course button, and then access it from there wherever the ML Ops/ And. dev. course is written.

**Comment by devsargam** [comment]
hey, this repo supports for app.100xdevs.com only!!!

**Comment by akshayK2021** [comment]
Yeah,I know we can access it from harkirat.classx.co.in but if we see to access the courses from app.100xdevs.com then it should be accessible from there also.
It's easy to open those courses from app.100xdevs.com


It's just my thought

**Comment by devsargam** [comment]
you can access it from app.100xdevs.com @akshayK2021
Can u mention ur issue more clearly

**Comment by akshayK2021** [comment]
I have attached the video above plz refer to that,
After clicking on view courses it doesn't open the content of courses for ML and Android it navigate us to harkirat.class.co.in and we are logged off. You can see the issue in attachment.
