### ISSUE TITLE
bug: video not fitted as window

### ISSUE THREAD

**Issue by saurabhraghuvanshii** [code100x/cms#1523]
when I open video it not fit as window some parts are downs and some are ups
![Screenshot 2024-10-28 234237](https://github.com/user-attachments/assets/ac478fb5-7f60-45a9-9f4e-21552464fb4d)
![Screenshot 2024-10-28 234151](https://github.com/user-attachments/assets/6932325a-6fa6-4b47-8cbe-adb30efff365)

**Expected behavior**
when a web open like YouTube a video should be fit and view whole in format and when when adjust frame of window video should be adjust according to it.

***One more fixture  can be added ***
 there should be cinema mode for adjust video to horizontal for fit screen as Like in YouTube.

**Comment by VedantBhawsar** [comment]
could you assign it to me?

**Comment by saurabhraghuvanshii** [comment]
I am working on it, and I am not maintainer so I can't assign you , I am also a contributor, thanks

**Comment by VedantBhawsar** [comment]
@saurabhraghuvanshii  okay bro
