### ISSUE TITLE
feature: improve the captions settings ui and add keyboard shortcuts to change font size 

### ISSUE THREAD

**Issue by Gourav-21** [code100x/cms#1526]
**Current UI**
The settings of caption looks really bad and there is no shortcut to change the size of fonts while watching the video, i have to open the settings everytime to change the size.

![image](https://github.com/user-attachments/assets/47b0706c-e4e3-46cc-bfbd-ec5eb6ee7687)

**Suggestions**

- [ ]  improve the ui of caption settings
- [ ] add shortcuts to change size of font like its on youtube using - and +
- [x] and add support for numpad to go forward and backward in video

**Comment by Gourav-21** [comment]
and add support for numpad to go forward and backward in video

**Comment by shahkashish** [comment]
To tackle the 2nd enhancement i.e. "add shortcuts to change size of font like its on youtube using - and +", we will have to 
1. Add a State for current Subtitle Font Size.
2. Attach a keydown event listener to the component to capture the + and - keys.
3. Dynamically adjust the font size of the subtitles according to the current state of subtitle and the key that is pressed.
above steps would let us complete the task

**Comment by shahkashish** [comment]
If you like the approach lmk and i'll start working on it, even if you have different views you can tell me.

**Comment by Gourav-21** [comment]
@shahkashish yeah please go on

**Comment by shahkashish** [comment]
could you assign it to me?
as it is mentioned that task should be assigned first and then i have to make PR

**Comment by devsargam** [comment]
This issue looks out of scope.
