### ISSUE TITLE
feature: An offline notification when the user is not connected to internet but tries to reach the web application.

### ISSUE THREAD

**Issue by ankush-web-eng** [code100x/cms#1527]
### When I open the [app.100xdevs.com](https://app.100xdevs.com) while not being connected to internet, I get this screen.
![image](https://github.com/user-attachments/assets/79946489-bdfd-40fe-b72a-2f359a5396c4)

## Solution
- A page cached on frontend side which should display Harkirat's icon in the center and text telling the user that user is not connected to internet. I recently did it for my [personal-website](https://ankushsingh.tech), so decided to do the same feature for [app.100xdevs.com](https://app.100xdevs.com) as well.

**Comment by IkramBagban** [comment]
Hey @devsargam Please Assign This Task to me.

**Comment by ankush-web-eng** [comment]
I opened this issue and done the work as well, just waiting for @devsargam or @hkirat to assign it so that I can raise my PR.
