### ISSUE TITLE
feature: Dev Containers addition for better support

### ISSUE THREAD

**Issue by Kannav02** [code100x/cms#1529]
Since this project has a lot of people contributing to it daily, contributors would face setup issues, environment mismatches, or dependency version conflicts. These issues can slow down onboarding for new contributors and make it harder to maintain a consistent development environment across different machines.

I'd like to propose the use of Dev Containers to provide a consistent, containerized development environment. Dev Containers allow contributors to open the project in a pre-configured development environment directly in their IDE (such as Visual Studio Code), with all necessary dependencies, tools, and configurations pre-installed. 

Implementing Dev Containers would be particularly helpful for remote contributors or those using different operating systems. It would also help us ensure that everyone is developing and testing against a standardized environment, potentially reducing "it works on my machine" issues.

If possible , can I work on this issue?

**Comment by devsargam** [comment]
This is a really good thinking but cms is a beginner friendly project so it's better to help people know how to setup, develop and test real world projects without going through things like gitpod or similar. Thanks but I don't think we will implement this right now

**Comment by Kannav02** [comment]
Sure , shouldn't be a problem
