### ISSUE TITLE
bug: Bottom Bar Overlaps Last Accordion Item

### ISSUE THREAD

**Issue by MNZ02** [code100x/cms#1544]
**Description:** 

When viewing the list of weeks in the accordion component, the last item (e.g., "Week 12") is partially hidden due to the bottom navigation bar overlaying it. This makes it difficult for users to access the last item, especially on smaller screens where space is limited.

**Steps to reproduce the behavior:**

1. Go to a course which has more than 10+ weeks
2. Click on show content and scroll to the bottom of the list to see the last week.
3. Observe that the last week item is partially hidden behind the bottom navigation bar.

**Expected behavior**
The full list of weeks should be visible and scrollable, with the last item fully accessible without obstruction by the bottom navigation bar.

**Screenshots or GIFs**
**Current UI**
![Screenshot from 2024-11-03 00-41-15](https://github.com/user-attachments/assets/3379a6a3-669b-468a-8e5d-0f969a45ad52)

**Expected UI**
![Screenshot from 2024-11-03 00-49-31](https://github.com/user-attachments/assets/8fbb5ec0-cdb5-42bb-a1f2-989a65650f65)

**Suggested Fixes:**
1. Add padding to the bottom of the accordion container to ensure the last item is above the bottom navigation bar.

I have already fixed the issue, I would be happy to push the changes if the issue is assigned to me!

**Comment by gaurav-mehta19** [comment]
would like to work on this 
\assign me

**Comment by MNZ02** [comment]
@devsargam I have fixed the issue and created a pull request, can you please check?

**Comment by trithanka** [comment]
Well done
