### ISSUE TITLE
feature: adding shortcuts to captions , picture-in-picture and add auto options to video quality

### ISSUE THREAD

**Issue by surya-moorthy** [code100x/cms#1545]
Description:
   I always wonder we can have shortcuts to make ourself easier just like watching a video in Youtube and the internet connection may be  low or slower which can held to loading..

Solution: 
  I would like to add shortcuts to captions and picture-in-picture mode and I would like to add auto option for video quality and set it as default

**Comment by surya-moorthy** [comment]
I would like to work on this , please assign me for this

**Comment by devsargam** [comment]
We are using custom iframe for rendering video here
