### ISSUE TITLE
bug: dropdowns and options are not visible for captions settings

### ISSUE THREAD

**Issue by ashokasec** [code100x/cms#1549]
**Describe the bug**
settings are not clearly visible for captions settings

**To Reproduce**
1. Start any video
2. Click on captions and then captions settings

**Expected behavior**
the options and dropdowns should be clearly visible on for captions settings

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/564abc18-d2c5-4707-99f9-9dc91fd51c41)

**Info (please complete the following information):**
 - Browser Brave
 - Version 1.71.121

**Comment by SukhvirKooner** [comment]
Can't see caption using temp login credentials

**Comment by devsargam** [comment]
Let's not worry about these small stuffs. We have bigger fish to fry
