### ISSUE TITLE
Implement a button for minimizing the left navbar (week wise navbar)

### ISSUE THREAD

**Issue by AxBwal** [code100x/cms#155]
"You can implement a button that, when clicked, allows the user to minimize the left navbar (week-wise navbar) and watch the video in full length on the page."

**Comment by okyash007** [comment]
> "You can implement a button that, when clicked, allows the user to minimize the left navbar (week-wise navbar) and watch the video in full length on the page."

it is already implemented 

![image](https://github.com/code100x/cms/assets/120806297/b5683332-1e12-4ff6-82e5-03a4564eb55d)

you can do this from here
