### ISSUE TITLE
feature:  Adding hover functionality in SearchBox

### ISSUE THREAD

**Issue by shubhanshu-02** [code100x/cms#1550]
A hover feature can be added to the search bar to display the full video title when it doesn’t fit in the box. Currently, longer titles are truncated with ellipses ("..."), but with this improvement, users will be able to hover over the title to see the complete text.

![WhatsApp Image 2024-11-07 at 01 55 54_fca9e627](https://github.com/user-attachments/assets/c700c960-4792-44f5-af8a-7d88776e86cb)

https://github.com/user-attachments/assets/f122b462-700a-4459-b170-befcb51a292c

**Comment by IkramBagban** [comment]
@devsargam please assign this to me. 
I am doing this

**Comment by IkramBagban** [comment]
Hey @devsargam Please look at this PR #1553

**Comment by Jatingupta9120** [comment]
Hey is this still open i would love to work on this issue @devsargam

**Comment by devsargam** [comment]
@Jatingupta9120 there's already a pr raise for this so that will get the preference
