### ISSUE TITLE
bug:  " week 35 " hidden 

### ISSUE THREAD

**Issue by sujalcharati** [code100x/cms#1559]
**Describe the bug**
when we click show content and want to see the last week content's e.g week 35 through scrolling we are not being able to see.
**To Reproduce**
1. Do something adding bottom padding or margin of scrollable container viewport .
2. See error https://app.100xdevs.com/courses/3

**Expected behavior**
when we scroll the content it should show till the very end of content showing week 35 
**Screenshots or GIFs**
![{C971200D-8FB8-4E1C-B376-A3CECD652F0C}](https://github.com/user-attachments/assets/0a606e06-745e-448b-a16f-b32c79f3e101)

**Info (please complete the following information):**

**Additional context**

**Comment by sujalcharati** [comment]
hey ,@devsargam  can i be assigned ?

**Comment by devsargam** [comment]
sure go on

**Comment by KeshavDev15** [comment]
Hello I was working on this issue from some time I have solved it . it will be my first PR can someone please help me ,what can I do next to merge or show the answer
