### ISSUE TITLE
feature: tooltip when hovering over the section button with timestamps to show the full name of the section

### ISSUE THREAD

**Issue by HarshitCodes2** [code100x/cms#1569]
**Is your feature request related to a problem? Please describe.**
I was very annoyed when i wanted to look at the section i am at or the next section but the name was either hidden by the timestamp of the progress bar or the name was too big to look at the section name.
<img width="514" alt="Screenshot 2024-11-18 at 16 45 06" src="https://github.com/user-attachments/assets/3b122cbf-e08d-40b7-aeb5-1201d6aade4e">
<img width="514" alt="Screenshot 2024-11-18 at 16 45 51" src="https://github.com/user-attachments/assets/1d1634ac-26c5-4c49-b54d-b8c66eff9067">

**Describe the solution you'd like**
I would like to have a tooltip than shows the full name of the section when hovered over the button

**Describe alternatives you've considered**
Well, The comment section have them usually but it's reliant on other students, would like it to be up with the video

**Additional context**
Provided ss above

## Request:
If issue is approved, would like it to be assigned to me

**Comment by HarshitCodes2** [comment]
I would like to solve this issue, please assign it to me

**Comment by nischal-shetty2** [comment]
> I would like to solve this issue, please assign it to me

You dont need to be assigned to fix this, just work on it and if your pr is good then itll be merged

**Comment by devsargam** [comment]
Anyone interested can raise a pr should be a really simple fix under VideoPlayer2 component

**Comment by IkramBagban** [comment]
@devsargam please check this pr
