### ISSUE TITLE
Figure out APIs to open a video player that appx has on our side

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#1572]
When the user signs in, we sign them into appx in the background
When user opens a video, if the type of the video is `appx_encrypted` , we embed an iframe that points to their player and send the users appx cookie in the request

**Comment by 10kumaranurag01** [comment]
I want to work on this, pls assign it to me

**Comment by VenkateshEVPE** [comment]
Assign it to me

**Comment by venkateshmallula** [comment]
Assign to me

**Comment by Piyushrathoree** [comment]
I think this is the issue "The AppX player can’t access the user’s authentication cookie" if I'm going in right way then please give feedback

**Comment by testing-archit** [comment]
interface VideoPlayerAccessRequest {
  videoId: string;         
  userId: string;           
  authToken: string;        
}


interface VideoPlayerAccessResponse {
  playerUrl: string;        //Secure URL for the AppX video player
  expiresAt: number;        // Timestamp when access expires
  encryptionKey?: string;   // Optional encryption key for the video
}


can we do something like this ???

**Comment by shahnawazAlam3641** [comment]
i dont know if it helps or not but i was just messing with the network tab of harkirat.classx and got the video url and key(this key only lets us play the video there is a different key to decrypt the video) if we send enrolled students jwt, so i just made this 

https://test-video-n4xa.onrender.com/?video_id=3003 

if we change the video id the video changes
like 3004, 3005, 3008 in the url
you have to allow pop ups to watch the video

**Comment by 0xkafkaa** [comment]
https://youtu.be/ZZe6wNQYiI4

**Comment by ayush-agrawal001** [comment]
If we are finding a way to download classx videos here it is 

[https://drive.google.com/file/d/1w4jwF6n0GYx-9N64eVOMg7W0LRECJRIT/view?usp=drive_link](url)

**Comment by hkirat** [comment]
feel free to take a stab at it I'm not assigning anyone per se

**Comment by Piyushrathoree** [comment]
@hkirat im not sure that you think of it or not  , but what if we can add **a extra layer (which contain userid and email or other details like phone number  )** in the video which is similar to the **harkirat.classx.co** video player  , it will remove the vulnerability of screen recording and if this layer attach with the video in encoding , then probably it can solve the issue . ****

**Comment by hkirat** [comment]
no one screen records, everyone uses bots.
Watermarks dont do much unless there is no automated way to download

**Comment by 0xkafkaa** [comment]
https://youtu.be/UhkTIRKdkV4

**Comment by shivam5017** [comment]
<img width="832" alt="Screenshot 2024-11-21 at 1 52 09 AM" src="https://github.com/user-attachments/assets/0b4474ac-578b-4f3c-927b-e71133c4056c">

What i think is m3u8 is not protect or we are directly sending the video url to frontend which can be access from frontend 

After we reach that m3u8 file is downloaded and we can convert it mp4 etc. we can make it more secure or will not send the urls in simple manner

**Comment by ayush-agrawal001** [comment]
we can download the file with single command

```
ffmpeg -i "file.m3u8" -c copy output.mp4
```

[https://drive.google.com/file/d/1sMuN3-jlkskBNIwn39cnz_AyXoDejc_k/view?usp=drive_link](url)

**Comment by GettingError404** [comment]
https://chatgpt.com/share/673feb56-9ca0-8001-af25-70a3896b7570  , ************  this solution  will work  here .

**Comment by 0xkafkaa** [comment]
@GettingError404, I guess it should be pretty tough to crack now but not completey impossible. Since at the moment, the keyformat which is being used is 'Identity' which offers ony minimal level of protection. But someone has to crack the key first in order to do that. If someone does it, it would be cool. I tried but am not able to do it yet.
https://developer.apple.com/documentation/http-live-streaming/using-content-protection-systems-with-hls#Choose-a-key-format
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="1705855799",IV=0xbac40ddde73318534b2f3baf737fd715
#EXTINF:8.333333,
master.ts
```
