### ISSUE TITLE
feature: Add "Mark as Done" Button for Videos and Notes to Manually Track Completion

### ISSUE THREAD

**Issue by SahilLamba0008** [code100x/cms#1576]
**Is your feature request related to a problem? Please describe.**  
I'm frustrated with how the current system marks content as "done." For video lectures, completion is tracked based on whether I watch the video until the end of the timeline. However, many lectures include extended Q&A sessions, and the core content might only last for 1–1.5 hours out of a 2-hour video. This means that even if I've completed the main lecture, it isn't marked as "done."  
Similarly, there is no mechanism to track whether I’ve read notes completely. Since only the user knows if they’ve reviewed the notes, it would be helpful to have a way to manually mark them as "done."  

**Describe the solution you'd like**  
I would like a "Mark as Done" button for both videos and notes. This button would allow users to manually mark content as completed.  
- **For videos:** The current automatic tracking based on the timeline should remain in place, but users should also have the option to manually mark content as done.  
- **For notes:** This feature would provide the only way to indicate completion, since there is no automated tracking for them.  

**Describe alternatives you've considered**  
- **For videos:** Adjust the current tracking mechanism to allow users to mark specific timestamps (e.g., after the main lecture ends) as the completion point.  
- **For notes:** Implement scroll-tracking or text-highlight tracking to estimate completion. However, these methods may not be reliable or user-friendly.  

**Additional context**  
Adding a "Mark as Done" button empowers users to track progress more accurately and flexibly. Here's a mockup of how the button might look on the content page (if needed, we can alter this as required ). This feature would also be helpful for users revisiting content who want to reset or update their completion status manually.  
![Screenshot (91)](https://github.com/user-attachments/assets/d74022f7-ee2a-4d8b-8524-ac81d88fe3cc)

**Comment by nischal-shetty2** [comment]
> /assign @devsargam can i submit a PR for this ?

dont have to wait to be assigned, just create a pr
