### ISSUE TITLE
bug: Unable to view videos in full screen in the app.100xdevs and no video player can be seen from week 14 . The issue seems to be related to video player functionality, causing problems with the display in full screen mode and video clarity issues even in best resolution.

### ISSUE THREAD

**Issue by anpc21** [code100x/cms#1579]
**Describe the bug**  
Unable to view videos in full screen in the app.100xdevs and no video player can be seen from week 14 . The issue seems to be related to video player functionality, causing problems with the display in full screen mode and video clarity issues even in best resolution.

**To Reproduce**  
1. Open the app.
2. Play a video.
3. Tap on the full-screen icon to expand the video.
4. The video fails to load or properly display in full screen.

**Expected behavior**  
The video should play in full-screen mode without issues, showing the entire video content and show the video in best quality as earlier.

**Screenshots or GIFs**  
![Screenshot 2024-11-23 233517](https://github.com/user-attachments/assets/52122153-e672-4daa-b7c1-94d4e7479e68)

**Info (please complete the following information):**  
- Browser: (if relevant, e.g., Chrome or Safari)  
- Version: (App version or browser version)  

**Additional context**  
The issue may be related to a bug in the video player system. This problem has been noted in the Week 13 .

**Comment by mehul-srivastava** [comment]
The screenshot you have attached above is at 1080p (or 720p)? @anpc21 
Can't view the video as I am not from the webdev cohort

**Comment by devsargam** [comment]
Should be really simple just a few tailwind classes in the videoplayer2 componentn

**Comment by SahilLamba0008** [comment]
> Should be really simple just a few tailwind classes in the videoplayer2 componentn

I don't think it's the` VideoPlayer2` component. Starting from week 13, the VideoPlayer component seems to have been replaced or modified, and I believe it's now a different component. **Could you please confirm?** The interface of the video player before week 13 looks completely different from the one used after that. I think it's `AppxVideoPlayer`.

**Comment by Smnthjm08** [comment]
@devsargam  a video from appx to test video player??

**Comment by devsargam** [comment]
Oh yeah you are right @SahilLamba0008. Also, I think the videoPlayer2 component is also rendering little bad video playback eperience

**Comment by devsargam** [comment]
This is fixed
