### ISSUE TITLE
feature: Add a Button to Redirect Users to Mapped Videos on harkirat.classx

### ISSUE THREAD

**Issue by devansh-m12** [code100x/cms#1590]
**Is your feature request related to a problem? Please describe.**  
Currently, videos are uploaded to both `app.100xdevs` (our in-house LMS) and `harkirat.classx`. However, when a video does not work on `app.100xdevs`, users do not have a straightforward way to navigate to the same video on `harkirat.classx`.

**Describe the solution you'd like**  
Add a button on `app.100xdevs` that redirects users to the corresponding video on `harkirat.classx`. This would provide a simple and manual fallback for users when a video fails to work on the LMS.

**Describe alternatives you've considered**  
- Informing users to manually search for the video on `harkirat.classx` through its search bar (less user-friendly).  

**Additional context**  
I would like to work on this issue. It will require:  
- Establishing a mapping between video IDs on `app.100xdevs` and `harkirat.classx`.  
- Adding a UI element (button) in the video player or error state to navigate to the mapped video on `harkirat.classx`.

**Comment by devansh-m12** [comment]
@devsargam can we add this ?

**Comment by devsargam** [comment]
Yes actually this should be great

**Comment by devansh-m12** [comment]
I’d like to work on this issue @devsargam . My initial thought is to add a field for video links in the `videoMetadata` model and follow a similar process as used for slides. Let me know if this approach works or if there are additional considerations.

**Comment by devsargam** [comment]
Sorry I didn't realize it earlier but I don't think it's possible in a good way. We can't assume a user has certain course so it's uncertain which url to put
