### ISSUE TITLE
bug: add volume button also 

### ISSUE THREAD

**Issue by moteeullahazmi** [code100x/cms#1594]
![image](https://github.com/user-attachments/assets/884fd40d-b231-4015-a853-3c544cc65e1e)

**Comment by DevDesignAmitesh** [comment]
can you assign me this @moteeullahazmi....?

**Comment by sanyamhbtu** [comment]
can you please assign it to me @moteeullahazmi

**Comment by devsargam** [comment]
dont think it's easy to integrate it in this type of player

**Comment by sanyamhbtu** [comment]
@devsargam Thank you, sir. I’d like to try it once and see how it works.

**Comment by sanyamhbtu** [comment]
Sir, I visited the official website to review the code and analyze how to fix the bug. However, I noticed that the volume button is already present in the player.
![Screenshot 2024-11-30 135942](https://github.com/user-attachments/assets/607eb044-4c04-44b7-b2f8-d5731ae5def8)

**Comment by moteeullahazmi** [comment]
In your screen shot also available full screen option

**Comment by sanyamhbtu** [comment]
Yes sir now what to do?

**Comment by devsargam** [comment]
@sanyamhbtu I think you fixed the wrong component. You needed to make changes in appxVideoPlayer component not here

**Comment by sanyamhbtu** [comment]
@devsargam  ohk sir i check

**Comment by sanyamhbtu** [comment]
@moteeullahazmi can you tell me where you exactly open this player on website

**Comment by devsargam** [comment]
This is not planned closing
