### ISSUE TITLE
  bug: Search Results Container Overflow Issue

### ISSUE THREAD

**Issue by designed2code** [code100x/cms#1596]
**Describe the bug**
When searching returns multiple results, the results list overflows outside its parent container instead of being contained within it.

**To Reproduce**
1. Navigate to the search bar after login to the https://app.100xdevs.com/ site
2. Enter a search term that will return many results (e.g., "mono")
3. Observe how results extend beyond the container boundaries

**Expected behavior**
1. Search results should be contained within the container
2. A vertical scrollbar should appear when results exceed container height
3. All results should be accessible by scrolling within the container

**Suggested Fix**
1. In the `src/components/search/SearchResults.tsx`
2. Add an `overflow:auto` to the `div` which is having `max-h-[40vh]` 

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/5660782a-b450-4577-a106-f583db46ef32)

![Takeyourdevelopmentskillsfrom0to100andjointhe100xdevscommunity-GoogleChrome2024-11-3022-49-05-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/40454b19-eeab-40c7-b717-a5f3d8d15007)
ser-attachments/assets/5372797b-29ca-48a6-bb3f-6663028ad087)

![image](https://github.com/user-attachments/assets/a7474acc-5aac-4b98-9891-95829b31019e)

**Info (please complete the following information):**
 - Browser :- Chrome
 - Version 131.0.6778.86

**Additional context**

**Comment by anniop** [comment]
if the bug is fixed why the fix is not showing on the website the pr is not merged or what? and if yes please merge it and close the issue

**Comment by designed2code** [comment]
Didn't raise a PR because as per the contributing guidelines "Don't make any pull request for issues you are not assigned to. It will be closed without merging".
https://github.com/code100x/cms/blob/main/CONTRIBUTING.md#dont-while-contributing

**Comment by anniop** [comment]
is this issue assigned to someone?

**Comment by designed2code** [comment]
The maintainer or moderator can assign the issue accordingly.

**Comment by anniop** [comment]
okay got it

**Comment by pkmanas22** [comment]
> Didn't raise a PR because as per the contributing guidelines "Don't make any pull request for issues you are not assigned to. It will be closed without merging". https://github.com/code100x/cms/blob/main/CONTRIBUTING.md#dont-while-contributing

Thank you @designed2code for informing. Sorry that I didn't followed the guidelines. 

What should I do now, should I close the PR or wait for assign or something else.

**Comment by anniop** [comment]
i guess don't close the pr rather ask moderators to assign this task to you or close the pr as soon as the task gets assigned to you then again raise a pr

**Comment by devsargam** [comment]
Feel free to take on the issues you find guys. The best written one will be picked and the issue owner will be given the priority
