### ISSUE TITLE
sidebar scroll UX inconvenience.

### ISSUE THREAD

**Issue by Npanda04** [code100x/cms#160]
When we scroll up and down while the cursor is on the main window then it moves smoothlybut when we try the same while the cursor is on the sidebar still the main window moves not the sidebar. 

It is not a functionally issue but a bad user experience I guess.

below is the attached link for better clarity.

https://drive.google.com/file/d/1PuHKzMauzX4rR9kV2PXrJXXh0lpkcilo/view?usp=sharing

**Comment by geekyharsh05** [comment]
@Npanda04 already solved in #168.
