### ISSUE TITLE
Sidebar Should be Scrollable Independently from Page Content || UX-UI issue

### ISSUE THREAD

**Issue by CodeforAbj** [code100x/cms#161]
Description:
Currently, the sidebar on the page scrolls along with the entire page content, making it difficult to navigate when the content is lengthy. To address this, I've locally implemented a solution using CSS to ensure that the sidebar has independent scrolling behavior.

Expected Behavior:
The sidebar should have its own scroll bar and should scroll independently from the rest of the page content.

Actual Behavior:
Currently, the sidebar scrolls along with the entire page content.

Additional Information:
I have temporarily resolved this issue locally by adding the following CSS properties to the sidebar in inspect window:

element {
  height: 100vh;
}
![image](https://github.com/code100x/cms/assets/142328838/45525982-8307-46b2-8b47-c2d74d5442f5)

**Comment by ramanuj07** [comment]
I am thinking to solve this issue by assigning "fixed" property to the sidebar and position it from the bottom. This way sidebar will have an independent scroll and this issue can be tackled.

**Comment by ayush9h** [comment]
@CodeforAbj @ramanuj07  overflow-y-scroll with fixed height of the sidebar can be used to prevent that. Any suggestions?

![Screenshot 2024-03-06 215252](https://github.com/code100x/cms/assets/102464313/ee91f97d-1dd8-4c01-a6c4-6f333017de19)

**Comment by Masood-ul-Rehman** [comment]
@CodeforAbj please assign this issue to me so that i can work on it

**Comment by Masood-ul-Rehman** [comment]
@CodeforAbj do you know who's the mod her?
