### ISSUE TITLE
bug: Glitch over course Progress Bar (%) 

### ISSUE THREAD

**Issue by CosmoWorker** [code100x/cms#1634]
**Description**
There is a glitch over the progress bar, when one refreshes the percentage keeps changing.
It also takes time to update over the progress bar even after the checking(✅) the videos.

Below is the video for the issue:

https://github.com/user-attachments/assets/e2215c36-42de-476a-945f-e3adfaade97b

**Comment by IkramBagban** [comment]
I have tried this, and it's working fine on my device. I think the problem is on your side.

**Comment by devsargam** [comment]
there are a lot of vides that are hidden which are not shown to the end user that is the problem that is causing the pie chart to not fill so we can ignore this issue
