### ISSUE TITLE
bug: Video is covered with this text informations.

### ISSUE THREAD

**Issue by wali55** [code100x/cms#1636]
![1](https://github.com/user-attachments/assets/f640dda2-a465-40d8-b79d-4f76c945b5e6)
**Describe the bug**
 Video is covered with this text informations. Cannot see the content properly becasue of this.

**Expected behavior**
This information should not be visible on top of the video.

**Info (please complete the following information):**
 - Browser [Chrome]
 - Version [Version 131.0.6778.109 (Official Build) (64-bit)]

**Comment by wali55** [comment]
After I cleared the cookie the issue is solved

**Comment by IkramBagban** [comment]
> After I cleared the cookie the issue is solved

so the problem was with your cookies. right?

**Comment by wali55** [comment]
Sir, I have asked about this problem is chatgpt. It suggests: "While clearing cookies fixes it temporarily for you, it suggests that the app's handling of state or cookies might need improvement."
I have recently faced in issue (around 1 week timeline). Someone familiar needs to check this out if they can ignore this issue or this needs some improvements in the application end.
![2](https://github.com/user-attachments/assets/e56e3ef4-0793-49b7-a2df-b4e6d563eb8e)
![3](https://github.com/user-attachments/assets/a1f53bd6-fa10-43a7-81f3-3d70749befff)
![4](https://github.com/user-attachments/assets/a8d31555-4f9b-4eca-8db6-8ad611e02953)
![5](https://github.com/user-attachments/assets/9def9735-85c7-4db0-b822-d0b4c20e5808)

**Comment by devsargam** [comment]
let's ignore for now unless a lot of people are facing the same issue
