### ISSUE TITLE
design-issue : Sticky header kinda defeats ui purpose on scroll

### ISSUE THREAD

**Issue by anudeeps352** [code100x/cms#1641]
On loading the weeks or lectures inside a course , the sticky header kinda gets in the way when scrolling.If it was done on purpose feel free to update me.Else it would be an easy fix and if needed it can also made into a scroll aware sticky header of sorts.

In the video below the sticky header i.e the home/Test-Course-1/week1 is what I'm mentioning

![2024-12-09 00-48-21](https://github.com/user-attachments/assets/fa9f473c-36e8-467f-943d-c8f3a501b642)

**Comment by anudeeps352** [comment]
If its an issue to be fixed, I'd love to work on it

**Comment by IkramBagban** [comment]
> If its an issue to be fixed, I'd love to work on it

Hey already created and issue and fixed it. Soon it will be merge

**Comment by anudeeps352** [comment]
Oh okay my bad.Will close the issue then
