### ISSUE TITLE
bug: Video Frame Underflows as Title/Breadcrumb Isn't Fixed to Top

### ISSUE THREAD

**Issue by sudhakarbaghel** [code100x/cms#1647]
**Describe the bug**
Title or breadcrumb just above the video is not fixed to top which causes the video frame to underflow below it.

**To Reproduce**
1.Play any course video.

**Expected behavior**
Title should stick to top when scrolling.

**Screenshots or GIFs**
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/ecb70f42-6ddf-4c05-b879-7b2c1f5d3e69">

**Info (please complete the following information):**
 - Chrome
 - Version 131.0.6778.86 (Official Build) (arm64)

**Comment by IkramBagban** [comment]
hey @sudhakarbaghel I already have fixed this issue in #1628

**Comment by devsargam** [comment]
closing in favour of https://github.com/code100x/cms/pull/1628
