### ISSUE TITLE
Too much space b/w video and comments

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#165]
<img width="1538" alt="Screenshot 2024-03-08 at 11 40 05 AM" src="https://github.com/code100x/cms/assets/8079861/1e802056-400a-41b0-998c-aa91c89edd86">

should be lesser

**Comment by Rash-Hit** [comment]
@hkirat .. will take care of that .. sending ss for confirmation from u in a few ..

**Comment by Rash-Hit** [comment]
@hkirat 
can you please confirm .. is this fine 
![image](https://github.com/code100x/cms/assets/73944177/3bd38808-1f56-4e1e-b73c-13dffeeaac85)

**Comment by hkirat** [comment]
looks good

**Comment by Rash-Hit** [comment]
@hkirat ok thanks .. will send pr
