### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by AlistairM13** [code100x/cms#1662]
**Describe the bug**
No titles visible in the course content sidebar

**To Reproduce**
- Clicked on the show content button to open the sidebar
- Can't see any titles

**Expected behavior**
- Should be seeing the titles of the videos

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/127277d6-4cc8-4504-a383-769e511ef795)

**Info (please complete the following information):**
 - Browser - chrome
 - Version - 131.0.6778.140 (64-bit)

**Comment by Kevinkp09** [comment]
Can i take up this issue?

**Comment by avparadox** [comment]
> Can i take up this issue?
This bug has been resolved, updated built is not deployed yet.
Hey @AlistairM13, please close it in favour of #1632

**Comment by AlistairM13** [comment]
Fixed in https://github.com/code100x/cms/pull/1632
