### ISSUE TITLE
Sidebar not scrolling independently

### ISSUE THREAD

**Issue by devsargam** [code100x/cms#167]
https://github.com/code100x/cms/assets/76874341/9456ce7d-a061-4441-89f4-46d7521e2a98

**Comment by devsargam** [comment]
hey @hkirat, is this a good catch? Can I work on it?

**Comment by hkirat** [comment]
yes please!

**Comment by Rimaru06** [comment]
is this issue solved ?

**Comment by devsargam** [comment]
@Rimaru06 Yep, fixed in #126
