### ISSUE TITLE
chapter part is to big in width and side bar is too small in width

### ISSUE THREAD

**Issue by Rimaru06** [code100x/cms#171]
The chapter size is too big because of it sidebar is small in width , chapter side need to be small in width   @hkirat  can i solve this issue
![Screenshot 2024-03-09 205121](https://github.com/code100x/cms/assets/118299308/ea60c842-b3f4-4c7b-b7ed-f3dec1e42ff3)

**Comment by YunusShaikh29** [comment]
@hkirat , is this a good issue?

**Comment by hkirat** [comment]
yes, please fix if u have the time!

**Comment by Rimaru06** [comment]
@hkirat   
![contribute](https://github.com/code100x/cms/assets/118299308/c0b76bd1-a4dc-4417-969d-087e5fd98235)
is this good width for the chapters   and should  i make the sidebar absolute so that it can take the width it want to look good
