### ISSUE TITLE
Hidden videos are showing in folders 

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#176]
They dont show up in the sidebar but seem to be showing up in the folder structure
<img width="843" alt="Screenshot 2024-03-10 at 1 44 44 PM" src="https://github.com/code100x/cms/assets/8079861/8d6526c5-0295-4df1-b9e7-86eee9efdd6b">

**Comment by Rash-Hit** [comment]
will take care of that ..

**Comment by Rimaru06** [comment]
they did show up in the sidebar  @hkirat 
![image](https://github.com/code100x/cms/assets/118299308/c35235d4-b75b-458c-80dd-51a404add033)

**Comment by hkirat** [comment]
oh this might not be an issue then let me confirm if 10.1 isn't hidden from the backend

**Comment by Rash-Hit** [comment]
@hkirat 
seems to be working fine 
![image](https://github.com/code100x/cms/assets/73944177/72e82ac7-515a-4b46-b89a-af0ae88c1e7a)


i 've one video hidden in db 
![image](https://github.com/code100x/cms/assets/73944177/9eb2cd13-7509-469e-ab75-9b50987dad9c)

**Comment by hkirat** [comment]
Yeah my bad closing this issue
