### ISSUE TITLE
docker-compose up Error

### ISSUE THREAD

**Issue by aadeshkulkarni** [code100x/cms#181]
### Description:
`docker-compose up` returns the following errors:

1. `Mounts denied` error for the db host volume address. (for Mac specifically) ( Screenshot attached below )
(Which when resolved by changing the host address, returns the next error)

2. `Error P1001: Can't reach database server.`
The `cms-app` docker container runs the migration script even before the `cms-db` docker container is up. (Error Screenshot attached below)

### Details on Issue 2:
By default, Docker Compose only ensures that the services listed under the `depends_on` property are started before the dependent service. This means that Compose doesn't guarantee that these services are fully operational and ready to process requests, but only that their containers are running.

It is however possible to set conditions to define when one service should start or wait for another service to reach a specific state. These conditions are defined in the `condition` property and take three possible values: `service_started`, `service_healthy`, and `service_completed_successfully`.

### Proposed Solution:
1. Investigate and resolve the issue with the Host volume address to ensure the build mount is successful.
2. Set the appropriate conditions for the `cms-app` container to wait for the `cms-db` container to reach a specific state before running the migration script.

### Steps to Reproduce the issue
1. Run the `docker-compose up` command on a local machine.
2. Monitor the logs and observe the build mount failure and premature migration script execution.
3. Review the Docker Compose file for the services' dependencies and conditions.
4. Implement the necessary changes to resolve the issues.

### Additional resources
https://www.warp.dev/terminus/docker-compose-depends-on

### Proposed solution
https://github.com/peter-evans/docker-compose-healthcheck

#### Issue 1 (Mount fail)
![Screenshot 2024-03-10 at 4 45 57 PM](https://github.com/code100x/cms/assets/67855887/72495eba-fb32-444f-9d04-f6bb6acdc17f)

#### Issue 2 (container cms-app starting before starting cms-db service is healthy)
![Screenshot 2024-03-10 at 5 14 13 PM](https://github.com/code100x/cms/assets/67855887/8601cee5-2342-4942-acdc-e2c52ae126e7)

**Comment by geekyharsh05** [comment]
@aadeshkulkarni you can configure the file sharing by going to settings. it works for me.
<img width="1440" alt="Screenshot 2024-03-10 at 6 00 27 PM" src="https://github.com/code100x/cms/assets/121746800/2814f4a0-1163-496b-981c-85450101982b">

**Comment by geekyharsh05** [comment]
If your db is not running try changing the port number in the `docker-compose.yml` file.

**Comment by aadeshkulkarni** [comment]
> @aadeshkulkarni you can configure the file sharing by going to settings. it works for me.
> 
> <img alt="Screenshot 2024-03-10 at 6 00 27 PM" width="1440" src="https://private-user-images.githubusercontent.com/121746800/311509617-2814f4a0-1163-496b-981c-85450101982b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzQzMDMsIm5iZiI6MTcxMDA3NDAwMywicGF0aCI6Ii8xMjE3NDY4MDAvMzExNTA5NjE3LTI4MTRmNGEwLTExNjMtNDk2Yi05ODFjLTg1NDUwMTAxOTgyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxMjMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTE5YzM4MjYxODNlODZlNzQ5NjA3NGJiMmI0MmFmNTZhYTFjNjViNjliNDY2OWZmMDdmMTRiMTdjNzBmMWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hobzYUCQIrr8Nmgve0lA3mgVMRq4K-NWysgZm9AVDw4">

I have tried doing this. But Docker does not let me create a directory for that address. Using MacOS.
There is a probability that something must be wrong on my end here.

<img width="1787" alt="Screenshot 2024-03-10 at 6 11 45 PM" src="https://github.com/code100x/cms/assets/67855887/633f93e3-913b-4846-9df2-b86b96f85037">

**Comment by devsargam** [comment]
hey @aadeshkulkarni, I am the author of Dockerfile for this repo. 
Try @geekyharsh05 approach or change the postgres volume in `docker-compose.yml`

TY

**Comment by devsargam** [comment]
Also, @aadeshkulkarni [this](https://discord.com/channels/1171768226691162162/1178318174920380566/1216292791911714938) has been resolved.

It's just the way docker is wired in mac os.

**Comment by aadeshkulkarni** [comment]
Configuring the file sharing by going to settings didn't work for me. 

I have changed the postgres volume to make it work for now.

 Can you confirm if Issue#2 is reproducible ? @devsargam  & @geekyharsh05 
 This issue only occurs during initial app setup (for fresh first time db migrations)
 If you've already performed db migrations, you might need to clear your volumes to test this.

**Comment by devsargam** [comment]
@aadeshkulkarni haven't reproduced but your point seems valid.

**Comment by geekyharsh05** [comment]
@devsargam what if you try this approach, instead of using absolute path we can use relative path, so it'll become easy for anyone to setup the project using docker. Is it a right approach?

```yaml
volumes:
      - /postgres-data:/var/lib/postgresql/data
```

**Comment by aadeshkulkarni** [comment]
> @devsargam what if you try this approach, instead of using absolute path we can use relative path, so it'll become easy for anyone to setup the project using docker. Is it a right approach?
> 
> ```yaml
> volumes:
>       - ./postgres-data:/var/lib/postgresql/data
> ```

This PR has the solution @geekyharsh05 mentioned above for issue #1.

It also has issue #2 resolution. but keeping the PR as draft until #2 is reproducible by someone else.

**Comment by devsargam** [comment]
Just in case did you do
docker rmi
docker compose up --build?

**Comment by aadeshkulkarni** [comment]
Yes, 

removed db volume on the local host by deleting the`/postgres-data` directory. (to clear all previous db migrations)

Then `docker compose up` with or without `--build` should trigger the issue
