### ISSUE TITLE
The sidebar height needs to consider it's height minus the navbar height.

### ISSUE THREAD

**Issue by nigupta29** [code100x/cms#187]
At present the height of the sidebar is of full screen height (i.e. h-screen), by which the content at very last accordion i.e. Week 15 is hidden from the main screen.
Such that the height of the navbar should be taken care in the height of the sidebar.

**Comment by YunusShaikh29** [comment]
@nigupta29 can you provide screenshot to make it clear that what changes you're suggesting?

**Comment by nigupta29** [comment]
In the below screenshot, if I have to select the week 15 content then I have scroll fully down to the page because the scroll bar has height of 100vh which is simply going out of the pov because the navbar height hasn't been considered in the view. 
If we simply compensate the height of navbar from sidebar (i.e. current height of sidebar - height of navbar) this will resolve the issue.
It's a quick fix if you wanna do or let someone pick who is new to OS contri.
If still got some queries, hit me up on discord - jerry_codes

![image](https://github.com/code100x/cms/assets/128571356/4bc84d4e-ff61-4ad5-8257-e42877ebbfa5)

**Comment by devsargam** [comment]
Hey @nigupta29 nice catch. I was the one responsible for this.

**Comment by devsargam** [comment]
Raise a pr mostly kirat will accept and mb

**Comment by prasanth7890** [comment]
Hey im new to opensource and still trying to understand the codebase. can i solve this issue.

**Comment by nigupta29** [comment]
@prasanth7890 Definitely! Go ahead!
