### ISSUE TITLE
Light mode is bonked for chapters

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#189]
<img width="985" alt="Screenshot 2024-03-11 at 12 44 34 AM" src="https://github.com/code100x/cms/assets/8079861/8acf9d87-efc5-430a-b22d-81bccb4dfaa7">

**Comment by Rash-Hit** [comment]
will .. check that. and fix it

**Comment by Rash-Hit** [comment]
@hkirat 
I think #178  addresses this issue.

@aadeshkulkarni , can you please confirm here once ..

**Comment by aadeshkulkarni** [comment]
Yes, that's right. 

@hkirat - have added before and after screenshots in #178.
