### ISSUE TITLE
Add some border to comment box

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#190]
<img width="1408" alt="Screenshot 2024-03-11 at 1 50 06 AM" src="https://github.com/code100x/cms/assets/8079861/2c7847b6-290a-468a-90e5-4abbda658fa1">
<img width="1458" alt="Screenshot 2024-03-11 at 1 50 01 AM" src="https://github.com/code100x/cms/assets/8079861/a543d320-a6b7-43bb-ad6a-3fb29522f34c">

**Comment by Rash-Hit** [comment]
@hkirat 
is this fine 
![image](https://github.com/code100x/cms/assets/73944177/08c5cc56-ee71-40df-b1ee-788230f9cbff)

![image](https://github.com/code100x/cms/assets/73944177/a5f7299f-d299-4cbf-b92e-19ac4cff6c5b)


obvio ,, will change the color ..

**Comment by nimit9** [comment]
@Rash-Hit I think he meant a border on an individual comment

**Comment by Rash-Hit** [comment]
@hkirat  can you please confirm , which one we want .. above one's or  these ...

![image](https://github.com/code100x/cms/assets/73944177/8215fdca-d72d-445d-af4d-8d8744fcebd2)

![image](https://github.com/code100x/cms/assets/73944177/fd3711d0-4305-41dc-84d3-0fd3c533f6bc)

**Comment by Prakhar788** [comment]
@hkirat 

![Screenshot (97)](https://github.com/code100x/cms/assets/102613412/a7f638f2-0b61-42e0-9b9c-68cd462e633d)
![Screenshot (96)](https://github.com/code100x/cms/assets/102613412/ac927fd2-6ee0-4c3d-a03b-027289f4af7b)

I am little confused about adding border to which box if you want I can add border individually to every comment box also.


![image](https://github.com/code100x/cms/assets/102613412/ab04b669-70b3-4aa9-a176-d5009126b517)
![Screenshot (99)](https://github.com/code100x/cms/assets/102613412/68df2c39-470e-4901-938c-6e28657d1087)

**Comment by Prakhar788** [comment]
@hkirat 
I am little confused about adding border to which box if you want I can add border individually to every comment box also.
![Screenshot (95)](https://github.com/code100x/cms/assets/102613412/aae0caa2-b760-4b09-89b1-d59b92563885)
![Screenshot (96)](https://github.com/code100x/cms/assets/102613412/fe1c0a0f-fcfb-4b9c-8b07-c6f54fd6126b)
![image](https://github.com/code100x/cms/assets/102613412/6769e544-844d-4144-8bf9-1dc01e8b0d8b)
![image](https://github.com/code100x/cms/assets/102613412/c261ceb9-8d5c-4646-ae01-ef54b4a015ac)
