### ISSUE TITLE
When hitting route app.100xdevs.com/api/user giving someone elses credentials

### ISSUE THREAD

**Issue by punyakrit** [code100x/cms#194]
Even if i am logged in or not in website and hitting url
https://app.100xdevs.com/api/user its spitting out someones else credentials

<img width="589" alt="Screenshot 2024-03-11 at 3 32 31 PM" src="https://github.com/code100x/cms/assets/67222925/a32944f8-d6c6-4e6a-8a8a-e637f0a334e2">

**Comment by himanshuxmehra** [comment]
i **think** this is likely not an issue but a user with token 'null' in the db.
however, api/user/route.ts should check for null in the token.

@hkirat can you assign me this?

**Comment by hkirat** [comment]
might be some incorrect cache @himanshuxmehra
