### ISSUE TITLE
Add big cache to appx api endpoint for purchases

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#195]
Add a 1 day cache here so dependency on this api reduces - https://github.com/code100x/cms/blob/main/src/utiles/appx.ts#L61

**Comment by devsargam** [comment]
Hey @hkirat already working on that file
Should I integrate it in #169

Or can u wait for the change?

**Comment by achyutvardhan** [comment]
I m intrested

**Comment by sahalbelam** [comment]
i think i have got the answer

**Comment by TanmayDhobale** [comment]
can u pls check the pull request #196

**Comment by bharathkumar01-k** [comment]
Will include redis here.store the the response of the api in redis with a key which has the expiry of about 24 hrs.If there is a cache hit will return the response , else fetch part will get called and stores it in redis and the response will be retruned

**Comment by nigupta29** [comment]
Will the Next JS [Cache](https://nextjs.org/docs/app/building-your-application/caching#data-cache) system can provide the solution for this issue?

**Comment by sahalbelam** [comment]
check the pull request ("i have added cache mechanism")
