### ISSUE TITLE
Progress feature

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#2]
store in the DB (along with the duration watched) if the video is marked as done
expose user progress in percentage and show somewhere on UI

**Comment by AakashTyagi354** [comment]
hey @hkirat can i work on this feature

**Comment by nimit9** [comment]
Hey @AakashTyagi354, are you still working on this feature?

**Comment by nimit9** [comment]
@hkirat After the video is marked as done, tracking the duration of the video should stop, or should it still continue if user again waches the video

**Comment by hkirat** [comment]
duration should be unaffacted by this

**Comment by nimit9** [comment]
This can be closed now @hkirat
