### ISSUE TITLE
Add standard linting for vscode 

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#201]
Lot of people are having big lint diffs while contributing
I'm assuming its because vscode (or whatever ide being used) is linting it a way that our project doesnt expect
For example - https://github.com/code100x/cms/pull/199#pullrequestreview-1928042480 
Need a way so that auto lints in vscode follow the pattern expected

**Comment by nimit9** [comment]
Can add prettier configuration for generalised formatting and linting

**Comment by TanmayDhobale** [comment]
@hkirat  We'll update  .editorconfig` and ESLint setup in VSCode to fix the linting issues. This will keep everyone's code consistent. what do u think

**Comment by devsargam** [comment]
should be fixible with eslint extending prettier config

**Comment by aadeshkulkarni** [comment]
Ideally, the pre-commit hook should have not allowed the commit to go through if the linting failed for #199 

The first checkpoint can be to fix the pre-commit hook. And if that does not solve the issue, we can extend / update ESLint setup.
