### ISSUE TITLE
Red Squiggle Line in courses / [...courseId] / page.tsx

### ISSUE THREAD

**Issue by amanbairagi30** [code100x/cms#212]

**Comment by amanbairagi30** [comment]
@hkirat 
![image](https://github.com/code100x/cms/assets/118182376/0c036c19-75eb-416e-8091-3f64d90dda29)

**Comment by YunusShaikh29** [comment]
![image](https://github.com/code100x/cms/assets/111998184/9b87109a-1a75-47f7-a8f0-d85caaeff640)
I don't see implicit any type on p?

**Comment by krishhh16** [comment]
Hey! I've managed to find out the output of the await call
