### ISSUE TITLE
Loader Doest go away 

### ISSUE THREAD

**Issue by vijayindalkar** [code100x/cms#223]
### **Simple Bug**

Steps To reproduce it : 

**1) Go to Any Course Page**

![image](https://github.com/code100x/cms/assets/61607592/ed7c0898-e5db-4d4e-950e-69403edbab48)

**2) Click on Buy Now:** 

![image](https://github.com/code100x/cms/assets/61607592/50591848-497a-433f-80be-626d79f99907)

**3) Cancel Payment:**
 
![image](https://github.com/code100x/cms/assets/61607592/fc12c6f2-264b-452f-a934-5e97b13ea761)

**4) You will see the Loading animation and doesn't go away:** 

![image](https://github.com/code100x/cms/assets/61607592/321e8aa6-bb41-49ed-a147-cff80ca2392b)

**Comment by devsargam** [comment]
Hey, this repo is only for app.100xdevs.com but the issue you are referring is for external service
