### ISSUE TITLE
Update footer twitter logo.

### ISSUE THREAD

**Issue by hanzalahwaheed** [code100x/cms#224]
# Issue
- The current logo of X (fka twitter) on the landing page is a deprecated one.
- The current icons library "lucide-react" doesn't have the new "X" logo.
![image](https://github.com/code100x/cms/assets/101456741/1513855a-af50-4b5c-b55d-a12c9fecdb26)

# Solution
- Just replace it with an SVG of the new "X" logo.

**Comment by maheshsp1809** [comment]
hi hanzalahwaheed will fix it but may I know why am I getting this 
![Screenshot 2024-03-15 173051](https://github.com/code100x/cms/assets/128578257/44a2bbb7-0320-4373-b954-1e60308826c1)

**Comment by Rimaru06** [comment]
![icons_CMS](https://github.com/code100x/cms/assets/118299308/4b5c3e15-7c7b-42fb-a844-30b05d5e2717)
i have replaced the lucide with react icons beacuse the icons from lucide are deprecated and changed the twitter icon  @hkirat

**Comment by Rimaru06** [comment]
should i raise the pr @hanzalahwaheed  @hkirat
