### ISSUE TITLE
Conflict between `.eslint` and `.prettierrc`

### ISSUE THREAD

**Issue by devsargam** [code100x/cms#23]
The following two config files contradict each other so
`npm run format:check`
`npm run lint:check`
will not be successful at the same time so, the whole repo needs to follow a single code style and must be linted in a separate pr
 
https://github.com/code100x/cms/blob/825b5ff4ed36745f086bb737af7659bb9b2952a8/.prettierrc#L2
https://github.com/code100x/cms/blob/825b5ff4ed36745f086bb737af7659bb9b2952a8/.eslintrc#L91

**Comment by devsargam** [comment]
I'll work on #19 after your word

**Comment by devsargam** [comment]
@hkirat sorry for the ping but can this get your attention?

**Comment by Airbornharsh** [comment]
@devsargam if resloved then close it
