### ISSUE TITLE
Sidebar | Improving the UX

### ISSUE THREAD

**Issue by aadeshkulkarni** [code100x/cms#232]
### UI/UX issues with Sidebar
1. Checkbox color (blue) increases visual instability by adding a third color to the sidebar. Changing it to shades of gray will improve UX. 
2. Go back button is unnecessarily getting focus due to blue bg-color. 
3. Accordion title hover changes bg color and adds underline to title. Underline is unnecessary, causes visual instability.
4. Accordion title does not have user's progress (For instance, 3/4 done. Something that apps like Udemy have)
5. Scrolling is required. But scrollbar can be hidden. The scrollbar uglifies the UI. It's possible to keep scrolling functionality without showing scrollbar. (And this is already implemented in other pages of cms)
6. Accordion children elements look congested. They can have some space to breathe. Looks visually depressing at this moment.

<hr />

###  Existing UI (Dark mode)
<img width="297" alt="Screenshot 2024-03-16 at 11 11 15 AM" src="https://github.com/code100x/cms/assets/67855887/8750721e-e7fe-4c98-82ac-56d6e141595a">

###  Proposed UI (Dark mode)
<img width="297" alt="Screenshot 2024-03-16 at 11 11 12 AM" src="https://github.com/code100x/cms/assets/67855887/d04c2f51-ec6e-4b12-8f19-8a771d9d3b3d">

<hr />

###  Existing UI (Light mode)
<img width="297" alt="Screenshot 2024-03-16 at 11 10 58 AM" src="https://github.com/code100x/cms/assets/67855887/16780423-4404-4786-8345-68cfef4d11a6">

### Proposed UI (Light mode)
<img width="310" alt="Screenshot 2024-03-16 at 11 26 43 AM" src="https://github.com/code100x/cms/assets/67855887/043fed1e-63a6-4f04-ba8f-b381ea55743e">

<hr />

**Comment by aadeshkulkarni** [comment]
I have made the proposed changes on my dev instance. If the maintainers feel like moving forward with this, I can raise a PR.

**Comment by nihar-hegde** [comment]
instead of completely removing the scrollbar a custom scrollbar can be implemented 


![Screenshot from 2024-03-24 12-44-36](https://github.com/code100x/cms/assets/59167599/7db372cc-55df-4c32-bf60-f59cece79197)
![Screenshot from 2024-03-24 12-44-54](https://github.com/code100x/cms/assets/59167599/37fde499-ba6e-4ed5-a2f2-de06edaa630b)

**Comment by hxdy-1** [comment]
@aadeshkulkarni @nihar-hegde why u guys have not raised a PR yet? custom scroll bar looks way better here!
