### ISSUE TITLE
Continue where you left at

### ISSUE THREAD

**Issue by devsargam** [code100x/cms#233]
Currently:
- Users are able to find the videos which they have completed
- Users are able to continue at a point where they left in video

Problem:
- A solution somewhat similar to netflix where it shows exactly where the user left when opening a course

**Comment by aadeshkulkarni** [comment]
So, If a user is on Week 12 - Video 2, at 12:35 mins. they close the browser. 
At any time in future, when they open https://app.100xdevs.com/, it should open Week 12 - Video 2, 12:35 mins. 

Is that correct ?

**Comment by devsargam** [comment]
@aadeshkulkarni I am working on a fix, okay? cool?
