### ISSUE TITLE
Cards are not aligned properly also some image is not visible in card.

### ISSUE THREAD

**Issue by pankaj-2503** [code100x/cms#24]
As you can see what the issue is from below images.
![image](https://github.com/code100x/cms/assets/90036864/e4883062-b47c-472a-9be3-9b9613529f2f)

**Comment by sahilsuman933** [comment]
If you inspect the flexbox layout using a browser inspector, you'll find it's properly aligned. Therefore, this is not an issue.
![image](https://github.com/code100x/cms/assets/34382211/10e4711b-dd20-4e1d-b477-5b2afba1eb94)

**Comment by sahilsuman933** [comment]
@hkirat close this PR as this is not a proper issue.
