### ISSUE TITLE
Inconsistency in ui

### ISSUE THREAD

**Issue by Pratham271** [code100x/cms#247]
<img width="1710" alt="Screenshot 2024-03-19 at 1 06 44 PM" src="https://github.com/code100x/cms/assets/83640434/c7616e19-2b0d-447f-b6fa-86dd0994f2a5">
While playing some videos the sidebar is taking less width while with others its fine 
<img width="1471" alt="Screenshot 2024-03-19 at 1 09 53 PM" src="https://github.com/code100x/cms/assets/83640434/e150d034-6d90-4258-aaa8-f8a5ee222291">

**Comment by Pratham271** [comment]
I'd like to work on this one but in cloned repo I can see the code base but I can't see the output for these parts for obvious reasons.

**Comment by devsargam** [comment]
Did u seed the db? @Pratham271

**Comment by Pratham271** [comment]
yeah i did seed it but it only shows the test courses but if I click on them I am being redirected to the original site therefore I am not able to reach this specific page on the dev side

**Comment by devsargam** [comment]
@Pratham271 it shouldn't be like that could u share a recording of what's going wrong?

**Comment by Pratham271** [comment]
@devsargam it is working fine with local setup but not the same with docker setup. It worked for local though
<img width="1709" alt="Screenshot 2024-03-19 at 4 12 03 PM" src="https://github.com/code100x/cms/assets/83640434/d9aa5a18-eefa-4839-a95a-bbe0872da2cf">

**Comment by devsargam** [comment]
Yeah got it. Need to figure out a way to exec into db and see it.
