### ISSUE TITLE
ipad layout is broken

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#249]
![WhatsApp Image 2024-03-19 at 23 28 29](https://github.com/code100x/cms/assets/8079861/104b3eb5-4236-4bd2-b80c-7d36411ba0a7)

**Comment by Pratham271** [comment]
@hkirat I would like to work on this one

**Comment by Pratham271** [comment]
I tried it using developer tools seems working can you tell what's the issue specificly

**Comment by Adiiittt** [comment]
Works fine for my iPad. I have asked the person having the issue to give a video how he reached to it.
![image](https://github.com/code100x/cms/assets/107144471/75872eba-7b0c-49c9-ac51-9f95de961792)

**Comment by Pratham271** [comment]
Yup that'd be better. Although there is a layout issue on some videos,
somehow they are not getting the width decided for them.

**Comment by Neon-20** [comment]
Not able to reproduce it @hkirat

**Comment by rahmatdeep** [comment]
![image](https://github.com/code100x/cms/assets/65558628/298c6cd6-170a-470b-9c02-32e5f01ce6eb)


can't reproduce
