### ISSUE TITLE
Add new History feature

### ISSUE THREAD

**Issue by Adityaakr** [code100x/cms#250]
Requesting a feature similar to YouTube's history tracking in Code100x. 
This would enhance user experience by allowing them to easily resume their coding journey and revisit previously viewed videos.

Something like this -

![Screenshot from 2024-03-20 13-20-38](https://github.com/code100x/cms/assets/128833380/f3caf2c6-b86f-4e88-b357-2d1e1ed63bb8)

**Comment by nimit9** [comment]
I'd like to work on this
@hkirat if you'd like this feature, please assign it to me

**Comment by hkirat** [comment]
Probably need to store update_time in `video_progress` and fetch it sorted by `update_time` from there

**Comment by nimit9** [comment]
> Probably need to store update_time in `video_progress` and fetch it sorted by `update_time` from there

Should we also store video_duration in video progress to show the bottom bar

**Comment by Adityaakr** [comment]
Great! @hkirat  
@nimit9 try solving this... and give update in next 24 hrs
otherwise I am going to build this feature anyways..

GoodLuck!

**Comment by nimit9** [comment]
> Great! @hkirat sir for suggestion.
> 
> and issue assigned to @nimit9 try solving this... and give update in next 24 hrs
> otherwise I am going to build this feature anyways..
> 
> GoodLuck!
> 

Hey, if you were going to develop this feature, then you can go ahead with this. I thought you were just requesting the feature, but not developing it. Let me know if you want me to take it up.

**Comment by Adityaakr** [comment]
@nimit9  issue is assigned Sir! Give it a try once
