### ISSUE TITLE
Highlight courses sidebar for the currently running content similar to YouTube.

### ISSUE THREAD

**Issue by haddercone** [code100x/cms#256]
Currently there is no way to know on which content we are at on the courses sidebar, this creates a bad user experience. 
It would be great , if we could implement currently running content highlighting similar to YouTube.

![Screenshot from 2024-03-22 08-58-59](https://github.com/code100x/cms/assets/32171406/946d0ffc-31ba-4881-9668-edf4b9c8dea7)

I'd like to work on it, if we decide to proceed with this issue.

Please let me know your thoughts on this.

**Comment by Deepak1649** [comment]
Hey haddercone, I hope you have already setup the project, just wanted to know if login is working when you proceed with docker?

**Comment by haddercone** [comment]
> Hey haddercone, I hope you have already setup the project, just wanted to know if login is working when you proceed with docker?

Yes, login is working for me. 
I'm not using docker.

**Comment by devsargam** [comment]
@Deepak1649 running with docker and login does work
![image](https://github.com/code100x/cms/assets/76874341/3f650944-ae2a-4e1c-b1fc-1335ea6dd71a)

**Comment by Deepak1649** [comment]
@devsargam Can you give after login ss

**Comment by devsargam** [comment]
If you are expecting courses here then you either need to seed the db or create courses from the /admin endpoint.

![image](https://github.com/code100x/cms/assets/76874341/d0dd3183-ab5d-4795-9cf6-732774d35049)

**Comment by Deepak1649** [comment]
Thanks, It might just now working on my system, with error logging in, I thought this could be a issue :)
