### ISSUE TITLE
Show duration (in hours) next to the video title

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#259]
In the sidebar

**Comment by nimit9** [comment]
Will add this in #253

**Comment by nimit9** [comment]
Currently, there is no video duration stored in our db

The way we can do this is whenever the admin adds the video metadata (which has the video url), we can use ffmpeg to get the video duration from the url and pass it along in the metadata.

In the videometadata table, duration column is already present, which will be mapped to whatever the duration we get from ffmpeg

P.S. I'm not sure how slow will ffmpeg work for large file.


The other option is to let the admin add duration itself.

@hkirat please let me know if this the correct approach?

**Comment by nimit9** [comment]
Tried fluent-ffmpeg, but it requires ffmpeg to be installed on the machine. Will we be able to install it on the server?  @hkirat

**Comment by hkirat** [comment]
there should be duration in the db - https://github.com/code100x/cms/blob/main/prisma/schema.prisma#L104
This is in seconds

**Comment by nimit9** [comment]
Is it getting added in prod though?
In local we're not setting it anywhere

**Comment by nimit9** [comment]
> In the videometadata table, duration column is already present, which will be mapped to whatever the duration we get from ffmpeg

But where is this duration coming from?

**Comment by nimit9** [comment]
@hkirat, if the video duration isn't there in the db, (it's there in the schema, but it would be null afaik),
we would need to run a script which will add the duration to the existing VideoMetadata table, where duration is null.
Also add the code for adding the duration for the new video added.

Please assign me the issue if this is the correct approach

**Comment by hkirat** [comment]
yeah people are adding it manually

**Comment by nimit9** [comment]
> yeah people are adding it manually

Okay, cool, thanks!
