### ISSUE TITLE
Feature needed:  Display Week Information Above Video Section for Improved Navigation Clarity

### ISSUE THREAD

**Issue by Abhishek-1337** [code100x/cms#261]
When a user plays a video from a specific week in the repository, the sidebar undergoes a re-rendering process, which complicates the user's ability to discern from which week the video is being played. This lack of clarity can lead to confusion and frustration among users. Additionally, without clear information about the week from which the video is playing, users may find it challenging to navigate back to the relevant content or maintain context within the repository.

If fixed it will definitely help in enhancing user experience and streamline navigation.

### How it looks:
![Screenshot 2024-03-22 203515](https://github.com/code100x/cms/assets/65114993/fe03cdbc-b3e7-4d9d-856d-5afee432e346)

### How it should look:
![Screenshot 2024-03-22 203833](https://github.com/code100x/cms/assets/65114993/8eab2aca-cebf-473b-b91c-9aa9bf27c4c5)

In above screenshot you can see it clearly shows that user is in order page now.

**Comment by haddercone** [comment]
Hi @Abhishek-1337 , #258 fixes this issue.

**Comment by Abhishek-1337** [comment]
@haddercone Is it pushed into the production?

**Comment by haddercone** [comment]
@Abhishek-1337 , not yet.
