### ISSUE TITLE
Enhancement: The course page needs to be more descriptive.

### ISSUE THREAD

**Issue by meetjn** [code100x/cms#266]
Current Behavior: In the image below, one can see that each folder has only the word "week" title, which can confuse someone switching from week folder to week folder. 

eg: If I want to know the contents of week 13 I first have to open the folder and then see the content inside which is an extra effort.

<img width="1440" alt="Screenshot 2024-03-24 at 8 23 37 AM" src="https://github.com/code100x/cms/assets/141674944/02dba29a-68c6-401b-b98a-c1c4df5c19b0">

Desired Behavior:  add a descriptive title of the folder after the word week eg: week 15 folder can be named as  "week 15- Docker end to end". So on and so forth for every week.

**Comment by VishruthVS** [comment]
Anyone working on this feature?
