### ISSUE TITLE
Add "Show Password" Checkbox for /api/auth/signin

### ISSUE THREAD

**Issue by sagarb2003** [code100x/cms#27]
I would like to  add a "Show Password" checkbox below the password field in the `/api/auth/signin` endpoint for a better user experience.

<h3>Current State</h3>
<img width="958" alt="image" src="https://github.com/code100x/cms/assets/99736036/e01219c9-bee9-4904-acd0-5b875dc93c59">

<h3>Desired Result</h3>
<img width="167" alt="image" src="https://github.com/code100x/cms/assets/99736036/20a452b1-28f5-4097-a274-692dd21b201d">

**Comment by krishnagptamcs** [comment]
naaah , i think it is okay !

**Comment by siinghd** [comment]
@sagarb2003 That's the default signin page of NextAuth. It can be improved with custom page. More info https://next-auth.js.org/configuration/pages.
