### ISSUE TITLE
Notion renderer is not rendering certain code blocks

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#270]
Original notion doc - https://quickest-juniper-f9c.notion.site/Week-10-2-a67d680967b3478fbe0f560edcd09d7c
Doc on website - https://app.100xdevs.com/courses/3/190/227#cf12889a91494be483b5ad64d7c9e999

Cant see the code snippets in here even though they are present in the original doc
<img width="1719" alt="Screenshot 2024-03-24 at 3 59 09 PM" src="https://github.com/code100x/cms/assets/8079861/e548516c-fc08-4854-ac60-2e567e29000c">

**Comment by nimit9** [comment]
On it
