### ISSUE TITLE
bug(edge case): Unable to see some courses

### ISSUE THREAD

**Issue by devsargam** [code100x/cms#272]
### User courses are stored in db so if anyone already in db purchases a new course db is not updated.

ref:https://github.com/code100x/cms/blob/c5c720cd71adff7ada1e2bb6f89f43f38667208d/src/utiles/appx.ts#L68-L87

context:
![image](https://github.com/code100x/cms/assets/76874341/10749d8d-0c05-4fcd-83dd-f18e8c947b0f)

@hkirat could u add this mail to db: `rahul.mymail1@gmail.com`

**Comment by hkirat** [comment]
probably need a job to run everyday that refreshes these

**Comment by hkirat** [comment]
Fine for now since videos are being added in both the places

**Comment by devsargam** [comment]
I have an idea can u assign this?
