### ISSUE TITLE
Feature Request: Enhanced Video Navigation Controls

### ISSUE THREAD

**Issue by vijaysingh2219** [code100x/cms#273]
As a user, I often find myself wanting more flexibility and control when navigating through videos on the platform. Currently, we have basic options like seeking 5 seconds backward and forward, but I believe we can significantly improve the user experience by introducing additional navigation controls.

- J and L Keys for 10-Second Seek: Adding keyboard shortcuts 'J' and 'L' to seek backward and forward by 10 seconds, respectively. This would provide users with a quicker way to navigate through longer videos. Also, For example, if the user increases the playback speed to 1.5x, seeking backward or forward by 10 seconds would actually seek 15 seconds in real time, providing a more accurate and intuitive navigation experience.
- K Key for Pause: Introducing the 'K' key as a shortcut for pausing and resuming video playback. This would streamline the user's ability to pause the video without having to reach for the mouse.

- Component [src/components/VideoPlayer.tsx](https://github.com/code100x/cms/blob/main/src/components/VideoPlayer.tsx)

**Comment by hkirat** [comment]
yup feel free to PR this
