### ISSUE TITLE
Server actions creating a new cache which is differnt from the cache being used by getPurchases

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#279]
https://github.com/code100x/cms/blob/main/src/actions/refresh-db/index.ts#L76 doesnt work since a new instance of the cache class is being created (even tho we're using singletons)

**Comment by devsargam** [comment]
@hkirat, I think it is because the server action is deployed independent as a serverless function during build.

Might be very wrong. 
![image](https://github.com/code100x/cms/assets/76874341/78f9b076-9a08-47eb-b902-8e8bf358e4d2)

**Comment by mumin-khan** [comment]
@hkirat if we use global Object instead of this. the issue gets resolved.
In the current state of code, all of the Server Actions have access to one object while as other code like get purchases used in api folder share another object. I thought it maybe because of what @devsargam suggested but using global Object, all of them have access to same object. If what @devsargam suggested was right then global Object should be also different which is not the case.
I am still exploring this.

**Comment by mumin-khan** [comment]
This fixes the issue.
Have found something strange
Server actions passed as prop don't initialize a new object for singelton where as if imported in client-component it initializes a new object.
Created a small example for replication and can confirm the issue exists.

**Comment by VK-RED** [comment]
@hkirat Seems like the actions are deployed in Serverless fashion. So this action can create a new Instance.

## Proof for the statement

### In Prod

Link to the DemoSite - https://serverless-demo-action.vercel.app/

![image](https://github.com/code100x/cms/assets/130341088/5f5b3f97-34f3-4dfc-b6d5-ffe0ed411561)
(The action can't access the env var)

![Screenshot from 2024-03-31 11-44-27](https://github.com/code100x/cms/assets/130341088/c09cbe39-fdb8-4b72-b0a5-2e64ce9ed103)

### In Dev
![Screenshot from 2024-03-31 11-44-45](https://github.com/code100x/cms/assets/130341088/8a30263f-a6b7-4276-9794-76af9df3d26d)

**Comment by mumin-khan** [comment]
@VK-RED 
![image](https://github.com/code100x/cms/assets/63766734/59ef3f9f-2739-4d4c-8576-a9fc157e3ddf)
https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations
What you are saying is not necessarily true as per docs.

**Comment by VK-RED** [comment]
@mumin-khan Yeah !! as per docs I can completely agree with you. But if the action runs on the same server then why can't the action access the variable and show the original value instead of undefined?

**Comment by mumin-khan** [comment]
@VK-RED please share repo link

**Comment by VK-RED** [comment]
@mumin-khan  Nothing fancy just an action getting the env and returning it. repo link https://github.com/VK-RED/serverless-demo-action. Just curious how you tested this issue and resolved it?
