### ISSUE TITLE
Bug:Video Continues Playing After Logout

### ISSUE THREAD

**Issue by Pratham271** [code100x/cms#284]
Even though I am logout video still plays until you refresh the page 
<img width="1555" alt="Screenshot 2024-03-28 at 7 49 36 AM" src="https://github.com/code100x/cms/assets/83640434/19acd7d8-e90e-4d6e-af48-83ffd8347717">

**Comment by Pratham271** [comment]
@hkirat I would like to fix this one

**Comment by Programmer-Dost** [comment]
@hkirat how am I supposed to login into the app to test this?

**Comment by devsargam** [comment]
Email: random@example.com
Pass: 123456

@Programmer-Dost

**Comment by Programmer-Dost** [comment]
> Email: [random@example.com](mailto:random@example.com) Pass: 123456
> 
> @Programmer-Dost

not working, I also tried adding a custom db in Prisma schema and it says **not in db** and throws an error.

**Comment by devsargam** [comment]
Have u setup env?

**Comment by Neon-20** [comment]
Hey @Pratham271 , this doesn't seem to be a bug on device, since once we logout we are redirected back to /signin immediately

**Comment by Pratham271** [comment]
@Neon-20 that's correct when the user logs out of the app but when his/her session is expired then the user is not logged out until it makes another request
