### ISSUE TITLE
Add a download button to notes

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#285]
Logic can be copied over from daily-code repo, it already has a download button
<img width="880" alt="Screenshot 2024-03-28 at 10 39 47 PM" src="https://github.com/code100x/cms/assets/8079861/102f7d07-8c9a-4483-8ee0-7ac2ec0a0723">

**Comment by nimit9** [comment]
On it

**Comment by nimit9** [comment]
Done @hkirat
