### ISSUE TITLE
Enhancement: Alignment Image colors with rest of UI color palette.

### ISSUE THREAD

**Issue by djbtw** [code100x/cms#295]
Currently in courses route for Folder, Video and Notes images have a very odd colors with rest of the UI color color palette.
![image](https://github.com/code100x/cms/assets/160743795/5c077b95-bf93-41c0-9d44-472301e98a72)

Proposed Enhancement

Changing the images colors to align with the rest of UI 
![image](https://github.com/code100x/cms/assets/59690289/a18ec21a-c67c-4b70-ba9d-9e950170d17e)

**Comment by djbtw** [comment]
@hkirat attached zip file with all the images
[images.zip](https://github.com/code100x/cms/files/14811753/images.zip)

**Comment by harpreet-deepdive** [comment]
Is this task assigned to someone. Can I work on this. @hkirat sir.
