### ISSUE TITLE
feature: theatre mode in the platform

### ISSUE THREAD

**Issue by ezhil56x** [code100x/cms#296]
**Is your feature request related to a problem? Please describe.**
For people using only one screen having theatre mode in the platform is really useful and a great ux

**Describe the solution you'd like**
Currently video.js is used which supports theatre mode. So I think it is not that difficult to implement theatre mode.

**Comment by Aryam2121** [comment]
import React, { useEffect, useRef, FunctionComponent, useState } from 'react';
import videojs from 'video.js';
import 'video.js/dist/video-js.css';

interface VideoPlayerProps {
  
}

const VideoPlayer: FunctionComponent<VideoPlayerProps> = ({ props }) => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState<boolean>(false);
  const [isFullscreen, setIsFullscreen] = useState<boolean>(false);

  useEffect(() => {
    const videoElement = videoRef.current;
    if (!videoElement) return;

    const player = videojs(videoElement);

    player.on('play', () => {
      setPlaying(true);
    });

    player.on('pause', () => {
      setPlaying(false);
    });

    // Listen for fullscreenchange event
    player.on('fullscreenchange', () => {
      setIsFullscreen(player.isFullscreen());
    });

    return () => {
      player.dispose();
    };
  }, []);

  const togglePlayPause = () => {
    const videoElement = videoRef.current;
    if (!videoElement) return;

    if (videoElement.paused) {
      videoElement.play();
    } else {
      videoElement.pause();
    }
  };

  const toggleFullscreen = () => {
    const videoElement = videoRef.current;
    if (!videoElement) return;

    if (!isFullscreen) {
      videoElement.requestFullscreen();
    } else {
      document.exitFullscreen();
    }
  };

  return (
    <div>
      <div className={isFullscreen ? 'video-container fullscreen' : 'video-container'}>
        <video ref={videoRef} className="video-js" />
      </div>
      <button onClick={togglePlayPause}>
        {playing ? 'Pause' : 'Play'}
      </button>
      <button onClick={toggleFullscreen}>
        {isFullscreen ? 'Exit Theater Mode' : 'Enter Theater Mode'}
      </button>
    </div>
  );
};

export default VideoPlayer;
///////////////////
logic is this if i am not wrong?
//////////////////
