### ISSUE TITLE
Chapters similar to YT on rihgt

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#3]
![291295106-b9daf31a-f9df-479f-a14d-3441f64f84ca](https://github.com/code100x/cms/assets/8079861/80d651cc-f26c-41ec-83f5-a67e92d7d15a)

**Comment by tejaskh3** [comment]
Hey @hkirat here also the image is not been uploaded properly please check that out.
![image](https://github.com/code100x/cms/assets/98630752/9239ea06-3b4e-435c-880d-5cc2df561c56)

**Comment by RitikBora** [comment]
Hey @hkirat  
I had already made a video player with chapters from the prevous course. Its deployed at http://ec2-51-20-82-83.eu-north-1.compute.amazonaws.com/player
it accepts a .vtt file for chapters based on 

If you get time please have a look and let me know if this works.
Thanks,
Ritik

**Comment by Min2who** [comment]
@hkirat working on it

**Comment by hkirat** [comment]
@RitikBora this is what I see in ur website
<img width="1373" alt="Screenshot 2024-02-01 at 2 51 06 PM" src="https://github.com/code100x/cms/assets/8079861/c8c3c5a9-4821-4298-8a1c-05b5269d64a0">

**Comment by nimit9** [comment]
Hey @hkirat, is this the desired functionality?
Let me know if I have to change something, or I can push the code

[Screencast from 2024-02-01 21-32-47_compressed.webm](https://github.com/code100x/cms/assets/37402791/a7a3cce7-e02c-4192-87ea-5f3b9f5e310b)

**Comment by sahilsuman933** [comment]
Close this Issue @hkirat as this was completed with PR #28
