### ISSUE TITLE
bug: topbar breaks on smaller screens

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#307]
<img width="884" alt="Screenshot 2024-04-02 at 12 21 49 AM" src="https://github.com/code100x/cms/assets/8079861/fdaa1ebe-e495-4b3a-9784-fa891050608e">

**Comment by nimit9** [comment]
Yeah, was going to raise a PR for this. Will move the nav items to a drop-down on the right. Like a profile menu

**Comment by nimit9** [comment]
Could you please assign these issues to me @hkirat

**Comment by rahmatdeep** [comment]
has this been fixed? still breaks in my browser, if not I would like to work on it.

**Comment by nimit9** [comment]
- This has been fixed in a PR, its not been reviewed and merged yet, you can find the referenced PR above
