### ISSUE TITLE
bug: Search bar exposes unwanted pages

### ISSUE THREAD

**Issue by devsargam** [code100x/cms#310]
![image](https://github.com/code100x/cms/assets/76874341/efe448f1-38a9-45c3-8b52-65fb33aca2cf)

Also, feels like fuzzy index is a bit high would love to hear from your side

**Comment by devsargam** [comment]
![image](https://github.com/code100x/cms/assets/76874341/4403ccd9-ac97-4def-941a-7af2245fdad8)

**Comment by devsargam** [comment]
@hkirat can I work on this? Probably would hardcode now to show these

**Comment by devsargam** [comment]
yeah, that can also help with optimizations : )

**Comment by giteshsarvaiya** [comment]
Fuzzy index ? What is it ?

**Comment by giteshsarvaiya** [comment]
@devsargam are you working on it? Can I take it ?

**Comment by devsargam** [comment]
hey @giteshsarvaiya, sure go on!!!

**Comment by giteshsarvaiya** [comment]
Hello @devsargam , what do you mean by fuzzy index ? Can you be specific, or share any resources ?

**Comment by devsargam** [comment]
Fuzzy value between 0 - 1 to make the search perfect
