### ISSUE TITLE
hamburger should reach the appbar rather than being in the body

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#32]
<img width="1728" alt="Screenshot 2024-02-01 at 11 58 23 PM" src="https://github.com/code100x/cms/assets/8079861/3c948ef4-8d45-4aab-a254-2f889a82d0ae">

**Comment by dhruvilmehta** [comment]
I want to work on this.

**Comment by shreyas0924** [comment]
Can anyone improvise this by using this https://ui.shadcn.com/docs/components/sheet ??

**Comment by markande98** [comment]
> Can anyone improvise this by using this https://ui.shadcn.com/docs/components/sheet ??

I will do it

**Comment by hkirat** [comment]
sheet probably only needed on mobile. On web its fine it it opens on the side

**Comment by markande98** [comment]
> sheet probably only needed on mobile. On web its fine it it opens on the side

ok
