### ISSUE TITLE
feature: Add a notification / alert when the connection is lost

### ISSUE THREAD

**Issue by mvking5464** [code100x/cms#326]
**Is your feature request related to a problem? Please describe.**
When there is no internet connection, we don't see any notification or error

**Describe the solution you'd like**
There should be some type of alert or notification to show user that they are offline

**Describe alternatives you've considered**
Add a toast / notification / alert that the connection has been lost 

**Additional context**

---- When User is Online

![When_Online](https://github.com/code100x/cms/assets/28997328/b584bd83-b1c1-4ce4-bd73-fa83e89a5aa6)

---- When User is Offline (needed)

![When_Offline](https://github.com/code100x/cms/assets/28997328/06989762-f813-49e9-a4ea-1a0c7579d534)

**Comment by hkirat** [comment]
Not needed

**Comment by mvking5464** [comment]
**Thank you Sir**
