### ISSUE TITLE
feature: Add a Time Duration on Video Thumbnail Like Youtube

### ISSUE THREAD

**Issue by mvp5464** [code100x/cms#329]
**Is your feature request related to a problem? Please describe.**
When we want to check the time duration of any video, We have to start the video or visit the mobile app to check duration

**Describe the solution you'd like**
Show time duration inside the application without starting a video 

**Describe alternatives you've considered**
We can add time duration in **[hh:mm:ss]** format on the thumbnail like youtube

**Additional context**

![photo_6084449297027414491_x](https://github.com/code100x/cms/assets/28997328/1b9b7398-6f82-4b82-b713-bb592f9f3254)

**Comment by mvp5464** [comment]
Hi @dhruvilmehta , I had completed the solution just waiting to assign, so Kindly close the PR, Thank You.

Also re-added green tick

![Screenshot from 2024-04-04 23-09-10](https://github.com/code100x/cms/assets/28997328/a01e7623-6cea-4088-aa2d-623a8b03b983)

**Comment by dhruvilmehta** [comment]
Sure. You can raise the PR now.

**Comment by mvp5464** [comment]
Thank you...

**Comment by dhruvilmehta** [comment]
Yes you can raise directly without assigning.

**Comment by mvp5464** [comment]
OK Thank You, I appreciate your help.
