### ISSUE TITLE
ChatBot 

### ISSUE THREAD

**Issue by Adiiii02** [code100x/cms#332]
**Describe the solution you'd like**
Chatbot for your website which helps students navigate the website as well ask doubts if any .

**Comment by Adiiii02** [comment]
I want to create a chatbot for your website by fine tuning large language models (llm) using quantized low rank adaption .

**Comment by krishhh16** [comment]
@Adiiii02 I think you'll get better results creating the chatbot with langchain then creating the whole LLM from scratch(if the point of you adding the chatbot here is to add value)

**Comment by Adiiii02** [comment]
@krishhh16 yep , creating chatbot with langchain using vector store for embeddings of course pdfs would make it much easier and better .
