### ISSUE TITLE
bug: Buttons text has different colours and no alignment

### ISSUE THREAD

**Issue by nischal-shetty2** [code100x/cms#333]
**Describe the bug**
The buttons "Mark as complete" "slides" and "view all chapters" have white text but the "comment" button has black text.
the alignment of "slides" and "view all chapters" needs to be better or atleast have some margin

**To Reproduce**
1. open any video
2. scroll down near the comment section

**Expected behavior**
"comment" button has to have white text, slides and view all chapters needs to be aligned right

**Screenshots or GIFs**
currently-
![Screenshot 2024-04-06 at 11 39 30 AM](https://github.com/code100x/cms/assets/136328410/d2f6d6bf-a455-4946-9edd-758f8d77fe14)

should look like-
![Screenshot 2024-04-06 at 11 48 20 AM](https://github.com/code100x/cms/assets/136328410/68b83478-c34f-40f3-90b9-ced6f9861234)

**Info (please complete the following information):**
 - Browser : chrome
 - Version 123.0.6312.107

**Additional context**
The solution has just given margin to the "view all chapters" button but can be improved more by keeping them next to each other if needed

**Comment by nischal-shetty2** [comment]
@hkirat i can easily fix this can i have this assigned to me

**Comment by Pratham271** [comment]
solved in #313 .
