### ISSUE TITLE
bug: video speed changes to 2x if the user changes tab and comes back

### ISSUE THREAD

**Issue by shawakash** [code100x/cms#335]
**Describe the bug**
the speed of video playing on app.100xdevs.com changes incase browser tabs are switched

i don't know if this problem is specific only to me.

**Comment by neeshant-pandey** [comment]
Tried in the local as well as the productio setup, unable to repicate the error can you share a ss or video recording and the steps you took that caused this bug(like using crtl + tab to shift the tabs or normally shifting the tabs)

**Comment by shawakash** [comment]
unable to reproduce it 
maybe some problem in my system 
closing this

**Comment by shawakash** [comment]
https://github.com/code100x/cms/assets/112852873/5ccd560b-d173-4bc6-81ce-bc276a9bf507


got one it happened when i created a new tab with cltr+T

**Comment by shawakash** [comment]
it happens only when the user is in full screen and creates a new tab
