### ISSUE TITLE
feature: adding email validation on login

### ISSUE THREAD

**Issue by harshdasila** [code100x/cms#336]
During login even if i enter a invalid email address it still processes the request. The same issue is with the 100xdevs website too on email and mobile number for otp we can add frontend validations for those feilds. For this we can use react hook forms or just using some variable.

**Comment by devsargam** [comment]
It also works with phone number. so, email only validation doesn't sounds too good.

It might be rare but there are people who login with they phone number

**Comment by harshdasila** [comment]
For number also although it check for the type number but  we can enter more than 10 digits and it still sends out the request.

**Comment by iamdarwinsai** [comment]
then a frontend validation would be fine for phone number then

**Comment by SujithThirumalaisamy** [comment]
I have came up with the solution for this issue. 

**Solution:**

1. Created a validation function that validates if a input is valid email or a valid phone number.```
function isValidEmailOrPhone(value: string) {
    if (value.length === 10 && !value.includes('@')) {
      const re = new RegExp(
        '^(\\+\\d{1,2}\\s?)?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$',
      );
      console.log(re.test(value));
      setEmailValidationError(!re.test(value));
      return;
    }
    const re = new RegExp('^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$');
    console.log(re.test(value));
    setEmailValidationError(!re.test(value));
  }
```

**Comment by hkirat** [comment]
We have some users that dont follow any format so wil have to skip this one altho its a good one

**Comment by Pratish10** [comment]
Hi @hkirat I have made the changes for this enhancement
1. Added react-hook-form in login component 
2. Added email validation regex that is **/^[^\s@]+@[^\s@]+\.[^\s@]+$/**
3. Marked Email and Password as required field 

The demo has been attached for your reference

Thanks
[login.webm](https://github.com/code100x/cms/assets/82207405/efabf006-c345-4831-877d-b62706575612)

**Comment by SujithThirumalaisamy** [comment]
> Hi @hkirat I have made the changes for this enhancement
> 
> 1. Added react-hook-form in login component
> 2. Added email validation regex that is **/^[^\s@]+@[^\s@]+.[^\s@]+$/**
> 3. Marked Email and Password as required field
> 
> The demo video has been attached for your reference
> 
> Thanks [login.webm](https://github.com/code100x/cms/assets/82207405/efabf006-c345-4831-877d-b62706575612)
> 
> Shall I push the changes ?

Yooo... Watch his reply.

**Comment by Pratish10** [comment]
We Can also disable the login button until both email and password fields are valid. In this way we can avoid un necessary api call for invalid credentials

**Comment by devsargam** [comment]
@Pratish10 read the thread again!!! It's not as simple as adding validation for email.

**Comment by dishak** [comment]
@SujithThirumalaisamy , Would like to know if gmail signin/signup  would be a good enhancement ?

**Comment by SujithThirumalaisamy** [comment]
> @SujithThirumalaisamy , Would like to know if gmail signin/signup  would be a good enhancement ?

It might be. IMO.
