### ISSUE TITLE
bug: Sidebar is messed up and breaks

### ISSUE THREAD

**Issue by mvp5464** [code100x/cms#337]
**Describe the bug**
Bug 1 => Sidebar is squeezed when any content is clicked from week-19. 
Bug 2 => Sidebar for folder page is smaller and for other page (video and notes) it is larger

**To Reproduce**
1.  For Bug 1:Click on any video from week-19 and sidebar should be enabled.  You will see it will get smaller [screenshot attached]
2. For Bug 2:See the folder page and video page, then compare. You will notice the difference [screenshot attached]

**Expected behavior**
The side bar should remain same for all pages 

**Screenshots or GIFs**

***Bug 1***
- Normal sidebar (week-18)
![Screenshot from 2024-04-07 14-17-27](https://github.com/code100x/cms/assets/28997328/492859b7-d393-412c-8401-f30353b6e80b)

- Normal sidebar (week-18)
![Screenshot from 2024-04-07 14-16-57](https://github.com/code100x/cms/assets/28997328/049c7305-c840-4343-ab86-0eb00ab84e16)

***Bug 2***
- Sidebar for Video page
![Screenshot from 2024-04-07 14-25-29](https://github.com/code100x/cms/assets/28997328/ef1a0eff-5282-497d-80ed-4195b6ccceae)

- Sidebar for Folder page
![Screenshot from 2024-04-07 14-25-44](https://github.com/code100x/cms/assets/28997328/001f8405-a319-4cff-b217-5e2e8fd276ba)

**Info (please complete the following information):**
 - Browser : Firefox

**Comment by mvp5464** [comment]
Working on it...

**Comment by nimit9** [comment]
I think this is resolved in #317

**Comment by mvp5464** [comment]
Ohh! I thought it was for appbar. Thanks.
