### ISSUE TITLE
Feature : Added the feature for layout toggling

### ISSUE THREAD

**Issue by amanbairagi30** [code100x/cms#338]
### Problem Statement
Currently users lack options in how they view content on our website, limiting their ability to personalize their experience. By introducing layout toggling, we can empower users to choose the presentation style that suits them best, enhancing their overall browsing experience.

### Solution (Took inspiration from Google Drive)
Implemented a layout toggle feature that allows users to switch between grid and line views for content presentation. This feature will provide users with the flexibility to customize their browsing experience according to their preferences and contextual needs, enhancing usability and user satisfaction on the website.

### How I did it : 
I have added a layout toggle button to the UI , allowing users to easily switch between grid and line views for content presentation. For this , I am conditionally changing the CSS properties of the JSX elements of Folder View and Content Card and Additionally, I ensured that the user's chosen layout preference is saved in local storage providing consistency in their browsing experience . 

You can see the changes below : 

https://github.com/code100x/cms/assets/118182376/cc445a53-ff5b-471c-9fdb-de398d11c527

**Comment by amanbairagi30** [comment]
Hey @hkirat Can you please see this , If this feature feels good to you then I would be happy raise PR for the same .

**Comment by iamdarwinsai** [comment]
This looks fab bro. I hope he agrees to this

**Comment by amanbairagi30** [comment]
Hi @hkirat , I have raised PR , Can you please review it .
