### ISSUE TITLE
bug: side squeezed because of the size of video container

### ISSUE THREAD

**Issue by Rimaru06** [code100x/cms#339]
![image](https://github.com/code100x/cms/assets/118299308/42901587-5e41-4fd7-bef6-b4fa89a480a7)
@hkirat  may i work on this

**Comment by Neon-20** [comment]
From my point of view, the best you can do here is add shadcn sheets, such that when the size of the video player or size of the screen expands/contracts u could contract and expand sidebar depending upon the requirement.
Source: https://ui.shadcn.com/docs/components/sheet

**Comment by Rimaru06** [comment]
@Neon-20  thank you for your guidance

**Comment by Pratham271** [comment]
#313 will solve this I guess

**Comment by Rimaru06** [comment]
it fine if its get solved by #313 i'll try to solve this too
