### ISSUE TITLE
bug: when clicked on any video in the history, it redirects to the main page

### ISSUE THREAD

**Issue by Devmanwani** [code100x/cms#342]
https://github.com/code100x/cms/assets/36275192/c0a8e9af-68e0-4cb7-84d3-948de7320c3b

**Comment by prajjwal2-3** [comment]
Hey are you working on this??

**Comment by aakash2330** [comment]
no , go ahead @prajjwal2-3

**Comment by ubaish01** [comment]
Hi , unable to reproduce the issue on local.

**Comment by Basant-Chahar-2003** [comment]
Hi, I just checked it it is doing what it should be. Not able to reproduce on either online or local

**Comment by Devmanwani** [comment]
it is a brave specific issue, when I watch a video in brave, the link doesn't open up, while when I watch a video in chrome, it does open up...
