### ISSUE TITLE
feature: Play/Pause Effect on the Video Player

### ISSUE THREAD

**Issue by Adiiittt** [code100x/cms#343]
Description:
Once the user hits play/pause an effect should be shown on the video player like we have in the below Screenshot/or a basic Youtube Video Player. 

![image](https://github.com/code100x/cms/assets/107144471/f3fe59b1-79fd-4f45-b14c-14cfde7bfd02)
![image](https://github.com/code100x/cms/assets/107144471/a908c300-9e1f-4037-9a55-0d312437ada0)

**Comment by dheerajsharma1805** [comment]
Trying this one out.

**Comment by Aryam2121** [comment]
I think this was the logic if i am right please merge this sir

const video = document.getElementById('videoPlayer') as HTMLVideoElement;
const playPauseButton = document.getElementById('playPauseButton') as HTMLButtonElement;

playPauseButton.addEventListener('click', togglePlayPause);

function togglePlayPause() {
  if (video.paused) {
    video.play();
    // Add effect for play
    video.classList.add('playing-effect');
  } else {
    video.pause();
    // Add effect for pause
    video.classList.remove('playing-effect');
  }
}
//and add some css ....

**Comment by Aryam2121** [comment]
import React, { useEffect, useRef, FunctionComponent, useState } from 'react';
import videojs from 'video.js';
import 'video.js/dist/video-js.css';

interface VideoPlayerProps {
 
}

const VideoPlayer: FunctionComponent<VideoPlayerProps> = ({ /* Your props destructuring */ }) => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState<boolean>(false);

  useEffect(() => {
    const videoElement = videoRef.current;
    if (!videoElement) return;

    const player = videojs(videoElement);

    player.on('play', () => {
      setPlaying(true);
    });

    player.on('pause', () => {
      setPlaying(false);
    });

    return () => {
      player.dispose();
    };
  }, []);

  const togglePlayPause = () => {
    const videoElement = videoRef.current;
    if (!videoElement) return;

    if (videoElement.paused) {
      videoElement.play();
    } else {
      videoElement.pause();
    }
  };

  return (
    <div>
      <video ref={videoRef} className="video-js" />
      <button onClick={togglePlayPause}>
        {playing ? 'Pause' : 'Play'}
      </button>
    </div>
  );
};

export default VideoPlayer;

**Comment by ubaish01** [comment]
Hi , is anyone working on this ??
