### ISSUE TITLE
bug: Some videos are easily downloadable

### ISSUE THREAD

**Issue by kushalnareda** [code100x/cms#344]
@hkirat 
I was just messing around trying to add some feature on the website when I came across this
I was able to easily download some videos.
Figuring out myself if this can be fixed or anyone else can chip in.

https://github.com/code100x/cms/assets/128476254/75427da4-4852-4ca4-bf85-07cdd5dd5cb0

**Comment by LokeshXs** [comment]
I am also trying to figure out how to stop this.

**Comment by devsargam** [comment]
DRM missing some videos is not a huge deal

**Comment by neeshant-pandey** [comment]
Certainly! Here's a more polite version of your message:

Hello @devsargam,

I hope this message finds you well. I wanted to bring to your attention that although only a few videos might be affected by the right-click issue, it might be prudent to disable the right-click functionality on our videos as a precaution. I've gone ahead and implemented a solution to address this, and I'll be submitting a pull request shortly for your review.

**Comment by kushalnareda** [comment]
Ayy people are fast here.
Good work guys :)

**Comment by kushalnareda** [comment]
> DRM missing some videos is not a huge deal

True and its very random. But still

**Comment by Neon-20** [comment]
Along with the download button, screen recorder shd also be disabled for the videos, otherwise they both mean the same thing eventually

**Comment by alexbennycodes** [comment]
DRM encryption seems like solution, preventing right click wont help, We can also get the url of the video from inspect element.

**Comment by devsargam** [comment]
@alexbennycodes we already do have DRM protection it's just not active on few videos
