### ISSUE TITLE
bug:  URL doesn't works as expected 

### ISSUE THREAD

**Issue by anuragnegi000** [code100x/cms#347]
**Describe the bug**
The URL [(https://cms-qrlx.vercel.app/)] is returning a 404: NOT_FOUND error with the following code: DEPLOYMENT_NOT_FOUND

**To Reproduce**
1. Click on the hosted URL in Github
2. See error

**Expected behavior**
I expected the URL (https://cms-qrlx.vercel.app/) to load without any errors and display the content it hosts.

**Screenshots or GIFs**
![issue_code_kirat](https://github.com/code100x/cms/assets/115611556/a8cddbb5-67c8-49d3-9a2d-d63696b5bfcd)

**Info (please complete the following information):**
 - Browser chrome
 - Version 123.0.6312.106

**Additional context**

**Comment by CodeAnk2829** [comment]
Two things you can do: 
- Try changing your root api
- Try adding `vercel.json` file in your root directory in case you didn't

**Comment by anuragnegi000** [comment]
@CodeAnk2829  the hosted url, which has been hosted by kirat is showing above error, it's not for localhost

**Comment by devsargam** [comment]
@anuragnegi000 ignore this not needed. It was for dev setup few months back

**Comment by Neon-20** [comment]
@anuragnegi000. This issue can be closed, it's not a bug. It is intended to open at https://app.100xdevs.com/.
Thanks

**Comment by anuragnegi000** [comment]
okay @devsargam @Neon-20
