### ISSUE TITLE
feature: Making app.100xdevs.com/ Landing Page look more animated and User Interactive

### ISSUE THREAD

**Issue by punyakrit** [code100x/cms#353]
**Is your feature request related to a problem? Please describe.**
Making Landing Page of website more user interactive and having animations

**Describe the solution you'd like**
I want to work on this animated landing page of website

**Comment by punyakrit** [comment]
If this feature is required i can work on it

**Comment by devsargam** [comment]
Is this even needed?

**Comment by punyakrit** [comment]
just depends on increasing look and feel for new visitors on website
