### ISSUE TITLE
bug: The options in three dots menu of comments ,are not working 

### ISSUE THREAD

**Issue by amilbcahat** [code100x/cms#354]
**Describe the bug**
The options in three dots menu of comments ,are not working 

**To Reproduce**
1. Go to any video 
2. Comment something 
3. Try delete and copy , both are not working 

**Expected behavior**
It should delete the comment made by the user and copy the comment text as well 

**Screenshots or GIFs**

https://github.com/code100x/cms/assets/68186313/1f0458ba-6282-40f9-8f0b-bd98d3c29b47

**Info (please complete the following information):**
 - Browser Chrome Latest

**Comment by amilbcahat** [comment]
#355

**Comment by amilbcahat** [comment]
#355 I have made a Pull request , that will fix these . Please check it out .

**Comment by siinghd** [comment]
Looked  now at https://app.100xdevs.com/, delete is working
