### ISSUE TITLE
feature: Cleaning up the UI 

### ISSUE THREAD

**Issue by Bishalmoktan** [code100x/cms#359]
The current UI looks good but can be better and I have tried to refine the desgin.
- The links on the navbar can be made as shown below. The bookmark, watch histroy and dark mode toggler can be kept under the dropdown of avatar.
- The links to slides, asssignments and join to discord can be showed as following and a tooltip can be shown on hover on each.
- The sidebar UI can also be improve as shown. Showing the '>' icon only on hover state. Also, we can add line-clamp property if the line exceeds it's widths.

![UI 1](https://github.com/code100x/cms/assets/81924505/8e14df8d-84c4-4300-b2e0-d38b3b209c96)

![UI 2](https://github.com/code100x/cms/assets/81924505/94a8dc4f-d3bf-4742-a1ae-da4f4405b7b8)

- We can show the details, that a folder contains while we hover on the card and if the card is the video we can change it as following.

![UI 3](https://github.com/code100x/cms/assets/81924505/bfe10c5d-4302-4b29-982c-d28ce41bbd2a)

![UI 4](https://github.com/code100x/cms/assets/81924505/fe2b5f6b-327a-4735-9d82-b2105c497c42)

- A feature to toggle grid mode and list mode can be added. So the list mode can be seen as following:

![UI 5](https://github.com/code100x/cms/assets/81924505/a0853528-89a2-4c1d-a148-78504a4b3a1d)

- In the video section, to view the chapter of the video, an arrow can be kept, which on  hover, it will show, View all Chapter, and on click, we can view the chapter and the UI can be as following.

![UI 6](https://github.com/code100x/cms/assets/81924505/dc0215f7-ff33-43d7-a787-10023ab6359e)

![UI 7](https://github.com/code100x/cms/assets/81924505/73fac5a7-6c17-4a63-a74c-eb72a67ee77f)

Query: These all are desgined in figma(not a perfect design, but only as a wireframe). The design can be improved while coding. This is me first time contributing so do I need to wait for this issue to get assigned to me or can I start working on it?

**Comment by nimit9** [comment]
Hey @Bishalmoktan ,the user profile drop-down is already done in #319

**Comment by Bishalmoktan** [comment]
@nimit9, it's okay. May be I could work on another part if this is approved.

**Comment by amanbairagi30** [comment]
Hello @Bishalmoktan , the layout toggle has already been done in #346
