### ISSUE TITLE
bug: Video player is not responsive for small screens

### ISSUE THREAD

**Issue by prajjwal2-3** [code100x/cms#360]
![Screenshot 2024-04-10 183707](https://github.com/code100x/cms/assets/121849327/d859ff89-7d51-4fec-b0c3-4edf8e039109)

**Comment by shashankdaima** [comment]
I will take this please.

**Comment by prajjwal2-3** [comment]
@shashankdaima ok go ahead.

**Comment by aakash-a-dev** [comment]
I didn't heard anything on this PR actually.
