### ISSUE TITLE
feature:  Header auto hide and unhide as user scroll. 

### ISSUE THREAD

**Issue by Aayuslad** [code100x/cms#361]
The header may be useless when exploring a slightly longer page or even while watching a video out of full-screen mode. 

We have seen responsive headers like on the official Medium website. The header which goes up while scrolling down and comes back on when scrolling up. 

**Additional context**

https://github.com/code100x/cms/assets/111479342/feb9e5c7-bb42-4057-9cf9-e879e5b8fead

**Comment by amilbcahat** [comment]
I think , current AppBar is fine . Medium has a lot of scrolling , thats why that approach suits them .

**Comment by Ydixit007** [comment]
Hi @Aayuslad - I agree the current header can be improved. I'm interested in implementing a responsive header similar to Medium's design to provide a better user experience. Please consider assigning this issue to me, would be excited to contribute.

**Comment by HusainModiwala** [comment]
@Aayuslad @hkirat 
I have added the feature. Kindly have a look at PR #363
