### ISSUE TITLE
bug: Sidebar too small

### ISSUE THREAD

**Issue by athar05** [code100x/cms#362]
**Describe the bug**
The sidebar is too small. Upon expanding, if I scroll, the scroll bar overlaps the checkbox, effectively not allowing me to click on the "mark as done" checkbox for a few seconds.

**To Reproduce**
1. Open any video, expand any module on the sidebar, scroll and try clicking on the checkbox. 

**Expected behavior**
The sidebar should be bigger and the "mark as done" checkbox should have some padding on the right.

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/82315023/c7a98af3-fe8e-45cc-8b24-c5584adce3b4)

**Info (please complete the following information):**
 - Browser: Chrome 
 - Version: 123.0.6312.107  

**Additional context**

**Comment by nimit9** [comment]
Hey, this is already fixed in some PR. Please check once

**Comment by athar05** [comment]
Ok
