### ISSUE TITLE
bug: Keybindings Interference Between Video Player and Comments Textarea

### ISSUE THREAD

**Issue by Devmanwani** [code100x/cms#364]
Description:
When using the website, I noticed that the keybindings for navigating within the video player interfere with the comments functionality. Specifically, when I click on the comments textarea and then use the keybindings <, >, t, Shift+Up, and Shift+Down, which are meant for controlling the video player, they trigger actions within the video player.

Steps to Reproduce:

Go to the website.
Click on the comments textarea to focus on it.
Use the keybindings <, >, t, Shift+Up, and Shift+Down, which are used for controlling the video player.
Expected Behavior:
The keybindings should only affect the video player when it is in focus, and affect the comments when it is in focus.

Video about the Issue:

https://github.com/code100x/cms/assets/36275192/243008f7-36f6-458d-9fbf-205ddc546d08

**Comment by Aayuslad** [comment]
@Devmanwani, I fond the way to solve this. can i take this?
