### ISSUE TITLE
(BUG) Major Signin Form validation and ux bug

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/cms#373]
Bug:

The signin form has few issues with it mentioned below :
1. No proper validation was setup instead just `error signin` is shown
2. no loader or a proper loading state to show the progress of the login process 
3. lacks the good ux as well as ui 
4. it doesn't gets the value from auto-fill feature from password manager

**To Reproduce**

Steps to reproduce the behavior 1 : 
1. Go to [signup page](https://app.100xdevs.com/signin?) and input for e.g. hello.com and then click on signin
2. toast appears

Steps to reproduce the behavior 2 : 
1. Go to [signup page](https://app.100xdevs.com/signin?) and input something and then click on signin
2. No way for user to understand if the request actually went through, there should be something that shows the loading state

Steps to reproduce the behavior 4 : 
1. Go to [signup page](https://app.100xdevs.com/signin?) and if there is autofill click on signin
2. see that the values being there, it shows required error

**Expected behavior**

1.  proper validation of input when the buttons get clicked
2. loading state for better ux 
3. autofill values acceptance 
4. better ux 

**Screenshots or GIFs**
autofill error 
![image](https://github.com/code100x/cms/assets/91052168/94ce6660-f047-46b7-8990-e94e703f915f)
wrong validation handling 
![image](https://github.com/code100x/cms/assets/91052168/803f5d0d-2884-487b-b97a-2de728ba3695)

**Info (please complete the following information):**
 - Browser [chrome, firefox]
 - Version [e.g. 124.0.1]

**Additional context**
i have a pr below attached that fixes all these errors

**Comment by Arunsoniiii** [comment]
Do you really think, it's a real issue? @VineeTagarwaL-code, can't see some big change rather adding form 

![image](https://github.com/code100x/cms/assets/149182931/0ea24a74-1c15-4e8f-b870-e39eb0077ace)

**Comment by VineeTagarwaL-code** [comment]
please go through the issues i mentioned #373 again

**Comment by Arunsoniiii** [comment]
Yes I have gone theough the issue and your changes seems minor not major but good work

**Comment by VineeTagarwaL-code** [comment]
if you have checked the pr convo, the major part was about the validation of and ux ..... i fixed both of them but the email validation was not that much needed so found a round way solution for that and made the changes, @devsargam also approved it so ig its good to go
