### ISSUE TITLE
bug: Clicking on Harnoor or Machine Learning course, it doesn't open in new tab

### ISSUE THREAD

**Issue by mvp5464** [code100x/cms#382]
**Describe the bug**
When clicking on the ML or Harnoor course, it open on the same tab.
**To Reproduce**
Click on the Course to check

**Expected behavior**
It should open in new tab rather than opening in the same tab

**Screenshots or GIFs**
- 
[ScreencastButton.webm](https://github.com/code100x/cms/assets/28997328/4cace39e-3b9c-4a3c-bc38-5ee973cd9d29)

**Info (please complete the following information):**
 - FireFox Browser

**Comment by Abhishek-1337** [comment]
why do you think it is a bug?

**Comment by mvp5464** [comment]
@Abhishek-1337, New link for different website should be open in the new tab, I guess . should I change the label. And How I misuse the oppertunity?

- Can you point any issue that I can work upon, It would be great

**Comment by Abhishek-1337** [comment]
I am not a expert but spend more time on quality bugs, there are few issues here like that which need more attention, indepth knowledge from which you can learn real stuff. Or if there is not find one...go deep in code find something complex, buggy fix it, refactor it. Just Learn something while doing this.
