### ISSUE TITLE
bug: Website current can't runing, show the 404 http code.

### ISSUE THREAD

**Issue by annder** [code100x/cms#389]
Open url is https://cms-qrlx.vercel.app/, but it can't render standard content and throw 404 http code, for instance:
![image](https://github.com/code100x/cms/assets/12369444/085b9f62-167c-4284-81e3-f00c7f732a6d)

I'm local in china , it is regard to region network  issue?

**Comment by pkmanas22** [comment]
https://app.100xdevs.com/ 
This is the website

**Comment by anuragnegi000** [comment]
this issue can be closed now
