### ISSUE TITLE
Create a simple script that takes a json with duration of videos and updates the `duration` parameter in the DB 

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#390]
In the `VideoMetadata` table, we have a duration field that isnt yet populated
Given a json that looks like this 
```
[{
	id: 3,
      duration: 905
}, {
	id: 4,
     duration: “”
}]
```

Where id is the `contentId` field in the `VideoMetadata` table

**Comment by hkirat** [comment]
Needed after https://github.com/code100x/cms/pull/331

**Comment by mvp5464** [comment]
On it.

**Comment by Pratham271** [comment]
can I work on this @hkirat?
