### ISSUE TITLE
Week-1 is rendoring twice in DSA Class module.  

### ISSUE THREAD

**Issue by paahaad** [code100x/cms#395]
**Describe the bug**
Week-1 is rendoring twice in sidebar as well as in courses containt.  

**To Reproduce**
1. login to application. go to DSA Class.

**Screenshots or GIFs**
![Screenshot from 2024-04-12 23-20-05](https://github.com/code100x/cms/assets/42418677/7a1644e7-fd74-4554-b416-d0b693a7e284)

**Comment by amilbcahat** [comment]
Working on it

**Comment by zelfroster** [comment]
Can I take this? I can fix it.

**Comment by initeshjain** [comment]
I believe, it is not a application level bug, May be a duplicate entry in database. 
Why I am saying this? because, second "Week 1" folder do not contain anything.
