### ISSUE TITLE
bookmark feature

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#4]
<img width="1719" alt="Screenshot 2024-02-02 at 7 09 20 PM" src="https://github.com/code100x/cms/assets/8079861/5a45740b-297f-44fd-a3a0-76bb4a0c647d">

Will require db migrations

**Comment by tejaskh3** [comment]
Hey @hkirat Your is is responding with 404 here, please checkout.
![image](https://github.com/code100x/cms/assets/98630752/622a945d-2b2e-43a1-9287-4abe4f33963c)

**Comment by AbdullahKhan08** [comment]
Hello @hkirat, the screenshot image is not visible.

**Comment by devsargam** [comment]
Hey @hkirat can I please work on this???

**Comment by Vivek-1102** [comment]
Hey guys I am really new to this thing and i have a feeling that i can contribute somewhere and make my first contribution can u guys help me in making my first merge @devsargam & @AbdullahKhan08

**Comment by hkirat** [comment]
Updated image 
<img width="1719" alt="Screenshot 2024-02-02 at 7 09 20 PM" src="https://github.com/code100x/cms/assets/8079861/de039f2d-b10c-4997-b3a1-d5b02fe62ad0">

**Comment by shivamhwp** [comment]
@Vivek-1102 learn and then contribute.

**Comment by Vivek-1102** [comment]
@shivamhwp I think i can do some of the stuffs but ur right i need to practise more than contributing i have still not manage to run the codebase locally can u help me to just to setup locally

**Comment by shivamhwp** [comment]
are you on 100xdevs discord. if not, join & i'll help you setup it locally.

**Comment by IftequarIffu** [comment]
Two things can be done here:

1) Allowing the user to set startTimestamp and endTimestamp for the video segment and having them listed in a bookmarks tab. Here, the video is played from the startTimestamp till endTimestamp.

2) Allowing the user to set startTimestamp and endTimestamp for the video segment and create a whole new video segment and place it in the bookmarks tab. In this case, the video can be downloaded by the user.

How can we proceed on this?
Any more ideas are appreciated for this issue.

**Comment by Antiarin** [comment]
@hkirat, is this issue still open? If so, I’d be happy to take it on.

**Comment by hkirat** [comment]
Issue is still open

**Comment by siinghd** [comment]
@Antiarin i'm working on it

**Comment by Antiarin** [comment]
@siinghd I have already started man!

**Comment by siinghd** [comment]
> @siinghd I have already started man!

i have also, its quite simple but you continue, i will do it quickly and probably ur will be better or if u need help let me know

**Comment by nimit9** [comment]
Had started on working on this feature, but then the repo went AWOL for a while, and got stuck into work. Have completed the basic version of it, willl be completing the full feature if this looks good enough #237
