### ISSUE TITLE
Sidebar content is not visible in light theme

### ISSUE THREAD

**Issue by AbdullahKhan08** [code100x/cms#40]
<img width="1511" alt="Screenshot 2024-02-02 at 12 10 19 PM" src="https://github.com/code100x/cms/assets/100870556/56c7eda3-3891-4940-8224-83a5911db8c5">

**Comment by Saurabh-001-S** [comment]
can i work one this!

**Comment by tanayvaswani** [comment]
Issue is fixed, PR has been merged already, soon the changes will be live on [**app.100xdevs.com**](https://app.100xdevs.com)
