### ISSUE TITLE
bug: sidebar is not consistent

### ISSUE THREAD

**Issue by siddanth-6365** [code100x/cms#401]
**Describe the bug**
currently the sidebar is not consistent, it is getting shorter width for some videos and perfect for some

**Expected behavior**
need to be consistent sidebar for all videos

**Screenshots or GIFs**
<img width="1710" alt="Screenshot 2024-04-13 at 9 34 21 PM" src="https://github.com/code100x/cms/assets/114846048/88e78f7c-1567-480b-81e5-628716b84eee">
<img width="1710" alt="Screenshot 2024-04-13 at 9 34 52 PM" src="https://github.com/code100x/cms/assets/114846048/287e2918-bbaa-4398-9006-e35c4014691f">

**are you working on this issue?**
no, anyone can pickup this if @hkirat feels this is an issue and approve it

**Comment by devsargam** [comment]
working on this
