### ISSUE TITLE
Implement Hover Scale Effect for Section Cards

### ISSUE THREAD

**Issue by pranav-2002** [code100x/cms#41]
## Description - 
Currently, our UI lacks interactivity when it comes to user interactions with section cards. I feel that Implementing a slight scale effect on hover can significantly enhance the user experience by providing visual feedback and making the interface more engaging.

## Proposed Solution:
I was thinking of introducing a CSS transition property to the section cards, enabling a smooth scale effect upon hover. By applying a transform scale property, we can achieve the desired visual effect without compromising the layout or functionality of the cards.

### I have attached a recording showing what exactly do I mean by a hover scale effect (although, the original effect will be more smoother and better than the one showcased in the recording).

https://github.com/code100x/cms/assets/77333789/b18738b7-3d5d-4041-926e-3a51ef594284

### Looking forward to contributing to the project!

**Comment by tanayvaswani** [comment]
Add `transition` property to make it smooth. A bit less of scaling would look good, can be turned off on mobile screens.

**Comment by pranav-2002** [comment]
Yes, in the recording I have just given some inline styling using the inspect element in order to show what exactly I was talking about but in general I will be using the transition property and scaling would be less. 

So can this issue be assigned to me so that I can start working on it?

**Comment by Neon-20** [comment]
This could be easily achieved with framer motion.

**Comment by pranav-2002** [comment]
Yes but that would be an additional package which needs to be installed right.
