### ISSUE TITLE
feature:  Caption option should be available in video

### ISSUE THREAD

**Issue by ramnaresh8** [code100x/cms#412]
Just a caption synced with the video should be available

**Comment by chiragcj27** [comment]
are you working on this?

**Comment by Pratish10** [comment]
Hi @ramnaresh8 In my local I don't have any courses because I connected to my local neon DB which doesn't have any data 
Without the courses and videos How can I work on this ?

**Comment by nimit9** [comment]
Follow the steps mentioned, there is a step which uses seed.ts file to seed the data to your db.
