### ISSUE TITLE
bug: Slides and View all Chapters Button do not have padding 

### ISSUE THREAD

**Issue by chiragcj27** [code100x/cms#418]
**Describe the bug**
Slides Button and View all Chapters Button do not have padding between them 

**To Reproduce**
Steps to reproduce the behaviour:
1. Cross the chapters of any video 
2. See error 

**Expected behaviour**
Both buttons should have padding between them.

**Screenshots or GIFs**
<img width="191" alt="Screenshot 2024-04-15 at 11 25 28 AM" src="https://github.com/code100x/cms/assets/127305936/8554f9aa-afc3-4fee-ab4f-6c2a66807f19">

**Comment by hxdy-1** [comment]
@chiragcj27 thing u r referring to as **padding** here is actually called **margin** (margin is the space between 2 elements, while padding is the space between the content of an element and its border.)
