### ISSUE TITLE
bug: Blank page when user clicks on slides button.

### ISSUE THREAD

**Issue by Shriom-Trivedi** [code100x/cms#426]
**Describe the bug**

**To Reproduce**
1. Click on the slides button when you go to the course
2. It shows a blank page

**Expected behavior**
- It should show the slides.

**Screenshots or GIFs**
[screen-capture.webm](https://github.com/code100x/daily-code/assets/32411707/8f912396-42d9-458e-8a4a-11dcbaf40546)

**Info (please complete the following information):**
 - Chrome

 - Version 123.0.6312.122 (Official Build) (64-bit)

**Additional context**
URL seems to be wrong - `https://projects.100xdevs.com/tracks/ABEC/[object%20Promise]`

**Comment by N4r35h** [comment]
its a bug in projects.100xdevs.com (dailycode repo) please have this closed and reopen that issue

**Comment by Shriom-Trivedi** [comment]
@nimit9 can you help me clear this here? is it suppose to be on `/cms` or `/daily-code`

**Comment by nimit9** [comment]
Yeah, I think @N4r35h has solved it. Please reopen the issue on daily-code

**Comment by Shriom-Trivedi** [comment]
alright, will do
