### ISSUE TITLE
feature: Video Quality Visibility

### ISSUE THREAD

**Issue by Hemant2335** [code100x/cms#434]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. Like Whenever i am taking lectures , I couldn't able to know on which quality i am taking lectures 

**Describe the solution you'd like**
A Solution is simple as the Problem where there is logo of HD so we can put the quality over there and if not selected then auto quite same as the youtube

**Describe alternatives you've considered**
Other alternatives could be a popup that the quality has been changed to whatever it is.

**Additional context**
Some reference Screenshots 
![WhatsApp Image 2024-04-16 at 17 00 35](https://github.com/code100x/cms/assets/85656999/9ede0d20-8dda-40c8-8a9f-c68ec8652cd7)
![WhatsApp Image 2024-04-16 at 17 00 36](https://github.com/code100x/cms/assets/85656999/cc8d5e7f-6d0f-4050-bed8-5770663ad66c)

**Comment by siinghd** [comment]
@Hemant2335 
Default quality is 1080, when you change it, it will appear in the URL

**Comment by Hemant2335** [comment]
Yup Sir , but I Suppose it would be better that way

Thank you Sir
