### ISSUE TITLE
feature: A battle playground for DSA 

### ISSUE THREAD

**Issue by zssssssf** [code100x/cms#441]
**Feature**
A Battle playground for solving DSA problem where a user create a room and share with his/here friends and they can join and solve some given problem within a timeframe but the user who created the room, can create a user based on problem difficulty. Also we can have a chat interface so that they can discuss their approach.

![image](https://github.com/code100x/cms/assets/149182931/f0a99c8f-6cfa-4c50-978a-9b4c8f522e84)
![image](https://github.com/code100x/cms/assets/149182931/2a167e99-39b3-4385-9d51-a2d828215af1)

![image](https://github.com/code100x/cms/assets/149182931/db419c4d-e3ba-498a-b4e1-d604eccf33c7)

Hey @hkirat @devsargam please do let me know, if you guys are gonna build this, I really want t work on this problem.

**Comment by kushalnareda** [comment]
Really interesting tbh
