### ISSUE TITLE
feature: Better looking and feature packed Video Player

### ISSUE THREAD

**Issue by nimit9** [code100x/cms#442]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. The current player lacks a sleek UI 

**Describe the solution you'd like**
Build a video player that looks like and has features of YT/Netflix or some other good video player out there.

Have been wanting to build this, since I wanted to work on video.js and learn it in some depth.

@hkirat Is this something that we'd like to have?

**Comment by vikaspatil0021** [comment]
Something like this?
https://youtube-player-0021.vercel.app/

**Comment by SujithThirumalaisamy** [comment]
> Something like this? https://youtube-player-0021.vercel.app/

Looks great. Missing controls in the fullscreen mode?

**Comment by vikaspatil0021** [comment]
@SujithThirumalaisamy click in the middle of the screen or click spacebar

**Comment by SujithThirumalaisamy** [comment]
> @SujithThirumalaisamy click in the middle of the screen or click spacebar

Its good to show it on
Mouse move and disable after 3s pf mouse move stop. Was expecting that
