### ISSUE TITLE
bug: Website link on the GitHub repo doesn't seem to be working

### ISSUE THREAD

**Issue by adwait-godbole** [code100x/cms#452]
https://github.com/code100x/cms/assets/68469605/a5bd6a33-7733-4f68-9f2f-ea017785ed5f

**Comment by nimit9** [comment]
It's changed to app.100xdevs.com

**Comment by adwait-godbole** [comment]
Oops just realized this is the duplicate of #389

**Comment by Neon-20** [comment]
close it !!
