### ISSUE TITLE
bug: Slides button not working properly

### ISSUE THREAD

**Issue by Pratham271** [code100x/cms#454]
**Describe the bug**
The slides button on under the video component is not redirecting to correct slide instead it is getting stuck in a promise

**Expected behavior**
To redirect to the right slide like before

**Screenshots or GIFs**
<img width="1706" alt="Screenshot 2024-04-17 at 12 58 14 PM" src="https://github.com/code100x/cms/assets/83640434/8afaeafd-3a25-4414-b91e-21372a726210">

**Comment by Pratham271** [comment]
I have checked the responsible components but everywhere I see the async is awaited

**Comment by iam-joey** [comment]
I did had this issue

**Comment by sourabh32** [comment]
works in my case

**Comment by N4r35h** [comment]
@Pratham271 its been fixed in https://github.com/code100x/daily-code/pull/281
