### ISSUE TITLE
feature: Static Site Generation (SSG) for all pages

### ISSUE THREAD

**Issue by mvp5464** [code100x/cms#455]
**Is your feature request related to a problem? Please describe.**
Data is fetched everytime it was requested

**Describe the solution you'd like**
To add SSG for all pages

**Comment by ivinayakg** [comment]
In a CMS you can have a welcome, homepage, landing page, about page, and content page with static in my opinion.
And if that's what you are planning kudos to you, but if you're thinking about any other page, like course, lessons and so on that won't work as they have dynamic content
