### ISSUE TITLE
bug: Using space button while playing the video is performing the last action rather than pause

### ISSUE THREAD

**Issue by priyanshu9899** [code100x/cms#458]
**Describe the bug**
Pressing the space button while playing a video performs the last action (e.g., previous or forward) instead of pausing the video.

**To Reproduce**
1.Play a video.
2.Perform an action that changes the playback state (e.g., go to the previous or next video).
3.Press the space button.

**Expected behavior**
The video should pause when the space button is pressed, regardless of the previous action.

**Info :**
 - Browser [chrome]

**Comment by vikaspatil0021** [comment]
![Screenshot from 2024-04-18 09-43-56](https://github.com/code100x/cms/assets/112180774/50019030-584a-471b-af7f-8a0bcd968b13)
Are you referring to the 15 secs playback speed ?

**Comment by priyanshu9899** [comment]
YES
