### ISSUE TITLE
bug: not able to filter comments

### ISSUE THREAD

**Issue by kamalxdev** [code100x/cms#460]
**Describe the bug**
When trying to filter comments its redirect to the home page.

**To Reproduce**
1. Go to any video
2. Above comments, try to filter them

**Expected behavior**
It should filter comments based on the given filter selection.

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/145190836/292715cb-35a8-4c6a-b976-83bfd2de66de)

**Info (please complete the following information):**

**Additional context**

**Comment by kmaity-9563** [comment]
are you still working on this bug @kamalxdev

**Comment by kamalxdev** [comment]
No I,m not, you can go ahead @kmaity-9563

**Comment by kmaity-9563** [comment]
> No I,m not, you can go ahead @kmaity-9563

sure!

**Comment by SOUMITRO-SAHA** [comment]
Hi, are you still working on this issue? If not, please let me know so I can start working on it.
@kmaity-9563 @kamalxdev

**Comment by kmaity-9563** [comment]
pr happened but didn't merge

**Comment by Jatingupta9120** [comment]
Hi, are you still working on this issue? If not, please let me know so I can start working on it.
