### ISSUE TITLE
bug: APPBAR responsiveness

### ISSUE THREAD

**Issue by shashankdaima** [code100x/cms#477]
**Describe the bug**
Appbar can be made better

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/64317542/47912985-6349-4d9b-bce2-5743c945728f)

**Info (please complete the following information):**
 - Brave Browser
 - [Version 1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by shashankdaima** [comment]
LMK if this issue is not mentioned by anyone eariler/solved by other, then I will make pr. xD
Thanks

**Comment by shaheer21-sys** [comment]
I ran the application locally I see hamburger straight away 
<img width="1440" alt="image" src="https://github.com/code100x/cms/assets/65283693/1aceae04-be9a-4032-8e91-7688ccec8b4d">
