### ISSUE TITLE
bug: not all search recommendation are routing to its page   

### ISSUE THREAD

**Issue by shashankdaima** [code100x/cms#478]
**Describe the bug**
Not sure whether this is bug or feature. But I can't route to nextAuth lecture. 

**To Reproduce**
1. Login
2. Search and type "nextauth", click on nextauth recommendation

**Given behavior**
it route to homepage

**Expected behavior**
it should route to nextauth lecture.

**Screenshots or GIFs**
[Screencast from 2024-04-22 18-42-20.webm](https://github.com/code100x/cms/assets/64317542/17e6cdd0-78f3-4df0-adf1-d7099970e110)

**Info about browser:**
Brave Browser
[Version 1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by hxdy-1** [comment]
@shashankdaima same issue persists from **Week 16 Offline** onwards. If u have fixed it plz open a PR, don't wait this much for getting an issue to be assigned.

**Comment by shashankdaima** [comment]
alright thanks @hxdy-1 I don't know the rules. Thanks for mentioning. will make PR  by night. thank you so much

**Comment by hkirat** [comment]
The problem is that the search endpoint doesnt ensure that u have access to a course
It should only show u videos of the courses you have access to 
If that is fixed, this error should be fiexd along
