### ISSUE TITLE
Side Chapter font color need to be fix in dark mode.

### ISSUE THREAD

**Issue by MrPurushotam** [code100x/cms#48]
![Screenshot 2024-02-03 013154](https://github.com/code100x/cms/assets/55340065/c38f5eb9-5098-4eb7-875a-7a1860302f6a)

**Comment by sahilsuman933** [comment]
#53 fix this issue @hkirat

**Comment by siinghd** [comment]
> #53 fix this issue @hkirat

Should be fixed I can see the text

**Comment by hkirat** [comment]
<img width="595" alt="Screenshot 2024-02-03 at 1 15 01 PM" src="https://github.com/code100x/cms/assets/8079861/66e7f224-ead8-44c8-9d2b-0a081d770ec9">

**Comment by krishna9358** [comment]
is it fixed  ?
