### ISSUE TITLE
feature: Certificate for users in 0-1

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#483]
We want to allow users to be able to create publically available certs
They should also be allowed to put it on twitter/linkedin

**Comment by hkirat** [comment]
Needs to have an id as well that employers can verify with

**Comment by hkirat** [comment]
pdf, can use some standard design like courseras

**Comment by VaibhavArora314** [comment]
hey @hkirat , I am thinking of adding a Certification model and we can use id of Certification model for verification purposes of any certificate

```
model User {
 // existing fields

  certifications Certification[]
}

model Certification {
  id                String    @id @default(cuid())
  user              User      @relation(fields: [userId], references: [id])
  userId            String
  course            Course    @relation(fields: [courseId], references: [id])
  courseId          Int
  certificationDate DateTime

  @@unique([userId, courseId])
}
```

Also do you want to generate the certificates once the course has been completed or purchased? As upon inspection I don't see any way of tracking user progress of the course.

**Comment by dhruvilmehta** [comment]
I am not getting a way to share the certificate image on Twitter and LinkedIn directly. I think we can only share links and not images. Images can only be uploaded by the user manually.
Do you know any other way to do so?
I tried these two ways:
For twitter: `https://twitter.com/intent/tweet`
For LinkedIn: `https://www.linkedin.com/sharing/share-offsite/?url={url}`

**Comment by SujithThirumalaisamy** [comment]
> I am not getting a way to share the certificate image on Twitter and LinkedIn directly. I think we can only share links and not images. Images can only be uploaded by the user manually. Do you know any other way to do so? I tried these two ways: For twitter: `https://twitter.com/intent/tweet` For LinkedIn: `https://www.linkedin.com/sharing/share-offsite/?url={url}`
> 
> If direct sharing is not possible, we can give the users the option to download both PDF and PNG files since PDF sharing is also not possible on LinkedIn/Twitter. Users can download PNG files and post on LinkedIn/Twitter.

I think that should be possible. I remember sharing some W3 certs comewhere in linked in and also shared some coursera certs it twitter. I think mostprobabbly we can get both the things done.

**Comment by dhruvilmehta** [comment]
This is how it is currently working.
LinkedIn sharing is not working.
The download is working fine both for PDF and PNG.
https://github.com/code100x/cms/assets/68022411/429026b3-d35f-43b4-bb2b-7e066b15f9ba
