### ISSUE TITLE
bug: No input validation on backend api routes

### ISSUE THREAD

**Issue by Sahil-Choudhary-17** [code100x/cms#484]
![code](https://github.com/code100x/cms/assets/128586019/396f4c0b-71ec-4603-872a-e07a77a33d5c)

right now there is no input validation on backend

we can create a zod schema to validate the input on backend and reuse the same schema in react-hook-forms to validate the form input on frontend. 

I would like to work on this issue.

**Comment by hxdy-1** [comment]
@Sahil-Choudhary-17 are u working on this?

**Comment by vikaspatil0021** [comment]
bro no need for assignment start working
