### ISSUE TITLE
bug: Checking off a video (to mark it watched in the side navbar) doesn't save state

### ISSUE THREAD

**Issue by ShivShankarDash** [code100x/cms#496]
**Describe the bug**
Checking off a video (to mark it watched in the side navbar) doesn't save state. If you open another tab in the side nav bar and navigate back to the page , you will find the check to be reset.

**To Reproduce**
1. Mark a video complete in the side nav-bar. 
2. Close the week tab and navigate to another week's tab and get back to the original , to find it reset. 
3. Only when you hard reload , is when the progress saved.

**Expected behavior**
The tick should maintain its state , and should not require a hard reload for the same. 

**Screenshots or GIFs**

https://github.com/code100x/cms/assets/35873312/2fc45997-c16c-4242-a1a7-898bd7a11d0c

**Info (please complete the following information):**
 - Browser : Google Chrome 
 - Version : 124

**Comment by manthan-sharma-23** [comment]
are you working on this ? 
Porbably it is due to unmounting of the microcompenent we have to make the statee available for that complete component
