### ISSUE TITLE
Allow users to post assignment submissions for the week #7

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#5]
put links in every week
Gives them a public portfolio of all they've done

**Comment by Srinivasan-Akash** [comment]
Could you please this to me

**Comment by chetanguptaa** [comment]
so the assignment submissions should be in the form of a link, right?

**Comment by syndg** [comment]
> so the assignment submissions should be in the form of a link, right?

Yes I think he meant the users should be able to link their github repo?

**Comment by nimit9** [comment]
Hey @hkirat , have you thought about the UX for this? I'd like to work on it
