### ISSUE TITLE
bug: View Content button of ML and Android course are not working

### ISSUE THREAD

**Issue by Satishkumar7991** [code100x/cms#503]
**Describe the bug**
 The **View Content** button on  Harnoors's Android cohort and Machine Learning + MLOps course Cohort card is not working.  After clicking **View Content**, it is redirecting to [harkirat.classx.co.in/](https://harkirat.classx.co.in/)

**To Reproduce**
1. Login to [app.100xdevs.com/](https://app.100xdevs.com/)
2. Click **View Content**  on Harnoor's Android cohort Cohort or Machine Learning + MLOps course Cohort

**Expected behavior**
After clicking **View Content**  on Harnoor's Android cohort Cohort or Machine Learning + MLOps course Cohort, user should see the course contents

**Screenshots or GIFs**
Screenshot of machine learning cohort

https://github.com/code100x/cms/assets/47490431/ac70b14d-e322-4fe6-90e2-9593b668a6ec

Screenshot of Android cohort

https://github.com/code100x/cms/assets/47490431/c6f0045e-21a2-42a2-ac73-746b48c168b8

**Comment by Raj-Thombare** [comment]
working on it!

**Comment by hxdy-1** [comment]
agree with @Raj-Thombare , those courses are not meant to be get accessed here, if u want to watch them, u have to go to classx website.

**Comment by Satishkumar7991** [comment]
@Raj-Thombare  and @hxdy-1 a few months ago, I accessed the ML course from [app.100xdevs.com](https://app.100xdevs.com/), which led me to suspect a potential bug. But If the courses are not intended to be accessed on classx then thank you for clarifying it.

**Comment by hxdy-1** [comment]
@Satishkumar7991 I meant those courses are only meant to be accessed on classx
