### ISSUE TITLE
hamburger icon is flipped

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#51]
<img width="461" alt="Screenshot 2024-02-02 at 11 41 06 PM" src="https://github.com/code100x/cms/assets/8079861/a9415a13-02cc-4def-862f-efbfeac9bdc9">
<img width="730" alt="Screenshot 2024-02-02 at 11 41 02 PM" src="https://github.com/code100x/cms/assets/8079861/d8869079-7913-4ef8-8e32-fb51262cb49f">

**Comment by markande98** [comment]
Hey @hkirat , can I work on this?
