### ISSUE TITLE
bug: Comments can be added but can't be deleted. 

### ISSUE THREAD

**Issue by shashankdaima** [code100x/cms#510]
**Describe the bug**
follow the video. 

**Screenshots or GIFs**
[screen-capture.webm](https://github.com/code100x/cms/assets/64317542/c7b0143d-74a9-4a42-b4c7-701684467f2c)

**Comment by shashankdaima** [comment]
![image](https://github.com/code100x/cms/assets/64317542/547840c2-f5e2-43e1-951f-08b31ad0fb4a)

**Comment by shashankdaima** [comment]
![8ojuoc](https://github.com/code100x/cms/assets/64317542/1e5c5671-749c-47cb-8a63-5fa561edc6ba)

**Comment by rathoreyuvraj19** [comment]
i hope this is correct now

**Comment by sachinninave** [comment]
hello , everyone here comment can only be deleted by  ADMIN

so , we can do this thing than who ever is not an admin we will not show them delete comment button on UI
