### ISSUE TITLE
bug: Anyone can download the notes or Notion doc  from `https://projects.100xdevs.com/` without login, @hkirat

### ISSUE THREAD

**Issue by sumedh404** [code100x/cms#526]
Anyone can download the notes or Notion doc from `https://projects.100xdevs.com/`
there is no need to login

**Comment by Ameerjafar** [comment]
Are you currently working on this @sumedh404

**Comment by sumedh404** [comment]
I just started

**Comment by HectorShaw** [comment]
this isnt the repo for that, ig ?
https://github.com/code100x/daily-code

**Comment by hxdy-1** [comment]
Hey @sumedh404 looks like you have mistook this repo for daily-code 🙂
