### ISSUE TITLE
bug: Slide button not available of the video

### ISSUE THREAD

**Issue by ramnaresh8** [code100x/cms#531]
**Describe the bug**
the slide button is not available for the slide associate with the video as it was before

![Screenshot (209)](https://github.com/code100x/cms/assets/76533244/91bf833d-47db-4bcb-87b4-e416cd6b953a)

**Comment by Raj-Thombare** [comment]
slides are not available for this video!

**Comment by ramnaresh8** [comment]
Got it

**Comment by ramnaresh8** [comment]
Since slides are not available, this is not the issue

**Comment by Raj-Thombare** [comment]
then whats the issue? cause except first 5 weeks videos everything has slides
