### ISSUE TITLE
bug: npm run prisma:migrate:dev does not work

### ISSUE THREAD

**Issue by psidh** [code100x/cms#533]
**Describe the bug**
<br>
When I was trying to setup the cms, the command `npm run prisma:migrate:dev` did not work
while npm run prisma:migrate works
<br>
This is due the following `package.json`
<img width="457" alt="Screenshot 2024-05-05 at 16 05 50" src="https://github.com/code100x/cms/assets/116720762/a241bad8-52fa-4493-98b2-564147a61ec4">

<br>
<br>

**To Reproduce**

Here if you run `npm run prisma:migrate:dev` you get the following error

<img width="772" alt="Screenshot 2024-05-05 at 16 05 35" src="https://github.com/code100x/cms/assets/116720762/5a6fc37a-964e-405d-97d1-a150c23106a2">

<br>

**Expected behavior**

<br>

We expect it to migrate without errors 

> This screenshot is after I executed this command

```
npm run prisma:migrate
```
<br>
<br>
<img width="758" alt="Screenshot 2024-05-05 at 16 06 37" src="https://github.com/code100x/cms/assets/116720762/150dbbe4-ee18-4840-97bb-4a4f13e4bc00">

**Info (please complete the following information):**
 - Browser FireFox
 - Version 125.0.3 (64-bit)
 - macOS 14.4.1 (Sonoma)

**Comment by Ameerjafar** [comment]
i have already made this pr borther error #524 pr #525

**Comment by psidh** [comment]
Okay, I am removing this PR and the issue
Thanks for the catch
