### ISSUE TITLE
bug: yarn install failing on a mac

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#542]
post https://github.com/code100x/cms/pull/487/files
Something with the canvas library

**Comment by hkirat** [comment]
/Users/harkiratsingh/Projects/cms/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments: 
Directory: /Users/harkiratsingh/Projects/cms/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11

**Comment by hkirat** [comment]
cc @dhruvilmehta`

**Comment by dhruvilmehta** [comment]
For Apple silicon chips, you need to run `brew install pkg-config cairo pango libpng jpeg giflib librsvg`. I tried this and it started running.
Source: 
1. https://github.com/Automattic/node-canvas/wiki/Installation%3A-Mac-OS-X
2. https://github.com/Automattic/node-canvas/issues/1825

**Comment by VK-RED** [comment]
Failing on Linux as well !

**Comment by dhruvilmehta** [comment]
Is it still failing after running the above command? It solved the issue for me on Mac.

**Comment by VK-RED** [comment]
No it did not solve for linux

**Comment by Arup20MA20010** [comment]
Canvas library is dependent on other packages that are not natively available on Linux machines and node-alpine images. So you need to install the dependencies in the machine before running npm install. Refence: [https://stackoverflow.com/questions/57088230/node-canvas-on-alpine-within-docker](url). 
I have fixed the same in the Dockerfile and raised a PR #564 .
