### ISSUE TITLE
feature: Make certificate frontend only and using react

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#545]
Canvas rendering on the server is very expensive
We should just render on the client since it is faster
Can this be done? check https://github.com/abhithory/auth-certficates

**Comment by hkirat** [comment]
Right now downloading a certificate is very slow

**Comment by hkirat** [comment]
@TanmayDhobale if you are free

**Comment by Pritam12F** [comment]
I would like to take on this issue/enhancement @hkirat. Would be nice to have some guidance though

**Comment by VK-RED** [comment]
Hi @hkirat Working on it , I have managed to render the Pdf on client. But for some reason when using canvas library to render the images, it breaks. Trying to find some work arounds. Will raise a PR soon ..
