### ISSUE TITLE
bug: dependencies conflicting while setting up the project using docker 

### ISSUE THREAD

**Issue by kethesainikhil** [code100x/cms#547]
**Describe the bug**
Peer dependencies conflicting while setting up the project.
**To Reproduce**
Fork the repo and try to run docker-compose up at npm install step we will get the error.

**Expected behavior**
Should be able to install without conflicts.
**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/70809367/c56fe124-8e1f-4613-a324-4dffb95a2f7e)

**Info (please complete the following information):**

**Additional context**

**Comment by Naveed-23** [comment]
Try removing canvas dependency in package.json, worked for me

**Comment by RushikeshShelar** [comment]
Tried Removing Canvas Dependency still the Issue Persists. The react versions needed for ` react-intersection-observer` and `react-lazy-images` are incompatible with project's react version atleast thats what my logs say when I try to start the project by `docker-compose up`

Here Are My Complete Logs
![image](https://github.com/code100x/cms/assets/112684561/4d7474ae-ff46-4991-8ade-5c0f32666d15)
![image](https://github.com/code100x/cms/assets/112684561/3d1b827f-db6c-4ff2-9c61-e4bfc5cc5618)


Maybe in my case there is Connection issue with the Docker. However I have a Strong internet connection everything else works fine.

**Comment by Pritam12F** [comment]
Works okay for me, I deleted the cms image I already had on my machine and re-ran docker-compose up

**Comment by kethesainikhil** [comment]
removing canvas worked for me thanks man @Naveed-23
