### ISSUE TITLE
bug: Text,buttons are not visible in 404 page not found in (opposite of system's default theme Mode)

### ISSUE THREAD

**Issue by kethesainikhil** [code100x/cms#552]
**Describe the bug**
When  a user goes to any non listed route a 404 default page will be rendered by the nextjs so in Light mode the text is not visible as it the text is in white color and also the color mode shift button also not visible , Logout / Login button also not visible.

**To Reproduce**
1.go to any random route that is not listed in the project 
2.change the mode like if you are in dark mode change it to light mode and viceversa.
3.You will notice the 404 page not found text is not visible .

**Expected behavior**
1.There we need to see the buttons and the text so that user can be noticed that the page is not listed.

**Screenshots or GIFs**
![Screenshot from 2024-05-07 13-50-41](https://github.com/code100x/cms/assets/70809367/37db940c-2a03-423c-8b57-27060b2b671d)

**Info (please complete the following information):**

**Additional context**

**Comment by Raj-Thombare** [comment]
working on it!

**Comment by kethesainikhil** [comment]
I have already worked on it and ready to pull the code man

**Comment by abhirupPann** [comment]
But this thing works on my system, there isn't any issue!(Browser: Chrome)
![Screenshot (576)](https://github.com/code100x/cms/assets/69336711/8c622184-661d-4767-b4f0-14c21b013f46)

**Comment by abhirupPann** [comment]
> I have already worked on it and ready to create the pull request for the same

But there isn't any error in my browser, whereas in my case the nav bar texts went out(Browser: Chrome)
![Screenshot (576)](https://github.com/code100x/cms/assets/69336711/170f4110-5822-4af3-9189-65e8b9141adc)

**Comment by kethesainikhil** [comment]
Could you please share the dark mode picture

**Comment by kethesainikhil** [comment]
> > I have already worked on it and ready to create the pull request for the same
> 
> But there isn't any error in my browser, whereas in my case the nav bar texts went out(Browser: Chrome) ![Screenshot (576)](https://private-user-images.githubusercontent.com/69336711/328982082-170f4110-5822-4af3-9189-65e8b9141adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTAxNDAsIm5iZiI6MTcxNTE4OTg0MCwicGF0aCI6Ii82OTMzNjcxMS8zMjg5ODIwODItMTcwZjQxMTAtNTgyMi00YWYzLTkxODktNjVlOGI5MTQxYWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE3MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxN2VjZmM3N2FmZTgyMjJmZjMzYzk2MmU2NmEwMTBjM2I4YWM2ZmJhNmRhY2QzMTVmMDU0YzM4YjYwZWE4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q_f6125PRMKEkULacG3JGT8Vl1pL-uUoqaqNQvDco60)

could you please share the same picture in dark mode as the issue will occur in opposite mode of user's default theme like if user default mode is dark then the issue occurs in light mode and viceversa

**Comment by abhirupPann** [comment]
> > > I have already worked on it and ready to create the pull request for the same
> > 
> > 
> > But there isn't any error in my browser, whereas in my case the nav bar texts went out(Browser: Chrome) ![Screenshot (576)](https://private-user-images.githubusercontent.com/69336711/328982082-170f4110-5822-4af3-9189-65e8b9141adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTAxNDAsIm5iZiI6MTcxNTE4OTg0MCwicGF0aCI6Ii82OTMzNjcxMS8zMjg5ODIwODItMTcwZjQxMTAtNTgyMi00YWYzLTkxODktNjVlOGI5MTQxYWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE3MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxN2VjZmM3N2FmZTgyMjJmZjMzYzk2MmU2NmEwMTBjM2I4YWM2ZmJhNmRhY2QzMTVmMDU0YzM4YjYwZWE4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q_f6125PRMKEkULacG3JGT8Vl1pL-uUoqaqNQvDco60)
> 
> could you please share the same picture in dark mode as the issue will occur in opposite mode of user's default theme like if user default mode is dark then the issue occurs in light mode and viceversa

Oh got it! Yeah I am having the problem on dark mode.

**Comment by kethesainikhil** [comment]
Yeh I have fixed that and also introduced inhouse error page which looks better than default one 
![image](https://github.com/code100x/cms/assets/70809367/67974abe-e1df-4324-bf9b-9a6987a5a78a)
