### ISSUE TITLE
Login not responsive on mobile

### ISSUE THREAD

**Issue by shreyas0924** [code100x/cms#56]
![image](https://github.com/code100x/cms/assets/72003665/8f48a4c3-d6e5-459d-9af4-6997c205591b)

**Comment by Sumit-Kumar-21** [comment]
hey, i solve the issue after getting help from chat-gpt, 

https://github.com/code100x/cms/assets/151529182/a8a52134-4b6e-43cb-8eec-be54a814cf5b

here is the preview.

if this ok then, assign this issue to me so i create pull request.
