### ISSUE TITLE
bug: Sidebar layout taking 100% width

### ISSUE THREAD

**Issue by yash-kh** [code100x/cms#562]
Sidebar layout, taking 100% width.

1. Start the app in main branch.
2. Go to any course

Should set it back to normal

Now sidebar looks like:
<img width="1680" alt="Screenshot 2024-05-11 at 4 07 38 PM" src="https://github.com/code100x/cms/assets/60394241/58149aef-8a28-4500-a2db-db964c55d6e7">

**Info (please complete the following information):**
 - Browser - chrome
 - Version - 124

**Comment by Pritam12F** [comment]
This is only happening because there is no content on the right side. Doesn't happen on app.100xdevs.com cos there are videos for each topic

**Comment by yash-kh** [comment]
> This is only happening because there is no content on the right side. Doesn't happen on app.100xdevs.com cos there are videos for each topic

This is not the case check my PR it have SS before and after.

**Comment by yash-kh** [comment]
Closed by mistake
