### ISSUE TITLE
The video completion tick-mark does not persist when the week section is re-opened

### ISSUE THREAD

**Issue by rayyan21d** [code100x/cms#567]
When I update the mark as complete check box, it doesn't persist when I close and reopen the week section.

![image](https://github.com/code100x/cms/assets/69739582/96d35505-76a0-4674-86d0-37b37f559b15)

**To Reproduce**
1. Open the website and log in
2. Open a video and follow what the video does

**Expected behavior**
The tick-mark should persist even if I close the week section.

**Screenshots or GIFs**

https://github.com/code100x/cms/assets/69739582/8093f50a-49ba-4ca8-948e-0250aebf7be3

**Info (please complete the following information):**
 - Browser Brave
 - Version: 1.65.132 Chromium: 124.0.6367.202 (Official Build) (64-bit)

**Additional context**

![image](https://github.com/code100x/cms/assets/69739582/e206fdd3-a6a4-4d65-a173-79e494c90f46)

I checked the network tab and found ki request for updating the course is running and it's successful. But when I close and open the section, there's no network request that's going to load the data, or I'm not sure how the state is being saved. Maybe the state goes back to default values once the request is being sent.

**Comment by shivam-raj03** [comment]
In this issue when refresh the website then it persiting the mark

**Comment by jayprakash25** [comment]
Can I get assigned to do this?

**Comment by jayprakash25** [comment]
I was thinking of using local storage to keep track of each checkbox's state.

**Comment by jayprakash25** [comment]
Sorry, but the above solution isn't working and I figured out why we are facing this in the first place. The check component is being re-rendered when the accordion is opened or closed, causing the check state to be reset. 

We can solve this by moving the check box state management to the parent Sidebar component,
then we will pass the checkbox state and a function to update the checkbox state as a prop to the Check component.

**Comment by jayprakash25** [comment]
https://www.loom.com/share/8fd99e679c7d4bf9b56612389e04e17e?t=10&sid=f908802e-e4f9-4755-b028-56b5ffafa7c0

And it's working!!!

**Comment by AbhimanyuAjudiya** [comment]
> When I update the mark as complete check box, it doesn't persist when I close and reopen the week section.
> 
> ![image](https://private-user-images.githubusercontent.com/69739582/329792709-96d35505-76a0-4674-86d0-37b37f559b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTIyNzYsIm5iZiI6MTcxNjExMTk3NiwicGF0aCI6Ii82OTczOTU4Mi8zMjk3OTI3MDktOTZkMzU1MDUtNzZhMC00Njc0LTg2ZDAtMzdiMzdmNTU5YjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA5NDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NWQ1NGIwZmRjMmQ2MjY1ODFjZmFlODZmNDQ1NDEzY2NkMjdkNTBjZDBkZGQyMzVjOTFiOTg3MGIzYzhmZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8fltThsSltaBnddU_DyDiAfFthrhbYpehBSD1kXcfEk)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open the website and log in
> 2. Open a video and follow what the video does
> 
> **Expected behavior** The tick-mark should persist even if I close the week section.
> 
> **Screenshots or GIFs**
> 
>  out.4.mp4 
> **Info (please complete the following information):**
> 
> * Browser Brave
> * Version: 1.65.132 Chromium: 124.0.6367.202 (Official Build) (64-bit)
> 
> **Additional context**
> 
> ![image](https://private-user-images.githubusercontent.com/69739582/329796598-e206fdd3-a6a4-4d65-a173-79e494c90f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTIyNzYsIm5iZiI6MTcxNjExMTk3NiwicGF0aCI6Ii82OTczOTU4Mi8zMjk3OTY1OTgtZTIwNmZkZDMtYTZhNC00ZDY1LWExNzMtNzllNDk0YzkwZjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA5NDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YjlmMzViMTRkZDBiMzgzNDY3ZDA0ZjcwYTU1MWZmYjdmYzE5YjU1M2NmZjVkYjdjZmZkYzI1MWE4OGFjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kEOAwb-wCOaxxfGY7l_xyIM3O3l7bt4V2K_lN0mRevU)
> 
> I checked the network tab and found ki request for updating the course is running and it's successful. But when I close and open the section, there's no network request that's going to load the data, or I'm not sure how the state is being saved. Maybe the state goes back to default values once the request is being sent.

Hey i'm also facing this issue, also after refreshing its is not getting checked.
I'm using chrome
