### ISSUE TITLE
bug: ceritifcate not centrally aligned

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#574]
text needs to be in the center for all name lengths

<img width="1280" alt="Screenshot 2024-05-12 at 11 32 48 PM" src="https://github.com/code100x/cms/assets/8079861/3d10c5ff-9ecd-467c-b1b3-2dd53a476292">

**Comment by shivamsinghcse** [comment]
i can work upon it sir

**Comment by victorchrollo14** [comment]
does this look fine? or Is the issue talking about something else.

![image](https://github.com/code100x/cms/assets/89346667/d0b50e87-4c51-40e1-9e07-3cb1f12ac952)

**Comment by Vishvsalvi** [comment]
Bro how did you get to this page? 
![image](https://github.com/code100x/cms/assets/82429084/17ae56f2-9cdc-425c-8039-fc43e786081a)

Mine is just empty

**Comment by victorchrollo14** [comment]
> Bro how did you get to this page? 
> ![image](https://github.com/code100x/cms/assets/82429084/17ae56f2-9cdc-425c-8039-fc43e786081a)
> 
> Mine is just empty

There is a condition that checks, for isCertified variable is true or not, based on that it would pass this data into certificate component, and then the component would render it, right now those values you get from db are set to false, so after retrieving the data, change it to true. Then it will get rendered.

Just backtrack the code from the certificate component, you'll get it.
