### ISSUE TITLE
bug: better loader, if possible design the whole page better

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#575]
Looks pretty ugly for a full stack course if I'm being honest

<img width="1696" alt="Screenshot 2024-05-12 at 11 33 39 PM" src="https://github.com/code100x/cms/assets/8079861/1816d9c1-7281-486b-abb7-2e1f7d952e6a">

**Comment by Vishvsalvi** [comment]
Please assign me this, I will work on it.

**Comment by Vishvsalvi** [comment]
@hkirat please clear my doubt, will this page display multiple certificates and upon clicking one a specific page for one certificate will be displayed. If this is the case then a table or grid can be added.

**Comment by victorchrollo14** [comment]
@hkirat . does any of the following look good?


![Desktop - 3](https://github.com/code100x/cms/assets/89346667/398b4538-82c5-4765-9e86-1fe7880978e1)
![Desktop - 4](https://github.com/code100x/cms/assets/89346667/c6d56854-9364-4e04-8651-09dfba44bd08)
![Desktop - 2](https://github.com/code100x/cms/assets/89346667/b2d26198-1cd0-42c4-bb4c-d0e361fe61c6)
![Desktop - 1](https://github.com/code100x/cms/assets/89346667/8b33d2ff-fa4e-4dbb-84f1-8ff37d0ec9d7)

**Comment by professor2345** [comment]
yeah its looking cool

**Comment by zeul22** [comment]
Would love to work on this, Here's what I have thought to do with the design

![image](https://github.com/code100x/cms/assets/62982824/8131b9a3-628e-45d1-ad8e-b65689a5f3aa)

**Comment by victorchrollo14** [comment]
> Would love to work on this, Here's what I have thought to do with the design
> 
> ![image](https://github.com/code100x/cms/assets/62982824/4db83959-98bb-4db7-a250-f3447d563541)
> 
> 

Where's the certificate?

**Comment by zeul22** [comment]
ah, my bad.This is my first time, I thought we were getting the user details.
