### ISSUE TITLE
feature: questions should be attached to content

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#576]
We should allow questions to be tagged with videos. 
So we can find all the questions for a given video in a single place.

Somewhere here allow the user to attach content to it. 

<img width="1201" alt="Screenshot 2024-05-12 at 11 46 27 PM" src="https://github.com/code100x/cms/assets/8079861/008d3bfd-df40-4391-99c2-e5631844bd61">

Also in the video add a button that lets the user create a question
<img width="868" alt="Screenshot 2024-05-12 at 11 47 59 PM" src="https://github.com/code100x/cms/assets/8079861/680d2913-2a0e-4c30-a4a7-bfd6e69fc964">

**Comment by jayprakash25** [comment]
Hi,
I think I might have an approach.
--For tagging questions, we can likely add a "video" field to the question submission modal where users can have the option to select from a dropdown of available videos. And update the db accordingly.
-- For a button like 'create question', we can add a simple component that will open the question modal which will be prepopulated with that particular video's ID.

Does this approach make sense? Let me know.

**Comment by jayprakash25** [comment]
I was actually waiting for this to be assigned as mentioned in contribution guidelines....
