### ISSUE TITLE
Video Player Size does not fill the width when the screen width is reduced.

### ISSUE THREAD

**Issue by aravindtm27** [code100x/cms#58]
![image](https://github.com/code100x/cms/assets/145952967/91587df7-3547-4190-9f75-46a8a2419b8e)

Earlier this wasn't an issue but I think the ideal solution is for it to fill the screen width available.

**Comment by tanishq-arya** [comment]
@aravindtm27 Are you working on this ? Can I raise a PR for this ?

**Comment by aravindtm27** [comment]
@tanishq-arya yea sure

**Comment by Lokendra-sinh** [comment]
@aravindtm27 the responsiveness is fine after a certain point there's a sudden jump in the aspect ratio of the player right?

**Comment by tanishq-arya** [comment]
### Before
![Screenshot (3)](https://github.com/code100x/cms/assets/77333275/c6edfd5c-a522-4673-9bff-464ceee42a00)

### After
![Screenshot (2)](https://github.com/code100x/cms/assets/77333275/f674a201-87ad-4cb6-91f1-40dae1768f9f)
