### ISSUE TITLE
bug: seeing this locally on running npm run dev

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#581]
<img width="1139" alt="Screenshot 2024-05-13 at 2 28 58 AM" src="https://github.com/code100x/cms/assets/8079861/949daf56-109b-4de4-9449-3abeea6f289f">

**Comment by SwarnenduG07** [comment]
![Screenshot 2024-05-13 105445](https://github.com/code100x/cms/assets/141937171/d6b785e5-ac2b-449a-8e50-07525a095ee5)
 In my local system it is working

**Comment by ashuk1109** [comment]
The issue is occurring due to removal of package-lock.json file in one of the latest commits. I am working on this and will send a PR for adding those back.
