### ISSUE TITLE
bug: nav loader issue

### ISSUE THREAD

**Issue by ssk090** [code100x/cms#582]
nav bar does not show up when clicked on view content
![image](https://github.com/code100x/cms/assets/22127725/1c0121e2-1131-4e5f-bd4d-86c7d53ee9c9)

navbar loader shows when clicked on 'test course 1'
![image](https://github.com/code100x/cms/assets/22127725/705c61b6-ee4d-4bb6-b952-d9b3c8c5c6c9)

but does not show when clicked on course card

**Comment by YunusShaikh29** [comment]
We have loading skeleton for that!
