### ISSUE TITLE
bug: seekbar doesnt appear if there are no segments

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#584]
need to fix this asap
is preventing deploying

**Comment by devsargam** [comment]
working on this hopefully can fix this up

**Comment by mumin-khan** [comment]
@hkirat hopefully this fixes it.

**Comment by mumin-khan** [comment]
@hkirat https://github.com/code100x/cms/pull/494 I think this pr has reverted most of the changes done to video player done in https://github.com/code100x/cms/pull/482 so we are now using old seekbar again.

**Comment by shuaibu-shehu** [comment]
yeah, that may be possible

**Comment by Ameerjafar** [comment]
is this issue is still open @hkirat
