### ISSUE TITLE
bug: somethings is up with subtitles

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#590]
<img width="1152" alt="Screenshot 2024-05-13 at 3 57 18 AM" src="https://github.com/code100x/cms/assets/8079861/0c9a0733-f7be-4215-8d2d-4e188c31f00d">

Steps to reproduce
Put a vtt file link as subtitles in the video

**Comment by NIXBLACK11** [comment]
I'm working on fix the issue. Will keep everyone posted on progress.

**Comment by NIXBLACK11** [comment]
I tried to reproduced this problem using [this](https://github.com/code100x/cms/blob/main/public/subs.vtt) sample file, and for this file the  captions are working fine.
Can you provide a sample file to recreate this issue?
![image](https://github.com/code100x/cms/assets/91743459/cdf044a5-3cd0-4f64-86f7-c8704f0ae96e)

**Comment by Kaif987** [comment]
I tried this on my machine and I didn't see any problem with the subtitles 
![Uploading Screenshot from 2024-05-14 15-16-18.png…]()

**Comment by Kaif987** [comment]
I tired this and there were no issues with the subititle
![Screenshot from 2024-05-14 15-16-18](https://github.com/code100x/cms/assets/98884589/a8035df2-aaba-4cc2-9ac6-1dec9c5acace)
