### ISSUE TITLE
bug: revert to this type of cert

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#596]
![WhatsApp Image 2024-05-13 at 10 06 08](https://github.com/code100x/cms/assets/8079861/f7f8023b-77ee-441d-9812-b08c524face9)

@TanmayDhobale

**Comment by TanmayDhobale** [comment]
@hkirat only  cert design  right ?

**Comment by hkirat** [comment]
yes

**Comment by hkirat** [comment]
keep the implementation the same

**Comment by TanmayDhobale** [comment]
@hkirat can u check this pr
