### ISSUE TITLE
Left slide bar should keep video items as link

### ISSUE THREAD

**Issue by tejaskh3** [code100x/cms#6]
While moving to one video to another I face problem and want the left bar items to be link so that i can open new videos on new tab, and i think most of us would be facing this issue.

attaching an image for better clarity.
![image](https://github.com/code100x/cms/assets/98630752/03a492e1-235c-4893-907a-05500bc41488)

**Comment by tejaskh3** [comment]
@hrikat if it need to you as well then only asign this to me otherwise i'll delete this issue no point of keeping junk

**Comment by SanketDhabarde** [comment]
Hi @tejaskh3 The better way I think the active tab should be collapsed and have the active option showing the option we are currently on.
