### ISSUE TITLE
View Chapters button is not showing video chapters on clicking

### ISSUE THREAD

**Issue by pankaj-2503** [code100x/cms#60]
I am getting this  after clicking the view all chapters button.
![image](https://github.com/code100x/cms/assets/90036864/ce4bad42-c53c-41dc-acff-c2d70633bb0e)

**Comment by shrutsureja** [comment]
I found a similar issue @pankaj-2503 in the videos where timestamp is not allotted. But i also encountered another problem. I would love to solve it but I still don't understand the nextjs.

I got a different error by clicking the "View all chapters" button but it only happened in a few of the videos and in the ones where time stamps have been added, the button and feature works great

Here is what popped up

1. Clicked the "View all chapters" button and this is the output.
![image](https://github.com/code100x/cms/assets/92169549/23ba9212-2230-4b96-85c0-803e6e3ac974)

Here is the console content Image
![image](https://github.com/code100x/cms/assets/92169549/eca2c61b-70f7-4f8c-a3c3-0eac7d6f9d53)

Now the same issue comes in the Edge Browser 

Here is the list of videos that i checked randomly and gave me this error (not check all the videos)
- Week 10 - 10.0.1 | Cohort 1 Postgres video
- Week 10 - 10.0.2 | Cohort 1 Prisma video
- Week 2 - 2.1 | Revision of Promises, Async JS
- Week 1.1 | Orientation class
