### ISSUE TITLE
bug: `nextjs-toploader` not being installed

### ISSUE THREAD

**Issue by psidh** [code100x/cms#603]
**Describe the bug**

nextjs-toploader not being installed

**To Reproduce**

When we execute `npm run dev` 

**Expected behavior**

**Screenshots or GIFs**

<img width="702" alt="Screenshot 2024-05-13 at 13 32 33" src="https://github.com/code100x/cms/assets/116720762/5f6bdbf8-ee89-46bb-b729-21ae4a003743">

## Logs of npm

<img width="991" alt="Screenshot 2024-05-13 at 13 40 52" src="https://github.com/code100x/cms/assets/116720762/0c628e88-d773-4de6-8f93-57c5d324fbc0">

<img width="1045" alt="Screenshot 2024-05-13 at 13 40 59" src="https://github.com/code100x/cms/assets/116720762/78db99ea-5d4a-4e93-8ce9-af47a8be87e1">

**Comment by hxdy-1** [comment]
@psidh  just install all the dependencies first by `npm i` or` yarn install`, it wont be an issue after.
