### ISSUE TITLE
bug: questions overlap footer

### ISSUE THREAD

**Issue by ezhil56x** [code100x/cms#619]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [https://app.100xdevs.com/questions](https://app.100xdevs.com/questions)
2. You can see the questions overlapping the footer

**Expected behavior**
Footer should not be overlapped by the questions

**Screenshots or GIFs**

https://github.com/code100x/cms/assets/103899034/abc8beac-5efb-4053-91cf-df7485d7a27d

**Comment by Upendra-Jaiswal** [comment]
Working on it

**Comment by ezhil56x** [comment]
@Upendra-Jaiswal 
Already raised a PR that fixes the issue

**Comment by hxdy-1** [comment]
This issue has already been reported and got PRs to fix it: #580
Hence this is a **duplicate**
