### ISSUE TITLE
Radix DropDownMenu Adds Additional Margin/Padding on the body causing layout shift

### ISSUE THREAD

**Issue by Lokendra-sinh** [code100x/cms#62]
## Description: 

Toggling the theme provider component results into additional margin/padding on the document/body causing layout shift.

## Steps to reproduce:

(1) Visit https://app.100xdevs.com/
(2) Toggle the theme 

## Actual Behaviour: shifts the entire app layout resulting into bad user experience

[RadixUi_DropDown_Menu_Issue.webm](https://github.com/code100x/cms/assets/138028282/b92f1241-598a-47be-a105-eed64b22ac11)

**Comment by Lokendra-sinh** [comment]
Looks like when the dropdown menu is active it adds additional margin to the document/body to prevent scrolling.

![image](https://github.com/code100x/cms/assets/138028282/d75fe26a-afb1-40ec-96ab-6a8b9e71114d)


By introducing "modal={false}" in the DropDown root, we can force the component to not apply typical modal styling's and behaviours. This also fixes the issue.

![image](https://github.com/code100x/cms/assets/138028282/24eb3f31-5f68-4910-ac40-626ac54f4697)

**Comment by Sumit-Kumar-21** [comment]
this issue not reflect when i check from my side
