### ISSUE TITLE
bug: Comment filter isn't working

### ISSUE THREAD

**Issue by rahulpandey70** [code100x/cms#621]
**Screenshots or GIFs**

![Screenshot from 2024-05-14 10-20-36](https://github.com/code100x/cms/assets/34403988/63ddc99d-5d13-4c36-9bd4-257013b40f90)

**Comment by kethesainikhil** [comment]
are you working on it or shall I work @rahulpandey70

**Comment by rahulpandey70** [comment]
sure you can work on it @kethesainikhil

**Comment by kethesainikhil** [comment]
could you please post a video regarding same as I am unable to produce the issue in my local setup

**Comment by rahulpandey70** [comment]
I haven't setup this project locally so can't provide you video but probably in local setup you don't have comments in your db that why you're not able to produce, try to add comments manually for any videos and then most probably you will see the issue.

**Comment by kethesainikhil** [comment]
I have done all those things by adding comments as the filter is working good you just post me a video without local setup.

**Comment by hxdy-1** [comment]
Agreeing with @shivatme

**Comment by rahulpandey70** [comment]
[Screencast from 14-05-24 12:07:50 PM IST.webm](https://github.com/code100x/cms/assets/34403988/93961f00-d0c5-4e05-bcba-b7d388a31f69)
@kethesainikhil
