### ISSUE TITLE
Extra comma in package.json file

### ISSUE THREAD

**Issue by Faizan711** [code100x/cms#624]
**Describe the bug**
There is an extra comma on line number 112 of package.json which is causing "npm install" to fail while using docker-compose up command.

**To Reproduce**
1. clone repo
2. run docker-compose up

**Expected behavior**
it should run without any issues to setup the project. It does when that comma is removed.

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/101268983/5483d566-b2b4-4797-9bba-79a186ba5cfb)

**Comment by GitHoobar** [comment]
fixed in #627
