### ISSUE TITLE
bug: Extra comma in package.json and some icons not defined.

### ISSUE THREAD

**Issue by Prakhar788** [code100x/cms#626]
**Describe the bug**
In the package.json file, there's an extra comma at the end, which prevents it from running. Additionally, CourseCard.tsx contains two undefined icons, causing errors.

**To Reproduce**
1.Just Run this code locally.

**Screenshots or GIFs**
![Screenshot 2024-05-14 185416](https://github.com/code100x/cms/assets/102613412/c9333bcd-b255-4300-842c-ac7284f47ec7)
![Screenshot 2024-05-14 185758](https://github.com/code100x/cms/assets/102613412/a3f70f19-266d-40bc-bbe9-4ee8e3630d8f)

**Comment by GitHoobar** [comment]
fixed
