### ISSUE TITLE
bug: Husky Install comment is Deprecated

### ISSUE THREAD

**Issue by manishpali17** [code100x/cms#630]
**Describe the bug**
Husky Install comment is Deprecated

**To Reproduce**
1. npm intall
2. Husky Install comment is Deprecated

**Screenshots or GIFs**

![huskydepricated](https://github.com/code100x/cms/assets/129128602/f0a45831-d048-4b2b-b1d0-0af76d3b6a48)

**Comment by sagnikc395** [comment]
husky v9.0.1 now changes from husky install to husky init. 
ref: https://stackoverflow.com/questions/77897612/problem-when-trying-to-add-prettiers-git-hook-husky-install-error-install-com

**Comment by manishpali17** [comment]
Yeah now you just have to add "prepare":"husky" in package.json instead of "husky install.

**Comment by Ameerjafar** [comment]
@manishpali17 if we can change the husky version to 8.0.0 it will work

**Comment by pixelmultiplo** [comment]
Great error message /s
