### ISSUE TITLE
bug: Video options overlap the chapters

### ISSUE THREAD

**Issue by Zafeeruddin** [code100x/cms#636]
**Describe the bug**
Video options overlap the chapter when they are opened
**To Reproduce**
1. Open a video
2. select chapters

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/121102547/85f97173-6709-4775-b03b-fefaa2dde060)

**Comment by hxdy-1** [comment]
@Zafeeruddin are u seeing this normally on ur screen? or u are seeing this when we inspect to check responsiveness?

**Comment by Zafeeruddin** [comment]
Happens on big screen(Monitor), works fine for my laptop which has relatively small screen

**Comment by hxdy-1** [comment]
> Happens on big screen(Monitor), works fine for my laptop which has relatively small screen

it shouldn't be happening on big screens, for me i can see the issue when i go below 1170px
