### ISSUE TITLE
bug: When refreshing the page the video is starting from beginning 

### ISSUE THREAD

**Issue by ramnaresh8** [code100x/cms#637]
**Describe the bug**

Video is not continuing from where it left and starting from beginning every time the page refresh

**Expected behavior**
It should remember watch history and start from where it left.

**Comment by ramnaresh8** [comment]
check for the week 7.1 I think it is with particular video,

**Comment by vidit-od** [comment]
Refer to issue #623 . There is some issue with the progress saving logic. 2 PR's already open on that issue. Should ideally solve this problem as well

**Comment by akshathere** [comment]
hey @vidit-od if issue still there can I work on this?

**Comment by Mohit-5500** [comment]
Video is starting from where it was left.The issues is resolved
