### ISSUE TITLE
bug: When opening the sidebar on the website, the main content area unexpectedly shrinks

### ISSUE THREAD

**Issue by Raj-Thombare** [code100x/cms#644]
**Describe the bug**
When opening the sidebar on the website, the main content area unexpectedly shrinks, causing a disruption in the layout and usability of the page.

**To Reproduce**

1.Navigate to the page where the sidebar is present.
2.Open the sidebar by clicking on the corresponding toggle button or action.
3.Observe that the main content area reduces in size or is compressed.
4.Close the sidebar to return to the normal layout.

**Expected behavior**
When opening the sidebar, the main content area should remain unaffected in size and layout. The sidebar should overlay on top of the content without causing any resizing or compression of the main content area.

**Screenshots or GIFs**
what it looks like:
![Screenshot 2024-05-15 215916](https://github.com/code100x/cms/assets/86057670/cfdb4685-c013-44a6-a442-d18b181123f2)

how it should look:
![Screenshot 2024-05-15 220034](https://github.com/code100x/cms/assets/86057670/20eec042-0ab5-4815-a9c0-f66780e509d4)

**Comment by harpreetsinghsandhu021** [comment]
hey @Raj-Thombare I think just adding 
`max-sm:fixed max-sm:z-10` to sidebar.tsx at line 162 will do this. It works well on my local. can I be assigned this issue

**Comment by hxdy-1** [comment]
hey @harpreetsinghsandhu021 and @Raj-Thombare , This issue has already been reported here: #607 and maybe fixed by: #612

**Comment by Raj-Thombare** [comment]
ok then im closing it
