### ISSUE TITLE
bug: Mark as Completed is not working

### ISSUE THREAD

**Issue by dev13-suthar** [code100x/cms#654]
When i click on Mark as Completed it not marking my video completion..

error in network tab: error: 
"[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"object\",\n    \"received\": \"promise\",\n    \"path\": [],\n    \"message\": \"Expected object, received promise\"\n  }\n]"

![Screenshot 2024-05-17 100635](https://github.com/code100x/cms/assets/83634894/dfe75d9b-3541-4330-b866-facce5e3de28)
[](url)

**Comment by safdarkb** [comment]
still not working
