### ISSUE TITLE
bug: Questions are not getting sorted in QnA section

### ISSUE THREAD

**Issue by hxdy-1** [code100x/cms#656]
**Describe the bug**
Questions listed in QnA section are not getting sorted despite the selected sorting option

**To Reproduce**
1. Got to "/questions"
2. Try to sort the questions
3. See the bug

**Expected behavior**
All the questions should be getting sorted as they are intended to based on available options

**Screenshots or GIFs**
https://github.com/code100x/cms/assets/115286446/e33ac491-2411-45cd-a55c-5737ba1c6c97

**Info (please complete the following information):**
 - Browser [Chrome]
 - Version [Latest]

**Comment by dishak** [comment]
@hxdy-1 , in my courses homepage i am unable to see the questions section anywhere.. but, when i type the url: https://app.100xdevs.com/questions  in the serach bar  then, it shows up. Did you face this issue too?

**Comment by hxdy-1** [comment]
@dishak yeah that's right, but it's not an issue, the QnA feature is not fully ready yet i think, that's why there's no way to go there from the UI.

**Comment by dishak** [comment]
> @dishak yeah that's right, but it's not an issue, the QnA feature is not fully ready yet i think, that's why there's no way to go there from the UI.

Also when we visit a video which has various comments below and if we try to reply to the comment it redirects to homepage have you faced it too?

**Comment by hxdy-1** [comment]
> > @dishak yeah that's right, but it's not an issue, the QnA feature is not fully ready yet i think, that's why there's no way to go there from the UI.
> 
> Also when we visit a video which has various comments below and if we try to reply to the comment it redirects to homepage have you faced it too?

Yeah, those issues are fixed by some PRs ig but they haven't been merged yet...
