### ISSUE TITLE
bug: Bookmarks seem broken

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#662]
1. All of my bookmarks seemed as marked 
2. In actuality I have only marked a few
3. They are redirecting to the wrong place

<img width="1591" alt="Screenshot 2024-05-17 at 6 15 46 PM" src="https://github.com/code100x/cms/assets/8079861/0310c164-fdd5-4161-8c01-92a0b81e00f2">
<img width="737" alt="Screenshot 2024-05-17 at 6 15 41 PM" src="https://github.com/code100x/cms/assets/8079861/691275b6-cf7e-4b6b-be35-732d8ef51a69">
<img width="1600" alt="Screenshot 2024-05-17 at 6 15 34 PM" src="https://github.com/code100x/cms/assets/8079861/c3980694-e721-4d85-9e3a-9ca976bfc7ab">

**Comment by nimit9** [comment]
This might have happened due to the change where we removed the bookmark from course.

Might need to write a script to make the changes.

**Comment by devansh-rai** [comment]
![In_hooks_useBookmark](https://github.com/code100x/cms/assets/93174679/28b59424-c15f-4734-9df9-6f726be20419)

In hooks  => useBookmark.tsx  ,  isDisabled should be "true" by default.

![in_bookmark_tsxFile](https://github.com/code100x/cms/assets/93174679/eaf1831f-ea49-4d33-a2d4-d2b35e8e59c1)

In the bookmark => BookmarkButton.tsx  file , isDisabled will be false as a result of  useBookmark hook and it will be bookmarked by default.

I think this might be the issue.

**Comment by manishpali17** [comment]
hey there,

I was actually working on this issue but I forgot to push my code. Someone fixed it, but there is still a bug in src/components/bookmark/BookmarkList.tsx. it destucting wrong id from bookmark data which is causing worng redirection issue

![bookmark error](https://github.com/code100x/cms/assets/129128602/4cfb8cfe-6a71-48c2-a677-21edfa383a41)

and  there also problem with src\db\course.ts it retiving cached bookmark which is not unique for current session 

![function](https://github.com/code100x/cms/assets/129128602/0a555079-b92e-4a29-afa6-00569212e231)

please take a look on my PR #631 @hkirat

**Comment by hkirat** [comment]
Closed via https://github.com/code100x/cms/commit/f27ef330ae93653ae7c039dce4e7059b2581b278

**Comment by manishpali17** [comment]
Cheak issue #684 @hkirat
