### ISSUE TITLE
bug:  Timestamp is not working. It redirects the user to the main page.

### ISSUE THREAD

**Issue by NawinKumarSharma** [code100x/cms#664]
Timestamps is redirecting user to the main page.

video:
[Screencast from 2024-05-17 21-57-26.webm](https://github.com/code100x/cms/assets/126372969/6d8b29a4-b160-4030-971b-e34cd81e469b)

**Expected behavior**
Timestamps should redirct to the specific part of video

**Comment by mvp5464** [comment]
fixed in #602
