### ISSUE TITLE
bug: Sidebar Highlight not working

### ISSUE THREAD

**Issue by nvenkm** [code100x/cms#671]
**Describe the bug**
The sidebar is highlighting the wrong content.

**To Reproduce**
1. Go to any video
2. Observe the sidebar, it's highlighting the wrong content or not highlighting anything

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/116103684/5713b763-aa37-4aff-b9fa-5d53c05bebd1)

**Comment by MrUnknown58** [comment]
Hey @nvenkm , are you working on this?
If not, I would like to work and fix this one...

**Comment by nvenkm** [comment]
@MrUnknown58 No, i am not working on this, feel free to work and fix this

**Comment by Pritam12F** [comment]
Works fine for me

**Comment by MrUnknown58** [comment]
Alright! I am starting to work on this..

**Comment by Pritam12F** [comment]
> Alright! I am starting to work on this..

Let me know if u wanna team up, I find it hard to test out the code cos this issue happens on some videos but works with other videos. And test db has only 1 week of content, so it's tough to verify the code

**Comment by MrUnknown58** [comment]
> Let me know if u wanna team up, I find it hard to test out the code cos this issue happens on some videos but works with other videos. And test db has only 1 week of content, so it's tough to verify the code

Alright, let's connect and check it out..

**Comment by AyushShivhare79** [comment]
@MrUnknown58 Did you figure it out?

**Comment by nvenkm** [comment]
@AyushShivhare79  checkout this PR by me https://github.com/code100x/cms/pull/396 , I solved this a while ago, but it got rejected

You can just do same and raise a PR

**Comment by AyushShivhare79** [comment]
@nvenkm Okay working on it is There any issue in your PR that i can enhance?

**Comment by MrUnknown58** [comment]
> @MrUnknown58 Did you figure it out?

I was busy with my exams and Internship projects, so didn't get the time for this..
Is it fixed, or should I check it out?
