### ISSUE TITLE
bug: In some videos you can't change the quality.

### ISSUE THREAD

**Issue by AyushShivhare79** [code100x/cms#672]
**Describe the bug**
In some videos for example week 14.3 Next.js Backend (Offline video), You can't change the quality of the video. I had seen this in some previous videos as well.

**To Reproduce**
1. Go to app.100xdevs.com and check week 14.3 Next.js Backend (Offline video).
2. Try to change the quality from 1080p to 360p or 720p.

**Comment by AyushShivhare79** [comment]
[Screencast from 18-05-24 02:39:09 PM IST.webm](https://github.com/code100x/cms/assets/132266426/90f96638-e58b-4ab6-b54b-8ce935fd614a)

This is the video

**Comment by MrUnknown58** [comment]
Hey @AyushShivhare79 , are you working on this?
If not, I would like to check this one out..

**Comment by AyushShivhare79** [comment]
@MrUnknown58  Yeah sure go ahead!

**Comment by dev-harshitsharma** [comment]
@AyushShivhare79  I guess it is not fixed yet , shall i look into this ?

**Comment by AyushShivhare79** [comment]
Yeah sure go for it @dev-harshitsharma
