### ISSUE TITLE
bug: lecture screen shows login button

### ISSUE THREAD

**Issue by Kunal-Ladhani** [code100x/cms#676]
**Describe the bug**
The lecture screen is showing login and create account buttons even after logged in. 

**To Reproduce**
1. login and move to lecture screen.

**Expected behavior**
These buttons should not be shown, instead it should show user button.

**Screenshots or GIFs**
<img width="1512" alt="Screenshot 2024-05-19 at 1 12 59 AM" src="https://github.com/code100x/cms/assets/28822285/153e9207-a6b0-4cf0-95e7-a5ff26884a19">

**Info (please complete the following information):**
 - Browser = chrome v124

**Comment by The-Saras** [comment]
its working fine for me

**Comment by rushikeshg25** [comment]
Does it still persist after refreshing ?

**Comment by Kunal-Ladhani** [comment]
Hey, it was working fine for me this morning after I updated chrome and cleared the cache, must've been something wrong with my browser. @rushikeshg25 @The-Saras
