### ISSUE TITLE
bug: bookmark redirecting to the wrong place

### ISSUE THREAD

**Issue by manishpali17** [code100x/cms#684]
**Describe the bug**
redirecting to the wrong Content ID 

**To Reproduce**
1. go to /bookmarks
2. redirection to worng url

Screenshots or GIFs

![image](https://github.com/code100x/cms/assets/129128602/b95584f7-8089-4e9e-9d4a-42e56280aca2)

possible fix

![image](https://github.com/code100x/cms/assets/129128602/e5b6fe28-7130-4f9b-acc8-7b0187441bff)

**Comment by Zafeeruddin** [comment]
Working on it..

**Comment by Zafeeruddin** [comment]
[[](url)](https://github.com/code100x/cms/pull/687)
fixed here
