### ISSUE TITLE
bug: dont see login button in incognito

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#690]
<img width="1624" alt="Screenshot 2024-05-22 at 8 54 04 AM" src="https://github.com/code100x/cms/assets/8079861/ee27a6c3-8b9f-4823-8979-6e3d8df6537e">

**Comment by Zafeeruddin** [comment]
![Screenshot 2024-05-22 110454](https://github.com/code100x/cms/assets/121102547/78126caa-b35e-47c5-8d35-29b07f785d2c)
Works fine for me in all browsers
This is a window machine

**Comment by mvp5464** [comment]
### Sir, seems working in ubuntu machine

![Screenshot](https://github.com/code100x/cms/assets/28997328/f033858a-f730-4570-ae68-f179e983e548)

**Comment by BishtAmi** [comment]
works for me in windows 
![100x](https://github.com/code100x/cms/assets/99594069/550cda68-499b-466f-896f-bcda4e784ff7)

**Comment by MrUnknown58** [comment]
Hi, @hkirat, Got the issue...
While opening in a incognito tab, there's a slight delay while loading session, and we aren't showing anything to the user during that time..
![image](https://github.com/code100x/cms/assets/91674120/6beb44d8-7378-448a-b80a-4fb2cda06315)

I am picking this up and fixing this...
Cheers :)

**Comment by hkirat** [comment]
Unable to reproduce
