### ISSUE TITLE
bug: docker-compose up not working as expected

### ISSUE THREAD

**Issue by Arnab2002Pal** [code100x/cms#696]
**Describe the bug**
The Docker build process gets stuck at the RUN npm install step when running docker-compose up.

**To Reproduce**
1. Fork  and clone the project to your local machine
2. Run the following command to start the application: docker-compose up

**Expected behavior**
The RUN npm install command should complete successfully and proceed to the next steps in the Dockerfile.

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/101279242/f6c9462e-8c72-4248-b74d-2c78a17a8ed3)

**Comment by MrUnknown58** [comment]
Hi @Arnab2002Pal , that isn't stuck, it takes some time when doing for the first time..
Paste the error if any after letting it complete
Cheers :)

**Comment by Arnab2002Pal** [comment]
if I run npm install separately its ok its done within 2-3mins but if I execute the dockor compose up command, it takes hrs to compile. so you are saying it's normal? Also you need to remove canva dependency first only then will it work.

![image](https://github.com/code100x/cms/assets/101279242/266397f3-41c2-4f1e-b76d-715e86795843)

**Comment by MrUnknown58** [comment]
Hey @Arnab2002Pal ,
Canva package was already removed from the main branch's package.json, so that shouldn't be a problem now ig.
And not sure about the npm install taking time. That usually varies depending on device's config. 
It is taking normal time at my end.

**Comment by Arnab2002Pal** [comment]
Still, check it once again,  I have recently cloned the project so there are some minor fixes in package.json
