### ISSUE TITLE
bug: Redirection of ML and Android course

### ISSUE THREAD

**Issue by Zafeeruddin** [code100x/cms#697]
**Describe the bug**
Upon clicking ML or Android course, its redirecting to harkirat.classx.co.in
**To Reproduce**

**Expected behavior**
To the course
**Screenshots or GIFs**
<img width="393" alt="image" src="https://github.com/code100x/cms/assets/121102547/6a11137c-894c-4cf2-8710-62c57d9dca8c">

**Comment by hxdy-1** [comment]
That's not an issue brother, those courses are meant to be watched on harkirat.classx.co.in !

**Comment by Zafeeruddin** [comment]
Well, Thanks. 
I thought otherwise
