### ISSUE TITLE
bug: Sort by function is not working as expected in question section under profile dropdown

### ISSUE THREAD

**Issue by Nitin6404** [code100x/cms#699]
**Describe the bug**
When user clicks on **sort by** function in questions section to render them according to the order, the function does not work properly as it works only for **Most voted Questions**

**To Reproduce**
1. Go to question section through dropdown in your profile avatar and try to display question in different order than usual by using **Sort By** button
2. You can see the **Sort By** is not working as expected 

**Expected behavior**
It should display result according to the preference of user like **Most UpVoted**, **Most DownVoted**, **Recent** etc.

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/104624489/1bed022f-cbff-4619-a1cf-8c11c3e96145)

**Comment by hxdy-1** [comment]
sup @Nitin6404 this issue is already reported here: [Click!](https://github.com/code100x/cms/issues/656)

**Comment by Nitin6404** [comment]
ok then @hxdy-1 what should we do ?

**Comment by hxdy-1** [comment]
u can close the issue @Nitin6404

**Comment by Nitin6404** [comment]
this issue is already planned raised at #656
