### ISSUE TITLE
bug: In a particular video, in comment section, clicking replies button redirect to home page.

### ISSUE THREAD

**Issue by krishna9358** [code100x/cms#700]
**Describe the bug**
Replies button in a video redirect to homepage.

**Expected behavior**
It should give a text box to reply, and also show other old replies.

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/37434769/21d15df3-4544-41ba-9bf7-3a5faac0b58b)

**Comment by 20santi** [comment]
@hkirat Can you assign it to me? Please

**Comment by mvp5464** [comment]
solved in #602
