### ISSUE TITLE
bug: On hover, few videos starts play, while others do not, (mainly in 0-1 cohort-2)

### ISSUE THREAD

**Issue by HirenGajjar** [code100x/cms#704]
**Describe the bug**

🚨 Only for desktop view 🚨 

When hovering over video files in certain folders (through the folder structure, not the sidebar), the videos play automatically. However, when you hover over video files in other folders, they do not play automatically.

**To Reproduce**

1. As front-end sims to working fine, there can be a possibility of a bug while getting the  'contentId' on hover (not quite sure)

**Expected behavior**

Either all videos should play automatically, or none should.

**Screenshots or GIFs**

Week 1 Folder Videos (where videos play automatically on Hover)
![image](https://github.com/code100x/cms/assets/40492198/10160804-7daa-48d8-a7c1-0955e6d13b8c)

Week 15 Folder videos (where videos do not play automatically on Hover)
![image](https://github.com/code100x/cms/assets/40492198/c5fa494a-412e-42a2-9c9f-d3425f4d21fe)

**Info **

 - Brave browser

**Comment by hxdy-1** [comment]
The issue u r facing is might be due to unsupported formats, the auto-play on hover only supports MP4 as of now...
Checkout some recent PRs... you'll get more context about what I'm trying to say

**Comment by hkirat** [comment]
yup a few open PRs fixing this

**Comment by HirenGajjar** [comment]
@hxdy-1 , That makes sense, as the code looks good to me As of now.
