### ISSUE TITLE
feature: Adding a rich text editor

### ISSUE THREAD

**Issue by sahilcodes-com** [code100x/cms#710]
We can add a rich text editor for writing the course description.
Just like we have it on the 100xdevs website.

![Screenshot from 2024-05-26 21-01-23](https://github.com/code100x/cms/assets/128586019/7ee54129-8315-44a6-a4f3-0cc565ff250d)

**Comment by Shashivadan** [comment]
hey. this issue is from. main [website](https://harkirat.classx.co.in/new-courses/8-live-0-100-complete) right.
as far as i know. it is not included in our cms repo....
