### ISSUE TITLE
bug: Clicking on the "Most upvotes" Or similar buttons redirects you to the home page..

### ISSUE THREAD

**Issue by Atharva-Kanherkar** [code100x/cms#712]
**Describe the bug**
As stated in the title, clicking on the button takes you to the homepage. 

**To Reproduce**
1. Click on the most upvoted button 
2. See error

**Expected behavior**
It should show you the correct thing which is intended to behave. 

**Screenshots or GIFs**
 

https://github.com/code100x/cms/assets/142440039/59f94eda-a7de-446c-96f4-4fa0829a3fc8

**Comment by mvp5464** [comment]
Fixed in PR #602 
Thanks as this issue help me in improving the pr
