### ISSUE TITLE
Clicking on comment replies redirects to the main site instead of showing replies.

### ISSUE THREAD

**Issue by 4kshi7** [code100x/cms#714]
**Describe the bug**
When clicking on the replies of a comment, the user is redirected to the main site instead of expanding the replies or navigating to the specific comment thread.

**To Reproduce**
1)Navigate to a post with comments on the 100xdevs CMS.
2)Click on the "Replies" link or button for any comment.
3)Observe that instead of expanding the replies or navigating to the comment thread, you are redirected to the main site.

**Expected behavior**
Clicking on the "Replies" link or button for a comment should either expand the replies below the comment or navigate to the specific comment thread without redirecting to the main site.
**Screenshots or GIFs**
![issue](https://github.com/code100x/cms/assets/90625345/b64f6ca7-e192-4a8e-8f79-f9306ac33e6f)

**Info (please complete the following information):**
 - Browser [e.g. chrome, safari,brave]

**Additional context**
This issue occurs consistently regardless of the post or comment being interacted with.

**Comment by mvp5464** [comment]
Fixed in PR #602

**Comment by 4kshi7** [comment]
okay
