### ISSUE TITLE
Bug: Comment Reply Redirects to 100xdevs Machine Learning + MLOps course with 'No Content to Display' Errorbug: 

### ISSUE THREAD

**Issue by TSharma30** [code100x/cms#715]
Description:

When attempting to reply to a comment on any video within the content section of the website (https://app.100xdevs.com), the page incorrectly redirects to the "100xdevs Machine Learning + MLOps" course page. Additionally, the redirected page displays a "No Content to Display" error message. This issue prevents users from engaging with comments and disrupts the user experience.

Steps to Reproduce:
1. Navigate to the content section of the website.
2. Select any video and view its comments.
3. Attempt to reply to a comment.

Expected Behavior:
Users should be able to reply to comments directly without being redirected to a different course page.

Actual Behavior:
Users are redirected to the "100xdevs Machine Learning + MLOps" course page, which shows a "No Content to Display" error.

Impact:
This bug prevents users from participating in discussions and replying to comments, which affects the overall interactivity and usability of the content section.

Environment:
- Browser: Opera GX
- OS: Windows 11
- URL: https://app.100xdevs.com

Please investigate and fix this issue to improve the user experience. Thank you.

Video
![issue2](https://github.com/code100x/cms/assets/142316441/bed13160-615a-4221-b179-337e017d9b30)

**Comment by mvp5464** [comment]
solved in PR #602
