### ISSUE TITLE
bug: certificate typo

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#720]
<img width="485" alt="Screenshot 2024-05-28 at 5 31 49 PM" src="https://github.com/code100x/cms/assets/8079861/b72950a5-12bb-4911-bc6b-d3f215330900">

**Comment by Smnthjm08** [comment]
we have to edit the public/certificate.png only right? @hkirat

**Comment by Smnthjm08** [comment]
@hkirat  can you assign it to me?

**Comment by AyushShivhare79** [comment]
Created dynamic description and fixed the typo.

![Screenshot from 2024-05-29 17-51-31](https://github.com/code100x/cms/assets/132266426/552f3f3a-354c-40b8-8f50-9b42fcce19e1)

**Comment by AyushShivhare79** [comment]
@hkirat  Can you check this ?

**Comment by Smnthjm08** [comment]
@AyushShivhare79 I'm a beginner to open source. Can you tell me how you run tests for the certificate? I tried the same way, but I couldn't get it to run.
