### ISSUE TITLE
bug: Share on LinkedIn button not visible initially on hover in light mode.

### ISSUE THREAD

**Issue by 4kshi7** [code100x/cms#722]
**Describe the bug**
The LinkedIn button in share certificate is not visible initially when hovered over in light mode, but becomes visible after hovering.

**To Reproduce**
1.  Switch to light mode.
2.  Hover over the LinkedIn button.
3.  Observe that the button is not visible initially and then becomes visible.

**Expected behavior**
The LinkedIn button should be clearly visible in light mode both before and after hovering.

**Screenshots or GIFs**
![bug-certificate](https://github.com/code100x/cms/assets/90625345/499ec7fc-6348-4176-8587-4570d083391b)

**Info (please complete the following information):**

**Additional context**
This issue affects the visibility of the LinkedIn button in light mode works fine in dark mode

**Comment by JTiscodin** [comment]
We have to remove the "bg-transparent" from the classname

**Comment by JTiscodin** [comment]
I made a pull request, can you please check if it works ? 
https://github.com/code100x/cms/pull/730

**Comment by t007rushi** [comment]
https://github.com/code100x/cms/pull/731

**Comment by 4kshi7** [comment]
#732
