### ISSUE TITLE
Control Bar Design Improvement

### ISSUE THREAD

**Issue by MohitGupta12** [code100x/cms#74]
### Proposed Changes
1. Introduce a settings icon to access video quality and playback speed options.
2. Move the progress bar above the control bar for improved visibility.
3. Apply a gradient background to enhance the control bar's aesthetics.

These changes will make a sleeker and more user-friendly control bar.

### Visuals:
**- Before Changes**
<img src="https://github.com/code100x/cms/assets/70692495/2c68fab2-a222-4e53-b563-d830bffb07e8" alt="Before Image" width="600" height="400">

**- After Changes**
<img src="https://github.com/code100x/cms/assets/70692495/682bb81b-6d4a-4708-b76e-24382bdcf6af" alt="Before Image" width="600" height="400">

### Request for Assignment :
Can I go ahead with implementing these changes? If possible, could someone (@hkirat) assign this enhancement to me?

**Comment by sahilsuman933** [comment]
Honestly, it looks pretty good. Feel free to create a PR for it. I'm confident that @hkirat  won't mind enhancing the cleanliness of the video player UI.

**Comment by sahilsuman933** [comment]
Honestly, it looks pretty good. Feel free to create a PR for it. I'm confident that @hkirat won't mind enhancing the cleanliness of the video player UI.

**Comment by MohitGupta12** [comment]
@sahilsuman933 i will start working on it 
can you assign this to me .

**Comment by sahilsuman933** [comment]
I don't have the permission to assign you! @MohitGupta12

**Comment by MohitGupta12** [comment]
@hkirat can you assign this to me

**Comment by MohitGupta12** [comment]
> I don't have the permission to assign you! @MohitGupta12

I will just start working on it

**Comment by sahilsuman933** [comment]
It seems @pankaj-2503 has already started working on it. 

// @MohitGupta12

**Comment by MohitGupta12** [comment]
he just added the color to the progress bar, that's fine I can manage the rest, thanks @pankaj-2503

**Comment by MohitGupta12** [comment]
@sahilsuman933 hey i was researching on this issue, so I found out that we were using video js for our video player and video js has various skins but nothing like youtube so should I came out with 2-3 solutions
 
- Create your control bar and hide videojs's control bar
    this will require to code functionality and style
- Overwrite videojs's control bar with our CSS 
    this would bemainly styles
    
what would be better?
