### ISSUE TITLE
feature: Script needed to migrate all videos to bunny

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#745]
We want to copy over all video data into our own systems
This would involve multiple workers running, finding a video url (720p, 360p, 240p) and copying over all the files from our current video provider to our own systems

We want to copy over files to bunny cdn - https://bunny.net/cdn/

Steps to follow
1. A script should start and pick up a video from the database, mark it `in_progres_migration` and a `migration_pickup_time`
2. It should copy over the 1080p, 720p and 360p video contents over to bunny. Video can be of type mp4 or m3u8 so we need to make sure we are actually copying over all the chunks rather than just copying over root level m3u8 file. Make sure the path is exactly the same in bunny as it was in our original video provider
3. Once everything has been copied, it should set `migrated` to `true`. 

This script will run in an autoscaling group where we will start 20 servers that should migrate all of our videos over to our own systems

Stack needed - Simple Node.js script with bunny client side APIs to upload to bunny. You will also have to write the logic to parse an m3u8

**Comment by nimit9** [comment]
Never worked on this, but trying it out

**Comment by TanmayDhobale** [comment]
Are any of video files currently using DRM or encryption? i can check it but still

**Comment by nimit9** [comment]
Done with the change:  https://github.com/nimit9/code100x-videos
