### ISSUE TITLE
bug: incorrect PDF certif being generated

### ISSUE THREAD

**Issue by HarshPatel5940** [code100x/cms#746]
**Describe the bug**
I am a part of 1-100 cohort and it tends to generate certificate for 0 - 1. Its an similar issue to #737 

I assume this is gonna get fixed it #739 , if not we can do it with #739 itself

**Expected behavior**
I should get certificate for  1 - 100 instead of 0 - 1

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/83941233/86d66f0f-5080-4c62-8d00-9606c99f5c62)

**Comment by AyushShivhare79** [comment]
@HarshPatel5940 It was resolved in #728

**Comment by HarshPatel5940** [comment]
> @HarshPatel5940 It was resolved in #728 for PNG
> For PDF it was resolved with correct credentials in #738

Mhmm, cool. Then we can close this as soon as those are merged.

**Comment by IAmRiteshKoushik** [comment]
Is this issue still open or can it be closed ? @hkirat
