### ISSUE TITLE
bug: Reply option in comments feature is not working

### ISSUE THREAD

**Issue by muthukannanmuruga** [code100x/cms#750]
**Describe the bug**
When the reply option is clicked in the comments section, its getting redirected to the landing page.

**To Reproduce**
1. Open any video under any course and scroll down.
2. You could see comments option. Add a comment under the video and click comment button. 
3. Once the comment is added, click reply option on the same comment. Once the reply button is clicked, the page gets redirected to the landing page.

**Expected behavior**
Once the reply button is clicked, a new reply comment box needs to get open under the parent comment.
The reply (child) comment need to be added under the corresponding parent (main) comment once the it is posted.

**Screenshots or GIFs**

https://github.com/code100x/cms/assets/99182229/ddffde6f-7a97-4a1d-a173-67bfcd4673a4

**Comment by muthukannanmuruga** [comment]
Im working on it.

**Comment by muthukannanmuruga** [comment]
The bug is fixed through Mk #751. Attached the video recording for reference.


https://github.com/code100x/cms/assets/99182229/4b306942-9d9b-444c-a438-f5f538ac6086

**Comment by muthukannanmuruga** [comment]
The bug is fixed through Mk #751. But still awaiting PR approval.

**Comment by ayesparshh** [comment]
can you please help me with this error please sorry for off topic question 
![Screenshot 2024-06-04 011257](https://github.com/code100x/cms/assets/96340685/d6719283-bbfa-4220-94be-65052e6a13d4)
![Screenshot 2024-06-04 011206](https://github.com/code100x/cms/assets/96340685/493f9c54-ae65-4ba7-8343-1e3f478ba697)
