### ISSUE TITLE
bug: fullscreen toggle out of bounds

### ISSUE THREAD

**Issue by siddarthpai** [code100x/cms#754]
**Describe the bug**
When browser in split screen mode, the view fullscreen button exceeds player with 

**To Reproduce**
Put the browser in split screen view and it can be noticed

**Screenshots or GIFs**
<img width="535" alt="Screenshot 2024-06-03 at 5 13 04 PM" src="https://github.com/code100x/cms/assets/63923548/afc331a2-50be-4b8a-9d01-324518637802">

**Info (please complete the following information):**
 - Browser : Brave
 - Version 1.66.115

**Comment by Mihirjataniya** [comment]
![Screenshot](https://github.com/code100x/cms/assets/120447734/c22b9524-1912-4916-a852-0efdd9bff41e)
Same thing is happening on phone as well.
