### ISSUE TITLE
feature: Convert to a monorepo 

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#755]
Make a monorepo
One app - next-frontend

Few packages
1. eslint
2. ui (can contain components)
3. common (can contain types/zod schemas)

**Comment by devsargam** [comment]
Would love to work on this

**Comment by hkirat** [comment]
@akshatarora130 go for it

**Comment by akshatarora130** [comment]
On it

**Comment by hiteshsharma-gh** [comment]
@hkirat what are your feedback on the pr
