### ISSUE TITLE
bug: sidebar css can be improved for mobile screens

### ISSUE THREAD

**Issue by ezhil56x** [code100x/cms#756]
**Describe the bug**
Improve sidebar for mobile screens

**To Reproduce**
1. Go to a course in mobile view and open sidebar

![image](https://github.com/code100x/cms/assets/103899034/439e5e3f-7387-4d95-afc8-3e171c2fad5b)

**Comment by NayanPatidar** [comment]
It would have been better if instead of making the sidebar of 100% width, you can keep it above the content on higher z-index (overlapping)
