### ISSUE TITLE
Feat:Add play/pause option on clicking video

### ISSUE THREAD

**Issue by pankaj-2503** [code100x/cms#76]
Right now if we want to play / pause video we need to go to bottom left corner to play/pause. Instead of this add this option on video hover so that user can do it easily.
---
![image](https://github.com/code100x/cms/assets/90036864/8fa71e14-9bab-40c6-8c86-57516990a446)

**Comment by shivamhwp** [comment]
@pankaj-2503 i think it works you have to click in the middle or click space. yes, there is no icon on hover.

**Comment by Adiiittt** [comment]
@pankaj-2503 Please close the issue. You can just hit left click anywhere on the screen & it plays and pauses.

**Comment by siinghd** [comment]
@pankaj-2503 Space bar should work fine or pause/play.

Issue can be closed

**Comment by pankaj-2503** [comment]
> @pankaj-2503 Space bar should work fine or pause/play.
> 
> Issue can be closed

okay i am closing this issue.
