### ISSUE TITLE
feature: Move auth to be jwt only

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#761]
We need to move off of next auth since we want to support react native
This would mean we use a simple `cookie` based auth for nextjs and `jwt based auth` for mobile apps.

Whenever the user signs in, we set the cookie on the domain for the browser. 

If the user logs in from mobile (/api/signin/mobile) , they get back a JWT that they can send in every future request to authenticate themselves.

**Comment by devsargam** [comment]
wokring on this

**Comment by hkirat** [comment]
@devsargam we're thinking of keeping next auth
And along with it introducing another endpoint that mobile can hit and get back a jwt

That way we dont have to touch the existing web code, can just expose an extra /signin/mobile endpoint for mobile

At the API route level we should update the middleware to check both next auth/authorization header
