### ISSUE TITLE
feature: Mobile app

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#762]
Create a basic mobile app that supports
1. Signin
2. User can see their purchases
3. User can see the folders and videos (if possible, notes as well but not a v1)

**Comment by ofcljaved** [comment]
On it sir

**Comment by Naveen-g09** [comment]
@hkirat we already have a repo which has all the basic configuration and stuff created by @devsargam , should we proceed on that? https://github.com/devsargam/100xdevs-mobile

**Comment by ofcljaved** [comment]
> @hkirat we already have a repo which has all the basic configuration and stuff created by @devsargam , should we proceed on that? https://github.com/devsargam/100xdevs-mobile

Yes I'm doing on top of that codebase @Naveen-g09
