### ISSUE TITLE
bug: When we hovering on the courses it getting black or blank. 

### ISSUE THREAD

**Issue by danishhansari** [code100x/cms#767]
[Screencast from 05-06-24 12:20:36 PM IST.webm](https://github.com/code100x/cms/assets/80449860/e937ea83-fe9b-46a8-bb40-5ce1f52f76d8)

**Comment by hxdy-1** [comment]
I think it was supposed to auto-play on hover. But the video format is not supported that's why it's showing blank. Also this issue is fixed somewhere... by some PR

**Comment by danishhansari** [comment]
thanks for the clarification @hxdy-1
