### ISSUE TITLE
Bug:  ML Course 'view content' button redirects to 100xdevs home page instead of content

### ISSUE THREAD

**Issue by Undisclosed64** [code100x/cms#77]
When clicking on the ML Course **View Content** button, instead of redirecting to the content of that course, it redirects us to [this](https://harkirat.classx.co.in/) page. The Android Course button also has the same issue.

Attaching screenshots for reference:

<img width="1440" alt="Screenshot 2024-02-07 at 12 56 55 PM" src="https://github.com/code100x/cms/assets/72087614/070e2b4e-c3ef-4fa5-b2ce-fcbd234703ec">
<img width="1440" alt="Screenshot 2024-02-07 at 12 57 05 PM" src="https://github.com/code100x/cms/assets/72087614/a9ca2d0b-a5a9-47da-ae8e-838e2f4a00ab">

(P.S. I'd like to work on it if approved.)

**Comment by Rash-Hit** [comment]
Please assign this issue to me ..

**Comment by siinghd** [comment]
@Undisclosed64 This isn't an issue but mostly likely intented. I think Android and ML courses are available only on https://harkirat.classx.co.in/.

can be closed

**Comment by Undisclosed64** [comment]
My bad @siinghd. You're right.
Closing it.
