### ISSUE TITLE
feature: SideBar UX Improvement request

### ISSUE THREAD

**Issue by akaashvaa** [code100x/cms#774]
<h1 align='center'>CMS</h1>

### Feature Request List

1. **Change the design**:
   - Update the visual design to be more modern and user-friendly.

2. **Remove the hamburger menu from the navigation bar**:
   - Eliminate the hamburger menu from the top navigation bar to streamline the user interface.

3. **Move the sidebar to the right side**:
   - Relocate the sidebar to the right side of the screen.
   - This will make the hamburger menu position more suitable and intuitive.

4. **Change the scrollbar style**:
   - Customize the scrollbar style to enhance the aesthetic and usability.
   
![Screenshot from 2024-06-08 20-07-51](https://github.com/code100x/cms/assets/98875003/49db4f62-e001-4d3f-88f1-bb136c25e368)
![Screens
![Screenshot from 2024-06-08 20-05-27](https://github.com/code100x/cms/assets/98875003/4baea56a-299e-40a1-ac06-9d6f86019df7)
hot from 2024-06-08 20-48-56](https://github.com/code100x/cms/assets/98875003/bd6050d6-065d-4ccd-a71c-ebd2d8bd0b71)

![Screenshot from 2024-06-08 20-24-56](https://github.com/code100x/cms/assets/98875003/d6baa31d-bf2c-4d96-8f69-3f1987fcdbec)
![Screenshot from 2024-06-08 20-05-27](https://github.com/code100x/cms/assets/98875003/35108e78-6268-4d26-bfe1-3a0922a39394)

**Comment by akaashvaa** [comment]
There will be two toggle buttons:
-  When the sidebar is open, there will be an "X" button.
-  When the sidebar is closed, there will be a hamburger menu button. This button will be positioned where the sidebar was, 
displaying the menu when the sidebar is hidden.

You can check out the fourth image for more understanding.( below profile icon)

**Comment by ShubhamGagare** [comment]
Got it. Can you assign this to me? I already went through code and have fair idea what changes need to make to match requirement

**Comment by akaashvaa** [comment]
ii'm not a maintainer.

**Comment by akaashvaa** [comment]
> # CMS
> ## Sidebar UX Improvement
> ### Feature Request List
> 1. **Change the design**:
>    
>    * Update the visual design to be more modern and user-friendly.
> 2. **Remove the hamburger menu from the navigation bar**:
>    
>    * Eliminate the hamburger menu from the top navigation bar to streamline the user interface.
> 3. **Move the sidebar to the right side**:
>    
>    * Relocate the sidebar to the right side of the screen.
>    * This will make the hamburger menu position more suitable and intuitive.
> 4. **Change the scrollbar style**:
>    
>    * Customize the scrollbar style to enhance the aesthetic and usability.
> 
> ![Screenshot from 2024-06-08 20-07-51](https://private-user-images.githubusercontent.com/98875003/337896409-49db4f62-e001-4d3f-88f1-bb136c25e368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDkxMjIsIm5iZiI6MTcyMDg0ODgyMiwicGF0aCI6Ii85ODg3NTAwMy8zMzc4OTY0MDktNDlkYjRmNjItZTAwMS00ZDNmLTg4ZjEtYmIxMzZjMjVlMzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA1MzM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMzg4YjViYWQ1OWM1MGQzZWY1OTUyYzIxNmNjYWUxMWRhY2FmMmEwZjZhMmVjMzUwNTBmNDIyMmU5Yjc2OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Fgs0Y4vxhjmRFcyu18ptg8nJDjP5GnJr-kn9TgbcM8) ![Screens Screenshot from 2024-06-08 20-05-27 hot from 2024-06-08 20-48-56](https://private-user-images.githubusercontent.com/98875003/337896722-bd6050d6-065d-4ccd-a71c-ebd2d8bd0b71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDkxMjIsIm5iZiI6MTcyMDg0ODgyMiwicGF0aCI6Ii85ODg3NTAwMy8zMzc4OTY3MjItYmQ2MDUwZDYtMDY1ZC00Y2NkLWE3MWMtZWJkMmQ4YmQwYjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA1MzM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNmM1ZTJlNDViYmIwODcyOTJlMzhhNTY1OWFmNzI1YTRkZTAwODYxN2E0N2NkY2QxMWU5ZmI4MDIzMzU1NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oMwleyM-Wc6jJLoBuJliEqDuZWHKJSKXKNDy5zlJq7k)
> 
> ![Screenshot from 2024-06-08 20-24-56](https://private-user-images.githubusercontent.com/98875003/337897437-d6baa31d-bf2c-4d96-8f69-3f1987fcdbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDkxMjIsIm5iZiI6MTcyMDg0ODgyMiwicGF0aCI6Ii85ODg3NTAwMy8zMzc4OTc0MzctZDZiYWEzMWQtYmYyYy00ZDk2LThmNjktM2YxOTg3ZmNkYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA1MzM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNDAyN2FiMTQ2OTZhODE5NjA1ZjE0NmE3MDhlOWIzOGQ2MGZkNGQyYzg5MzQ5YzcwMjhkNTY3NzUwZTlhM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rKuojQ-WbQssdVvWRA3-L5C3w0Krt_2tQ0mnuIIwCIY) ![Screenshot from 2024-06-08 20-05-27](https://private-user-images.githubusercontent.com/98875003/337898225-35108e78-6268-4d26-bfe1-3a0922a39394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDkxMjIsIm5iZiI6MTcyMDg0ODgyMiwicGF0aCI6Ii85ODg3NTAwMy8zMzc4OTgyMjUtMzUxMDhlNzgtNjI2OC00ZDI2LWJmZTEtM2EwOTIyYTM5Mzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA1MzM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MTIxMDBiNzgyYWJkNDAwODczODNlNjk0YzIwNzMyZDhiOTIyYTdhMzg3MjRlYjQzNzQ1OTk1ZTUwMzA4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eDcXlfi5IdRGw-3TC2Z9YJ50W0JwJI--GdvXjwwOm_8)

#825 PR
