### ISSUE TITLE
bug: In the comment sections of every video the ending word of a line gets splits into parts 

### ISSUE THREAD

**Issue by dishant440** [code100x/cms#801]
**Describe the bug**
The bug i think is in the comment sections of every video I saw this in week 14.3 video of nextjs backend (offline) video in the comment section of the video, in the specific comment when the line ends with a word  for example "accordingly" the last word gets splits into two parts  "Acco" and the next line starts with the remaining "rdingly" and the line coninues

**To Reproduce**
Go to week14 video 14.3 Nextjs backend offline and see the comment section 
![Screenshot (100)](https://github.com/code100x/cms/assets/127651650/a738b3d1-de94-4567-89c7-4538d9db49c6)
![Screenshot (101)](https://github.com/code100x/cms/assets/127651650/c5f9c7d3-e59a-4f07-9856-115c18a12be3)
![Screenshot (103)](https://github.com/code100x/cms/assets/127651650/d22a4f50-fe6b-4987-a228-975997ba609d)

**Expected behavior**
If the comment is exceeding the width of the comment section it should not split the last words of the line

**Comment by JTiscodin** [comment]
![image](https://github.com/code100x/cms/assets/113091818/098182b0-ccc8-4dc4-ac07-95268a7ae07d)


In TimeCodeComments.tsx component, the break-all should not be there, because the split is doing it's job to break the string accordingly, removing "break-all" from className  solves the problem.

Raising a PR for this

**Comment by 4kshi7** [comment]
I tried the same thing but it added a horizontal scrollbar on long comments for me. Is this the case for you as well? its kinda ugly tho

**Comment by JTiscodin** [comment]
@4kshi7, I didn't see any such thing, in the code, we are splitting the string, based on "\n", so I don't think, a scrollbar should appear. In the PR that I linked, I posted the photo after the changes, it seems right to me, can you see the screen shot and let me know how can I recreate the issue ?

**Comment by 4kshi7** [comment]
@JTiscodin ah I didnt see the images you provided on the pr, yeah you have done it right
