### ISSUE TITLE
Let user add a DP

### ISSUE THREAD

**Issue by vverma022** [code100x/cms#802]
To make the website a little more appealing we can give the users an option to add a profile picture. 
<img width="239" alt="Screenshot 2024-06-26 at 12 16 55 PM" src="https://github.com/code100x/cms/assets/109036913/c14181e0-97ba-442b-9e01-db3c65cb6854">

**Comment by Sigma2345** [comment]
One approach that I would like to use is designing an option to edit DP inside the dropdown. On clicking that a modal would appear allowing user to add a photo. The photo would be stored inside the DB as binary data. We can use react-modal for the modal. 

![image](https://github.com/code100x/cms/assets/95545310/828bfeef-c0eb-42a6-9512-fc7615e6ab95)

A rough design of the modal would be like above

**Comment by JTiscodin** [comment]
Shouldn't we use AWS S3 for storing it ? Instead of storing it in DB @Sigma2345

**Comment by Sigma2345** [comment]
Yeah @JTiscodin S3 would be better. Would be doing that instead

**Comment by pantharshit007** [comment]
@Sigma2345 for by default you can use this API which automatically will create you a user dp based on his/her initals
like: `https://api.dicebear.com/5.x/initials/svg?seed=harshit%20pant`
will generate
![image](https://github.com/code100x/cms/assets/97608579/a1caaecc-d21e-45ac-91ad-222d90a5f8b8)
