### ISSUE TITLE
bug:  Android and ML course redirects to harkirat.classx.co.in

### ISSUE THREAD

**Issue by shauryaa19** [code100x/cms#805]
Clicking on "View Content" button or Card of the Android and ML course redirects to harkirat.classx.co.in even if the user is signed in and has the access to the course. All other cards of courses are working fine.

**Comment by hxdy-1** [comment]
Yeah, they're meant to be watched only on classx as of now

**Comment by shauryaa19** [comment]
> Yeah, they're meant to be watched only on classx as of now

Oh, Got it!
