### ISSUE TITLE
feature: Adding a next button for watching the next video in the thread.

### ISSUE THREAD

**Issue by akshathere** [code100x/cms#811]
**Problem description**
I'm always frustrated whenever I finish watching a video I always search for the next button so that I can jump over to  video in the order. For eg :
      If I am on 3.1 video, a button which on click takes us to 3.2 will be very helpful to make it more userfriendly.
Also 
![image](https://github.com/code100x/cms/assets/106247875/e48d793d-6ac8-41aa-a6df-19e7f508a819)
I am watching this video the side bar does not shows which week or video is selected. This feature will help tackle that problem as well

***Solution***
A solution can be linking the videos with each other (maybe use doubly linked list which can have prev and next as well . We can add a prev link as well (maybe not needed) but can add that as well.
All the video be sorted week wise and contains a prev button to go to prev video i.e if you are on video 8.2 prev will take you to 8.1
and A next link which takes us to 8.3 .

**Comment by SargunSinghSethi** [comment]
working on this

**Comment by shantanuSakpal** [comment]
@hkirat @devsargam upon inspection, i found there was already a function getNextVideo. i wonder why it wasnt used?
