### ISSUE TITLE
bug: going back in any of the MLOps cohort redirects back to all contents, instead of showing the previous menu

### ISSUE THREAD

**Issue by vihaan-that** [code100x/cms#815]
**Describe the bug**
 It is inconvinient to use the MLOps cohort, as the site navigation is broken. when I go to listen to any lecture within any subtopic, pressing back doesn't redirect to the previous menu listing the subtopics, but rather the total cohort topics.

**To Reproduce**
1. Listen to any Mlops cohort lecture
2. go back to the previous menu.

**Info** 
 - Browser - all

**Comment by shantanuSakpal** [comment]
Unfortunately, android cohort and ml ops cohort are currently accessible on a third party platform , classx.co.in, so we cannot do anything about this. This repo is for https://app.100xdevs.com/.
