### ISSUE TITLE
bug: missing vimium extension button

### ISSUE THREAD

**Issue by AuenKr** [code100x/cms#817]
**Describe the bug**

Missing Vimium buttons
1. On Subfolder of each course
2. On Profile dropdown menu
3. Bookmark Button on svg

**To Reproduce**
1. Install vimium extension
2. Goto `/courses/*`
    eg: `https://app.100xdevs.com/courses/4`

**Expected behavior**
Vimium button should present 

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/103646877/e268f261-53c3-4075-aa34-4373114b51a5)

**Comment by AuenKr** [comment]
Working on it

**Comment by shantanuSakpal** [comment]
its cause vimium only add keys on certain tags like input, button, a , etc.. however, the components you mentioned are divs and svgs, so ,
On Subfolder of each course : its a div, try changing it to button
On Profile dropdown menu: its an svg, wrapped by a div, change the wrapper to button
Bookmark Button on svg: wrap it around a button

this should solve it.

**Comment by AuenKr** [comment]
> its cause vimium only add keys on certain tags like input, button, a , etc.. however, the components you mentioned are divs and svgs, so , On Subfolder of each course : its a div, try changing it to button On Profile dropdown menu: its an svg, wrapped by a div, change the wrapper to button Bookmark Button on svg: wrap it around a button
> 
> this should solve it.

You can add button in className of div component that also work 
[refrence](https://stackoverflow.com/questions/53918093/how-can-i-make-my-element-clickable-for-vimium)

Already fixed it in the PR
