### ISSUE TITLE
bug:  Installation error via docker

### ISSUE THREAD

**Issue by pantharshit007** [code100x/cms#822]
**Describe the bug**
I was trying to set the project locally as per the readme instruction via docker when I did `docker-compose up` everything ran fine but it got stuck at the `RUN npm install` command. I tried googling the error and was able to figure out the problem but don't know how to fix this.

**To Reproduce**
1. follow set up instruction using docker
2. I am getting error because of mis match react version I am guessing

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/97608579/c5e580c9-d296-49c2-90c1-ba78a3ff0c31).

![image](https://github.com/code100x/cms/assets/97608579/112bc684-a1eb-44bf-9492-901a5d98f396)

**Comment by dishant440** [comment]
when you run docker-compose up command when it reaches the step [5/6] RUN npm install open a new terminal in your vs code and run "npm install " from the parent directory

**Comment by dishant440** [comment]
@pantharshit007 when you run docker-compose up command when it reaches the step [5/6] RUN npm install open a new terminal in your vs code and run "npm install " in the parent directory

**Comment by pantharshit007** [comment]
@dishant440 I tried docker-compose up again and this time it said due to a lower node version error occurring so I updated my node and npm. Prisma started working at localhost:5555 but 3000 didn't work so I restarted the terminal and tried again but this time in between seeding it got stuck on this error:

![image](https://github.com/code100x/cms/assets/97608579/22d75662-86f6-468c-8451-8ae1e5029164)

and even though the container is running localhost:3000 is loading and loading

**Comment by dishant440** [comment]
@pantharshit007 yesterday i faced the same error  just kill all the containers running and delete all the images present using the docker desktop application and retry all the steps used to setup the project locally it will work...

**Comment by DipakKhade** [comment]
after rerunning it probabaly works but if it did not fix by any reason you can try last option i.e replace RUN npm install with 
RUN npm install --legacy-peer-deps
