### ISSUE TITLE
bug: sidebar navigation breaking the ui in mobile view

### ISSUE THREAD

**Issue by dishant440** [code100x/cms#823]
When sidebar nav is opened the course content in the background get squeezed 

**To Reproduce**
1. Go to the view content of your purchased course eg 0-1
2. In mobile view open the sidebar navigation 

**Expected behavior**

When the sidebar nav is opened on clicking the hamburger icon it should overlap the content beside it instead of squeezing it.

![Screenshot (112)](https://github.com/code100x/cms/assets/127651650/95f3fa0a-d7ea-4310-9d05-347b6dc2162a)

**Comment by NayanPatidar** [comment]
Already Fixed in #809
