### ISSUE TITLE
feature:  Changing UI

### ISSUE THREAD

**Issue by zakiabdullahi** [code100x/cms#824]
To Look UI  better I   i thought what if  we need to change   the  default  **scrollbar**,**profileIcon** and **Course Folders View**  a little bit

<img width="956" alt="ss-2" src="https://github.com/user-attachments/assets/b72319aa-af15-4a55-8ba5-9ead932b70cc">
<img width="960" alt="ss-3" src="https://github.com/user-attachments/assets/e9e0a479-8422-447f-9ee1-ff8fc208305c">
<img width="960" alt="ss-5" src="https://github.com/user-attachments/assets/ca755b0c-32a4-443d-8288-ee0acb2380a4">

**Comment by sahilsheikh-dev** [comment]
I can design UIUX for this section!

**Comment by zakiabdullahi** [comment]
@sahilsheikh-dev thanks for your feedback bro i just tried, then I decided to work and change

**Comment by somkumar-CT** [comment]
> I can design UIUX for this section! edit: working on it! redesigning this section.

where can i see your designs

**Comment by sahilsheikh-dev** [comment]
> > I can design UIUX for this section! edit: working on it! redesigning this section.
> 
> where can i see your designs

I have designed these cards, but I am unsure if it is good!
![Group 8](https://github.com/user-attachments/assets/a4f1edd4-8423-4fcb-a177-fc97774160ba)

**Comment by riturajreal** [comment]
I think you should the current theme of website in this content card

**Comment by sahilsheikh-dev** [comment]
this looks good, but what if we replace the image with the course image? live below or something similar?
![image](https://github.com/user-attachments/assets/9fdbe350-a11f-4aee-8e1e-7a2e18c9b9f3)

**Comment by riturajreal** [comment]
Yaa we can also create a similar card for courses
