### ISSUE TITLE
feature: calendar view

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#845]
harkirat can you provide us a calender made in notion which will be having all the classes mentioned with topics to be coverd in them so that we can manage and note our progress in the cohort?

**Comment by XTurbo07** [comment]
How can i get the topics?

**Comment by hkirat** [comment]
They'll be in the DB in the CourseContent table.
We already have a sidebar, we just need a different view for it

**Comment by ameeetgaikwad** [comment]
Got it! 
Can i work on this @hkirat ?

I'll be using `react-big-calendar` and `date-fns` as the main dependencies. Using the data in the db.

**Comment by Pritam12F** [comment]
Can I work on this @hkirat ?
I'll be using [https://www.npmjs.com/package/@fullcalendar/react](url)

**Comment by Smnthjm08** [comment]
is this issue still open to work??
