### ISSUE TITLE
bug: Sidebar navigation not working properly.

### ISSUE THREAD

**Issue by Roshanbhadauriya** [code100x/cms#847]
**Describe the bug**
When you open the course and try navigating through the sidebar, the moment you click it, it will redirect you to the homepage.

**To Reproduce**
1. Open course (https://app.100xdevs.com/)
2. click on any lecture from sidebar

**Expected behavior**
open the video

**Screenshots or GIFs**
https://github.com/user-attachments/assets/1eae636b-c7e8-4e4e-ab21-5a2edf29beb7

**Info (please complete the following information):**
 - chrome
 - Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by codenchantress** [comment]
works for me, check again and revert please

**Comment by vikas-chaudhari** [comment]
It works fine for me.

**Comment by Devam433** [comment]
Works fine for me.

**Comment by Roshanbhadauriya** [comment]
Now it is working fine . It has not been working for the last two days.

**Comment by nischal-shetty2** [comment]
@Roshanbhadauriya @siinghd close this issue
