### ISSUE TITLE
bug: Some additional courses are not displaying in the courses app

### ISSUE THREAD

**Issue by Shashivadan** [code100x/cms#849]
# Course App Issue Report

## Describe the bug
Some additional courses are not displaying.

## To Reproduce
1. Open the cms app
3. Observe that some expected additional courses are missing

## Expected behavior
All additional courses should be visible and accessible.

## Screenshots or GIFs
![Screenshot from 2024-08-04 09-15-44](https://github.com/user-attachments/assets/4787e377-9cd2-464e-b792-4ba2392d5dfb)

**Comment by NumanFaisal** [comment]
Can we do this considering it is a good first issue? I am new and there is no good first issue present in this repository
