### ISSUE TITLE
bug: Scroll bar appears on the x-axis when hovering over the 3D card

### ISSUE THREAD

**Issue by Fardeen26** [code100x/cms#853]
**Describe the bug**
When hovering over the 3D card on the home page of [app.100xdevs](https://app.100xdevs.com/), a scroll bar appears on the x-axis of the page. This issue occurs due to the overflow property not being correctly handled.

**To Reproduce**
1. Go to the app.100xdevs.com website.
2. Hover over second 3D card .
3. Observe the scroll bar appearing on the x-axis.

**Expected behavior**
No scroll bar should appear when hovering over that 3D card.

**Screenshots or GIFs**
https://github.com/user-attachments/assets/49f3fadf-2d31-4cbd-bec7-01932e9d71d6

**Info (please complete the following information):**
 - Browser: Chrome
 - Version : 127.0.6533.89

**Additional context**
I already adjusted the styling properties to prevent overflow, ensuring that no scroll bar appears when hovering over that 3D card.

**Comment by Dishantydv7** [comment]
Hey @Fardeen26 , this issue still persists. U too stated that you adjusted the overflow property . If it isn't resolved . Can i have a look onto it ?

**Comment by Fardeen26** [comment]
hey @Dishantydv7, The pull request I created to address this issue hasn't been merged yet; it's currently under review.
