### ISSUE TITLE
feature: Cinema Mode in the video player

### ISSUE THREAD

**Issue by skyyycodes** [code100x/cms#858]
When I'm splitting screen and using VS Code + app.100xdevs.com, the video becomes so small this issue can be solved by introducing a feature like 'Cinema mode'.

What is Cinema mode?
- Open any YouTube video and press 't' or Check the button 2nd last button.

- I would like to work on it.
![cinema_mode](https://github.com/user-attachments/assets/891cb383-61fb-4f2b-b22e-2a04374209e6)

**Comment by Kesarrudr** [comment]
still working on this ?

**Comment by skyyycodes** [comment]
> still working on this ?

Yes
