### ISSUE TITLE
Video playing speed automatically get set to 1x when the quality of the video is changed on  100x devs site

### ISSUE THREAD

**Issue by akshathere** [code100x/cms#86]
It is like if your video is selected to run at any faster speed take it as 1.5x for example then if we change the video quality of the video then the video automatically switches to 1x but still showing 1.5x .

**Comment by joshihemal** [comment]
@akshathere are you using any extensions i was facing similar issue when i was using video speed controller extension please check

**Comment by akshathere** [comment]
@joshihemal No I'm not using any extensions

**Comment by prateeksingh19** [comment]
@hkirat this seems to be an active issue to date ( noone has fixed it yet ), i can work on it
