### ISSUE TITLE
bug: signing in toast pops up without entering email and password

### ISSUE THREAD

**Issue by rushikeshg25** [code100x/cms#861]
**Describe the bug**

When u press signin without the email and pass, the signing in toast pops up

**To Reproduce**
1. Login without the email and password

**Expected behavior**
Login Button should be disabled if user has not entered anything in email and password

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/771215c3-e031-46d6-a9ec-944b417f6932)

**Comment by akash-R-A-J** [comment]
but the bug still is not resolved, you can verify it here
![image](https://github.com/user-attachments/assets/d41ba06d-fc0b-4255-90a9-c4f92c93a1ea)

I have raised a PR regarding this after fixing the respective error.

**Comment by akash-R-A-J** [comment]
@siinghd can you merge this code?

**Comment by rushikeshg25** [comment]
@akash-R-A-J it's fixed bruh. U can't press the login button whenever the user has left at least one of the two fields empty, I verified it myself. Did you verify on prod? because that branch is different

**Comment by akash-R-A-J** [comment]
yeah I verified it on prod and is still displaying the error

**Comment by rushikeshg25** [comment]
@akash-R-A-J welcome to Open-source bro, Only the fastest people last here. I don't want to discredit nor am I a false developer. Better luck next time
