### ISSUE TITLE
feature: Connect the question to the video (High priority - valuable bounty) 

### ISSUE THREAD

**Issue by siinghd** [code100x/cms#862]
We already have a platform for questions at [100xdevs](https://app.100xdevs.com/questions), but it is currently underutilized.

To increase engagement, I propose connecting questions to specific videos. Here's a plan for implementation, which can be further improved for a better outcome:

### Proposed Features:

1. **Linking Questions to Videos**:
    - When creating a question, users should have the option to link it to a specific video.
    - Users can either search for a video or select one from a searchable dropdown menu. 
    - This feature should be optional, as we still want to allow questions without associated videos.

2. **Video Integration**:
    - Each video should have a button that, when clicked, redirects the user to all questions related to that video.

3. **Database Changes**:
    - Add an optional `video_id` field to the question table to store the associated video ID.

4. **Future Improvements (V2)**:
    - Implement notifications to a specific Discord channel when a new question is created.

---

Note: These are initial thoughts, and any further improvements are welcome! (do not limit to only initial thoughts!)

**Comment by Sajal0208** [comment]
taking this up

**Comment by krishna9358** [comment]
@siinghd can work on it.

**Comment by sand-storm-17** [comment]
@siinghd working on it, will create a PR. Do I need to provide video proof in pull request ?

**Comment by krishna9358** [comment]
@sand-storm-17 hii, I am already working on it. Thanks!

**Comment by Sajal0208** [comment]
@krishna9358 @sand-storm-17 even I am working on it.

**Comment by sand-storm-17** [comment]
@krishna9358 @Sajal0208 okay you guys work on it. I'll start on it if there is no pull request by tomorrow.

**Comment by iSouvikKhan** [comment]
![image](https://github.com/user-attachments/assets/4425160b-4db9-407d-9983-03c10a46b8f8)


getting this error upon committing
can anyone tell me how can i resolve this ??
i did husky uninstall -> install no luck

**Comment by krishna9358** [comment]
@iSouvikKhan if it's coming while installing the packages, then install forcefully. npm install --force....
some packages are depricated !

**Comment by iSouvikKhan** [comment]
Hi @krishna9358, it is coming when I click on the commit button in vs code

**Comment by siinghd** [comment]
The better PR will get merged only, make sure to not work quickly and push it just for the sake of time...i will review all and choose the better solution.

**Comment by iSouvikKhan** [comment]
Hi @siinghd, could you please help me in the Git: husky issue.

**Comment by iSouvikKhan** [comment]
Hi @krishna9358, resolved the issue using `--no-verify` flag while committing in terminal

**Comment by shaurya35** [comment]
@siinghd 
still open for new PRs?

**Comment by shaurya35** [comment]
@devsargam please review #1340 
Tried to implement most out of least code possible.
Open for improvements

**Comment by avparadox** [comment]
@devsargam i guess this can be closed too.
