### ISSUE TITLE
feature: Live class zoom link should be available on the dashboard.

### ISSUE THREAD

**Issue by Misal-Ambasta** [code100x/cms#868]
**Problem**
Lots of people don't receive emails of the zoom live class link on their respective emails. If its available on dashboard, It will be access to all of them even if they didn't receive on their respective mail.

**Solution**
A zoom link should be visible on the dashboard when live class going to takes place on that particular day.

**Additional addon**
 Will also get notification when class link added on the dashboard can also be mark as read and unread.

**Comment by devsargam** [comment]
I agree nice feature 👌

**Comment by Sajal0208** [comment]
@Misal-Ambasta @devsargam Any suggestions on how we can implement this? I can work on the same.

Ways which I can think of is: 
1) Discord Maintainer who sends the link in discord can also update it in the website manually. 
2) A Discord bot which can read zoom links from discord when the maintainer sends it and then we can implement a webhook to update it on the site.

First one is easier but manual. And the second one is way cooler :p

**Comment by devsargam** [comment]
2nd one is the best as we can automate 

Can add both! But 1st one is viable as we don't have a discord bot rn

**Comment by DraKen0009** [comment]
@devsargam  creating one won't take much time. And having a custom bot for our server is a cool idea that we can work upon?

**Comment by devsargam** [comment]
Yeah we are working on a discord bot. https://github.com/VineeTagarwaL-code/100xdev-discord-bot/

**Comment by DraKen0009** [comment]
oh great! @devsargam  is it open to contribute?

**Comment by devsargam** [comment]
@DraKen0009 yeah after a basic one is built

**Comment by Misal-Ambasta** [comment]
>You can build the basic form for the starting. The format will be similar as we receive in emails.
1. Title
2. Description(optional)
3. Date & Time
4. Zoom link
5. Webinar ID(optional)
6. Who will take the class (dropdown)
