### ISSUE TITLE
bug: Video Resizing Problem on Window Resize

### ISSUE THREAD

**Issue by akash-R-A-J** [code100x/cms#871]
**Describe the bug**
When the browser window is resized to a smaller width (e.g., when splitting the screen with another application), the video player does not maintain a proportional size. Instead, the video shrinks significantly, making it difficult to view. This issue occurs when the webpage is reduced to half the screen size. The video element should scale down proportionally while maintaining a reasonable viewable size.

**To Reproduce**
Steps to Reproduce:
1. Open the webpage with the video in a full-screen browser window.
2. Resize the browser window to half of the screen width.
3. Observe the size of the video player.

**Expected behavior**
The video should resize proportionally to the window size, maintaining a reasonable viewing area even when the browser window is reduced in size.

**Screenshots or GIFs**
![flexible-video](https://github.com/user-attachments/assets/ffa06392-ddcb-4a77-83a3-5af2ce4155fa)

**Info (please complete the following information):**
 - Browser: Chrome (and possibly in others too)

**Comment by akash-R-A-J** [comment]
I just opened it because I found there is a need for improvement here, if anyone wants to work on it then please go on, it's completely fine. @anudeeps352 @Shubhamxshah

**Comment by sundaramsharma** [comment]
You may click the 'X' icon so that the sidebar will be closed and video will get to full size

**Comment by sundaramsharma** [comment]
https://github.com/user-attachments/assets/68c0ac72-aa61-467f-aab0-41e70a2e760d

Here's the video for the mentioned bug

**Comment by akash-R-A-J** [comment]
yes, I see my bad, I was irritated so much back then. Thanks though!
