### ISSUE TITLE
bug: Sign in page problem in https://app.100xdevs.com/signin

### ISSUE THREAD

**Issue by TarunVishwakarma1** [code100x/cms#872]
**Describe the bug**
When you visit the signin page of 100xdevs URL: https://app.100xdevs.com/signin, you get a modal where you fill the credentials to log into the site, but if you dont fill the credentials or fill only one of the field and click on login button, on the bottom right corner of the screen the you get the message saying 'signing in...' with a loader icon.

**To Reproduce**
1. visit the home page of 100xdevs URL: https://app.100xdevs.com
2. click on the Login button on top right corner.
3. Without filling the fields or filling only one field click on login button below.
4. A error on the fields will be generated and a message saying 'signing in..' with loader will come

**Expected behavior**
only the error on the fields should be there without the signing in message

**Screenshots or GIFs**
Screenshot with none of the field filled with message.
![100xDevSiginPageBug](https://github.com/user-attachments/assets/9b3f68cb-9617-40a1-af9f-d5154cc67685)

**Info (please complete the following information):**
 - Browser [opera GX, Microsoft Edge]

**Additional context**
The user can safely log in if the credentials are correct or an error will pop up if the credentials are not correct which is expected.

**Comment by iSouvikKhan** [comment]
Hi @TarunVishwakarma1, it has been fixed in this PR - #870

**Comment by Arjun149133** [comment]
Is this Issue already solved? because in localhost the login button is disabled when the required fields are not filled, but in production app - https://app.100xdevs.com/signin  the login button is active even when the fields are empty.

**Comment by TarunVishwakarma1** [comment]
Sure Closing the issue
