### ISSUE TITLE
feature: Add a section where user can add their payout method

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#873]
A place where user can come and add their
1. upi
2. solana address

**Comment by Pritam12F** [comment]
I will take this up

**Comment by Pritam12F** [comment]
@hkirat this is for the bounties right? should i just add a section can come and add their upi and sol address and can select one as default which will be used during payouts?

**Comment by chiragcj27** [comment]
How would that page or stored payment info be sent to the classx website where the actual payment takes place???

**Comment by thrishank** [comment]
Hey @hkirat  if this is for the bounty distribution then we need a /admin/bounty page where you can enter the GitHub username and get their payment details. Can I work on this @hkirat
