### ISSUE TITLE
feature: Write a script that constantly polls the DB and adds subtitles to videos 

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#875]
<img width="1157" alt="Screenshot 2024-08-11 at 6 56 42 PM" src="https://github.com/user-attachments/assets/6fd3591e-8ec5-43e3-b43e-e53510f76637">

It needs to get a video without subtitles
Download the video
Transcode it to mp4
convert it to mp3
use Whisper to generate subs
Upload the subs to bunny
Add an entry to `subtitles` fields in the VideoMetadata table

**Comment by Pritam12F** [comment]
Working on this

**Comment by Pritam12F** [comment]
@hkirat What are the formats of these videos and which one should i download to get good audio quality but also save on the download size?

**Comment by iSouvikKhan** [comment]
Hi @Pritam12F,
Are you planning to download the video when it is added or somewhere else ??
I have gone through the code, metadata is implemented, if it has the bunny url then button will be visible in video
For testing I created a .srt file, uploaded in a free cdn, placed the url in the VideoMetadata table still caption did not come on the video
Could you please tell me what did I do wrong ??

**Comment by SujithThirumalaisamy** [comment]
> @hkirat What are the formats of these videos and which one should i download to get good audio quality but also save on the download size?

Actually you dont want to download the .mp4 you can directly get the .mp3 from the url of a video

**Comment by Pritam12F** [comment]
> Hi @Pritam12F, Are you planning to download the video when it is added or somewhere else ?? I have gone through the code, metadata is implemented, if it has the bunny url then button will be visible in video For testing I created a .srt file, uploaded in a free cdn, placed the url in the VideoMetadata table still caption did not come on the video Could you please tell me what did I do wrong ??

I am just going through the codebase now I am gonna let you know soon

**Comment by Pritam12F** [comment]
> > @hkirat What are the formats of these videos and which one should i download to get good audio quality but also save on the download size?
> 
> Actually you dont want to download the .mp4 you can directly get the .mp3 from the url of a video

How so? Where can I find the mp3's link?

**Comment by iSouvikKhan** [comment]
@Pritam12F 

mp3 links are stored in VideoMetadata table
the point being,
- we need to get the subtitles
- store it in a .srt file,
- upload the file in the bunny cdn
- get the cdn link and store that in the `subtitle`  column of VideoMetadata table

rest otherthings are already set up
the trickiest part is getting the subtitles which I am unable to figure out

**Comment by Pritam12F** [comment]
@iSouvikKhan I don't see any field for the mp3 link in the videoMetadata table. Unless I am missing something. Do you mean the mp4 links are already present so we can skip the step of transcoding the video?

**Comment by SujithThirumalaisamy** [comment]
Let me give a small context here. You will have multiple trancoded video urls there. Get one video. Download it. Get the .mp3 from the file. Submit it to Whisper AI. Get the subtitles. Parse it to SRT format. Then put it into bunny.

**Comment by Pritam12F** [comment]
Okay yeah that makes sense @SujithThirumalaisamy

**Comment by SujithThirumalaisamy** [comment]
- [x] Done Ref: https://github.com/SujithThirumalaisamy/100x-subtitles

**Comment by iSouvikKhan** [comment]
@SujithThirumalaisamy 

Page not found

**Comment by SujithThirumalaisamy** [comment]
> @SujithThirumalaisamy 
> 
> 
> 
> Page not found

Private for now.
