### ISSUE TITLE
bug: pin functionality is not working

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#877]
<img width="696" alt="Screenshot 2024-08-12 at 7 02 58 AM" src="https://github.com/user-attachments/assets/db48d221-0c26-48a0-8c50-f841e376332c">

**Comment by amanbairagi30** [comment]
@hkirat it was always working but only when the content (pin , copy  , delete etc ) were clicked , but i have fixed that small issue .

**Comment by Pritam12F** [comment]
@hkirat It is working for me, in the current code the admin can only pin one comment if they try to pin another comment while there is already one pinned comment, the existing pinned comment gets unpinned and the new one gets pinned

**Comment by amanbairagi30** [comment]
> @hkirat It is working for me, in the current code the admin can only pin one comment if they try to pin another comment while there is already one pinned comment, the existing pinned comment gets unpinned and the new one gets pinned

Yeah , working the same but if you click the item other than the content of the item(pin, delete etc) then it will just close the dialog .

**Comment by Pritam12F** [comment]
> > @hkirat It is working for me, in the current code the admin can only pin one comment if they try to pin another comment while there is already one pinned comment, the existing pinned comment gets unpinned and the new one gets pinned
> 
> Yeah , working the same but if you click the item other than the content of the item(pin, delete etc) then it will just close the dialog .

Yeah i just saw that now
