### ISSUE TITLE
bug: user email and phone number displayed on course videos

### ISSUE THREAD

**Issue by vikasMotwani** [code100x/cms#878]
**Describe the bug**
When I go to any course, my email and phone number appear on every recording 

**To Reproduce**
1. Go to any course video
2. See error

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/074cfa50-1a09-4642-9806-c92ff38e2c48)

**Info**
 - Browser: Chrome

**Comment by ankitmukhia** [comment]
@vikasMotwani , this is not specifically the error I suppose, it did annoy a lot. But I will suggest you to watch videos on [https://app.100xdevs.com](https://github.com/code100x/cms/issues/url). And most probably they don't own this codebase of [https://harkirat.classx.co.in](https://github.com/code100x/cms/issues/url)

**Comment by ramnaresh8** [comment]
It's not the bug, it's to prevent piracy i guess

**Comment by 4kshi7** [comment]
not a bug lmao

**Comment by sundaramsharma** [comment]
I agree @ramnaresh8 @4kshi7

**Comment by vikasMotwani** [comment]
Understood
