### ISSUE TITLE
feature: Add a QR code that takes the user directly to the Play Store for simple download.

### ISSUE THREAD

**Issue by karan-vaishnav** [code100x/cms#883]
**Is your feature request related to a problem? Please describe.**

We need to establish a user-friendly website that users can quickly access, and the problem with our website is that if a person wants to access an app from their mobile device, they must first search for it.

**Describe the solution you'd like**

For this according to me the adding QR code is the best option.

**Comment by NithinJ-17** [comment]
@karan-vaishnav Can i take up this issue?

**Comment by R0hitG0yal** [comment]
@karan-vaishnav can you please assign me this task.

**Comment by AyushBarai** [comment]
hey @karan-vaishnav , is this still available?

**Comment by shashwat558** [comment]
hey i can fix this if still open?
