### ISSUE TITLE
bug: Video Quality Change Affects Playback Speed Inconsistently

### ISSUE THREAD

**Issue by sujan321-oss** [code100x/cms#886]
**Description**
When changing the video quality from 480p to 1080p, the playback speed of the video changes inconsistently. Specifically:

- When watching a video at 480p resolution, the playback speed is set to 2x.
- Upon changing the video quality to 1080p, the playback speed should remain at 2x but instead, it reverts to 1x while the speed indicator still shows 2x.

**To Reproduce**
1. Play a video at 480p resolution.
2. Set the playback speed to 2x.
3. Change the video quality to 1080p.
4. Observe that the video playback speed changes to 1x, even though the speed indicator still displays 2x.

**Expected behavior**
The playback speed should remain consistent regardless of the video quality. If the playback speed is set to 2x, it should stay at 2x after changing the video quality.

**Actual Behavior:**
The playback speed changes to 1x when switching from 480p to 1080p, despite the speed indicator still showing 2x.

**Info (please complete the following information):**
 - Browser [chrome]
 - video link [https://harkirat.classx.co.in/video/2801?courseId=12&ytFlag=0&isFolderCourse=1]

**Comment by iSouvikKhan** [comment]
Hi @sujan321-oss

It also depends on network bandwidth, for me there is no lag

**Comment by zenithexe** [comment]
@sujan321-oss 
this repo is for [app.100xdevs.com/](https://app.100xdevs.com/) and not [https://harkirat.classx.co.in/](https://harkirat.classx.co.in/)

**Comment by sujan321-oss** [comment]
i thought repo is for https://harkirat.classx.co.in/
