### ISSUE TITLE
bug : able to login without credentials (signin field validation missing)

### ISSUE THREAD

**Issue by TamasRaj** [code100x/cms#89]
- we can login without entering email and password.

https://github.com/code100x/cms/assets/15179161/b1254cb2-d723-473d-a8e5-e675c660a9ad

- if either email or password is not provided it doesn't present proper error. Faced login issue when the mail and password was auto filled but  sign in request was not sending the username in the request.

https://github.com/code100x/cms/assets/15179161/f6d54fc4-bead-47ef-a6f7-23e8020d1b29

Solution : 
validate if the email or password is not provided.
![image](https://github.com/code100x/cms/assets/15179161/a3cf29d9-16a1-44bd-8c8d-da2351aed431)
![image](https://github.com/code100x/cms/assets/15179161/b97101af-5788-4daa-9a56-9aee8ad18ba3)

**Comment by Sameer93A** [comment]
Hey I don't know this issue related to this But why i am not able see some Test Course??.Or I am missing something.

**Comment by HusainModiwala** [comment]
I have fixed the issue and raised a PR for the same, but don't know why it's not linked. Pls have a look I think it may fix the issue.
@TamasRaj @hkirat 
PR link:- https://github.com/code100x/cms/pull/120

**Comment by HusainModiwala** [comment]
Pls close this issue as PR has been merged
