### ISSUE TITLE
bug: On changing the quality of the video, the playback speed resets to 1x

### ISSUE THREAD

**Issue by GrowthCoder7** [code100x/cms#908]
**Describe the bug**
While watching the lecture , if I change the video quality, the playback speed always resets to 1

**To Reproduce**
1. Start a lecture
2. Change the playback speed
3.  Change the current video quality

**Expected behavior**
The playback speed shouldn't be effected from the quality change.

**Screenshots or GIFs**

**Info (please complete the following information):**

**Additional context**

**Comment by ssai-manoj** [comment]
Working on it

**Comment by ssai-manoj** [comment]
@hkirat , @ssk090 , @mvp5464 I'm unable to repro this issue on my local but able to repro it on app.100xdevs.com, can you please help me out how i can repro this on my local device so that i can work and resolve this issue.

**Comment by GrowthCoder7** [comment]
it got fixed already

**Comment by nolostra** [comment]
@GrowthCoder7 i was able to reproduce it
