### ISSUE TITLE
bug: fix error screaming in the terminal

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#919]
<img width="1312" alt="Screenshot 2024-08-20 at 10 24 02 AM" src="https://github.com/user-attachments/assets/bb0f9ab9-ab77-4904-bb42-d119771786ff">

**Comment by HectorShaw** [comment]
working on it

**Comment by SujithThirumalaisamy** [comment]
Seems to be the issue of local node version.
Fix:
`
nvm install 20.5.1
nvm use 20.5.1
`

**Comment by Allan2000-Git** [comment]
Run `npm install` and start the server

**Comment by Ashutoshpadhi629** [comment]
hey @hkirat , Removing all instances of 'punycode' from the lock files will fix this Error .
