### ISSUE TITLE
bug: Incorrect spelling of Watch History

### ISSUE THREAD

**Issue by GrowthCoder7** [code100x/cms#934]
**Describe the bug**
Incorrect spelling of Watch History

**To Reproduce**
Open the side bar

**Expected behavior**

**Screenshots or GIFs**

**Info (please complete the following information):**

**Additional context**
![image](https://github.com/user-attachments/assets/3ce4af21-844a-456c-a1dc-44f64fce3f2c)

**Comment by Munadil16** [comment]
#922 addresses this issue.

**Comment by NeelContractor** [comment]
#937 solved the problem please check
