### ISSUE TITLE
Fix captions on faster speeds

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#94]
![Screenshot 2024-02-12 at 10 50 41 PM](https://github.com/code100x/cms/assets/8079861/07d1eeab-5a33-4c88-be33-86bea48fc2d0)

**Comment by shreyas0924** [comment]
Even at 2x, the captions appear to be functioning properly. I tested few videos, and all the captions work as it should. 
It's possible that **some videos may include incorrect metadata** from db.  
I found that week 5 - React, 5.2 Todo app(reupload) has incorrect captions.

What do you think @hkirat ?

**Comment by hkirat** [comment]
yeah that sounds right, closing until we get more compaints

**Comment by ramnaresh8** [comment]
![image](https://github.com/code100x/cms/assets/76533244/553ee56c-5f33-4f77-b0d7-d1372b98a95d)
the captions are not correct, there is some issue i guess.. attaching the image
