### ISSUE TITLE
bug: Login button not working on mobile

### ISSUE THREAD

**Issue by AmanJais14** [code100x/cms#940]
![Screenshot_2024-08-20-19-01-31-06_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/ac8bedf8-6751-4df4-9831-9d57dac2a611)

This login button is not working in my mobile chrome browser. Needs to be fixed

**Comment by pratiksrivastava01** [comment]
Please assign me

**Comment by AmanJais14** [comment]
Go ahead

**Comment by abhishek-dev12** [comment]
Seems like the login button is not redirecting to login page or the  "smooth scrolling" behavior is not working for the button, this can be resolve either by making changes in " smooth scrolling" behavior of login button or redirecting to a login page.
