### ISSUE TITLE
bug: state of sidebar should be by default false 

### ISSUE THREAD

**Issue by Taqi20** [code100x/cms#941]
### **On opening sidebar takes a chunk of space initially and almost everyone closes it, which I think is irritating** 

Therefore its state should be by default false so that on opening the app the sidebar should be minimized and upon clicking it opens

![image](https://github.com/user-attachments/assets/ae13ff35-fd36-4920-b02a-14defb34f5eb)

**Comment by pratiksrivastava01** [comment]
give it to me

**Comment by Taqi20** [comment]
> give it to me

Already proposed a solution and opened the pull request 😁
