### ISSUE TITLE
bug: Redirect issue of course ML and Android

### ISSUE THREAD

**Issue by rishab2211** [code100x/cms#943]
**Describe the bug**
when we click on the view content button on the course of ML or Android then it redirects to https://harkirat.classx.co.in/ instead of actual course content

**To Reproduce**
1. open https://app.100xdevs.com/my-courses
2. Click on the view content button of ML course or Android course

**Expected behavior**
It should redirect the user to the actual content according to the course

**Screenshots or GIFs**

https://github.com/user-attachments/assets/056c2145-c79f-416a-9252-144404ec33f0

**Info (please complete the following information):**
 - Browser : Brave
 - Version : 1.68.141

**Comment by avayyyyyyy** [comment]
The ML Course is uploaded on https://harkirat.classx.co.in/ only that's why it gets redirected... @rishab2211
