### ISSUE TITLE
bug: Sidebar taking a lot of unnecessary space and not collapsing when reducing screen size

### ISSUE THREAD

**Issue by kraj2503** [code100x/cms#948]
**Describe the bug**
The side bar is too persistent and takes a decent amount of space even when minimize which will make video player get less space and will impact the viewers watching and coding alongside on single screen.

**To Reproduce**
1. reduce screen size 
2. See error

**Expected behavior**
There should be a button on AppBar that should toggle SideBar and SideBar by default and when reducing screen size should be set as false or minimized

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/87dc8fa4-d291-460a-8e3a-16da05bb0e8b)

**Info (please complete the following information):**
 - Browser Arc
 - Version- latest

**Additional context**
This bug can be easily fixed by making changes in CSS of the code to change when screen size changes.

**Comment by avayyyyyyy** [comment]
<img width="83" alt="Screenshot 2024-08-21 at 9 40 55 PM" src="https://github.com/user-attachments/assets/72fe3c64-7335-4517-b67d-4dfa7c000b8d">


there is already a button to toggle the sidebar
@kraj2503

**Comment by kraj2503** [comment]
Agreed, but have a look

With Sidebar: 
![image](https://github.com/user-attachments/assets/07a4201a-b893-4fd8-a792-ce1666ce007b)


Without sidebar:
![image](https://github.com/user-attachments/assets/7633ac03-a326-431d-91a2-88feaa9c8242)

That place can be completely removed and we can implement them on top or even just collapsing as a whole

**Comment by avayyyyyyy** [comment]
that is some minimal changes only, it wouldn't effect that much in stylings and experience.....in my opinion
