### ISSUE TITLE
bug: After clicking the course content the sidebar's button to collapse gets disappeared

### ISSUE THREAD

**Issue by Taqi20** [code100x/cms#957]
https://github.com/user-attachments/assets/33263fc7-407c-47f5-bc06-7aab69520f24

**Comment by Hkumar2401** [comment]
I tried doing the same thing but it seems to be working fine for me.

https://github.com/user-attachments/assets/9f2d96b2-da70-4293-810c-62d76677b3a2

If still facing issue, could you provide some more details for the same.

**Comment by Taqi20** [comment]
@Hkumar2401 at 0:16 you have too encountered that, watch it again !
on clicking any of the course module the collapse button of the sidebar shouldn't get vanished !

I'm looking for the solution in codebase and will try to fix it ASAP and raise a PR

**Comment by Hkumar2401** [comment]
> @Hkumar2401 at 0:16 you have too encountered that, watch it again ! on clicking any of the course module the collapse button of the sidebar shouldn't get vanished !

@Taqi20 Yeah, saw it! Sorry about that.
