### ISSUE TITLE
fix Login page UI in mobiler view

### ISSUE THREAD

**Issue by chakripavankumar** [code100x/cms#96]
![isuue](https://github.com/code100x/cms/assets/116485764/6996c13f-7b63-477f-b77c-c843933a2001)

**Comment by PranitPatil03** [comment]
hello @chakripavankumar 

Can I work on this issue?

**Comment by PranitPatil03** [comment]
Hello @chakripavankumar 

I reviewed the login form UI on the local setup, and I found that the login UI is responsive for mobile devices. You can check the attached image for reference.

<details><summary>Mobile View In Local Setup</summary>
<img src="https://github.com/code100x/cms/assets/91155068/e78a7e32-bf8d-4a9e-a08c-bc293720ffd6">
</img>
</details>

**Comment by hkirat** [comment]
seems fixed
