### ISSUE TITLE
bug: the MARK AS COMPLETED button is missing .

### ISSUE THREAD

**Issue by prasanna1504** [code100x/cms#962]
Initially there was a button to mark a particular video as complete but at present this option is not visible at all

**Comment by basedD3v** [comment]
<img width="932" alt="Screenshot 2024-08-21 at 04 03 47" src="https://github.com/user-attachments/assets/d86ab4dc-f543-49cb-8444-4c7d3f9098da">

hello ser, you can use these checkboxes for now to mark video as completed

**Comment by jayzalani** [comment]
Hi I think this is solved as I can mark the video as completed
