### ISSUE TITLE
some padding here will look nice.

### ISSUE THREAD

**Issue by krish858** [code100x/cms#971]
![ksnip_20240821-184314](https://github.com/user-attachments/assets/d8df16c5-c734-48ec-b1c0-da8804706f60)

**Comment by krish858** [comment]
should I do a pr for this ?

**Comment by abhirupPann** [comment]
> should I do a pr for this ?

yes i think you should do it.

**Comment by krish858** [comment]
@abhirupPann pull a pull request #973 to solve this

**Comment by rajan153** [comment]
@krish858 @abhirupPann can you help to setup it in my local machine whenever i setup it with docker then it gives me many error while RUN DATABASE_URL=$DATABASE_URL npm run build. I am just clone it and run sudo docker-compose up command.
