### ISSUE TITLE
bug: when i run project locally it give me this error

### ISSUE THREAD

**Issue by Rahul-Bhati** [code100x/cms#982]
![Screenshot (197)](https://github.com/user-attachments/assets/ed81c3df-414f-49d3-982f-9756adc4e8c9)

**Comment by avayyyyyyy** [comment]
We don't have the permission to access the image, that's why

@hkirat

**Comment by irfan0807** [comment]
Images were in AWS S3 bucket, and those are not shared outside . @hkirat discussed about this in one of the class videos

**Comment by rajan153** [comment]
anyone can help me to setup this project to my local machine using docker whenever i am setup it then at last command it's giving prisma error the command is npm run build. I am just run this command sudo docker-compose up after clone the repo.

**Comment by ayushagarwal27** [comment]
@rajan153 you can set local postgreSQL in docker and provide link in .env.example, then run prisma migrate and seed command. 

* jusr rename .env.example to .env

**Comment by rajan153** [comment]
@ayushagarwal27 i do but nothing is happened.

**Comment by rajan153** [comment]
@ayushagarwal27 have i need to make postgres manually or using command it will create automatically ?

**Comment by ayushagarwal27** [comment]
@rajan153 can you share screenshot of error ?

You need to make manual postgreSQL instance in your docker container, or get one from neon. Provide that.

**Comment by rajan153** [comment]
@ayushagarwal27 can i paste the error here ?

**Comment by ayushagarwal27** [comment]
Sure, better provide screenshot

**Comment by rajan153** [comment]
@ayushagarwal27 
#0 156.8    Generating static pages (0/46) ...
   Generating static pages (11/46) 
   Generating static pages (22/46) 
   Generating static pages (34/46) 
#0 160.1  ⚠ Entire page /discord/redirect/cohort3 deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /discord/redirect/cohort3
#0 160.2  ⚠ Entire page /discord/redirect deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /discord/redirect
#0 160.2 PrismaClientInitializationError: 
#0 160.2 Invalid `prisma.course.findMany()` invocation:
#0 160.2 
#0 160.2 
#0 160.2 error: Error validating datasource `db`: You must provide a nonempty URL. The environment variable `DATABASE_URL` resolved to an empty string.
#0 160.2   -->  schema.prisma:8
#0 160.2    | 
#0 160.2  7 |   provider = "postgresql"
#0 160.2  8 |   url      = env("DATABASE_URL")
#0 160.2    | 
#0 160.2 
#0 160.2 Validation Error Count: 1
#0 160.2     at ai.handleRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:126:7075)
#0 160.2     at ai.handleAndLogRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:126:6109)
#0 160.2     at ai.request (/usr/src/app/node_modules/@prisma/client/runtime/library.js:126:5817)
#0 160.2     at async l (/usr/src/app/node_modules/@prisma/client/runtime/library.js:131:9709)
#0 160.2     at async i (/usr/src/app/.next/server/app/courses/page.js:1:3318) {
#0 160.2   clientVersion: '5.9.1',
#0 160.2   errorCode: undefined
#0 160.2 }
#0 160.2 PrismaClientInitializationError: 
#0 160.2 Invalid `prisma.course.findMany()` invocation:
#0 160.2 
#0 160.2 
#0 160.2 error: Error validating datasource `db`: You must provide a nonempty URL. The environment variable `DATABASE_URL` resolved to an empty string.
#0 160.2   -->  schema.prisma:8
#0 160.2    | 
#0 160.2  7 |   provider = "postgresql"
#0 160.2  8 |   url      = env("DATABASE_URL")
#0 160.2    | 
#0 160.2 
#0 160.2 Validation Error Count: 1
#0 160.2     at ai.handleRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:126:7075)
#0 160.2     at ai.handleAndLogRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:126:6109)
#0 160.2     at ai.request (/usr/src/app/node_modules/@prisma/client/runtime/library.js:126:5817)
#0 160.2     at async l (/usr/src/app/node_modules/@prisma/client/runtime/library.js:131:9709)
#0 160.2     at async i (/usr/src/app/.next/server/app/courses/page.js:1:3318) {
#0 160.2   clientVersion: '5.9.1',
#0 160.2   errorCode: undefined
#0 160.2 }
#0 160.4 
#0 160.4 Error occurred prerendering page "/courses". Read more: https://nextjs.org/docs/messages/prerender-error
#0 160.4 PrismaClientInitializationError: 
#0 160.4 Invalid `prisma.course.findMany()` invocation:
#0 160.4 
#0 160.4 
#0 160.4 error: Error validating datasource `db`: You must provide a nonempty URL. The environment variable `DATABASE_URL` resolved to an empty string.
#0 160.4   -->  schema.prisma:8
#0 160.4    | 
#0 160.4  7 |   provider = "postgresql"
#0 160.4  8 |   url      = env("DATABASE_URL")
#0 160.4    | 
#0 160.4 
#0 160.4 Validation Error Count: 1
#0 160.4     at ai.handleRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:126:7075)
#0 160.4     at ai.handleAndLogRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:126:6109)
#0 160.4     at ai.request (/usr/src/app/node_modules/@prisma/client/runtime/library.js:126:5817)
#0 160.4     at async l (/usr/src/app/node_modules/@prisma/client/runtime/library.js:131:9709)
#0 160.4     at async i (/usr/src/app/.next/server/app/courses/page.js:1:3318)
 ✓ Generating static pages (46/46) 
#0 160.8 
#0 160.8 > Export encountered errors on following paths:
#0 160.8        /courses/page: /courses
------
failed to solve: process "/bin/sh -c DATABASE_URL=$DATABASE_URL npm run build" did not complete successfully: exit code: 1
![Screenshot from 2024-08-23 00-08-52](https://github.com/user-attachments/assets/19815c59-2a2d-48cc-9871-47b8a280e046)
![Screenshot from 2024-08-23 00-09-47](https://github.com/user-attachments/assets/6138f18b-b328-41c6-b3d4-b18dd795e5a7)

**Comment by ayushagarwal27** [comment]
@rajan153 make sure you add postgreSQL url in env file,

` Error validating datasource db: You must provide a nonempty URL. The environment variable DATABASE_URL resolved to an empty string.`

**Comment by rajan153** [comment]
@ayushagarwal27 yeah, also i added screenshot there is one of env file there i already added postgres link.

**Comment by ayushagarwal27** [comment]
@rajan153 are you following with docker commands or without  docker,

follow without docker one, skip (3) option and provide your own postgrSQL url

**Comment by rajan153** [comment]
@ayushagarwal27 i am going with docker commands, Okay i will try then i will told you.

**Comment by divu777** [comment]
@rajan153 i did encounter this issue , the basic fix that worked was having the same version of prisma and prisma client installed in the package.json , let me know if you need further help .

**Comment by Rahul-Bhati** [comment]
@avayyyyyyy bro , when i click on view content it is not load any content.

**Comment by avayyyyyyy** [comment]
> @avayyyyyyy bro When I click on "View Content," it doesn't load any content.

Have you run that seed command??

`npm run db:seed` - this one

**Comment by Rahul-Bhati** [comment]
This is the error after running :` npm run db:seed`
`
```
  152
  153 async function seedCourseContent() {
  154   try {

→ 155     await db.courseContent.create(
Unique constraint failed on the fields: (`courseId`,`contentId`)

    at ai.handleRequestError (cms\node_modules\@prisma\client\runtime\library.js:126:6775)

    at ai.handleAndLogRequestError (cms\node_modules\@prisma\client\runtime\library.js:126:6109)

    at ai.request (cms\node_modules\@prisma\client\runtime\library.js:126:5817)

    at async l (cms\node_modules\@prisma\client\runtime\library.js:131:9709) {

  code: 'P2002',
  clientVersion: '5.9.1',
  meta: { modelName: 'CourseContent', target: [ 'courseId', 'contentId' ] }
}

An unexpected error occurred during seeding: PrismaClientKnownRequestError:
Invalid `db.courseContent.create()` invocation in
```
`

**Comment by VardaanAggarwal** [comment]
> This is the error after running :` npm run db:seed` `
> 
> ```
>   152
>   153 async function seedCourseContent() {
>   154   try {
> 
> → 155     await db.courseContent.create(
> Unique constraint failed on the fields: (`courseId`,`contentId`)
> 
>     at ai.handleRequestError (cms\node_modules\@prisma\client\runtime\library.js:126:6775)
> 
>     at ai.handleAndLogRequestError (cms\node_modules\@prisma\client\runtime\library.js:126:6109)
> 
>     at ai.request (cms\node_modules\@prisma\client\runtime\library.js:126:5817)
> 
>     at async l (cms\node_modules\@prisma\client\runtime\library.js:131:9709) {
> 
>   code: 'P2002',
>   clientVersion: '5.9.1',
>   meta: { modelName: 'CourseContent', target: [ 'courseId', 'contentId' ] }
> }
> 
> An unexpected error occurred during seeding: PrismaClientKnownRequestError:
> Invalid `db.courseContent.create()` invocation in
> ```
> 
> `

this is a unique constraint violation error, common while seeding the databases with random values. I think you should just run it once more and this should not be a problem for you next time

**Comment by Azathoth-11** [comment]
> anyone can help me to setup this project to my local machine using docker whenever i am setup it then at last command it's giving prisma error the command is npm run build. I am just run this command sudo docker-compose up after clone the repo.

have you solved this issue? I am also facing this now.

**Comment by Azathoth-11** [comment]
> > > anyone can help me to setup this project to my local machine using docker whenever i am setup it then at last command it's giving prisma error the command is npm run build. I am just run this command sudo docker-compose up after clone the repo.
> > 
> > 
> > have you solved this issue? I am also facing this now.
> 
> not yet, can you tell me which error you are facing ?

same error as you.

**Comment by rajan153** [comment]
@Azathoth-11 maybe i will work on it tonight if something happened then i will ping you.

**Comment by Azathoth-11** [comment]
> maybe i will work on it tonight if something happened then i will ping you.

i made it work but not sure if its correct. just pasted the dockerfile.dev to dockerfile
