### ISSUE TITLE
bug: Mobile UI is not responsive and Spelling error "watch hostory" 

### ISSUE THREAD

**Issue by sachinshrmaa** [code100x/cms#985]
**Describe the bug**
In the mobile view the website is not responsive very hard to navio through other chapters. And there is a spelling mistake in the side menu "watch hostory"

 
**To Reproduce**
1. Do something
2. See error

**Expected behavior**

**Screenshots or GIFs**
![Screenshot_2024-08-23-00-42-14-14_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/835b93e7-d210-4ca4-8753-37ba8e95eb8a)

**Info (please complete the following information):**

**Additional context**

**Comment by toufiqfarhan0** [comment]
the typo has been fixed not yet merged

**Comment by Masood-ul-Rehman** [comment]
Hello @sachinshrmaa I would like to work on this, main issue is that sidebar don't close automatically on small screens, I will do that and will show the refresh database on while the sidebar is open 
![Screenshot_3](https://github.com/user-attachments/assets/e7c82915-0553-48f5-b0c0-344409e6c671)

![Screenshot_2](https://github.com/user-attachments/assets/7fb4f196-1182-4987-bd3b-fa135a3c0a08)
