### ISSUE TITLE
bug: Images not rendering

### ISSUE THREAD

**Issue by manasdodiya** [code100x/cms#987]
**Describe the bug**
The images are not rendering correctly in course. The tiles are working properly, but the images are not appearing.

**To Reproduce**
1. Go to <a href="https://app.100xdevs.com/my-courses">app.100xdevs.com/my-courses</a> 
2. Login and you will see the error

**Expected behavior**
The images should render correctly.

**Screenshots or GIFs**
![Screenshot 2024-08-23 at 05 42 06](https://github.com/user-attachments/assets/3d95f58a-98ba-48d8-a1fd-94fa74f79025)

**Info (please complete the following information):**
 - Browser: chrome, brave, safari

Please let me know if you need any further assistance.

**Comment by AdityaPainuli** [comment]
Hey  , I am new to this repo and settled up the project locally. while trying to look for solving this issue I come up with not any of these image loading . seems like the error is of `access denied` . Is I need to configure something else more or this is the error ? 
![image](https://github.com/user-attachments/assets/3c7aa057-5159-463a-81d1-a5e2465bf427)

**Comment by VardaanAggarwal** [comment]
> Hey , I am new to this repo and settled up the project locally. while trying to look for solving this issue I come up with not any of these image loading . seems like the error is of `access denied` . Is I need to configure something else more or this is the error ? ![image](https://private-user-images.githubusercontent.com/66621672/360817994-3c7aa057-5159-463a-81d1-a5e2465bf427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzQ3NjksIm5iZiI6MTcyNDQzNDQ2OSwicGF0aCI6Ii82NjYyMTY3Mi8zNjA4MTc5OTQtM2M3YWEwNTctNTE1OS00NjNhLTgxZDEtYTVlMjQ2NWJmNDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE3MzQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OTc2ODEyNzVjYTA4ZGZhMjk1ZWQwMjUwMGQxNTk1MGNkNGM2NjRjZDA5YzIzM2Q1MDM0YzQxYzcwZjhmMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DEZnP2QhD2TvX2_jY0slA6Y05ljVr4QvtqJqrkCwl4Y)

images are stored in AWS S3 bucket which you do not access to
