### ISSUE TITLE
Getting 500 on adding intro comments

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#99]
intro:
00:40 - 02:15 - What is CSS 
02:15 - 05:25 - How to add styles 
05:25 - 06:38 - borderRadius 
06:38 - 08:05 - border
08:05 - 13:40 - padding/margin 
13:40 - 16:40 - boxShadow 
16:40 - 17:10 - fontSize 
17:10 - 18:00 - Positioning in CSS 
18:00 - 20:35 - divs & span theory 
20:35 - 21:55 - float property 
21:55 - 24:10 - flex box 
24:10 - 33:00 - flex box attributes 
33:00 - 37:10 - flex inside flex 
37:10 - 38:20 - Creating zerodha landing page 
38:20 - 44:10 - how to see other websites styles 
44:10 - 55:15 - difference between padding & margin 
55:15 - 52:45 - cursor:pointer 
52:45 - 56:40 - Custom button 
56:40 - 59:59 - font-weight 

<img width="1442" alt="Screenshot 2024-02-21 at 7 03 33 AM" src="https://github.com/code100x/cms/assets/8079861/674dfa7a-ee52-40de-9611-40ac9f40f7c0">

**Comment by hkirat** [comment]
cc @siinghd

**Comment by siinghd** [comment]
Hi @hkirat 

Is there any info on server side logs? 

trying to figure out whats going on here, as always dev always works on prod things explode :(

<img width="692" alt="Screenshot 2024-02-21 at 8 38 41 AM" src="https://github.com/code100x/cms/assets/38940603/e72e5423-23b2-46f6-bd8f-17bb77d04e70">

**Comment by siinghd** [comment]
Seems like its not only the intro comment, but all comments an thats little weird

**Comment by hkirat** [comment]
need any help from me? Any logs from netlify?

**Comment by hkirat** [comment]
ah ok nvm not worth pursuing, let me deploy to AWS

**Comment by hkirat** [comment]
Actually, might have to move this to API routes

**Comment by siinghd** [comment]
@hkirat Alright will do it, otherwise what we also can do is to use EC2 and set our deployment pipelines for development and production. That can be also cool because this way cohort people can see how these works too.

Might EC2 will be little expensive, normally I use hetzner that’s really really cheap, like  AMD Ryzen 5 3600 6-Core Processor 12 with Hyper-Threading, 64gb ram for around 30$ 

Let me know how you want to proceed

**Comment by hkirat** [comment]
I think anything would be cheap vercel bill was $720

**Comment by siinghd** [comment]
@hkirat if you down we can try hetzner behind cloud flare for caching, In around 20/30 mins we can put it up
Db should be on cloud right?

**Comment by hkirat** [comment]
https://github.com/code100x/cms/commit/15b0af830e72127a387386e9e71d848f7086443f was the fix

**Comment by siinghd** [comment]
@hkirat Amazing Veere, let’s go
