### ISSUE TITLE
bug: Image issue on dashboard 

### ISSUE THREAD

**Issue by nolostra** [code100x/cms#993]
**Describe the bug**

![image](https://github.com/user-attachments/assets/6a249192-d21f-4666-a319-9b6963c8c629)

**To Reproduce**
1. open  [cms dashboard](https://app.100xdevs.com/my-courses)
2. See error

**Expected behavior**
it should have shown the images properly 

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/6a249192-d21f-4666-a319-9b6963c8c629)
<img width="636" alt="image" src="https://github.com/user-attachments/assets/a871acb1-8979-41f9-bfb1-4b4a09090ae6">

**Info (please complete the following information):**
 - Browser chrome

**Additional context**
it was also checked by TA Rushikesh G

**Comment by sreenathkumar** [comment]
I am also having the same issues. The AWS image link is throwing an error.

**Comment by asdfghjA1** [comment]
The backend side of it is broken , the link possibly on the database side , use a makeshift thumbnail for now , and Inform the maintainer about this not the TA

**Comment by sreenathkumar** [comment]
when you i tried to access the image url it was showing 'Unauthorized', which is thrown by the AWS.

**Comment by asdfghjA1** [comment]
> when you i tried to access the image url it was showing 'Unauthorized', which is thrown by the AWS.

Use your database to host the images , my previous reply was bargery , shall you get your own instance , then it should run
