### ISSUE TITLE
feature: Only Logout Button showing even after Logging out

### ISSUE THREAD

**Issue by navaljangir** [code100x/cms#996]
Can be improved: 
After Logout from the website, when we visit the [https://app.100xdevs.com/courses](https://app.100xdevs.com/courses) the Logout Button on the bottom left Corner is Still there. So either good to hide it or make it for the use of Login and Logout.  

Solution:
Can customize the course page better so making the button for Both signin and signout 

![image](https://github.com/user-attachments/assets/8e641200-b8d9-43ab-8dae-8b43ade653f4)

Can i be assigned to fix the issue?

**Comment by ahmad-nadeem877** [comment]
in my opinion if someone is logged out he should not be shown this page like this, its basically showing him his watch history bookmarks etc, After logging out it should be only the courses listed on the website.
